Locales = Locales or {}

Locales['ar'] = {
  -- UI
  vehicle = "مركبة",
  vehicles = "مركبات",
  dealership = "وكالة",
  dealerships = "وكالات",
  vehiclesCount = "مركبة/مركبات",
  dealersCount = "وكيل/وكلاء",
  accountBalance = "رصيد الحساب",
  bank = "حساب بنكي",
  cash = "نقد",
  amount = "المبلغ",
  societyFund = "صندوق المجتمع",
  paymentSource = "مصدر الدفع",
  purchase = "شراء",
  personalPurchase = "شراء شخصي",
  societyPurchase = "شراء للمجتمع",
  purchaseType = "نوع الشراء",
  deposit = "إيداع",
  withdraw = "سحب",
  all = "الكل",
  yes = "نعم",
  no = "لا",
  add = "إضافة",
  edit = "تعديل",
  id = "معرف",
  created = "تم الإنشاء",
  type = "النوع",
  name = "الاسم",
  owner = "المالك",
  bankBalance = "رصيد البنك",
  status = "الحالة",
  back = "رجوع",
  previous = "السابق",
  next = "التالي",
  admin = "مسؤول",
  vehiclesAdmin = "إدارة المركبات",
  dealershipsAdmin = "إدارة الوكالات",
  search = "بحث",
  noDealershipsFound = "لم يتم العثور على وكالات",
  noVehicles = "لم يتم العثور على مركبات",
  page = "صفحة",
  of = "من",
  every = "كل",
  show = "عرض",
  active = "نشط",
  activeFinance = "تمويل نشط",
  failed = "فشل الدفع",
  removed = "تمت الإزالة",
  setOwner = "تعيين المالك",
  manage = "إدارة",
  deleteData = "حذف البيانات",
  deleteVehicle = "حذف المركبة",
  delete = "حذف",
  deleteConfirmation = "هل أنت متأكد؟",
  deleteConfirmationDanger = "هل أنت متأكد؟ هذا الإجراء لا يمكن التراجع عنه.",
  setDealershipOwner = "تعيين مالك الوكالة",
  overwriteDealerPrices = "تجاوز أسعار الوكالة",
  nearbyPlayers = "اللاعبين القريبين",
  noPlayersNearby = "لا يوجد لاعبين قريبين",
  selectPlayer = "اختر لاعب",
  required = "مطلوب",
  forExample = "على سبيل المثال",
  spawnCode = "رمز الاستدعاء",
  brand = "العلامة التجارية",
  model = "الموديل",
  category = "الفئة",
  price = "السعر",
  import = "استيراد",
  importing = "جارٍ الاستيراد",
  importBehaviour = "سلوك الاستيراد",
  importVehicles = "استيراد المركبات",
  importFrom = "استيراد من",
  dashboard = "لوحة القيادة",
  displayVehicle = "عرض المركبة",
  displayVehicles = "عرض المركبات",
  orders = "الطلبات",
  sales = "المبيعات",
  vehiclesOnDisplay = "المركبات المعروضة",
  employees = "الموظفين",
  settings = "الإعدادات",
  switchVehicle = "تبديل المركبة",
  remove = "إزالة",
  noDisplayVehicles = "لا توجد مركبات معروضة",
  selectVehicle = "اختر مركبة",
  colour = "اللون",
  placeVehicle = "وضع المركبة",
  orderVehicle = "طلب مركبة",
  cancelOrder = "إلغاء الطلب",
  delivery = "التسليم",
  delivered = "تم التسليم",
  noOrders = "لم يتم العثور على طلبات",
  quantity = "الكمية",
  totalCost = "التكلفة الإجمالية",
  totalSales = "إجمالي المبيعات",
  noSales = "لم يتم العثور على مبيعات",
  paid = "مدفوع",
  owed = "مستحق",
  dealershipName = "اسم الوكالة",
  save = "حفظ التغييرات",
  cancel = "إلغاء",
  notEnoughMoney = "لا يوجد ما يكفي من المال",
  placeOrder = "تقديم الطلب",
  purchaseCost = "تكلفة الشراء",
  salePrice = "سعر البيع",
  inStock = "متوفر في المخزون",
  outOfStock = "غير متوفر في المخزون",
  placeVehiclePrompt = "اضغط %{value} لوضع المركبة. يمكنك إجراء تعديلات دقيقة بعد ذلك!",
  remaining = "المتبقي",
  prePurchaseRepoWarning = "إذا لم تتمكن من متابعة دفعات التمويل، سيتم استعادة مركبتك.",
  repossessionWarning = "فشلت دفعتك الأخيرة - سيتم استعادة مركبتك ما لم تقم بالدفع الآن.",
  recurringPayment = "دفعة متكررة",
  remainingBalance = "الرصيد المتبقي",
  remainingPayments = "الدفعات المتبقية",
  paymentTakenEvery = "يتم أخذ الدفع كل",
  hours = "ساعات",
  seconds = "ثواني",
  nextPayment = "الدفعة التالية",
  makePayment = "قم بالدفع",
  vehicleRepossessed = "سيتم استعادة المركبة",
  payInFull = "الدفع بالكامل",
  earlyPaymentConfirmation = "هل أنت متأكد أنك تريد الدفع المبكر بمبلغ",
  financedVehicles = "المركبات الممولة",
  noFinancedVehicles = "ليس لديك مركبات بتمويل نشط",
  financeBreakdown = "تفاصيل التمويل",
  initialPayment = "الدفعة الأولى",
  payments = "الدفعات",
  length = "المدة",
  interest = "الفائدة",
  totalPayable = "الإجمالي المستحق",
  leaveShowroom = "مغادرة صالة العرض",
  handling = "المناولة",
  topSpeed = "السرعة القصوى",
  power = "القوة",
  torque = "العزم",
  brake = "الفرامل",
  financing = "التمويل",
  financingAvailable = "التمويل متاح",
  paymentsOf = "دفعات من",
  clear = "مسح",
  testDrive = "تجربة قيادة",
  allCategories = "جميع الفئات",
  sortByName = "ترتيب حسب: الاسم",
  sortByAvailability = "ترتيب حسب: التوفر",
  sortByCheapest = "ترتيب حسب: الأرخص",
  sortByMostExpensive = "ترتيب حسب: الأغلى",
  sortByNewest = "ترتيب حسب: الأحدث",
  purchaseVehicle = "شراء مركبة",
  purchaseFor = "شراء لـ",
  selectSociety = "اختر مجتمع",
  financeOverPayments = "تمويل على %{value} دفعات",
  payToday = "ادفع اليوم",
  financeThen = "ثم",
  seeFullBreakdown = "عرض التفاصيل الكاملة",
  testDriveExit = "يمكنك الخروج من مركبتك في أي وقت لإنهاء تجربة القيادة.",

  -- NOTIFICATIONS
  purchaseSuccess = "تهانينا على الشراء!",
  depositSuccess = "تم الإيداع بنجاح",
  withdrawSuccess = "تم السحب بنجاح",
  errorNotEnoughMoney = "لا يوجد لديك ما يكفي من المال",
  errorVehicleOutOfStock = "هذه المركبة غير متوفرة في المخزون",
  errorCannotAffordVehicle = "لا يمكنك تحمل تكلفة هذه المركبة",
  vehicleFinancePaymentMade = "تم دفع دفعة التمويل لمركبتك %{value}",
  vehicleFinancePaidOff = "تهانينا، لقد دفعت بالكامل وتملك الآن مركبتك %{value}",
  vehicleFinancePaymentFailed = "فشلت دفعة التمويل لمركبتك %{value}",
  vehicleFinanceRepossessedSoon = "تحتاج إلى دفع لمركبتك %{value} أو سيتم استعادة مركبتك قريبًا",
  vehicleFinanceRepossessed = "بسبب الفشل في الدفع، تم استعادة مركبتك برقم اللوحة %{value}",
  dealershipNotEnoughFunds = "الوكالة لا تملك ما يكفي من الأموال",
  dealershipVehiclesOrdered = "تم طلب المركبات بنجاح",
  dealershipOrderCancelled = "تم إلغاء الطلب بنجاح",
  errorVehicleWithSpawnCodeExists = "مركبة بهذا الرمز موجودة بالفعل",
  errorExitVehicle = "تحتاج إلى الخروج من مركبتك أولاً",

  -- NEW v1.1
  purchaseRequest = "طلب شراء",
  sendRequest = "إرسال الطلب",
  dealer = "وكيل",
  financed = "ممول",
  signHere = "وقع هنا",
  signFirstError = "يرجى التوقيع أولاً",
  denyRequest = "رفض الطلب",
  playerTooManyFinancedVehicles = "اللاعب لديه الكثير من المركبات الممولة",
  employeePermissionsError = "ليس لديك الصلاحيات اللازمة للموظف",
  managerRole = "مدير",
  supervisorRole = "مشرف",
  salesRole = "مبيعات",
  ownerRole = "مالك",
  employmentRequest = "طلب توظيف",
  accept = "قبول",
  jobOfferDescription = "تم عرض وظيفة لك في وكالة \"%{value}\". هل ترغب في القبول؟",
  pending = "قيد الانتظار",
  employeeHiredMsg = "تم قبول طلب التوظيف في الوكالة!",
  employeeRejectedMsg = "تم رفض طلب التوظيف في الوكالة",
  sellVehicle = "بيع مركبة",
  vehicleTerms = "شروط المركبة",
  financePayments = "دفعات التمويل",
  commission = "العمولة",
  role = "الدور",
  firedNotification = "تم فصلك من وكالة \"%{value}\"",
  dealershipTooFarAway = "أنت لست بالقرب من أي وكالات",
  restoreDisplayVehicles = "استعادة صالة العرض",
  customer = "عميل",
  lessThanAMin = "أقل من دقيقة",
  mins = "دقيقة/دقائق",
  notInVehicle = "أنت لست جالسًا في مركبة",
  notYourVehicleError = "هذه المركبة لا تخصك",
  vehicleFinancedError = "لا يمكنك بيع هذه المركبة لأنها تحتوي على دفعات تمويل متبقية",
  dealershipDoesntSellVehicle = "هذه الوكالة لا تستطيع شراء هذه المركبة",
  dealershipWantsYourVehicle = "تهانينا! ترغب هذه الوكالة في شراء مركبتك.",
  purchasePrice = "السعر المعروض: ",
  
  spawnCodeInvalid = "رمز الاستدعاء غير صالح",
  salesRep = "ممثل مبيعات",
  directSaleAccepted = "تم قبول طلب البيع المباشر! تم دفع عمولتك.",
  directSaleRejected = "تم رفض طلب البيع المباشر",

  displayVehicleOutsideZone = "يجب وضع مركبات العرض داخل منطقة الوكالة",
  serverAdmin = "مسؤول الخادم",
  selfService = "خدمة ذاتية",
  owned = "مملوكة",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "طريقة دفع غير صالحة",
  paymentMethodNoFinance = "طريقة الدفع هذه لا تدعم التمويل",
  couldNotGeneratePlate = "تعذر إنشاء لوحة الأرقام",
  invalidCoupon = "قسيمة غير صالحة: %{value}",
  tooManyFinancedVehicles = "لديك مركبات ممولة كثيرة جداً",
  couldNotSpawnVehicle = "تعذر إنشاء المركبة",

  -- v2: Permissions
  insufficientPermissions = "صلاحيات غير كافية",

  -- v2: Coupons
  couponCodeAlreadyExists = "رمز القسيمة موجود بالفعل",
  failedToCreateCoupon = "فشل في إنشاء القسيمة",
  couponCreatedSuccessfully = "تم إنشاء القسيمة بنجاح",
  couponNotFound = "القسيمة غير موجودة",
  couponUpdatedSuccessfully = "تم تحديث القسيمة بنجاح",
  failedToDeleteCoupon = "فشل في حذف القسيمة",
  couponDeletedSuccessfully = "تم حذف القسيمة بنجاح",
  editCoupon = "تعديل القسيمة",
  addCoupon = "إضافة قسيمة",
  couponCode = "رمز القسيمة",
  generating = "جاري الإنشاء...",
  generate = "إنشاء",
  discountType = "نوع الخصم",
  percentageOff = "نسبة الخصم",
  amountOff = "مبلغ الخصم",
  discountValue = "قيمة الخصم",
  unlimitedTotalUses = "استخدامات إجمالية غير محدودة",
  unlimitedUsesPerPlayer = "استخدامات غير محدودة لكل لاعب",
  setExpiryDate = "تحديد تاريخ انتهاء الصلاحية",
  restrictToSpecificVehicles = "تقييد لمركبات محددة",
  restrictToSpecificCategories = "تقييد لفئات محددة",
  allowUseWithFinance = "السماح بالاستخدام مع التمويل",
  deleteCoupon = "حذف القسيمة",
  inactive = "غير نشط",
  expired = "منتهي الصلاحية",
  maxUses = "الحد الأقصى للاستخدام",
  coupons = "القسائم",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "فقط مسؤولو الخادم يمكنهم توظيف أنفسهم",
  playerNotFound = "اللاعب غير موجود",
  failedToHireEmployee = "فشل في توظيف الموظف",
  failedToFireEmployee = "فشل في فصل الموظف",
  failedToUpdateEmployeeRole = "فشل في تحديث دور الموظف",
  hireEmployee = "توظيف موظف",
  fireEmployee = "فصل موظف",
  editRole = "تعديل الدور",
  fire = "فصل",
  changeRole = "تغيير الدور",
  updateRole = "تحديث الدور",

  -- v2: Test drives
  maxTestDrivesReached = "وصلت هذه الوكالة للحد الأقصى من تجارب القيادة النشطة",
  testDriveNotEnabled = "تجارب القيادة غير مفعلة في هذه الوكالة",
  noTestDriveSpawnCoords = "لا توجد إحداثيات استدعاء لتجربة القيادة مهيأة لهذه الوكالة",
  couldNotSpawnTestDriveVehicle = "تعذر إنشاء مركبة تجربة القيادة",
  couldNotGetPlateFromServer = "تعذر الحصول على لوحة الأرقام من الخادم",
  couldNotRegisterTestDriveVehicle = "تعذر تسجيل مركبة تجربة القيادة",
  testDriveEndedByEmployee = "تم إنهاء تجربة القيادة بواسطة موظف آخر",
  trackingVehicleLocation = "جاري تتبع موقع المركبة...",
  directSaleCancelled = "تم إلغاء طلب البيع من قبل البائع",
  testDriveKeysReceived = "استلمت مفاتيح مركبة تجربة القيادة",
  testDriveEndedCustomer = "انتهت تجربة القيادة",
  starting = "جاري البدء...",
  startTestDrive = "بدء تجربة القيادة",
  spawningTestDriveVehicle = "جاري إنشاء مركبة تجربة القيادة...",
  testDriveReady = "تجربة القيادة جاهزة",
  testDriveWalkToVehicle = "تم إنشاء مركبة تجربة القيادة في الموقع المحدد على خريطتك. رافق العميل إلى المركبة. بعد إعطاء المفاتيح للعميل، ستحتاج إلى إنهاء تجربة القيادة يدوياً عند عودته.",
  givingKeys = "جاري إعطاء المفاتيح...",
  continueAndGiveKeys = "استمر وأعط المفاتيح",
  endTestDrive = "إنهاء تجربة القيادة",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "لا يوجد مخزون متاح لهذه المركبة",
  globalStockLimitExceeded = "متاح فقط %{value} وحدات",
  orderNotFoundOrFulfilled = "الطلب غير موجود أو تم تنفيذه بالفعل",
  priceBelowMinimum = "لا يمكن أن يكون السعر أقل من %{value}",
  priceAboveMaximum = "لا يمكن أن يكون السعر أعلى من %{value}",
  stockUpdated = "تم تحديث المخزون",
  changesSaved = "تم حفظ التغييرات",
  noStockAvailable = "لا يوجد مخزون متاح",
  orderPlaced = "تم تقديم الطلب",
  remainingInStock = "متبقي في المخزون العالمي",
  exceedsStockLimit = "يتجاوز حد المخزون",
  setStockQty = "تعيين كمية المخزون",
  invalidStockValue = "يرجى إدخال قيمة مخزون صالحة",
  errorSettingStock = "خطأ في تعيين المخزون",
  stockQuantity = "كمية المخزون",
  currentStock = "المخزون الحالي",
  priceLimitsEnabled = "تفعيل حدود الأسعار",
  priceLimitsDescription = "عند التفعيل، يمكن لمديري الوكالة فقط تعيين الأسعار ضمن النطاق المحدد.",
  minPrice = "الحد الأدنى للسعر",
  maxPrice = "الحد الأقصى للسعر",
  optional = "اختياري",
  unlimitedStock = "مخزون غير محدود",
  globalStockLimit = "حد المخزون العالمي",
  globalStockLimitDescription = "تعيين الحد الأقصى لعدد الوحدات التي يمكن طلبها عبر جميع الوكالات.",
  currentlyOrdered = "مطلوب حالياً",
  priceRange = "نطاق السعر",
  noMinimum = "لا يوجد حد أدنى",
  noMaximum = "لا يوجد حد أقصى",
  vehicleStock = "مخزون المركبات",

  -- v2: Sales
  allSales = "جميع المبيعات",
  paidInFull = "مدفوع بالكامل",
  salesVolume = "حجم المبيعات",
  pastMonth = "الشهر الماضي",
  pastYear = "السنة الماضية",

  -- v2: Management misc
  exploitAttemptDetected = "توقف عن محاولة استغلال السكريبت",
  dealershipNoJobConfigured = "الوكالة ليس لديها وظيفة مهيأة",
  modelDoesNotMatchDb = "موديل المركبة لا يتطابق مع قاعدة البيانات",
  importFailed = "فشل الاستيراد: %{value}",
  notInDealershipZone = "يجب أن تكون داخل وكالة لاستخدام هذا الأمر",
  notAnEmployee = "أنت لست موظفاً في هذه الوكالة.",
  failedToPrepareDelivery = "فشل في إعداد التسليم",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "موديل المركبة غير موجود - تواصل مع المسؤول",
  vehiclePlateInvalid = "لوحة أرقام هذه المركبة غير صالحة (اضغط F8 للمزيد من التفاصيل)",
  currentlyInRagdollState = "أنت حالياً في حالة سقوط",
  vehicleDoesNotExistContactAdmin = "المركبة غير موجودة. يرجى التواصل مع المسؤول!",
  vehicleSecurityBreachDetected = "تم اكتشاف خرق أمني للمركبة",

  -- v2: Admin vehicles
  allVehicles = "جميع المركبات",
  unassignedVehicles = "بدون وكالة",
  searchDealerships = "البحث في الوكالات...",

  -- v2: Trucking mission
  truckingGetInTruck = "اركب الشاحنة في الموقع المحدد لبدء التسليم",
  truckingDriveToDelivery = "اقترب من موقع التسليم",
  truckingCompleteDelivery = "أكمل التسليم",
  truckingDeliveryComplete = "اكتمل التسليم: أكملت التسليم بنجاح!",
  truckingDeliveryFailed = "فشل التسليم: حدث خطأ في التسليم",
  truckingDriveToPickup = "اقترب من نقطة الاستلام لاستلام المقطورة",
  truckingMissionFailedSpawnCargo = "فشلت المهمة: تعذر إنشاء مقطورة الشحن",
  truckingMissionFailedFindCargo = "فشلت المهمة: تعذر العثور على الشحنة المنشأة",
  truckingVehiclesLoaded = "تم تحميل %{count} مركبة",
  truckingWrongTrailer = "مقطورة خاطئة! يجب ربط مقطورة المهمة الصحيحة.",
  truckingTrailerAttached = "تم ربط المقطورة - جاهز للمتابعة",
  truckingDriveToPickupLocation = "اقترب من نقطة الاستلام",
  truckingWaitingForVehicles = "في انتظار تحميل المركبات...",
  truckingDriveUnderTrailer = "ادخل تحت المقطورة لربطها",
  truckingGetInTruckContinue = "اركب الشاحنة للمتابعة",
  truckingMissionStarted = "بدأت مهمة النقل: نقطة الاستلام - %{location}",
  truckingMissionCancelled = "تم إلغاء المهمة: ألغيت مهمة النقل",
  truckingNoActiveMission = "لا توجد مهمة نقل نشطة للإلغاء",
  deliveryNotPrepared = "التسليم غير جاهز - يرجى المحاولة مرة أخرى",
  deliveryConfigMismatch = "عدم تطابق إعدادات التسليم",
  deliveryPreparationExpired = "انتهت صلاحية إعداد التسليم - يرجى المحاولة مرة أخرى",
  noTruckingVehicleCoordinates = "لم يتم تعيين إحداثيات مركبة النقل",
  pickupLocationUnavailable = "نقطة الاستلام لم تعد متاحة - يرجى المحاولة مرة أخرى",
  failedToSpawnTruck = "فشل في إنشاء الشاحنة",
  clientFailedToStartMission = "فشل العميل في بدء المهمة",

  -- v2: Trucking UI/Keys
  keyDismiss = "إغلاق",
  keyDeliverCargo = "تسليم الشحنة",
  keyContinueToDelivery = "متابعة إلى التسليم",
  startDeliveryMission = "بدء مهمة التسليم",
  orderDetails = "تفاصيل الطلب",
  pickupLocation = "نقطة الاستلام",
  deliveryStatus = "حالة التسليم",
  selectOrders = "اختيار الطلبات",
  carTrailer = "ناقلة سيارات",
  container = "حاوية",
  deliveryRoute = "مسار التسليم",
  startDelivery = "بدء التسليم",

  -- v2: Direct sales UI
  waitingForCustomer = "في انتظار العميل",
  cancelRequest = "إلغاء الطلب",
  saleComplete = "اكتملت البيع!",
  done = "تم",
  saleDeclined = "تم رفض البيع",
  close = "إغلاق",

  -- v2: Display vehicle placement
  movement = "الحركة",
  rotate = "تدوير",
  forward = "للأمام",
  backward = "للخلف",
  left = "يسار",
  right = "يمين",
  rotateLeft = "تدوير لليسار",
  rotateRight = "تدوير لليمين",

  -- v2: Showroom misc
  originalPrice = "السعر الأصلي",
  discount = "الخصم",
  createInteraction = "إنشاء تفاعل",
  viewAll = "عرض الكل",
  fetchingPlayers = "جاري جلب اللاعبين",
  refresh = "تحديث",

  -- v2: Self-service & Categories
  selfServiceDealership = "وكالة خدمة ذاتية",
  categories = "الفئات",

  -- v2: Loading/Players UI
  loadingPlayers = "جاري تحميل اللاعبين...",
  failedToLoadPlayers = "فشل في تحميل اللاعبين",
  selectAPlayer = "اختر لاعباً",
  failedToLoadPlayersRetry = "فشل في تحميل اللاعبين. انقر 'تحديث' للمحاولة مرة أخرى.",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "المواقع",
  createNew = "إنشاء جديد",
  enable = "تفعيل",
  disable = "تعطيل",
  loading = "جاري التحميل...",
  errors = "أخطاء",
  update = "تحديث",
  create = "إنشاء",

  -- v2: Dealership creation/editing
  createDealership = "إنشاء وكالة",
  editDealership = "تعديل وكالة",
  essentials = "الأساسيات",
  advanced = "متقدم",
  noDealershipLocations = "لا توجد مواقع وكالات",
  noDealershipLocationsDesc = "يمكنك إضافة موقع جديد، أو الاستيراد من الإعدادات (إذا كنت تنتقل من الإصدار 1) أو إضافة بعض المواقع الافتراضية تلقائياً.",

  -- v2: Location sections
  dealershipZone = "منطقة الوكالة",
  showroomAndManagement = "صالة العرض والإدارة",
  openShowroom = "فتح صالة العرض",
  openManagement = "فتح الإدارة",
  enableSellVehicle = "تفعيل بيع المركبات",
  percentageOfVehicleValue = "نسبة مئوية % من قيمة المركبة",
  enablePurchase = "تفعيل الشراء",
  purchasedVehicleSpawn = "نقطة استدعاء المركبة المشتراة",
  enableTestDrive = "تفعيل تجربة القيادة",
  testDriveVehicleSpawn = "نقطة استدعاء مركبة تجربة القيادة",
  truckDelivery = "توصيل بالشاحنة",
  truckDeliveryVehicleSpawn = "نقطة استدعاء شاحنة التوصيل",

  -- v2: Location advanced settings
  paymentMethods = "طرق الدفع",
  supportsFinancing = "(يدعم التمويل)",
  enableFinance = "تفعيل التمويل",
  cameraPreset = "الكاميرا",
  preset = "إعداد مسبق",
  custom = "مخصص",
  vehiclePosition = "موضع المركبة",
  zoomPositions = "مواضع التكبير (مفصولة بفواصل)",
  zoomPositionsPlaceholder = "مثال: 5,8,12,8",
  vehicleColour = "لون المركبة",
  selectionType = "نوع الاختيار",
  noColourSelection = "بدون اختيار لون",
  rgbColourWheel = "عجلة ألوان RGB",
  listOfRgbColours = "قائمة ألوان RGB",
  listOfColourIds = "قائمة معرفات الألوان",
  accessControl = "التحكم في الوصول",
  showroomJobWhitelist = "القائمة البيضاء لوظائف صالة العرض",
  showroomGangWhitelist = "القائمة البيضاء لعصابات صالة العرض",
  societyPurchaseJobWhitelist = "القائمة البيضاء لوظائف شراء المجتمع",
  societyPurchaseGangWhitelist = "القائمة البيضاء لعصابات شراء المجتمع",
  setInGame = "تعيين داخل اللعبة",
  addNew = "إضافة جديد",

  -- v2: Job/Gang whitelist editor
  job = "الوظيفة",
  gang = "العصابة",
  jobWhitelist = "القائمة البيضاء للوظائف",
  gangWhitelist = "القائمة البيضاء للعصابات",
  addJob = "إضافة وظيفة",
  addGang = "إضافة عصابة",
  editJob = "تعديل وظيفة",
  editGang = "تعديل عصابة",
  manageJobs = "إدارة الوظائف",
  manageGangs = "إدارة العصابات",
  jobName = "اسم الوظيفة",
  gangName = "اسم العصابة",
  selectGrades = "اختر الرتب",
  selectAll = "اختر الكل",
  deselectAll = "إلغاء اختيار الكل",
  invalidJobName = "اسم وظيفة غير صالح. يرجى التحقق من إعدادات الإطار.",
  invalidGangName = "اسم عصابة غير صالح. يرجى التحقق من إعدادات الإطار.",
  grades = "الرتب",
  noJobsConfigured = "لا توجد وظائف مهيأة",
  noGangsConfigured = "لا توجد عصابات مهيأة",
  click = "انقر",
  toGetStarted = "للبدء.",
  more = "المزيد",
  jobPlaceholder = "على سبيل المثال: cardealer",
  jobOptionalDescription = "اختيارياً ربط أدوار الوكالة بوظيفة الإطار. عند توظيف/فصل الموظفين، سيتم تحديث وظيفتهم في الإطار أيضاً.",
  jobRankPermissions = "صلاحيات رتب الوظيفة",
  roleToJobRankMapping = "ربط الدور برتبة الوظيفة",
  addPerm = "إضافة صلاحية",

  -- v2: Colour selector
  searchColours = "البحث في الألوان...",
  noColoursFound = "لم يتم العثور على ألوان",

  -- v2: Interactions creator
  noInteractions = "لا توجد تفاعلات",
  highlightInteractions = "إبراز التفاعلات",
  explorationMode = "وضع الاستكشاف",
  pressEsc = "اضغط ESC",
  toWalkAround = "للتجول",
  toReturnToUI = "للعودة إلى الواجهة",
  points = "نقاط",
  location = "الموقع",
  manageLocations = "إدارة المواقع",

  -- v2: Interaction modal
  interactionType = "النوع",
  nicknameOptional = "اللقب (اختياري)",
  invalidModel = "موديل غير صالح",
  failedToValidateModel = "فشل في التحقق من الموديل",
  pedScenario = "سيناريو الشخصية",
  coords = "الإحداثيات",
  size = "الحجم",
  blip = "علامة الخريطة",
  enableBlip = "تفعيل علامة الخريطة",
  blipIconId = "معرف أيقونة العلامة",
  blipColourId = "معرف لون العلامة",
  blipSize = "حجم العلامة",
  marker = "العلامة",
  enableMarker = "تفعيل العلامة",
  markerStyleId = "معرف نمط العلامة",
  markerSize = "حجم العلامة",
  markerColor = "لون العلامة",
  markerBobUpAndDown = "حركة صعود وهبوط",
  markerFaceCamera = "مواجهة الكاميرا",
  markerRotate = "دوران",
  markerDrawOnEnts = "رسم على الكيانات",
  updatePosition = "تحديث الموضع",
  setPosition = "تعيين الموضع",

  -- v2: Interaction types
  interactionPoint = "نقطة",
  interactionPointDesc = "نقطة واحدة قابلة لتغيير الحجم، مع علامة اختيارية",
  interactionPolyzone = "منطقة متعددة",
  interactionPolyzoneDesc = "منطقة متعددة الإحداثيات لإنشاء منطقة تفاعل محددة",
  interactionVehicle = "مركبة",
  interactionVehicleDesc = "استدعاء موديل مركبة، مثالي لطرق التفاعل بالهدف أو واجهة النص ثلاثية الأبعاد",
  interactionObject = "كائن",
  interactionObjectDesc = "استدعاء موديل كائن، مثالي لطرق التفاعل بالهدف أو واجهة النص ثلاثية الأبعاد",
  interactionPed = "شخصية",
  interactionPedDesc = "استدعاء موديل شخصية مع سيناريو مهمة اختياري، مثالي لطرق التفاعل بالهدف أو واجهة النص ثلاثية الأبعاد",

  -- v2: Import modal
  importLocationsTitle = "استيراد المواقع",
  syncStockLabel = "مزامنة المخزون",
  syncStockDescription = "إضافة مركبات لمخزون كل وكالة بناءً على فئاتها",
  importSourceSelectorDesc = "يمكنك استيراد مجموعة من المواقع الافتراضية للإعداد الجاهز، أو استيراد مواقعك الحالية من الإعدادات إذا كنت تنتقل من الإصدار 1.",
  importSourceSelectorSkipDesc = "سيتم تخطي المواقع الموجودة بالفعل في قاعدة البيانات؛ سيتم استيراد المواقع الجديدة فقط.",
  successfullyImported = "تم الاستيراد بنجاح",
  alreadyExist = "موجود بالفعل",
  defaultLocations = "المواقع الافتراضية",
  defaultLocationsDesc = "استيراد مواقع وكالات مهيأة مسبقاً (PDM، الفاخرة، القوارب، الجوية، الشاحنات)",
  existingConfig = "الإعدادات الحالية",
  existingConfigDesc = "استيراد المواقع من config.lua (للانتقال من الإصدار 1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "هل تريد إضافة مركبات تلقائياً لمخزون هذه الوكالة بناءً على الفئات المختارة؟",
  categorySyncEditDesc = "لقد غيرت الفئات لهذه الوكالة. هل تريد تحديث مخزون المركبات تلقائياً؟",
  addVehicles = "إضافة مركبات",
  removeVehicles = "إزالة مركبات",
  fromNewCategories = "من الفئات الجديدة",
  fromSelectedCategories = "من الفئات المختارة",
  fromRemovedCategories = "من الفئات المحذوفة",
  categoriesAdded = "الفئات المضافة:",
  categoriesRemoved = "الفئات المحذوفة:",
  skip = "تخطي",
  syncStock = "مزامنة المخزون",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "التحقق من توفر المصدر...",
  vehiclesAvailableToImport = "مركبات متاحة للاستيراد",
  includesDealershipIds = "يتضمن معرفات الوكالات",
  sourceUnavailable = "المصدر غير متاح",
  noVehiclesAdminDescription = "يمكنك إضافة مركبات يدوياً أو استيرادها من الإطار.",
  appendBehaviour = "إلحاق",
  overwriteBehaviour = "استبدال",
  appendDescription = "إضافة المركبات الجديدة التي لا توجد في قاعدة البيانات فقط",
  overwriteDescription = "حذف جميع بيانات المركبات الحالية واستيراد جديد",
  stockAssignmentMethod = "طريقة تعيين المخزون",
  useDealershipIdsFromSource = "استخدام معرفات الوكالات من المصدر",
  matchByVehicleCategory = "المطابقة حسب فئة المركبة",
  byShopDescription = "سيتم تعيين المركبات للوكالات بناءً على حقل 'shop' في بيانات المصدر",
  byCategoryDescription = "سيتم تعيين المركبات للوكالات التي لها فئات مطابقة",
  overwriteWarning = "تحذير: الاستبدال سيحذف جميع المركبات والطلبات ومركبات العرض وبيانات المبيعات الحالية.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "جدول مركبات ESX",
  selectCategory = "اختر فئة",

  -- v2: Management menu items
  vehiclesMenu = "المركبات",
  displayVehiclesMenu = "مركبات العرض",
  ordersMenu = "الطلبات",
  salesMenu = "المبيعات",
  bankAccountMenu = "الحساب البنكي",
  employeesMenu = "الموظفين",
  couponsMenu = "القسائم",
  settingsMenu = "الإعدادات",
  noPermissionAccessManagement = "ليس لديك صلاحية للوصول إلى أي ميزات إدارية.",
  backToAdmin = "العودة للإدارة",
  viewingAsAdmin = "عرض كمسؤول",

  -- v2: Coupons table
  code = "الرمز",
  uses = "الاستخدامات",
  perPlayer = "لكل لاعب",
  never = "أبداً",
  noCoupons = "لا توجد قسائم",
  noCouponsDescription = "يمكن للعملاء إدخال قسيمة في مرحلة شراء المركبة وتوفير المال.",

  -- v2: Coupon modal
  couponCodeLabel = "رمز القسيمة",
  couponCodePlaceholder = "مثال: SUMMER2024 أو SAVE10",
  couponCodeHelp = "أدخل رمزاً مخصصاً (حتى 25 حرفاً، أحرف وأرقام وشرطات فقط) أو انقر 'إنشاء'.",
  maxNumberOfUsesPlaceholder = "الحد الأقصى لعدد الاستخدامات",
  maxUsesPerPlayerPlaceholder = "الحد الأقصى للاستخدامات لكل لاعب",
  vehicleRestrictionsPlaceholder = "أدخل رموز الاستدعاء مفصولة بفواصل (مثال: adder, t20, zentorno)",
  allowOnFinancedPurchases = "السماح في المشتريات الممولة",
  createCoupon = "إنشاء قسيمة",
  updateCoupon = "تحديث قسيمة",

  -- v2: Coupon validation messages
  couponCodeRequired = "رمز القسيمة مطلوب",
  couponCodeMaxLength = "الرمز يجب أن يكون 25 حرفاً أو أقل",
  couponCodeInvalidChars = "الرمز يمكن أن يحتوي على أحرف كبيرة وأرقام وشرطات فقط",
  discountTypeRequired = "نوع الخصم مطلوب",
  discountValueRequired = "قيمة الخصم مطلوبة",
  discountValueMin = "قيمة الخصم يجب أن تكون أكبر من 0",
  discountValueMaxPercent = "النسبة المئوية لا يمكن أن تتجاوز 100",
  maxUsesRequired = "الحد الأقصى للاستخدامات مطلوب",
  maxUsesMin = "يجب أن يكون 1 على الأقل",
  perPlayerLimitRequired = "حد اللاعب مطلوب",
  expiryDateRequired = "تاريخ انتهاء الصلاحية مطلوب",
  vehicleRestrictionsRequired = "قيود المركبات مطلوبة",
  categoryRestrictionsRequired = "قيود الفئات مطلوبة",
  selectAtLeastOneCategory = "اختر فئة واحدة على الأقل",

  -- v2: Dashboard
  today = "اليوم",
  thisMonth = "هذا الشهر",
  allTime = "كل الوقت",
  recentSales = "المبيعات الأخيرة",
  noSalesYet = "لا توجد مبيعات بعد!",
  noSalesDescription = "ستظهر مبيعات المركبات هنا بعد إجراء عملية بيع.",
  past7Days = "آخر 7 أيام",
  past6Months = "آخر 6 أشهر",
  numberOfSales = "عدد المبيعات",
  noDataAvailableForPeriod = "لا توجد بيانات متاحة لهذه الفترة",

  -- v2: Display vehicles
  displayVehiclesDescription = "مركبات العرض هي نماذج صالة عرض ثابتة تُستخدم لعرض مخزونك وجذب العملاء للشراء.",

  -- v2: Employees
  frameworkJobsEnabled = "وظائف الإطار مفعلة",
  frameworkJobsDescription = "تتم إدارة الموظفين من خلال نظام وظائف الإطار. اللاعبون الذين لديهم وظيفة الوكالة سيحصلون تلقائياً على صلاحيات بناءً على رتبة وظيفتهم. قم بتهيئة صلاحيات الوظائف في إعدادات الموقع في لوحة المسؤول.",
  joinedColumn = "تاريخ الانضمام",
  youBadge = "أنت",

  -- v2: Orders
  noOrdersTitle = "لا توجد طلبات",
  noOrdersDescription = "لتقديم طلب، افتح علامة تبويب 'المركبات' وانقر 'تقديم طلب' على المركبة التي تريد إعادة تخزينها.",
  inProgress = "قيد التنفيذ",
  awaitingDelivery = "في انتظار التسليم",
  orderedBy = "طلبه",
  viewDeliveryInfo = "عرض معلومات التسليم",

  -- v2: Delivery
  startDeliveryMissionTitle = "بدء مهمة التسليم",
  startDeliveryDescription = "أنت على وشك بدء مهمة تسليم لهذا الطلب. ستحتاج للقيادة إلى موقع الاستلام، وجمع مقطورة الشحن، وتسليمها إلى الوكالة.",
  totalDistanceAndDriveTime = "المسافة الإجمالية ووقت القيادة",
  roundTrip = "ذهاب وإياب",
  deliveryCompleteTitle = "اكتمل التسليم",
  deliveryInProgressTitle = "التسليم قيد التنفيذ",
  deliveredAt = "تم التسليم في:",
  startedAt = "بدأ في:",
  deliveredBy = "تم التسليم بواسطة:",
  beingDeliveredBy = "يتم التسليم بواسطة:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "لا توجد طلبات متاحة للتسليم. يجب أن تكون الطلبات جاهزة وليست في تسليم نشط.",
  confirmDeliveryTitle = "تأكيد التسليم",
  configureDeliveryTitle = "تهيئة التسليم",
  trailerCapacityExceeded = "تم تجاوز سعة المقطورة! لقد اخترت %{usedSlots} فتحة ولكن الحد الأقصى هو %{maxSlots} فتحة.",
  smallVehiclesSlotInfo = "تذكر: المركبات الصغيرة تستخدم فتحة واحدة، والمركبات المتوسطة تستخدم 1.5 فتحة.",
  fetchingRoute = "جاري الجلب...",
  getRouteButton = "الحصول على المسار",
  selectTrailerType = "اختر نوع المقطورة",
  carTrailerLabel = "ناقلة سيارات",
  smallMedium = "(صغير/متوسط)",
  containerLabel = "حاوية",
  large = "(كبير)",
  carTrailerDescription = "ناقلة السيارات بها صفان. كل صف يتسع لـ 3 صغيرة (فتحة واحدة لكل منها) أو 2 متوسطة (1.5 فتحة لكل منها). الحد الأقصى 6 فتحات.",
  containerDescription = "مقطورة الحاوية تحمل مركبة كبيرة واحدة",
  selectOrdersTitle = "اختر الطلبات",
  slots = "فتحات",
  noOrdersForTrailerType = "لا توجد طلبات متاحة لهذا النوع من المقطورات.",
  qty = "الكمية:",
  inTransit = "في الطريق",
  totalVehicles = "إجمالي المركبات:",
  estimatedTime = "الوقت المقدر:",
  unknown = "غير معروف",

  -- v2: Sales
  salesEmptyDescription = "ستظهر مبيعات المركبات هنا بعد إجراء عملية بيع.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "تم تقديم الطلب!",
  orderPlacedTruckingDescription = "طلبك جاهز للاستلام. اذهب إلى صفحة الطلبات لتنفيذه.",
  orderPlacedTimedDescription = "سيستغرق وصول طلبك %{value} دقيقة.",
  goToOrders = "الذهاب إلى الطلبات",
  noStockAvailableDescription = "لا يوجد مخزون متاح لهذه المركبة. تم الوصول إلى حد المخزون العالمي.",
  stockUpdatedDescription = "تم تحديث كمية المخزون بنجاح.",

  -- v2: Direct sales tablet
  activeTestDrives = "تجارب القيادة النشطة",
  tracking = "التتبع",
  track = "تتبع",
  endButton = "إنهاء",
  endTestDriveTitle = "إنهاء تجربة القيادة",
  endTestDriveConfirmation = "هل أنت متأكد أنك تريد إنهاء تجربة القيادة هذه؟ سيتم حذف المركبة ولن يتم نقل أي ركاب في المركبة إلى الوكالة.",
  vehicleLocationOnMap = "تم وضع موقع المركبة على خريطتك.",
  sell = "بيع",
  couponCodeOptional = "رمز القسيمة (اختياري)",
  pleaseEnterCouponCode = "يرجى إدخال رمز القسيمة",
  invalidCouponCode = "رمز قسيمة غير صالح",
  failedToValidateCoupon = "فشل في التحقق من القسيمة",
  apply = "تطبيق",
  applying = "جاري التطبيق...",
  allStock = "كل المخزون",
  inStockFilter = "متوفر",
  outOfStockFilter = "غير متوفر",
  noResultsFound = "لم يتم العثور على نتائج",
  noResults = "لا توجد نتائج",
  noVehiclesMatchSearch = "لا توجد مركبات تطابق بحثك",
  noVehiclesMatchFilters = "لا توجد مركبات تطابق الفلاتر الحالية",
  noItemsMatchSearch = "لا توجد عناصر تطابق بحثك",
  noItemsMatchFilters = "لا توجد عناصر تطابق الفلاتر الحالية",
  selectColour = "اختر اللون",
  refreshNearbyPlayers = "تحديث اللاعبين القريبين",
  you = "أنت",
  items = "عناصر",
  waitingForCustomerToRespond = "في انتظار قبول أو رفض العميل...",
  vehicleSpawnedMessage = "تم استدعاء المركبة في النقطة على خريطتك - اصطحب العميل إليها.",
  customerDeclinedMessage = "رفض العميل طلب الشراء.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "وقع هنا",
  acceptAndPurchase = "قبول وشراء",
  couponApplied = "تم تطبيق القسيمة %{code}! توفير %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "تحتاج 3 نقاط على الأقل لإكمال المنطقة! (لديك حالياً %{value})",
  addPoint = "إضافة نقطة",
  removeLast = "إزالة الأخير",
  completeZone = "إكمال المنطقة",
  spawnPreview = "معاينة الاستدعاء",
  up = "أعلى",
  down = "أسفل",
  confirm = "تأكيد",
  placePoint = "وضع نقطة",
  radius = "نصف القطر",

  -- v2: Blip labels
  soldVehicleLocation = "موقع المركبة المباعة",
  testDriveVehicleBlip = "مركبة تجربة القيادة",

  -- v2: Stock sync
  stockSyncResult = "مزامنة المخزون: تمت إضافة %{added}، إزالة %{removed}",
  stockSyncAdded = "مزامنة المخزون: تمت إضافة %{value} مركبة",
  importSuccessful = "نجح الاستيراد! تم استيراد %{imported} مركبة (الإجمالي %{total})",

  -- v2: Tooltip actions
  findOnMap = "البحث على الخريطة",
  adminPanel = "لوحة المسؤول",

  -- v2: Common dropdown
  selectOne = "اختر واحداً",
}
