Locales = Locales or {}

Locales['cn'] = {
  -- 界面
  vehicle = "车辆",
  vehicles = "车辆",
  dealership = "汽车销售商",
  dealerships = "汽车销售商",
  vehiclesCount = "辆车",
  dealersCount = "个销售商",
  accountBalance = "账户余额",
  bank = "银行账户",
  cash = "现金",
  amount = "金额",
  societyFund = "社团资金",
  paymentSource = "支付来源",
  purchase = "购买",
  personalPurchase = "个人购买",
  societyPurchase = "社团购买",
  purchaseType = "购买类型",
  deposit = "存款",
  withdraw = "取款",
  all = "全部",
  yes = "是",
  no = "否",
  add = "添加",
  edit = "编辑",
  id = "ID",
  created = "创建时间",
  type = "类型",
  name = "名称",
  owner = "拥有者",
  bankBalance = "银行余额",
  status = "状态",
  back = "返回",
  previous = "上一步",
  next = "下一步",
  admin = "管理员",
  vehiclesAdmin = "车辆管理员",
  dealershipsAdmin = "销售商管理员",
  search = "搜索",
  noDealershipsFound = "未找到销售商",
  noVehicles = "未找到车辆",
  page = "页",
  of = "共",
  every = "每",
  show = "显示",
  active = "启用",
  activeFinance = "启用融资",
  failed = "支付失败",
  removed = "已移除",
  setOwner = "设置拥有者",
  manage = "管理",
  deleteData = "删除数据",
  deleteVehicle = "删除车辆",
  delete = "删除",
  deleteConfirmation = "确定删除？",
  deleteConfirmationDanger = "确定删除？此操作不可逆。",
  setDealershipOwner = "设置销售商拥有者",
  overwriteDealerPrices = "覆盖销售商价格",
  nearbyPlayers = "附近玩家",
  noPlayersNearby = "附近没有玩家",
  selectPlayer = "选择玩家",
  required = "必填",
  forExample = "例如",
  spawnCode = "生成代码",
  brand = "品牌",
  model = "型号",
  category = "类别",
  price = "价格",
  import = "导入",
  importing = "正在导入",
  importBehaviour = "导入行为",
  importVehicles = "导入车辆",
  importFrom = "从...导入",
  dashboard = "仪表盘",
  displayVehicle = "展示车辆",
  displayVehicles = "展示车辆",
  orders = "订单",
  sales = "销售",
  vehiclesOnDisplay = "展厅展示车辆",
  employees = "员工",
  settings = "设置",
  switchVehicle = "切换车辆",
  remove = "移除",
  noDisplayVehicles = "没有展示车辆",
  selectVehicle = "选择车辆",
  colour = "颜色",
  placeVehicle = "放置车辆",
  orderVehicle = "订购车辆",
  cancelOrder = "取消订单",
  delivery = "交付",
  delivered = "已交付",
  noOrders = "没有找到订单",
  quantity = "数量",
  totalCost = "总成本",
  totalSales = "总销售额",
  noSales = "没有找到销售记录",
  paid = "已支付",
  owed = "欠款",
  dealershipName = "销售商名称",
  save = "保存更改",
  cancel = "取消",
  notEnoughMoney = "余额不足",
  placeOrder = "下订单",
  purchaseCost = "购买成本",
  salePrice = "销售价格",
  inStock = "库存",
  outOfStock = "售罄",
  placeVehiclePrompt = "按 %{value} 放置车辆。您可以之后做更细致的调整！",
  remaining = "剩余",
  prePurchaseRepoWarning = "如果您未能按时付款，您的车辆将被回收。",
  repossessionWarning = "您的最后一次付款失败——如果不立即付款，您的车辆将被回收。",
  recurringPayment = "定期付款",
  remainingBalance = "剩余余额",
  remainingPayments = "剩余付款次数",
  paymentTakenEvery = "每",
  hours = "小时",
  seconds = "秒",
  nextPayment = "下一次付款",
  makePayment = "付款",
  vehicleRepossessed = "车辆将被回收",
  payInFull = "一次性付款",
  earlyPaymentConfirmation = "确定要提前支付",
  financedVehicles = "融资车辆",
  noFinancedVehicles = "您没有融资车辆",
  financeBreakdown = "融资明细",
  initialPayment = "首付",
  payments = "付款次数",
  length = "期限",
  interest = "利率",
  totalPayable = "总需支付",
  leaveShowroom = "离开展厅",
  handling = "操控",
  topSpeed = "最高速度",
  power = "功率",
  torque = "扭矩",
  brake = "刹车",
  financing = "融资",
  financingAvailable = "提供融资",
  paymentsOf = "每期付款",
  clear = "清除",
  testDrive = "试驾",
  allCategories = "所有类别",
  sortByName = "按名称排序",
  sortByAvailability = "按可用性排序",
  sortByCheapest = "按最便宜排序",
  sortByMostExpensive = "按最贵排序",
  sortByNewest = "按最新排序",
  purchaseVehicle = "购买车辆",
  purchaseFor = "为...购买",
  selectSociety = "选择社团",
  financeOverPayments = "分期付款 %{value} 次",
  payToday = "今天付款",
  financeThen = "然后",
  seeFullBreakdown = "查看完整明细",
  testDriveExit = "您可以随时离开车辆以结束试驾。",

  -- 通知
  purchaseSuccess = "恭喜您购买成功！",
  depositSuccess = "存款成功",
  withdrawSuccess = "取款成功",
  errorNotEnoughMoney = "余额不足",
  errorVehicleOutOfStock = "该车辆已售罄",
  errorCannotAffordVehicle = "您无法购买此车辆",
  vehicleFinancePaymentMade = "您的车辆 %{value} 已成功付款",
  vehicleFinancePaidOff = "恭喜您已付清并拥有车辆 %{value}",
  vehicleFinancePaymentFailed = "您的车辆 %{value} 付款失败",
  vehicleFinanceRepossessedSoon = "您需要支付车辆 %{value} 欠款，否则将被回收",
  vehicleFinanceRepossessed = "由于未支付款项，您的车辆（车牌 %{value}）已被回收",
  dealershipNotEnoughFunds = "销售商资金不足",
  dealershipVehiclesOrdered = "车辆已成功订购",
  dealershipOrderCancelled = "订单已成功取消",
  errorVehicleWithSpawnCodeExists = "该生成代码对应的车辆已存在",
  errorExitVehicle = "您需要先下车",
  errorPlacementCollision = "您不能在这里放置车辆",

  -- 新增 v1.1
  purchaseRequest = "购买请求",
  sendRequest = "发送请求",
  dealer = "销售商",
  financed = "已融资",
  signHere = "请在此签名",
  signFirstError = "请先签名",
  denyRequest = "拒绝请求",
  playerTooManyFinancedVehicles = "玩家拥有的融资车辆过多",
  employeePermissionsError = "您没有足够的员工权限",
  managerRole = "经理",
  supervisorRole = "主管",
  salesRole = "销售",
  ownerRole = "拥有者",
  employmentRequest = "招聘申请",
  accept = "接受",
  jobOfferDescription = "您已获得来自 \"%{value}\" 销售商的工作邀请。您愿意接受吗？",
  pending = "待定",
  employeeHiredMsg = "销售商已接受您的聘用请求！",
  employeeRejectedMsg = "销售商已拒绝您的聘用请求",
  sellVehicle = "出售车辆",
  vehicleTerms = "车辆条款",
  financePayments = "融资付款",
  commission = "佣金",
  role = "角色",
  firedNotification = "您已被 \"%{value}\" 销售商解雇",
  dealershipTooFarAway = "您距离任何销售商太远",
  restoreDisplayVehicles = "恢复展厅",
  customer = "客户",
  lessThanAMin = "少于一分钟",
  mins = "分钟",
  notInVehicle = "您没有坐在车辆中",
  notYourVehicleError = "这不是您的车辆",
  vehicleFinancedError = "此车辆有未付清的融资款项，不能出售",
  dealershipDoesntSellVehicle = "此销售商不出售该车辆",
  dealershipWantsYourVehicle = "恭喜！此销售商愿意购买您的车辆。",
  purchasePrice = "报价：",

  spawnCodeInvalid = "生成代码无效",
  salesRep = "销售代表",
  directSaleAccepted = "直接销售请求已接受！您的佣金已支付。",
  directSaleRejected = "直接销售请求已拒绝",

  displayVehicleOutsideZone = "展示车辆必须放置在经销商区域内",
  serverAdmin = "服务器管理员",
  selfService = "自助服务",
  owned = "已拥有",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "无效的支付方式",
  paymentMethodNoFinance = "此支付方式不支持分期付款",
  couldNotGeneratePlate = "无法生成车牌",
  invalidCoupon = "无效优惠券：%{value}",
  tooManyFinancedVehicles = "您的分期付款车辆过多",
  couldNotSpawnVehicle = "无法生成车辆",

  -- v2: Permissions
  insufficientPermissions = "权限不足",

  -- v2: Coupons
  couponCodeAlreadyExists = "优惠券代码已存在",
  failedToCreateCoupon = "创建优惠券失败",
  couponCreatedSuccessfully = "优惠券创建成功",
  couponNotFound = "未找到优惠券",
  couponUpdatedSuccessfully = "优惠券更新成功",
  failedToDeleteCoupon = "删除优惠券失败",
  couponDeletedSuccessfully = "优惠券删除成功",
  editCoupon = "编辑优惠券",
  addCoupon = "添加优惠券",
  couponCode = "优惠券代码",
  generating = "生成中...",
  generate = "生成",
  discountType = "折扣类型",
  percentageOff = "百分比折扣",
  amountOff = "金额折扣",
  discountValue = "折扣值",
  unlimitedTotalUses = "无限总使用次数",
  unlimitedUsesPerPlayer = "每位玩家无限使用",
  setExpiryDate = "设置到期日期",
  restrictToSpecificVehicles = "限制特定车辆",
  restrictToSpecificCategories = "限制特定类别",
  allowUseWithFinance = "允许与分期付款一起使用",
  deleteCoupon = "删除优惠券",
  inactive = "未激活",
  expired = "已过期",
  maxUses = "最大使用次数",
  coupons = "优惠券",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "只有服务器管理员可以自雇",
  playerNotFound = "未找到玩家",
  failedToHireEmployee = "雇用员工失败",
  failedToFireEmployee = "解雇员工失败",
  failedToUpdateEmployeeRole = "更新员工角色失败",
  hireEmployee = "雇用员工",
  fireEmployee = "解雇员工",
  editRole = "编辑角色",
  fire = "解雇",
  changeRole = "更改角色",
  updateRole = "更新角色",

  -- v2: Test drives
  maxTestDrivesReached = "该经销商已达到最大活跃试驾次数",
  testDriveNotEnabled = "该经销商未启用试驾",
  noTestDriveSpawnCoords = "该经销商未配置试驾生成坐标",
  couldNotSpawnTestDriveVehicle = "无法生成试驾车辆",
  couldNotGetPlateFromServer = "无法从服务器获取车牌",
  couldNotRegisterTestDriveVehicle = "无法注册试驾车辆",
  testDriveEndedByEmployee = "试驾已被其他员工结束",
  trackingVehicleLocation = "正在追踪车辆位置...",
  directSaleCancelled = "销售请求已被销售员取消",
  testDriveKeysReceived = "您已收到试驾车辆的钥匙",
  testDriveEndedCustomer = "试驾已结束",
  starting = "启动中...",
  startTestDrive = "开始试驾",
  spawningTestDriveVehicle = "正在生成试驾车辆...",
  testDriveReady = "试驾已准备就绪",
  testDriveWalkToVehicle = "试驾车辆已在您地图上标记的位置生成。请带领客户前往车辆。将钥匙交给客户后，您需要在客户返回时手动结束试驾。",
  givingKeys = "正在交付钥匙...",
  continueAndGiveKeys = "继续并交付钥匙",
  endTestDrive = "结束试驾",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "该车辆无库存",
  globalStockLimitExceeded = "仅剩 %{value} 台可用",
  orderNotFoundOrFulfilled = "订单未找到或已完成",
  priceBelowMinimum = "价格不能低于 %{value}",
  priceAboveMaximum = "价格不能高于 %{value}",
  stockUpdated = "库存已更新",
  changesSaved = "更改已保存",
  noStockAvailable = "无可用库存",
  orderPlaced = "订单已提交",
  remainingInStock = "全球库存剩余",
  exceedsStockLimit = "超出库存限制",
  setStockQty = "设置库存数量",
  invalidStockValue = "请输入有效的库存值",
  errorSettingStock = "设置库存时出错",
  stockQuantity = "库存数量",
  currentStock = "当前库存",
  priceLimitsEnabled = "启用价格限制",
  priceLimitsDescription = "启用后，经销商管理者只能在指定范围内设置价格。",
  minPrice = "最低价格",
  maxPrice = "最高价格",
  optional = "可选",
  unlimitedStock = "无限库存",
  globalStockLimit = "全球库存限制",
  globalStockLimitDescription = "设置所有经销商可订购的最大单位数量。",
  currentlyOrdered = "当前已订购",
  priceRange = "价格范围",
  noMinimum = "无最低限制",
  noMaximum = "无最高限制",
  vehicleStock = "车辆库存",

  -- v2: Sales
  allSales = "所有销售",
  paidInFull = "全额付款",
  salesVolume = "销售量",
  pastMonth = "上个月",
  pastYear = "去年",

  -- v2: Management misc
  exploitAttemptDetected = "请停止尝试利用脚本漏洞",
  dealershipNoJobConfigured = "该经销商未配置职业",
  modelDoesNotMatchDb = "车辆型号与数据库不匹配",
  importFailed = "导入失败：%{value}",
  notInDealershipZone = "您必须在经销商区域内才能使用此命令",
  notAnEmployee = "您不是该经销商的员工。",
  failedToPrepareDelivery = "准备交付失败",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "车辆型号不存在 - 请联系管理员",
  vehiclePlateInvalid = "该车辆的车牌无效（按F8获取更多详情）",
  currentlyInRagdollState = "您目前处于倒地状态",
  vehicleDoesNotExistContactAdmin = "车辆不存在。请联系管理员！",
  vehicleSecurityBreachDetected = "检测到车辆安全漏洞",

  -- v2: Admin vehicles
  allVehicles = "所有车辆",
  unassignedVehicles = "未分配经销商",
  searchDealerships = "搜索经销商...",

  -- v2: Trucking mission
  truckingGetInTruck = "进入标记位置的卡车以开始您的交付",
  truckingDriveToDelivery = "驾驶前往交付地点",
  truckingCompleteDelivery = "完成交付",
  truckingDeliveryComplete = "交付完成：您已成功完成交付！",
  truckingDeliveryFailed = "交付失败：交付过程中出现问题",
  truckingDriveToPickup = "驾驶前往取货点取挂车",
  truckingMissionFailedSpawnCargo = "任务失败：无法生成货运挂车",
  truckingMissionFailedFindCargo = "任务失败：无法找到生成的货物",
  truckingVehiclesLoaded = "已装载 %{count} 辆车",
  truckingWrongTrailer = "错误的挂车！您必须连接正确的任务挂车。",
  truckingTrailerAttached = "挂车已连接 - 准备继续",
  truckingDriveToPickupLocation = "驾驶前往取货点",
  truckingWaitingForVehicles = "等待车辆装载...",
  truckingDriveUnderTrailer = "驾驶到挂车下方进行连接",
  truckingGetInTruckContinue = "进入卡车以继续",
  truckingMissionStarted = "运输任务已开始：取货点 - %{location}",
  truckingMissionCancelled = "任务已取消：您已取消运输任务",
  truckingNoActiveMission = "没有活跃的运输任务可取消",
  deliveryNotPrepared = "交付未准备好 - 请重试",
  deliveryConfigMismatch = "交付配置不匹配",
  deliveryPreparationExpired = "交付准备已过期 - 请重试",
  noTruckingVehicleCoordinates = "未设置运输车辆坐标",
  pickupLocationUnavailable = "取货点已不可用 - 请重试",
  failedToSpawnTruck = "生成卡车失败",
  clientFailedToStartMission = "客户端启动任务失败",

  -- v2: Trucking UI/Keys
  keyDismiss = "关闭",
  keyDeliverCargo = "交付货物",
  keyContinueToDelivery = "继续交付",
  startDeliveryMission = "开始交付任务",
  orderDetails = "订单详情",
  pickupLocation = "取货点",
  deliveryStatus = "交付状态",
  selectOrders = "选择订单",
  carTrailer = "汽车拖车",
  container = "集装箱",
  deliveryRoute = "交付路线",
  startDelivery = "开始交付",

  -- v2: Direct sales UI
  waitingForCustomer = "等待客户",
  cancelRequest = "取消请求",
  saleComplete = "销售完成！",
  done = "完成",
  saleDeclined = "销售被拒绝",
  close = "关闭",

  -- v2: Display vehicle placement
  movement = "移动",
  rotate = "旋转",
  forward = "前进",
  backward = "后退",
  left = "左",
  right = "右",
  rotateLeft = "向左旋转",
  rotateRight = "向右旋转",

  -- v2: Showroom misc
  originalPrice = "原价",
  discount = "折扣",
  createInteraction = "创建交互",
  viewAll = "查看全部",
  fetchingPlayers = "获取玩家中",
  refresh = "刷新",

  -- v2: Self-service & Categories
  selfServiceDealership = "自助服务经销商",
  categories = "分类",

  -- v2: Loading/Players UI
  loadingPlayers = "正在加载玩家...",
  failedToLoadPlayers = "加载玩家失败",
  selectAPlayer = "选择一个玩家",
  failedToLoadPlayersRetry = "加载玩家失败。点击'刷新'重试。",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "位置",
  createNew = "新建",
  enable = "启用",
  disable = "禁用",
  loading = "加载中...",
  errors = "错误",
  update = "更新",
  create = "创建",

  -- v2: Dealership creation/editing
  createDealership = "创建经销商",
  editDealership = "编辑经销商",
  essentials = "基础设置",
  advanced = "高级设置",
  noDealershipLocations = "没有经销商位置",
  noDealershipLocationsDesc = "您可以添加新位置、从配置导入（如果从v1迁移）或自动添加一些默认位置。",

  -- v2: Location sections
  dealershipZone = "经销商区域",
  showroomAndManagement = "展厅与管理",
  openShowroom = "打开展厅",
  openManagement = "打开管理",
  enableSellVehicle = "启用车辆销售",
  percentageOfVehicleValue = "车辆价值的百分比%",
  enablePurchase = "启用购买",
  purchasedVehicleSpawn = "已购车辆生成点",
  enableTestDrive = "启用试驾",
  testDriveVehicleSpawn = "试驾车辆生成点",
  truckDelivery = "卡车配送",
  truckDeliveryVehicleSpawn = "卡车配送车辆生成点",

  -- v2: Location advanced settings
  paymentMethods = "支付方式",
  supportsFinancing = "(支持分期)",
  enableFinance = "启用分期付款",
  cameraPreset = "相机",
  preset = "预设",
  custom = "自定义",
  vehiclePosition = "车辆位置",
  zoomPositions = "缩放位置（逗号分隔）",
  zoomPositionsPlaceholder = "示例: 5,8,12,8",
  vehicleColour = "车辆颜色",
  selectionType = "选择类型",
  noColourSelection = "无颜色选择",
  rgbColourWheel = "RGB色轮",
  listOfRgbColours = "RGB颜色列表",
  listOfColourIds = "颜色ID列表",
  accessControl = "访问控制",
  showroomJobWhitelist = "展厅职业白名单",
  showroomGangWhitelist = "展厅帮派白名单",
  societyPurchaseJobWhitelist = "社团购买职业白名单",
  societyPurchaseGangWhitelist = "社团购买帮派白名单",
  setInGame = "游戏内设置",
  addNew = "新增",

  -- v2: Job/Gang whitelist editor
  job = "职业",
  gang = "帮派",
  jobWhitelist = "职业白名单",
  gangWhitelist = "帮派白名单",
  addJob = "添加职业",
  addGang = "添加帮派",
  editJob = "编辑职业",
  editGang = "编辑帮派",
  manageJobs = "管理职业",
  manageGangs = "管理帮派",
  jobName = "职业名称",
  gangName = "帮派名称",
  selectGrades = "选择等级",
  selectAll = "全选",
  deselectAll = "取消全选",
  invalidJobName = "无效的职业名称。请检查框架配置。",
  invalidGangName = "无效的帮派名称。请检查框架配置。",
  grades = "等级",
  noJobsConfigured = "未配置职业",
  noGangsConfigured = "未配置帮派",
  click = "点击",
  toGetStarted = "开始。",
  more = "更多",
  jobPlaceholder = "例如: cardealer",
  jobOptionalDescription = "可选择将经销商角色绑定到框架职业。当员工被雇用/解雇时，他们的框架职业也会更新。",
  jobRankPermissions = "职业等级权限",
  roleToJobRankMapping = "角色到职业等级映射",
  addPerm = "添加权限",

  -- v2: Colour selector
  searchColours = "搜索颜色...",
  noColoursFound = "未找到颜色",

  -- v2: Interactions creator
  noInteractions = "无交互",
  highlightInteractions = "高亮交互",
  explorationMode = "探索模式",
  pressEsc = "按ESC",
  toWalkAround = "四处走动",
  toReturnToUI = "返回界面",
  points = "点",
  location = "位置",
  manageLocations = "管理位置",

  -- v2: Interaction modal
  interactionType = "类型",
  nicknameOptional = "昵称（可选）",
  invalidModel = "无效模型",
  failedToValidateModel = "验证模型失败",
  pedScenario = "NPC场景",
  coords = "坐标",
  size = "大小",
  blip = "标记",
  enableBlip = "启用标记",
  blipIconId = "标记图标ID",
  blipColourId = "标记颜色ID",
  blipSize = "标记大小",
  marker = "标志",
  enableMarker = "启用标志",
  markerStyleId = "标志样式ID",
  markerSize = "标志大小",
  markerColor = "标志颜色",
  markerBobUpAndDown = "上下浮动",
  markerFaceCamera = "面向相机",
  markerRotate = "旋转",
  markerDrawOnEnts = "绘制在实体上",
  updatePosition = "更新位置",
  setPosition = "设置位置",

  -- v2: Interaction types
  interactionPoint = "点",
  interactionPointDesc = "单个可调整大小的点，带可选标志",
  interactionPolyzone = "多边形区域",
  interactionPolyzoneDesc = "多坐标区域用于创建特定交互区域",
  interactionVehicle = "车辆",
  interactionVehicleDesc = "生成车辆模型，适合目标或3D文本UI交互方式",
  interactionObject = "物体",
  interactionObjectDesc = "生成物体模型，适合目标或3D文本UI交互方式",
  interactionPed = "NPC",
  interactionPedDesc = "生成带可选任务场景的NPC模型，适合目标或3D文本UI交互方式",

  -- v2: Import modal
  importLocationsTitle = "导入位置",
  syncStockLabel = "同步库存",
  syncStockDescription = "根据类别向每个经销商的库存添加车辆",
  importSourceSelectorDesc = "您可以导入一组默认位置以获得即用设置，或者如果您正在从v1迁移，则导入现有配置中的位置。",
  importSourceSelectorSkipDesc = "数据库中已存在的位置将被跳过；只会导入新位置。",
  successfullyImported = "成功导入",
  alreadyExist = "已存在",
  defaultLocations = "默认位置",
  defaultLocationsDesc = "导入预配置的经销商位置（PDM、豪华、游艇、航空、卡车）",
  existingConfig = "现有配置",
  existingConfigDesc = "从config.lua导入位置（用于v1迁移）",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "是否要根据选定的类别自动向此经销商的库存添加车辆？",
  categorySyncEditDesc = "您已更改此经销商的类别。是否要自动更新车辆库存？",
  addVehicles = "添加车辆",
  removeVehicles = "移除车辆",
  fromNewCategories = "从新类别",
  fromSelectedCategories = "从选定类别",
  fromRemovedCategories = "从已移除类别",
  categoriesAdded = "已添加类别:",
  categoriesRemoved = "已移除类别:",
  skip = "跳过",
  syncStock = "同步库存",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "检查源可用性...",
  vehiclesAvailableToImport = "可导入的车辆",
  includesDealershipIds = "包含经销商ID",
  sourceUnavailable = "源不可用",
  noVehiclesAdminDescription = "您可以手动添加车辆或从框架导入。",
  appendBehaviour = "追加",
  overwriteBehaviour = "覆盖",
  appendDescription = "仅添加数据库中不存在的新车辆",
  overwriteDescription = "删除所有现有车辆数据并重新导入",
  stockAssignmentMethod = "库存分配方式",
  useDealershipIdsFromSource = "使用源中的经销商ID",
  matchByVehicleCategory = "按车辆类别匹配",
  byShopDescription = "车辆将根据源数据中的'shop'字段分配给经销商",
  byCategoryDescription = "车辆将分配给具有匹配类别的经销商",
  overwriteWarning = "警告：覆盖将删除所有现有车辆、订单、展示车辆和销售数据。",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX车辆表",
  selectCategory = "选择分类",

  -- v2: Management menu items
  vehiclesMenu = "车辆",
  displayVehiclesMenu = "展示车辆",
  ordersMenu = "订单",
  salesMenu = "销售",
  bankAccountMenu = "银行账户",
  employeesMenu = "员工",
  couponsMenu = "优惠券",
  settingsMenu = "设置",
  noPermissionAccessManagement = "您没有权限访问任何管理功能。",
  backToAdmin = "返回管理",
  viewingAsAdmin = "以管理员身份查看",

  -- v2: Coupons table
  code = "代码",
  uses = "使用次数",
  perPlayer = "每位玩家",
  never = "永不",
  noCoupons = "无优惠券",
  noCouponsDescription = "客户可以在购买车辆时输入优惠券并节省费用。",

  -- v2: Coupon modal
  couponCodeLabel = "优惠券代码",
  couponCodePlaceholder = "例如: SUMMER2024 或 SAVE10",
  couponCodeHelp = "输入自定义代码（最多25个字符，仅限字母、数字和短横线）或点击'生成'。",
  maxNumberOfUsesPlaceholder = "最大使用次数",
  maxUsesPerPlayerPlaceholder = "每位玩家最大使用次数",
  vehicleRestrictionsPlaceholder = "输入以逗号分隔的生成代码（例如: adder, t20, zentorno）",
  allowOnFinancedPurchases = "允许用于分期购买",
  createCoupon = "创建优惠券",
  updateCoupon = "更新优惠券",

  -- v2: Coupon validation messages
  couponCodeRequired = "优惠券代码必填",
  couponCodeMaxLength = "代码必须为25个字符或更少",
  couponCodeInvalidChars = "代码只能包含大写字母、数字和短横线",
  discountTypeRequired = "折扣类型必填",
  discountValueRequired = "折扣值必填",
  discountValueMin = "折扣值必须大于0",
  discountValueMaxPercent = "百分比不能超过100",
  maxUsesRequired = "最大使用次数必填",
  maxUsesMin = "至少为1",
  perPlayerLimitRequired = "每位玩家限制必填",
  expiryDateRequired = "到期日期必填",
  vehicleRestrictionsRequired = "车辆限制必填",
  categoryRestrictionsRequired = "类别限制必填",
  selectAtLeastOneCategory = "至少选择一个类别",

  -- v2: Dashboard
  today = "今天",
  thisMonth = "本月",
  allTime = "全部时间",
  recentSales = "最近销售",
  noSalesYet = "暂无销售！",
  noSalesDescription = "完成销售后，车辆销售将显示在这里。",
  past7Days = "过去7天",
  past6Months = "过去6个月",
  numberOfSales = "销售数量",
  noDataAvailableForPeriod = "此期间无可用数据",

  -- v2: Display vehicles
  displayVehiclesDescription = "展示车辆是固定的展厅模型，用于展示您的库存并吸引客户购买。",

  -- v2: Employees
  frameworkJobsEnabled = "框架职业已启用",
  frameworkJobsDescription = "员工管理通过框架的职业系统处理。拥有经销商职业的玩家将根据其职业等级自动获得访问权限。在管理面板的位置设置中配置职业权限。",
  joinedColumn = "加入时间",
  youBadge = "你",

  -- v2: Orders
  noOrdersTitle = "无订单",
  noOrdersDescription = "要下订单，打开'车辆'标签并点击要补货的车辆上的'下订单'。",
  inProgress = "进行中",
  awaitingDelivery = "等待配送",
  orderedBy = "订购者",
  viewDeliveryInfo = "查看配送信息",

  -- v2: Delivery
  startDeliveryMissionTitle = "开始配送任务",
  startDeliveryDescription = "您即将开始此车辆订单的配送任务。您需要驾驶到取货点，收集货运挂车，然后将其送回经销商。",
  totalDistanceAndDriveTime = "总距离和行驶时间",
  roundTrip = "往返",
  deliveryCompleteTitle = "配送完成",
  deliveryInProgressTitle = "配送中",
  deliveredAt = "送达时间:",
  startedAt = "开始时间:",
  deliveredBy = "配送人:",
  beingDeliveredBy = "正在配送:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "没有可配送的订单。订单必须准备就绪且不在活跃配送中。",
  confirmDeliveryTitle = "确认配送",
  configureDeliveryTitle = "配置配送",
  trailerCapacityExceeded = "超出挂车容量！您选择了 %{usedSlots} 个槽位，但最大为 %{maxSlots} 个槽位。",
  smallVehiclesSlotInfo = "提示：小型车辆使用1个槽位，中型车辆使用1.5个槽位。",
  fetchingRoute = "获取中...",
  getRouteButton = "获取路线",
  selectTrailerType = "选择挂车类型",
  carTrailerLabel = "汽车拖车",
  smallMedium = "(小型/中型)",
  containerLabel = "集装箱",
  large = "(大型)",
  carTrailerDescription = "汽车拖车有2排。每排可装3辆小型（每辆1个槽位）或2辆中型（每辆1.5个槽位）。最多6个槽位。",
  containerDescription = "集装箱挂车可装载1辆大型车辆",
  selectOrdersTitle = "选择订单",
  slots = "槽位",
  noOrdersForTrailerType = "此挂车类型没有可用订单。",
  qty = "数量:",
  inTransit = "运输中",
  totalVehicles = "车辆总数:",
  estimatedTime = "预计时间:",
  unknown = "未知",

  -- v2: Sales
  salesEmptyDescription = "完成销售后，车辆销售将显示在这里。",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "订单已提交！",
  orderPlacedTruckingDescription = "您的订单已准备好取货。前往订单页面完成它。",
  orderPlacedTimedDescription = "您的订单将在 %{value} 分钟后送达。",
  goToOrders = "前往订单",
  noStockAvailableDescription = "此车辆无可用库存。已达到全球库存限制。",
  stockUpdatedDescription = "库存数量已成功更新。",

  -- v2: Direct sales tablet
  activeTestDrives = "活跃试驾",
  tracking = "追踪",
  track = "追踪",
  endButton = "结束",
  endTestDriveTitle = "结束试驾",
  endTestDriveConfirmation = "确定要结束此试驾吗？车辆将被删除，车内乘客不会被传送回经销商。",
  vehicleLocationOnMap = "车辆位置已标记在您的地图上。",
  sell = "销售",
  couponCodeOptional = "优惠券代码（可选）",
  pleaseEnterCouponCode = "请输入优惠券代码",
  invalidCouponCode = "无效的优惠券代码",
  failedToValidateCoupon = "验证优惠券失败",
  apply = "应用",
  applying = "应用中...",
  allStock = "全部库存",
  inStockFilter = "有库存",
  outOfStockFilter = "缺货",
  noResultsFound = "未找到结果",
  noResults = "无结果",
  noVehiclesMatchSearch = "没有车辆匹配您的搜索",
  noVehiclesMatchFilters = "没有车辆匹配当前筛选条件",
  noItemsMatchSearch = "没有项目匹配您的搜索",
  noItemsMatchFilters = "没有项目匹配当前筛选条件",
  selectColour = "选择颜色",
  refreshNearbyPlayers = "刷新附近玩家",
  you = "你",
  items = "项目",
  waitingForCustomerToRespond = "等待客户接受或拒绝...",
  vehicleSpawnedMessage = "车辆已在地图标记点生成 - 带客户前往。",
  customerDeclinedMessage = "客户拒绝了购买请求。",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "在此签名",
  acceptAndPurchase = "接受并购买",
  couponApplied = "优惠券 %{code} 已应用！节省 %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "至少需要3个点才能完成区域！（当前有 %{value} 个）",
  addPoint = "添加点",
  removeLast = "移除最后一个",
  completeZone = "完成区域",
  spawnPreview = "生成预览",
  up = "上",
  down = "下",
  confirm = "确认",
  placePoint = "放置点",
  radius = "半径",

  -- v2: Blip labels
  soldVehicleLocation = "已售车辆位置",
  testDriveVehicleBlip = "试驾车辆",

  -- v2: Stock sync
  stockSyncResult = "库存同步: 添加 %{added}，移除 %{removed}",
  stockSyncAdded = "库存同步: 添加了 %{value} 辆车",
  importSuccessful = "导入成功！导入了 %{imported} 辆车（共 %{total} 辆）",

  -- v2: Tooltip actions
  findOnMap = "在地图上查找",
  adminPanel = "管理面板",

  -- v2: Common dropdown
  selectOne = "选择一个",
}
