Locales = Locales or {}

Locales['cs'] = {
  -- UI
  vehicle = "Vozidlo",
  vehicles = "Vozidla",
  dealership = "Prodejna vozidel",
  dealerships = "Prodejny vozidel",
  vehiclesCount = "vozidlo(a)",
  dealersCount = "Obchodníci",
  accountBalance = "Zůstatek na účtu",
  bank = "Bankovní účet",
  cash = "Hotovost",
  amount = "Množství",
  societyFund = "Společenský fond",
  paymentSource = "Způsob platby",
  purchase = "Nákup",
  personalPurchase = "Osobní nákup",
  societyPurchase = "Nákup společnosti",
  purchaseType = "Typ nákupu",
  deposit = "Vklad",
  withdraw = "Vybrat",
  all = "Vše",
  yes = "Ano",
  no = "Ne",
  add = "Přidat",
  edit = "Upravit",
  id = "ID",
  created = "Vytvořil",
  type = "Typ",
  name = "Jméno",
  owner = "Vlastník",
  bankBalance = "Bankovní zůstatek",
  status = "Stav",
  back = "Zpět",
  previous = "Předchozí",
  next = "Další",
  admin = "Admin",
  vehiclesAdmin = "Správce vozidel",
  dealershipsAdmin = "Správce prodejen",
  search = "Hledání",
  noDealershipsFound = "Nebyli nalezeni žádní prodejci",
  noVehicles = "Nebyla nalezena žádná vozidla",
  page = "Stránka",
  of = "z",
  every = "každý",
  show = "Ukázat",
  active = "Aktivní",
  activeFinance = "Aktivní finance",
  failed = "Platba se nezdařila",
  removed = "Odstraněný",
  setOwner = "Nastavit vlastníka",
  manage = "Spravovat",
  deleteData = "Smazání dat",
  deleteVehicle = "Smazat vozidlo",
  delete = "Vymazat",
  deleteConfirmation = "Opravdu?",
  deleteConfirmationDanger = "Opravdu? Tato akce je nevratná.",
  setDealershipOwner = "Nastavit majitele prodejny",
  overwriteDealerPrices = "Přepsání prodejních cen",
  nearbyPlayers = "Hráči v okolí",
  noPlayersNearby = "V okolí nejsou žádní hráči",
  selectPlayer = "Vyberte hráče",
  required = "Požadovaný",
  forExample = "Například",
  spawnCode = "Kód pro spawn",
  brand = "Značka",
  model = "Model",
  category = "Kategorie",
  price = "Cena",
  import = "Dovoz",
  importing = "Importování",
  importBehaviour = "Chování při importu",
  importVehicles = "Importovaná vozidla",
  importFrom = "Dovoz z",
  dashboard = "Hlavní",
  displayVehicle = "Zobrazit vozidlo",
  displayVehicles = "Zobrazit vozidla",
  orders = "Objednávky",
  sales = "Prodej",
  vehiclesOnDisplay = "Vystavená vozidla",
  employees = "Zaměstnanci",
  settings = "Nastavení",
  switchVehicle = "Přepnout vozidlo",
  remove = "Odstranit",
  noDisplayVehicles = "Žádná vystavená vozidla",
  selectVehicle = "Vybrat vozidlo",
  colour = "Barva",
  placeVehicle = "Místo vozidla",
  orderVehicle = "Objednat vozidlo",
  cancelOrder = "Zrušit objednávku",
  delivery = "Doručení",
  delivered = "Doručil",
  noOrders = "Nebyly nalezeny žádné objednávky",
  quantity = "Množství",
  totalCost = "Celkové náklady",
  totalSales = "Celkové tržby",
  noSales = "Nebyl nalezen žádný prodej",
  paid = "Zaplaceno",
  owed = "Dlužil",
  dealershipName = "Název prodejny",
  save = "Uložit změny",
  cancel = "Zrušit",
  notEnoughMoney = "Nedostatek peněz",
  placeOrder = "Zadat objednávku",
  purchaseCost = "Nákupní náklady",
  salePrice = "Prodejní cena",
  inStock = "Na skladě",
  outOfStock = "Není skladem",
  placeVehiclePrompt = "Stiskněte %{value} umístit vozidlo. Poté můžete provést menší úpravy!",
  remaining = "Zbývající",
  prePurchaseRepoWarning = "Pokud nebudete schopni splácet své finanční závazky, bude vám vozidlo zabaveno.",
  repossessionWarning = "Vaše poslední platba se nezdařila - vaše vozidlo bude zabaveno, pokud nyní neprovedete platbu.",
  recurringPayment = "Opakovaná platba",
  remainingBalance = "Zbývající zůstatek",
  remainingPayments = "Zbývající platby",
  paymentTakenEvery = "Platba se provádí každé",
  hours = "hodiny",
  seconds = "sekundy",
  nextPayment = "Příští platba",
  makePayment = "Proveďte platbu",
  vehicleRepossessed = "Vozidlo bude zabaveno",
  payInFull = "Zaplaťte v plné výši",
  earlyPaymentConfirmation = "Opravdu chcete provést předčasnou platbu",
  financedVehicles = "Financovaná vozidla",
  noFinancedVehicles = "Nemáte žádná vozidla s aktivním financováním",
  financeBreakdown = "Finanční členění",
  initialPayment = "Počáteční platba",
  payments = "Platby",
  length = "Délka",
  interest = "Úrok",
  totalPayable = "Celkem splatné",
  leaveShowroom = "Opustit showroom",
  handling = "Handling",
  topSpeed = "Maximální rychlost",
  power = "Síla",
  torque = "Točivý moment",
  brake = "Brzda",
  financing = "Financování",
  financingAvailable = "Dostupné financování",
  paymentsOf = "platby",
  clear = "Vymazat",
  testDrive = "Testovací jízda",
  allCategories = "Všechny kategorie",
  sortByName = "Seřadit podle: Název",
  sortByAvailability = "Seřadit podle: Dostupnost",
  sortByCheapest = "Seřadit podle: Nejlevnější",
  sortByMostExpensive = "Seřadit podle: Nejdražší",
  sortByNewest = "Seřadit podle: Nejnovější",
  purchaseVehicle = "Koupit vozidlo",
  purchaseFor = "Nákup za",
  selectSociety = "Vyberte společnost",
  financeOverPayments = "Zbývající částka k zaplacení je %{value}",
  payToday = "Zaplaťte ještě dnes",
  financeThen = "Potom",
  seeFullBreakdown = "Zobrazit úplný rozpis",
  testDriveExit = "Zkušební jízdu můžete kdykoli opustit a zkušební jízdu ukončit.",

  -- NOTIFICATIONS
  purchaseSuccess = "Gratulujeme k nákupu!",
  depositSuccess = "Vklad byl úspěšný",
  withdrawSuccess = "Úspěšný výběr",
  errorNotEnoughMoney = "Nemáte dost peněz",
  errorVehicleOutOfStock = "Toto vozidlo není skladem",
  errorCannotAffordVehicle = "Toto vozidlo si nemůžete dovolit",
  vehicleFinancePaymentMade = "Finanční platba za vaše vozidlo %{value}",
  vehicleFinancePaidOff = "Gratulujeme, vyplatili jste se a nyní vlastníte své vozidlo %{value}",
  vehicleFinancePaymentFailed = "Finanční platba za vaše vozidlo se nezdařila %{value}",
  vehicleFinanceRepossessedSoon = "Musíte provést platbu za své vozidlo %{value} nebo bude vaše vozidlo brzy zabaveno",
  vehicleFinanceRepossessed = "Z důvodu nezaplacení bylo vaše vozidlo zabaveno i s poznávací značkou %{value}",
  dealershipNotEnoughFunds = "Prodejce nemá dostatek finančních prostředků",
  dealershipVehiclesOrdered = "Vozidlo (vozidla) bylo úspěšně objednáno",
  dealershipOrderCancelled = "Objednávka byla úspěšně zrušena",
  errorVehicleWithSpawnCodeExists = "Vozidlo s tímto spawn kódem již existuje",
  errorExitVehicle = "Nejprve musíte opustit své vozidlo",

  -- NEW v1.1
  purchaseRequest = "Žádost o nákup",
  sendRequest = "Odeslat žádost",
  dealer = "Prodejce",
  financed = "Financováno",
  signHere = "Podepište se zde",
  signFirstError = "Nejprve se podepište",
  denyRequest = "Odmítnutí žádosti",
  playerTooManyFinancedVehicles = "Hráč má příliš mnoho financovaných vozidel",
  employeePermissionsError = "Nemáte potřebná oprávnění zaměstnance",
  managerRole = "Manažer",
  supervisorRole = "Supervizor",
  salesRole = "Prodej",
  ownerRole = "Majitel",
  employmentRequest = "Žádost o zaměstnání",
  accept = "Přijmout",
  jobOfferDescription = "Byla vám nabídnuta práce u prodejce \"%{value}\". Chtěli byste ji přijmout?",
  pending = "Čeká se na",
  employeeHiredMsg = "Žádost o pronájem dealerství byla přijata!",
  employeeRejectedMsg = "Žádost o pronájem dealerství byla zamítnuta",
  sellVehicle = "Prodej vozidla",
  vehicleTerms = "Podmínky pro vozidla",
  financePayments = "Finanční platby",
  commission = "Komise",
  role = "Úloha",
  firedNotification = "Byl jste propuštěn z \"%{value}\" dealerství",
  dealershipTooFarAway = "Nejste v blízkosti žádného prodejce",
  restoreDisplayVehicles = "Předváděcí místnost Restore",
  customer = "Zákazník",
  lessThanAMin = "Méně než minuta",
  mins = "minuty",
  notInVehicle = "Nesedíte ve vozidle",
  notYourVehicleError = "Toto vozidlo vám nepatří",
  vehicleFinancedError = "Toto vozidlo nemůžete prodat, protože na něm zůstávají finanční splátky",
  dealershipDoesntSellVehicle = "Tento prodejce nemůže koupit toto vozidlo",
  dealershipWantsYourVehicle = "Gratulujeme! Tento prodejce by rád zakoupil vaše vozidlo.",
  purchasePrice = "Nabízená cena: ",

  spawnCodeInvalid = "Neplatný spawn kód",
  salesRep = "Obchodní zástupce",
  directSaleAccepted = "Požadavek na přímý prodej přijat! Vaše provize byla vyplacena.",
  directSaleRejected = "Požadavek na přímý prodej zamítnut",

  displayVehicleOutsideZone = "Výstavní vozidla musí být umístěna v zóně dealerství",
  serverAdmin = "Správce serveru",
  selfService = "Samoobsluha",
  owned = "Vlastněno",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Neplatný způsob platby",
  paymentMethodNoFinance = "Tento způsob platby nepodporuje financování",
  couldNotGeneratePlate = "Nepodařilo se vygenerovat SPZ",
  invalidCoupon = "Neplatný kupon: %{value}",
  tooManyFinancedVehicles = "Máte příliš mnoho financovaných vozidel",
  couldNotSpawnVehicle = "Nepodařilo se vytvořit vozidlo",

  -- v2: Permissions
  insufficientPermissions = "Nedostatečná oprávnění",

  -- v2: Coupons
  couponCodeAlreadyExists = "Tento kód kuponu již existuje",
  failedToCreateCoupon = "Nepodařilo se vytvořit kupon",
  couponCreatedSuccessfully = "Kupon úspěšně vytvořen",
  couponNotFound = "Kupon nenalezen",
  couponUpdatedSuccessfully = "Kupon úspěšně aktualizován",
  failedToDeleteCoupon = "Nepodařilo se smazat kupon",
  couponDeletedSuccessfully = "Kupon úspěšně smazán",
  editCoupon = "Upravit kupon",
  addCoupon = "Přidat kupon",
  couponCode = "Kód kuponu",
  generating = "Generování...",
  generate = "Generovat",
  discountType = "Typ slevy",
  percentageOff = "Procentuální sleva",
  amountOff = "Částka slevy",
  discountValue = "Hodnota slevy",
  unlimitedTotalUses = "Neomezený počet použití",
  unlimitedUsesPerPlayer = "Neomezené použití na hráče",
  setExpiryDate = "Nastavit datum expirace",
  restrictToSpecificVehicles = "Omezit na konkrétní vozidla",
  restrictToSpecificCategories = "Omezit na konkrétní kategorie",
  allowUseWithFinance = "Povolit použití s financováním",
  deleteCoupon = "Smazat kupon",
  inactive = "Neaktivní",
  expired = "Vypršelo",
  maxUses = "Maximální použití",
  coupons = "Kupony",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Pouze správci serveru se mohou sami zaměstnat",
  playerNotFound = "Hráč nenalezen",
  failedToHireEmployee = "Nepodařilo se najmout zaměstnance",
  failedToFireEmployee = "Nepodařilo se propustit zaměstnance",
  failedToUpdateEmployeeRole = "Nepodařilo se aktualizovat roli zaměstnance",
  hireEmployee = "Najmout zaměstnance",
  fireEmployee = "Propustit zaměstnance",
  editRole = "Upravit roli",
  fire = "Propustit",
  changeRole = "Změnit roli",
  updateRole = "Aktualizovat roli",

  -- v2: Test drives
  maxTestDrivesReached = "Toto dealerství dosáhlo maximálního počtu aktivních zkušebních jízd",
  testDriveNotEnabled = "Zkušební jízdy nejsou v tomto dealerství povoleny",
  noTestDriveSpawnCoords = "Pro toto dealerství nejsou nakonfigurovány souřadnice pro zkušební jízdu",
  couldNotSpawnTestDriveVehicle = "Nepodařilo se vytvořit vozidlo pro zkušební jízdu",
  couldNotGetPlateFromServer = "Nepodařilo se získat SPZ ze serveru",
  couldNotRegisterTestDriveVehicle = "Nepodařilo se zaregistrovat vozidlo pro zkušební jízdu",
  testDriveEndedByEmployee = "Zkušební jízda byla ukončena jiným zaměstnancem",
  trackingVehicleLocation = "Sledování polohy vozidla...",
  directSaleCancelled = "Požadavek na prodej byl zrušen prodejcem",
  testDriveKeysReceived = "Obdrželi jste klíče od vozidla pro zkušební jízdu",
  testDriveEndedCustomer = "Zkušební jízda skončila",
  starting = "Spouštění...",
  startTestDrive = "Zahájit zkušební jízdu",
  spawningTestDriveVehicle = "Vytváření vozidla pro zkušební jízdu...",
  testDriveReady = "Zkušební jízda připravena",
  testDriveWalkToVehicle = "Vozidlo pro zkušební jízdu bylo vytvořeno na označeném místě na vaší mapě. Doprovoďte zákazníka k vozidlu. Po předání klíčů zákazníkovi budete muset zkušební jízdu ukončit ručně, až se vrátí.",
  givingKeys = "Předávání klíčů...",
  continueAndGiveKeys = "Pokračovat a předat klíče",
  endTestDrive = "Ukončit zkušební jízdu",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Pro toto vozidlo není dostupný žádný sklad",
  globalStockLimitExceeded = "K dispozici pouze %{value} kusů",
  orderNotFoundOrFulfilled = "Objednávka nenalezena nebo již vyřízena",
  priceBelowMinimum = "Cena nemůže být nižší než %{value}",
  priceAboveMaximum = "Cena nemůže být vyšší než %{value}",
  stockUpdated = "Sklad aktualizován",
  changesSaved = "Změny uloženy",
  noStockAvailable = "Žádný sklad k dispozici",

  orderPlaced = "Objednávka zadána",
  remainingInStock = "zbývá v globálním skladu",
  exceedsStockLimit = "Překračuje limit skladu",
  setStockQty = "Nastavit množství skladu",
  invalidStockValue = "Zadejte platnou hodnotu skladu",
  errorSettingStock = "Chyba při nastavování skladu",
  stockQuantity = "Množství na skladě",
  currentStock = "Aktuální sklad",
  priceLimitsEnabled = "Povolit cenové limity",
  priceLimitsDescription = "Je-li povoleno, manažeři dealerství mohou nastavovat ceny pouze v určeném rozsahu.",
  minPrice = "Minimální cena",
  maxPrice = "Maximální cena",
  optional = "Volitelné",
  unlimitedStock = "Neomezený sklad",
  globalStockLimit = "Globální limit skladu",
  globalStockLimitDescription = "Nastavte maximální počet jednotek, které lze objednat ve všech dealerstvích.",
  currentlyOrdered = "Aktuálně objednáno",
  priceRange = "Cenový rozsah",
  noMinimum = "Žádné minimum",
  noMaximum = "Žádné maximum",
  vehicleStock = "Sklad vozidel",

  -- v2: Sales
  allSales = "Všechny prodeje",
  paidInFull = "Zaplaceno v plné výši",
  salesVolume = "Objem prodeje",
  pastMonth = "Minulý měsíc",
  pastYear = "Minulý rok",

  -- v2: Management misc
  exploitAttemptDetected = "Přestaňte se pokoušet zneužívat skript",
  dealershipNoJobConfigured = "Dealerství nemá nakonfigurovanou práci",
  modelDoesNotMatchDb = "Model vozidla neodpovídá databázi",
  importFailed = "Import selhal: %{value}",
  notInDealershipZone = "Pro použití tohoto příkazu musíte být v dealerství",
  notAnEmployee = "Nejste zaměstnancem tohoto dealerství.",
  failedToPrepareDelivery = "Nepodařilo se připravit doručení",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Model vozidla neexistuje - kontaktujte správce",
  vehiclePlateInvalid = "SPZ tohoto vozidla je neplatná (stiskněte F8 pro více detailů)",
  currentlyInRagdollState = "Právě jste ve stavu ragdoll",
  vehicleDoesNotExistContactAdmin = "Vozidlo neexistuje. Kontaktujte správce!",
  vehicleSecurityBreachDetected = "Zjištěno narušení bezpečnosti vozidla",

  -- v2: Admin vehicles
  allVehicles = "Všechna vozidla",
  unassignedVehicles = "Bez dealerství",
  searchDealerships = "Hledat dealerství...",

  -- v2: Trucking mission
  truckingGetInTruck = "Nasedněte do kamionu na označeném místě pro zahájení doručení",
  truckingDriveToDelivery = "Jeďte na místo doručení",
  truckingCompleteDelivery = "Dokončit doručení",
  truckingDeliveryComplete = "Doručení dokončeno: Úspěšně jste dokončili doručení!",
  truckingDeliveryFailed = "Doručení selhalo: Něco se pokazilo při doručení",
  truckingDriveToPickup = "Jeďte na místo vyzvednutí pro návěs",
  truckingMissionFailedSpawnCargo = "Mise selhala: Nepodařilo se vytvořit nákladní návěs",
  truckingMissionFailedFindCargo = "Mise selhala: Nepodařilo se najít vytvořený náklad",
  truckingVehiclesLoaded = "%{count} vozidel naloženo",
  truckingWrongTrailer = "Špatný návěs! Musíte připojit správný misijní návěs.",
  truckingTrailerAttached = "Návěs připojen - připraveno pokračovat",
  truckingDriveToPickupLocation = "Jeďte na místo vyzvednutí",
  truckingWaitingForVehicles = "Čekání na naložení vozidel...",
  truckingDriveUnderTrailer = "Zajeďte pod návěs pro připojení",
  truckingGetInTruckContinue = "Nasedněte do kamionu pro pokračování",
  truckingMissionStarted = "Přepravní mise zahájena: Místo vyzvednutí - %{location}",
  truckingMissionCancelled = "Mise zrušena: Zrušili jste přepravní misi",
  truckingNoActiveMission = "Žádná aktivní přepravní mise ke zrušení",
  deliveryNotPrepared = "Doručení nepřipraveno - zkuste to znovu",
  deliveryConfigMismatch = "Neshoda konfigurace doručení",
  deliveryPreparationExpired = "Příprava doručení vypršela - zkuste to znovu",
  noTruckingVehicleCoordinates = "Souřadnice přepravního vozidla nejsou nastaveny",
  pickupLocationUnavailable = "Místo vyzvednutí již není k dispozici - zkuste to znovu",
  failedToSpawnTruck = "Nepodařilo se vytvořit kamion",
  clientFailedToStartMission = "Klient nemohl zahájit misi",

  -- v2: Trucking UI/Keys
  keyDismiss = "Zavřít",
  keyDeliverCargo = "Doručit náklad",
  keyContinueToDelivery = "Pokračovat k doručení",
  startDeliveryMission = "Zahájit doručovací misi",
  orderDetails = "Detaily objednávky",
  pickupLocation = "Místo vyzvednutí",
  deliveryStatus = "Stav doručení",
  selectOrders = "Vybrat objednávky",
  carTrailer = "Autovůz",
  container = "Kontejner",
  deliveryRoute = "Trasa doručení",
  startDelivery = "Zahájit doručení",

  -- v2: Direct sales UI
  waitingForCustomer = "Čekání na zákazníka",
  cancelRequest = "Zrušit požadavek",
  saleComplete = "Prodej dokončen!",
  done = "Hotovo",
  saleDeclined = "Prodej odmítnut",
  close = "Zavřít",

  -- v2: Display vehicle placement
  movement = "Pohyb",
  rotate = "Otočit",
  forward = "Vpřed",
  backward = "Vzad",
  left = "Vlevo",
  right = "Vpravo",
  rotateLeft = "Otočit vlevo",
  rotateRight = "Otočit vpravo",

  -- v2: Showroom misc
  originalPrice = "Původní cena",
  discount = "Sleva",
  createInteraction = "Vytvořit interakci",
  viewAll = "Zobrazit vše",
  fetchingPlayers = "Načítání hráčů",
  refresh = "Obnovit",

  -- v2: Self-service & Categories
  selfServiceDealership = "Samoobslužné dealerství",
  categories = "Kategorie",

  -- v2: Loading/Players UI
  loadingPlayers = "Načítání hráčů...",
  failedToLoadPlayers = "Nepodařilo se načíst hráče",
  selectAPlayer = "Vyberte hráče",
  failedToLoadPlayersRetry = "Nepodařilo se načíst hráče. Klikněte na 'Obnovit' a zkuste to znovu.",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Lokace",
  createNew = "Vytvořit nový",
  enable = "Povolit",
  disable = "Zakázat",
  loading = "Načítání...",
  errors = "Chyby",
  update = "Aktualizovat",
  create = "Vytvořit",

  -- v2: Dealership creation/editing
  createDealership = "Vytvořit dealerství",
  editDealership = "Upravit dealerství",
  essentials = "Základy",
  advanced = "Pokročilé",
  noDealershipLocations = "Žádné lokace dealerství",
  noDealershipLocationsDesc = "Můžete přidat novou lokaci, importovat z konfigurace (při migraci z v1) nebo automaticky přidat výchozí lokace.",

  -- v2: Location sections
  dealershipZone = "Zóna dealerství",
  showroomAndManagement = "Showroom a správa",
  openShowroom = "Otevřít showroom",
  openManagement = "Otevřít správu",
  enableSellVehicle = "Povolit prodej vozidel",
  percentageOfVehicleValue = "Procento % z hodnoty vozidla",
  enablePurchase = "Povolit nákup",
  purchasedVehicleSpawn = "Spawn zakoupeného vozidla",
  enableTestDrive = "Povolit zkušební jízdu",
  testDriveVehicleSpawn = "Spawn vozidla pro zkušební jízdu",
  truckDelivery = "Doručení kamionem",
  truckDeliveryVehicleSpawn = "Spawn vozidla pro doručení",

  -- v2: Location advanced settings
  paymentMethods = "Platební metody",
  supportsFinancing = "(podporuje financování)",
  enableFinance = "Povolit financování",
  cameraPreset = "Kamera",
  preset = "Předvolba",
  custom = "Vlastní",
  vehiclePosition = "Pozice vozidla",
  zoomPositions = "Pozice přiblížení (oddělené čárkou)",
  zoomPositionsPlaceholder = "příklad: 5,8,12,8",
  vehicleColour = "Barva vozidla",
  selectionType = "Typ výběru",
  noColourSelection = "Bez výběru barvy",
  rgbColourWheel = "RGB barevné kolo",
  listOfRgbColours = "Seznam RGB barev",
  listOfColourIds = "Seznam ID barev",
  accessControl = "Řízení přístupu",
  showroomJobWhitelist = "Whitelist práce pro showroom",
  showroomGangWhitelist = "Whitelist gangů pro showroom",
  societyPurchaseJobWhitelist = "Whitelist práce pro nákup společnosti",
  societyPurchaseGangWhitelist = "Whitelist gangů pro nákup společnosti",
  setInGame = "Nastavit ve hře",
  addNew = "Přidat nový",

  -- v2: Job/Gang whitelist editor
  job = "Práce",
  gang = "Gang",
  jobWhitelist = "Whitelist práce",
  gangWhitelist = "Whitelist gangů",
  addJob = "Přidat práci",
  addGang = "Přidat gang",
  editJob = "Upravit práci",
  editGang = "Upravit gang",
  manageJobs = "Spravovat práce",
  manageGangs = "Spravovat gangy",
  jobName = "Název práce",
  gangName = "Název gangu",
  selectGrades = "Vybrat hodnosti",
  selectAll = "Vybrat vše",
  deselectAll = "Zrušit výběr",
  invalidJobName = "Neplatný název práce. Zkontrolujte konfiguraci frameworku.",
  invalidGangName = "Neplatný název gangu. Zkontrolujte konfiguraci frameworku.",
  grades = "Hodnosti",
  noJobsConfigured = "Žádné nakonfigurované práce",
  noGangsConfigured = "Žádné nakonfigurované gangy",
  click = "Klikněte",
  toGetStarted = "pro začátek.",
  more = "více",
  jobPlaceholder = "Například: cardealer",
  jobOptionalDescription = "Volitelně propojte role dealerství s prací frameworku. Při najímání/propouštění zaměstnanců bude jejich práce také aktualizována.",
  jobRankPermissions = "Oprávnění pracovních hodností",
  roleToJobRankMapping = "Mapování rolí na pracovní hodnosti",
  addPerm = "Přidat oprávnění",

  -- v2: Colour selector
  searchColours = "Hledat barvy...",
  noColoursFound = "Žádné barvy nenalezeny",

  -- v2: Interactions creator
  noInteractions = "Žádné interakce",
  highlightInteractions = "Zvýraznit interakce",
  explorationMode = "Režim průzkumu",
  pressEsc = "Stiskněte ESC",
  toWalkAround = "pro procházení",
  toReturnToUI = "pro návrat do UI",
  points = "body",
  location = "lokace",
  manageLocations = "Spravovat lokace",

  -- v2: Interaction modal
  interactionType = "Typ",
  nicknameOptional = "Přezdívka (volitelné)",
  invalidModel = "Neplatný model",
  failedToValidateModel = "Nepodařilo se ověřit model",
  pedScenario = "Scénář peda",
  coords = "Souřadnice",
  size = "Velikost",
  blip = "Blip",
  enableBlip = "Povolit blip",
  blipIconId = "ID ikony blipu",
  blipColourId = "ID barvy blipu",
  blipSize = "Velikost blipu",
  marker = "Značka",
  enableMarker = "Povolit značku",
  markerStyleId = "ID stylu značky",
  markerSize = "Velikost značky",
  markerColor = "Barva značky",
  markerBobUpAndDown = "Pohyb nahoru a dolů",
  markerFaceCamera = "Čelem ke kameře",
  markerRotate = "Rotace",
  markerDrawOnEnts = "Kreslit na entity",
  updatePosition = "Aktualizovat pozici",
  setPosition = "Nastavit pozici",

  -- v2: Interaction types
  interactionPoint = "Bod",
  interactionPointDesc = "Jediný zmenšitelný bod s volitelnou značkou",
  interactionPolyzone = "Polyzona",
  interactionPolyzoneDesc = "Vícebodová zóna pro vytvoření specifické interakční oblasti",
  interactionVehicle = "Vozidlo",
  interactionVehicleDesc = "Spawn modelu vozidla, ideální pro target nebo 3D text UI metody",
  interactionObject = "Objekt",
  interactionObjectDesc = "Spawn modelu objektu, ideální pro target nebo 3D text UI metody",
  interactionPed = "Ped",
  interactionPedDesc = "Spawn modelu peda s volitelným scénářem, ideální pro target nebo 3D text UI metody",

  -- v2: Import modal
  importLocationsTitle = "Importovat lokace",
  syncStockLabel = "Synchronizovat sklad",
  syncStockDescription = "Přidat vozidla do skladu každého dealerství podle jeho kategorií",
  importSourceSelectorDesc = "Můžete importovat sadu výchozích lokací pro připravené nastavení, nebo importovat existující lokace z konfigurace při migraci z v1.",
  importSourceSelectorSkipDesc = "Lokace, které již v databázi existují, budou přeskočeny; importovány budou pouze nové lokace.",
  successfullyImported = "Úspěšně importováno",
  alreadyExist = "Již existuje",
  defaultLocations = "Výchozí lokace",
  defaultLocationsDesc = "Importovat předkonfigurované lokace dealerství (PDM, Luxury, Boats, Air, Truck)",
  existingConfig = "Existující konfigurace",
  existingConfigDesc = "Importovat lokace z config.lua (pro migraci z v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Chcete automaticky přidat vozidla do skladu tohoto dealerství podle vybraných kategorií?",
  categorySyncEditDesc = "Změnili jste kategorie tohoto dealerství. Chcete automaticky aktualizovat sklad vozidel?",
  addVehicles = "Přidat vozidla",
  removeVehicles = "Odebrat vozidla",
  fromNewCategories = "z nových kategorií",
  fromSelectedCategories = "z vybraných kategorií",
  fromRemovedCategories = "z odebraných kategorií",
  categoriesAdded = "Přidané kategorie:",
  categoriesRemoved = "Odebrané kategorie:",
  skip = "Přeskočit",
  syncStock = "Synchronizovat sklad",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Kontrola dostupnosti zdroje...",
  vehiclesAvailableToImport = "vozidel k importu",
  includesDealershipIds = "obsahuje ID dealerství",
  sourceUnavailable = "Zdroj nedostupný",
  noVehiclesAdminDescription = "Můžete přidat vozidla ručně nebo je importovat z frameworku.",
  appendBehaviour = "Připojit",
  overwriteBehaviour = "Přepsat",
  appendDescription = "Přidat pouze nová vozidla, která v databázi neexistují",
  overwriteDescription = "Smazat všechna existující data vozidel a importovat znovu",
  stockAssignmentMethod = "Metoda přiřazení skladu",
  useDealershipIdsFromSource = "Použít ID dealerství ze zdroje",
  matchByVehicleCategory = "Přiřadit podle kategorie vozidla",
  byShopDescription = "Vozidla budou přiřazena dealerstvím podle pole 'shop' ve zdrojových datech",
  byCategoryDescription = "Vozidla budou přiřazena dealerstvím s odpovídajícími kategoriemi",
  overwriteWarning = "Varování: Přepsání smaže všechna existující vozidla, objednávky, vystavená vozidla a data o prodejích.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX tabulka vozidel",
  selectCategory = "Vybrat kategorii",

  -- v2: Management menu items
  vehiclesMenu = "Vozidla",
  displayVehiclesMenu = "Vystavená vozidla",
  ordersMenu = "Objednávky",
  salesMenu = "Prodeje",
  bankAccountMenu = "Bankovní účet",
  employeesMenu = "Zaměstnanci",
  couponsMenu = "Kupony",
  settingsMenu = "Nastavení",
  noPermissionAccessManagement = "Nemáte oprávnění k přístupu k žádným funkcím správy.",
  backToAdmin = "Zpět do admin",
  viewingAsAdmin = "ZOBRAZENO JAKO ADMIN",

  -- v2: Coupons table
  code = "Kód",
  uses = "Použití",
  perPlayer = "Na hráče",
  never = "Nikdy",
  noCoupons = "Žádné kupony",
  noCouponsDescription = "Zákazníci mohou zadat kupon při nákupu vozidla a ušetřit.",

  -- v2: Coupon modal
  couponCodeLabel = "Kód kuponu",
  couponCodePlaceholder = "např. SUMMER2024 nebo SAVE10",
  couponCodeHelp = "Zadejte vlastní kód (max 25 znaků, pouze písmena, čísla a pomlčky) nebo klikněte na 'Generovat'.",
  maxNumberOfUsesPlaceholder = "Maximální počet použití",
  maxUsesPerPlayerPlaceholder = "Maximální použití na hráče",
  vehicleRestrictionsPlaceholder = "Zadejte spawn kódy oddělené čárkami (např. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Povolit u financovaných nákupů",
  createCoupon = "Vytvořit kupon",
  updateCoupon = "Aktualizovat kupon",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kód kuponu je povinný",
  couponCodeMaxLength = "Kód musí mít maximálně 25 znaků",
  couponCodeInvalidChars = "Kód může obsahovat pouze velká písmena, čísla a pomlčky",
  discountTypeRequired = "Typ slevy je povinný",
  discountValueRequired = "Hodnota slevy je povinná",
  discountValueMin = "Hodnota slevy musí být větší než 0",
  discountValueMaxPercent = "Procenta nemohou přesáhnout 100",
  maxUsesRequired = "Maximální použití je povinné",
  maxUsesMin = "Musí být alespoň 1",
  perPlayerLimitRequired = "Limit na hráče je povinný",
  expiryDateRequired = "Datum expirace je povinné",
  vehicleRestrictionsRequired = "Omezení vozidel jsou povinná",
  categoryRestrictionsRequired = "Omezení kategorií jsou povinná",
  selectAtLeastOneCategory = "Vyberte alespoň jednu kategorii",

  -- v2: Dashboard
  today = "Dnes",
  thisMonth = "Tento měsíc",
  allTime = "Celkově",
  recentSales = "Nedávné prodeje",
  noSalesYet = "Zatím žádné prodeje!",
  noSalesDescription = "Prodeje vozidel se zde zobrazí po uskutečnění prodeje.",
  past7Days = "Posledních 7 dní",
  past6Months = "Posledních 6 měsíců",
  numberOfSales = "Počet prodejů",
  noDataAvailableForPeriod = "Pro toto období nejsou k dispozici žádná data",

  -- v2: Display vehicles
  displayVehiclesDescription = "Vystavená vozidla jsou pevné showroom modely používané k prezentaci vašeho inventáře a přilákání zákazníků.",

  -- v2: Employees
  frameworkJobsEnabled = "Práce frameworku povoleny",
  frameworkJobsDescription = "Správa zaměstnanců probíhá přes systém prací frameworku. Hráči s prací dealerství budou mít automaticky přístup podle své pracovní hodnosti. Nakonfigurujte oprávnění prací v nastavení lokace v admin panelu.",
  joinedColumn = "Připojeno",
  youBadge = "Vy",

  -- v2: Orders
  noOrdersTitle = "Žádné objednávky",
  noOrdersDescription = "Pro zadání objednávky otevřete záložku 'Vozidla' a klikněte na 'Zadat objednávku' u vozidla, které chcete doplnit.",
  inProgress = "Probíhá",
  awaitingDelivery = "Čeká na doručení",
  orderedBy = "Objednal",
  viewDeliveryInfo = "Zobrazit info o doručení",

  -- v2: Delivery
  startDeliveryMissionTitle = "Zahájit doručovací misi",
  startDeliveryDescription = "Chystáte se zahájit doručovací misi pro tuto objednávku. Budete muset dojet na místo vyzvednutí, vyzvednout nákladní návěs a doručit ho do dealerství.",
  totalDistanceAndDriveTime = "Celková vzdálenost a doba jízdy",
  roundTrip = "tam a zpět",
  deliveryCompleteTitle = "Doručení dokončeno",
  deliveryInProgressTitle = "Doručení probíhá",
  deliveredAt = "Doručeno:",
  startedAt = "Zahájeno:",
  deliveredBy = "Doručil:",
  beingDeliveredBy = "Doručuje:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Žádné objednávky nejsou k dispozici pro doručení. Objednávky musí být připraveny a nesmí být v aktivním doručení.",
  confirmDeliveryTitle = "Potvrdit doručení",
  configureDeliveryTitle = "Konfigurovat doručení",
  trailerCapacityExceeded = "Kapacita návěsu překročena! Vybrali jste %{usedSlots} slotů, ale maximum je %{maxSlots} slotů.",
  smallVehiclesSlotInfo = "Pamatujte: malá vozidla zabírají 1 slot, střední vozidla zabírají 1.5 slotu.",
  fetchingRoute = "Načítání...",
  getRouteButton = "Získat trasu",
  selectTrailerType = "Vybrat typ návěsu",
  carTrailerLabel = "Autovůz",
  smallMedium = "(Malý/Střední)",
  containerLabel = "Kontejner",
  large = "(Velký)",
  carTrailerDescription = "Autovůz má 2 řady. Každá řada pojme 3 malá (1 slot každé) nebo 2 střední (1.5 slotu každé). Max 6 slotů celkem.",
  containerDescription = "Kontejnerový návěs přepravuje 1 velké vozidlo",
  selectOrdersTitle = "Vybrat objednávky",
  slots = "sloty",
  noOrdersForTrailerType = "Žádné objednávky pro tento typ návěsu.",
  qty = "Množství:",
  inTransit = "na cestě",
  totalVehicles = "Celkem vozidel:",
  estimatedTime = "Odhadovaný čas:",
  unknown = "Neznámý",

  -- v2: Sales
  salesEmptyDescription = "Prodeje vozidel se zde zobrazí po uskutečnění prodeje.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Objednávka zadána!",
  orderPlacedTruckingDescription = "Vaše objednávka je připravena k vyzvednutí. Přejděte na stránku objednávek a dokončete ji.",
  orderPlacedTimedDescription = "Vaše objednávka bude doručena za %{value} minut.",
  goToOrders = "Přejít na objednávky",
  noStockAvailableDescription = "Pro toto vozidlo není k dispozici žádný sklad. Byl dosažen globální limit skladu.",
  stockUpdatedDescription = "Množství skladu bylo úspěšně aktualizováno.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktivní zkušební jízdy",
  tracking = "Sledování",
  track = "Sledovat",
  endButton = "Ukončit",
  endTestDriveTitle = "Ukončit zkušební jízdu",
  endTestDriveConfirmation = "Opravdu chcete ukončit tuto zkušební jízdu? Vozidlo bude smazáno a cestující ve vozidle nebudou teleportováni zpět do dealerství.",
  vehicleLocationOnMap = "Poloha vozidla byla umístěna na vaši mapu.",
  sell = "Prodat",
  couponCodeOptional = "Kód kuponu (volitelné)",
  pleaseEnterCouponCode = "Zadejte prosím kód kuponu",
  invalidCouponCode = "Neplatný kód kuponu",
  failedToValidateCoupon = "Nepodařilo se ověřit kupon",
  apply = "Použít",
  applying = "Aplikuji...",
  allStock = "Veškerý sklad",
  inStockFilter = "Na skladě",
  outOfStockFilter = "Vyprodáno",
  noResultsFound = "Žádné výsledky",
  noResults = "Žádné výsledky",
  noVehiclesMatchSearch = "Žádná vozidla neodpovídají vašemu hledání",
  noVehiclesMatchFilters = "Žádná vozidla neodpovídají aktuálním filtrům",
  noItemsMatchSearch = "Žádné položky neodpovídají vašemu hledání",
  noItemsMatchFilters = "Žádné položky neodpovídají aktuálním filtrům",
  selectColour = "Vybrat barvu",
  refreshNearbyPlayers = "Obnovit blízké hráče",
  you = "Vy",
  items = "položky",
  waitingForCustomerToRespond = "Čekání na odpověď zákazníka...",
  vehicleSpawnedMessage = "Vozidlo bylo vytvořeno na místě označeném na vaší mapě - doprovoďte zákazníka.",
  customerDeclinedMessage = "Zákazník odmítl žádost o nákup.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "PODEPIŠTE ZDE",
  acceptAndPurchase = "Přijmout a koupit",
  couponApplied = "Kupon %{code} použit! Ušetříte %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "K dokončení zóny potřebujete alespoň 3 body! (Aktuálně máte %{value})",
  addPoint = "Přidat bod",
  removeLast = "Odebrat poslední",
  completeZone = "Dokončit zónu",
  spawnPreview = "Náhled spawnu",
  up = "Nahoru",
  down = "Dolů",
  confirm = "Potvrdit",
  placePoint = "Umístit bod",
  radius = "Poloměr",

  -- v2: Blip labels
  soldVehicleLocation = "Poloha prodaného vozidla",
  testDriveVehicleBlip = "Vozidlo zkušební jízdy",

  -- v2: Stock sync
  stockSyncResult = "Synchronizace skladu: %{added} přidáno, %{removed} odebráno",
  stockSyncAdded = "Synchronizace skladu: %{value} vozidel přidáno",
  importSuccessful = "Import úspěšný! %{imported} vozidel importováno (celkem %{total})",

  -- v2: Tooltip actions
  findOnMap = "Najít na mapě",
  adminPanel = "Admin panel",

  -- v2: Common dropdown
  selectOne = "Vyberte jednu",
}
