Locales = Locales or {}

Locales['de'] = {
  -- UI
  vehicle = "Fahrzeug",
  vehicles = "Fahrzeuge",
  dealership = "Autohaus",
  dealerships = "Autohäuser",
  vehiclesCount = "Fahrzeuge Anzahl",
  dealersCount = "Händler",
  accountBalance = "Kontostand",
  bank = "Bankkonto",
  cash = "Bargeld",
  amount = "Betrag",
  societyFund = "Gewerbegeld",
  paymentSource = "Zahlungsquelle",
  purchase = "Kaufen",
  personalPurchase = "Privater Kauf",
  societyPurchase = "Gewerblicher Kauf",
  purchaseType = "Kaufart",
  deposit = "Einzahlen",
  withdraw = "Auszahlen",
  all = "Alle",
  yes = "Ja",
  no = "Nein",
  add = "Hinzufügen",
  edit = "Bearbeiten",
  id = "ID",
  created = "Erstellt",
  type = "Typ",
  name = "Name",
  owner = "Besitzer",
  bankBalance = "Kontostand",
  status = "Status",
  back = "Zurück",
  previous = "Vorherige",
  next = "Nächste",
  admin = "Verwaltung",
  vehiclesAdmin = "Fahrzeug Verwaltung",
  dealershipsAdmin = "Autohaus Verwaltung",
  search = "Suchen",
  noDealershipsFound = "Keine Autohäuser gefunden",
  noVehicles = "Keine Fahrzeuge",
  page = "Seite",
  of = "von",
  every = "alle",
  show = "Anzeigen",
  active = "Aktiv",
  activeFinance = "Aktive Finanzierung",
  failed = "Fehlgeschlagen",
  removed = "Entfernt",
  setOwner = "Besitzer festlegen",
  manage = "Verwalten",
  deleteData = "Daten löschen",
  deleteVehicle = "Fahrzeug entfernen",
  delete = "Entfernen",
  deleteConfirmation = "Sind Sie sich wirklich sicher?",
  deleteConfirmationDanger = "Bestätigen, dies kann nicht rückgängig gemacht werden.",
  setDealershipOwner = "Besitzer festlegen",
  overwriteDealerPrices = "Händlerpreise Überschreiben",
  nearbyPlayers = "Spieler in der Nähe",
  noPlayersNearby = "Kein Spieler in der Nähe",
  selectPlayer = "Einen Spieler auswählen",
  required = "Erforderlich",
  forExample = "Zum Beispiel",
  spawnCode = "Spawnname",
  brand = "Marke",
  model = "Model",
  category = "Kategorie",
  price = "Preis",
  import = "Importieren",
  importing = "Importiere...",
  importBehaviour = "Fahrzeug Daten",
  importVehicles = "Fahrzeuge importieren",
  importFrom = "Importieren von",
  dashboard = "Dashboard",
  displayVehicle = "Fahrzeug anzeigen",
  displayVehicles = "Ausstellung",
  orders = "Bestellungen",
  sales = "Verkäufe",
  vehiclesOnDisplay = "Fahrzeuge in der Ausstellung",
  employees = "Mitarbeiter",
  settings = "Einstellungen",
  switchVehicle = "Fahrzeug wechseln",
  remove = "Entfernen",
  noDisplayVehicles = "Keine Ausstellungsfahrzeuge",
  selectVehicle = "Fahrzeug auswählen",
  colour = "Farbe",
  placeVehicle = "Fahrzeug platzieren",
  orderVehicle = "Fahrzeug/e bestellen",
  cancelOrder = "Bestellung stornieren",
  delivery = "Lieferung",
  delivered = "Ausgeliefert",
  noOrders = "keine Bestellungen",
  quantity = "Menge",
  totalCost = "Gesamtkosten",
  totalSales = "Verkäufe",
  noSales = "Keine Verkäufe",
  paid = "Bezahlt",
  owed = "Schulden",
  dealershipName = "Händler Name",
  save = "Speichern",
  cancel = "Abbrechen",
  notEnoughMoney = "Nicht genügend Geld",
  placeOrder = "Bestellen",
  purchaseCost = "Einkaufspreis",
  salePrice = "Verkaufspreis",
  inStock = "auf Lager",
  outOfStock = "Ausverkauft",
  placeVehiclePrompt = "Drücke %{value}, um das Fahrzeug zu platzieren. Du kannst später noch feinere Einstellungen vornehmen!",
  remaining = "Verbleibend",
  prePurchaseRepoWarning = "Wenn du deinen Zahlungen nicht nachkommst, wird dein Fahrzeug wieder entzogen.",
  repossessionWarning = "Deine letzte Zahlung ist fehlgeschlagen: Wenn du nicht sofort eine Zahlung leistest, wird dein Fahrzeug beschlagnahmt.",
  recurringPayment = "Wiederkehrende Zahlungen",
  remainingBalance = "Verbleibender Betrag",
  remainingPayments = "Erledigte Zahlungen",
  paymentTakenEvery = "Die Zahlung wird fällig alle",
  hours = "Stunden",
  seconds = "Sekunden",
  nextPayment = "Nächste Zahlung",
  makePayment = "Vorrauszahlung leisten",
  vehicleRepossessed = "Fahrzeug beschlagnahmt",
  payInFull = "Vollständig bezahlen",
  earlyPaymentConfirmation = "Möchtest du wirklich eine Vorrauszahlung in folgender Höhe tätigen",
  financedVehicles = "Finanzierte Fahrzeuge",
  noFinancedVehicles = "Du hast keine Fahrzeuge mit aktiver Finanzierung",
  financeBreakdown = "Einzelheiten zur Finanzierung",
  initialPayment = "Anzahlung",
  payments = "Raten",
  length = "Dauer",
  interest = "Zinsen",
  totalPayable = "Zu zahlende Summe",
  leaveShowroom = "Verlassen",
  handling = "Handling",
  topSpeed = "vMax",
  power = "Leistung",
  torque = "Drehmoment",
  brake = "Bremsen",
  financing = "Finanzierung",
  financingAvailable = "Finanzierung verfügbar",
  paymentsOf = "Raten a",
  clear = "Löschen",
  testDrive = "Probefahrt",
  allCategories = "Alle Kategorien",
  sortByName = "Nach Namen sortieren",
  sortByAvailability = "Nach Verfügbarkeit sortieren",
  sortByCheapest = "Günstigste zuerst",
  sortByMostExpensive = "Teuerste zuerst",
  sortByNewest = "Neueste zuerst",
  purchaseVehicle = "Fahrzeug kaufen",
  purchaseFor = "Kauf durch",
  selectSociety = "Wähle ein Unternehmen aus",
  financeOverPayments = "Finanzierung durch %{value} Raten",
  payToday = "Heute fälliger Betrag",
  financeThen = "Danach",
  seeFullBreakdown = "Einzelheiten zur Finanzierung",
  testDriveExit = "Du kannst dein Fahrzeug jederzeit verlassen, um die Probefahrt zu beenden...",

  -- NOTIFICATIONS
  purchaseSuccess = "Herzlichen Glückwunsch zu deinem Kauf!",
  depositSuccess = "Der Betrag wurde erfolgreich einbezahlt!",
  withdrawSuccess = "Der Betrag wurde erfolgreich ausbezahlt!",
  errorNotEnoughMoney = "Du hast nicht genügend Geld!",
  errorVehicleOutOfStock = "Dieses Fahrzeug ist leider nicht auf Lager!",
  errorCannotAffordVehicle = "Du kannst dir dieses Fahrzeug nicht leisten!",
  vehicleFinancePaymentMade = "Vorrauszahlung geleistet für das Fahrzeug mit folgendem Kennzeichen: %{value}",
  vehicleFinancePaidOff = "Herzlichen Glückwunsch, Du hast vollständig bezahlt und besitzen nun das Fahrzeug mit dem Kennzeichen: %{value}",
  vehicleFinancePaymentFailed = "Fehlgeschlagene Finanzierungszahlung für dein Fahrzeug mit dem Kennzeichen: %{value}",
  vehicleFinanceRepossessedSoon = "Du musst eine Zahlung für dein Fahrzeug %{value} leisten oder dein Fahrzeug wird bald wieder eingezogen.",
  vehicleFinanceRepossessed = "Wegen Nichtzahlung wurde dein Fahrzeug mit dem Kennzeichen %{value} wieder eingezogen.",
  dealershipNotEnoughFunds = "Der Händler hat nicht genug Geld.",
  dealershipVehiclesOrdered = "Die Fahrzeuge wurden erfolgreich bestellt!",
  dealershipOrderCancelled = "Auftrag erfolgreich storniert",
  errorVehicleWithSpawnCodeExists = "Ein Fahrzeug mit diesem Nummernsch existiert bereits!",
  errorExitVehicle = "Du musst zuerst aus deinem Fahrzeug aussteigen.",

  -- NEW v1.1
  purchaseRequest = "Anfrage zum Kauf",
  sendRequest = "Anfrage senden",
  dealer = "Händler",
  financed = "Finanziert",
  signHere = "Hier unterschreiben",
  signFirstError = "Bitte erst unterschreiben",
  denyRequest = "Antrag ablehnen",
  playerTooManyFinancedVehicles = "Spieler hat zu viele finanzierte Fahrzeuge",
  employeePermissionsError = "Sie haben nicht die erforderlichen Mitarbeiterrechte",
  managerRole = "Leiter",
  supervisorRole = "Datenschutzbeauftragter",
  salesRole = "Vertrieb",
  ownerRole = "Eigentümer",
  employmentRequest = "Antrag auf Beschäftigung",
  accept = "Akzeptieren",
  jobOfferDescription = "Ihnen wurde eine Stelle im Autohaus \"%{value}\" angeboten. Möchten Sie annehmen?",
  pending = "Anhängig",
  employeeHiredMsg = "Der Einstellungsantrag des Händlers wurde angenommen!",
  employeeRejectedMsg = "Antrag auf Einstellung eines Händlers wurde abgelehn",
  sellVehicle = "Fahrzeug verkaufen",
  vehicleTerms = "Fahrzeugbedingungen",
  financePayments = "Finanzierung Zahlungen",
  commission = "Kommission",
  role = "Rolle",
  firedNotification = "Sie wurden vom Händler \"%{value}\" entlassen",
  dealershipTooFarAway = "Sie sind nicht in der Nähe eines Autohauses",
  restoreDisplayVehicles = "Ausstellungsraum restaurieren",
  customer = "Kunde",
  lessThanAMin = "Weniger als eine Minute",
  mins = "min(s)",
  notInVehicle = "Sie befinden sich nicht in einem Fahrzeug",
  notYourVehicleError = "Dieses Fahrzeug gehört Ihnen nicht",
  vehicleFinancedError = "Sie können dieses Fahrzeug nicht verkaufen, weil es noch Finanzierungsraten hat",
  dealershipDoesntSellVehicle = "Dieses Autohaus kann dieses Fahrzeug nicht kaufen",
  dealershipWantsYourVehicle = "Herzlichen Glückwunsch! Dieses Autohaus möchte Ihr Fahrzeug kaufen.",
  purchasePrice = "Angebotener Preis: ",

  spawnCodeInvalid = "Spawn code invalid",
  salesRep = "Sales Rep",
  directSaleAccepted = "Direct sale request accepted! Your commission has been paid.",
  directSaleRejected = "Direct sale request rejected",

  displayVehicleOutsideZone = "Ausstellungsfahrzeuge müssen innerhalb der Händlerzone platziert werden",
  serverAdmin = "Server Admin",
  selfService = "Selbstbedienung",
  owned = "Im Besitz",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Ungültige Zahlungsmethode",
  paymentMethodNoFinance = "Diese Zahlungsmethode unterstützt keine Finanzierung",
  couldNotGeneratePlate = "Kennzeichen konnte nicht generiert werden",
  invalidCoupon = "Ungültiger Gutschein: %{value}",
  tooManyFinancedVehicles = "Sie haben zu viele finanzierte Fahrzeuge",
  couldNotSpawnVehicle = "Fahrzeug konnte nicht gespawnt werden",

  -- v2: Permissions
  insufficientPermissions = "Unzureichende Berechtigungen",

  -- v2: Coupons
  couponCodeAlreadyExists = "Gutscheincode existiert bereits",
  failedToCreateCoupon = "Gutschein konnte nicht erstellt werden",
  couponCreatedSuccessfully = "Gutschein erfolgreich erstellt",
  couponNotFound = "Gutschein nicht gefunden",
  couponUpdatedSuccessfully = "Gutschein erfolgreich aktualisiert",
  failedToDeleteCoupon = "Gutschein konnte nicht gelöscht werden",
  couponDeletedSuccessfully = "Gutschein erfolgreich gelöscht",
  editCoupon = "Gutschein bearbeiten",
  addCoupon = "Gutschein hinzufügen",
  couponCode = "Gutscheincode",
  generating = "Wird generiert...",
  generate = "Generieren",
  discountType = "Rabattart",
  percentageOff = "Prozent Rabatt",
  amountOff = "Betrag Rabatt",
  discountValue = "Rabattwert",
  unlimitedTotalUses = "Unbegrenzte Gesamtnutzung",
  unlimitedUsesPerPlayer = "Unbegrenzte Nutzung pro Spieler",
  setExpiryDate = "Ablaufdatum festlegen",
  restrictToSpecificVehicles = "Auf bestimmte Fahrzeuge beschränken",
  restrictToSpecificCategories = "Auf bestimmte Kategorien beschränken",
  allowUseWithFinance = "Mit Finanzierung erlauben",
  deleteCoupon = "Gutschein löschen",
  inactive = "Inaktiv",
  expired = "Abgelaufen",
  maxUses = "Max. Nutzungen",
  coupons = "Gutscheine",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Nur Server-Admins können sich selbst einstellen",
  playerNotFound = "Spieler nicht gefunden",
  failedToHireEmployee = "Mitarbeiter konnte nicht eingestellt werden",
  failedToFireEmployee = "Mitarbeiter konnte nicht entlassen werden",
  failedToUpdateEmployeeRole = "Mitarbeiterrolle konnte nicht aktualisiert werden",
  hireEmployee = "Mitarbeiter einstellen",
  fireEmployee = "Mitarbeiter entlassen",
  editRole = "Rolle bearbeiten",
  fire = "Entlassen",
  changeRole = "Rolle ändern",
  updateRole = "Rolle aktualisieren",

  -- v2: Test drives
  maxTestDrivesReached = "Dieses Autohaus hat die maximale Anzahl aktiver Probefahrten erreicht",
  testDriveNotEnabled = "Probefahrten sind in diesem Autohaus nicht aktiviert",
  noTestDriveSpawnCoords = "Keine Probefahrt-Spawn-Koordinaten für dieses Autohaus konfiguriert",
  couldNotSpawnTestDriveVehicle = "Probefahrt-Fahrzeug konnte nicht gespawnt werden",
  couldNotGetPlateFromServer = "Kennzeichen konnte nicht vom Server abgerufen werden",
  couldNotRegisterTestDriveVehicle = "Probefahrt-Fahrzeug konnte nicht registriert werden",
  testDriveEndedByEmployee = "Die Probefahrt wurde von einem anderen Mitarbeiter beendet",
  trackingVehicleLocation = "Fahrzeugposition wird verfolgt...",
  directSaleCancelled = "Die Verkaufsanfrage wurde vom Verkäufer storniert",
  testDriveKeysReceived = "Sie haben die Schlüssel für das Probefahrt-Fahrzeug erhalten",
  testDriveEndedCustomer = "Die Probefahrt ist beendet",
  starting = "Wird gestartet...",
  startTestDrive = "Probefahrt starten",
  spawningTestDriveVehicle = "Probefahrt-Fahrzeug wird gespawnt...",
  testDriveReady = "Probefahrt bereit",
  testDriveWalkToVehicle = "Das Probefahrt-Fahrzeug wurde am markierten Punkt gespawnt. Begleiten Sie den Kunden zum Fahrzeug. Sobald Sie dem Kunden die Schlüssel geben, müssen Sie die Probefahrt manuell beenden, wenn er zurückkehrt.",
  givingKeys = "Schlüssel werden übergeben...",
  continueAndGiveKeys = "Fortfahren & Schlüssel übergeben",
  endTestDrive = "Probefahrt beenden",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Kein Bestand für dieses Fahrzeug verfügbar",
  globalStockLimitExceeded = "Nur %{value} Einheiten verfügbar",
  orderNotFoundOrFulfilled = "Bestellung nicht gefunden oder bereits erfüllt",
  priceBelowMinimum = "Preis kann nicht unter %{value} liegen",
  priceAboveMaximum = "Preis kann nicht über %{value} liegen",
  stockUpdated = "Bestand aktualisiert",
  changesSaved = "Änderungen gespeichert",
  noStockAvailable = "Kein Bestand verfügbar",
  orderPlaced = "Bestellung aufgegeben",
  remainingInStock = "verbleibend im globalen Bestand",
  exceedsStockLimit = "Überschreitet Bestandslimit",
  setStockQty = "Bestandsmenge festlegen",
  invalidStockValue = "Bitte geben Sie einen gültigen Bestandswert ein",
  errorSettingStock = "Fehler beim Festlegen des Bestands",
  stockQuantity = "Bestandsmenge",
  currentStock = "Aktueller Bestand",
  priceLimitsEnabled = "Preislimits aktivieren",
  priceLimitsDescription = "Wenn aktiviert, können Autohaus-Manager nur Preise innerhalb des angegebenen Bereichs festlegen.",
  minPrice = "Mindestpreis",
  maxPrice = "Höchstpreis",
  optional = "Optional",
  unlimitedStock = "Unbegrenzter Bestand",
  globalStockLimit = "Globales Bestandslimit",
  globalStockLimitDescription = "Legen Sie eine maximale Anzahl von Einheiten fest, die über alle Autohäuser bestellt werden können.",
  currentlyOrdered = "Aktuell bestellt",
  priceRange = "Preisbereich",
  noMinimum = "Kein Minimum",
  noMaximum = "Kein Maximum",
  vehicleStock = "Fahrzeugbestand",

  -- v2: Sales
  allSales = "Alle Verkäufe",
  paidInFull = "Vollständig bezahlt",
  salesVolume = "Verkaufsvolumen",
  pastMonth = "Letzter Monat",
  pastYear = "Letztes Jahr",

  -- v2: Management misc
  exploitAttemptDetected = "Versuchen Sie nicht, das Skript zu exploiten",
  dealershipNoJobConfigured = "Autohaus hat keinen Job konfiguriert",
  modelDoesNotMatchDb = "Fahrzeugmodell stimmt nicht mit der Datenbank überein",
  importFailed = "Import fehlgeschlagen: %{value}",
  notInDealershipZone = "Sie müssen sich in einem Autohaus befinden, um diesen Befehl zu verwenden",
  notAnEmployee = "Sie sind kein Mitarbeiter in diesem Autohaus.",
  failedToPrepareDelivery = "Lieferung konnte nicht vorbereitet werden",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Fahrzeugmodell existiert nicht - kontaktieren Sie einen Admin",
  vehiclePlateInvalid = "Das Kennzeichen dieses Fahrzeugs ist ungültig (F8 für Details)",
  currentlyInRagdollState = "Sie befinden sich derzeit im Ragdoll-Zustand",
  vehicleDoesNotExistContactAdmin = "Fahrzeug existiert nicht. Bitte kontaktieren Sie einen Admin!",
  vehicleSecurityBreachDetected = "Fahrzeugsicherheitsverletzung erkannt",

  -- v2: Admin vehicles
  allVehicles = "Alle Fahrzeuge",
  unassignedVehicles = "Kein Autohaus",
  searchDealerships = "Autohäuser suchen...",

  -- v2: Trucking mission
  truckingGetInTruck = "Steigen Sie in den LKW am markierten Standort ein, um Ihre Lieferung zu starten",
  truckingDriveToDelivery = "Fahren Sie zum Lieferort",
  truckingCompleteDelivery = "Lieferung abschließen",
  truckingDeliveryComplete = "Lieferung abgeschlossen: Sie haben die Lieferung erfolgreich abgeschlossen!",
  truckingDeliveryFailed = "Lieferung fehlgeschlagen: Bei der Lieferung ist ein Fehler aufgetreten",
  truckingDriveToPickup = "Fahren Sie zum Abholort, um den Anhänger abzuholen",
  truckingMissionFailedSpawnCargo = "Mission fehlgeschlagen: Frachtanhänger konnte nicht gespawnt werden",
  truckingMissionFailedFindCargo = "Mission fehlgeschlagen: Gespawnte Fracht konnte nicht gefunden werden",
  truckingVehiclesLoaded = "%{count} Fahrzeug%{s} geladen",
  truckingWrongTrailer = "Falscher Anhänger! Sie müssen den richtigen Missionsanhänger anhängen.",
  truckingTrailerAttached = "Anhänger angehängt - bereit fortzufahren",
  truckingDriveToPickupLocation = "Fahren Sie zum Abholort",
  truckingWaitingForVehicles = "Warten auf Fahrzeugbeladung...",
  truckingDriveUnderTrailer = "Fahren Sie unter den Anhänger, um ihn anzuhängen",
  truckingGetInTruckContinue = "Steigen Sie in den LKW, um fortzufahren",
  truckingMissionStarted = "LKW-Mission gestartet: Abholort - %{location}",
  truckingMissionCancelled = "Mission abgebrochen: Sie haben die LKW-Mission abgebrochen",
  truckingNoActiveMission = "Keine aktive LKW-Mission zum Abbrechen",
  deliveryNotPrepared = "Lieferung nicht vorbereitet - bitte erneut versuchen",
  deliveryConfigMismatch = "Lieferungskonfiguration stimmt nicht überein",
  deliveryPreparationExpired = "Lieferungsvorbereitung abgelaufen - bitte erneut versuchen",
  noTruckingVehicleCoordinates = "Keine LKW-Fahrzeugkoordinaten festgelegt",
  pickupLocationUnavailable = "Abholort nicht mehr verfügbar - bitte erneut versuchen",
  failedToSpawnTruck = "LKW konnte nicht gespawnt werden",
  clientFailedToStartMission = "Client konnte Mission nicht starten",

  -- v2: Trucking UI/Keys
  keyDismiss = "Schließen",
  keyDeliverCargo = "Fracht liefern",
  keyContinueToDelivery = "Weiter zur Lieferung",
  startDeliveryMission = "Liefermission starten",
  orderDetails = "Bestelldetails",
  pickupLocation = "Abholort",
  deliveryStatus = "Lieferstatus",
  selectOrders = "Bestellungen auswählen",
  carTrailer = "Autotransporter",
  container = "Container",
  deliveryRoute = "Lieferroute",
  startDelivery = "Lieferung starten",

  -- v2: Direct sales UI
  waitingForCustomer = "Warten auf Kunden",
  cancelRequest = "Anfrage abbrechen",
  saleComplete = "Verkauf abgeschlossen!",
  done = "Fertig",
  saleDeclined = "Verkauf abgelehnt",
  close = "Schließen",

  -- v2: Display vehicle placement
  movement = "Bewegung",
  rotate = "Drehen",
  forward = "Vorwärts",
  backward = "Rückwärts",
  left = "Links",
  right = "Rechts",
  rotateLeft = "Nach links drehen",
  rotateRight = "Nach rechts drehen",

  -- v2: Showroom misc
  originalPrice = "Originalpreis",
  discount = "Rabatt",
  createInteraction = "Interaktion erstellen",
  viewAll = "Alle anzeigen",
  fetchingPlayers = "Spieler werden abgerufen",
  refresh = "Aktualisieren",

  -- v2: Self-service & Categories
  selfServiceDealership = "Selbstbedienungs-Autohaus",
  categories = "Kategorien",

  -- v2: Loading/Players UI
  loadingPlayers = "Spieler werden geladen...",
  failedToLoadPlayers = "Spieler konnten nicht geladen werden",
  selectAPlayer = "Spieler auswählen",
  failedToLoadPlayersRetry = "Spieler konnten nicht geladen werden. Klicken Sie auf 'Aktualisieren', um es erneut zu versuchen.",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Standorte",
  createNew = "Neu erstellen",
  enable = "Aktivieren",
  disable = "Deaktivieren",
  loading = "Wird geladen...",
  errors = "Fehler",
  update = "Aktualisieren",
  create = "Erstellen",

  -- v2: Dealership creation/editing
  createDealership = "Autohaus erstellen",
  editDealership = "Autohaus bearbeiten",
  essentials = "Grundlagen",
  advanced = "Erweitert",
  noDealershipLocations = "Keine Autohaus-Standorte",
  noDealershipLocationsDesc = "Sie können einen neuen Standort hinzufügen, aus Ihrer Konfiguration importieren (bei Migration von v1) oder einige Standardstandorte automatisch hinzufügen lassen.",

  -- v2: Location sections
  dealershipZone = "Autohaus-Zone",
  showroomAndManagement = "Showroom & Verwaltung",
  openShowroom = "Showroom öffnen",
  openManagement = "Verwaltung öffnen",
  enableSellVehicle = "Fahrzeugverkauf aktivieren",
  percentageOfVehicleValue = "Prozent % des Fahrzeugwerts",
  enablePurchase = "Kauf aktivieren",
  purchasedVehicleSpawn = "Spawn gekaufter Fahrzeuge",
  enableTestDrive = "Probefahrt aktivieren",
  testDriveVehicleSpawn = "Spawn Probefahrt-Fahrzeuge",
  truckDelivery = "LKW-Lieferung",
  truckDeliveryVehicleSpawn = "Spawn LKW-Lieferfahrzeuge",

  -- v2: Location advanced settings
  paymentMethods = "Zahlungsmethoden",
  supportsFinancing = "(unterstützt Finanzierung)",
  enableFinance = "Finanzierung aktivieren",
  cameraPreset = "Kamera",
  preset = "Voreinstellung",
  custom = "Benutzerdefiniert",
  vehiclePosition = "Fahrzeugposition",
  zoomPositions = "Zoom-Positionen (kommagetrennt)",
  zoomPositionsPlaceholder = "Beispiel: 5,8,12,8",
  vehicleColour = "Fahrzeugfarbe",
  selectionType = "Auswahltyp",
  noColourSelection = "Keine Farbauswahl",
  rgbColourWheel = "RGB-Farbrad",
  listOfRgbColours = "Liste der RGB-Farben",
  listOfColourIds = "Liste der Farb-IDs",
  accessControl = "Zugriffskontrolle",
  showroomJobWhitelist = "Showroom Job-Whitelist",
  showroomGangWhitelist = "Showroom Gang-Whitelist",
  societyPurchaseJobWhitelist = "Gesellschaftskauf Job-Whitelist",
  societyPurchaseGangWhitelist = "Gesellschaftskauf Gang-Whitelist",
  setInGame = "Im Spiel festlegen",
  addNew = "Neu hinzufügen",

  -- v2: Job/Gang whitelist editor
  job = "Job",
  gang = "Gang",
  jobWhitelist = "Job-Whitelist",
  gangWhitelist = "Gang-Whitelist",
  addJob = "Job hinzufügen",
  addGang = "Gang hinzufügen",
  editJob = "Job bearbeiten",
  editGang = "Gang bearbeiten",
  manageJobs = "Jobs verwalten",
  manageGangs = "Gangs verwalten",
  jobName = "Job-Name",
  gangName = "Gang-Name",
  selectGrades = "Ränge auswählen",
  selectAll = "Alle auswählen",
  deselectAll = "Alle abwählen",
  invalidJobName = "Ungültiger Job-Name. Überprüfen Sie Ihre Framework-Konfiguration.",
  invalidGangName = "Ungültiger Gang-Name. Überprüfen Sie Ihre Framework-Konfiguration.",
  grades = "Ränge",
  noJobsConfigured = "Keine Jobs konfiguriert",
  noGangsConfigured = "Keine Gangs konfiguriert",
  click = "Klicken",
  toGetStarted = "um zu beginnen.",
  more = "mehr",
  jobPlaceholder = "Zum Beispiel: cardealer",
  jobOptionalDescription = "Optional können Sie Autohaus-Rollen mit einem Framework-Job verknüpfen. Wenn Mitarbeiter eingestellt/entlassen werden, wird ihr Framework-Job ebenfalls aktualisiert.",
  jobRankPermissions = "Job-Rang-Berechtigungen",
  roleToJobRankMapping = "Rolle-zu-Job-Rang-Zuordnung",
  addPerm = "Berechtigung hinzufügen",

  -- v2: Colour selector
  searchColours = "Farben suchen...",
  noColoursFound = "Keine Farben gefunden",

  -- v2: Interactions creator
  noInteractions = "Keine Interaktionen",
  highlightInteractions = "Interaktionen hervorheben",
  explorationMode = "Erkundungsmodus",
  pressEsc = "ESC drücken",
  toWalkAround = "zum Herumlaufen",
  toReturnToUI = "zur Rückkehr zur UI",
  points = "Punkte",
  location = "Standort",
  manageLocations = "Standorte verwalten",

  -- v2: Interaction modal
  interactionType = "Typ",
  nicknameOptional = "Spitzname (Optional)",
  invalidModel = "Ungültiges Modell",
  failedToValidateModel = "Modell konnte nicht validiert werden",
  pedScenario = "Ped-Szenario",
  coords = "Koordinaten",
  size = "Größe",
  blip = "Blip",
  enableBlip = "Blip aktivieren",
  blipIconId = "Blip-Icon-ID",
  blipColourId = "Blip-Farb-ID",
  blipSize = "Blip-Größe",
  marker = "Marker",
  enableMarker = "Marker aktivieren",
  markerStyleId = "Marker-Stil-ID",
  markerSize = "Marker-Größe",
  markerColor = "Marker-Farbe",
  markerBobUpAndDown = "Auf und ab bewegen",
  markerFaceCamera = "Zur Kamera ausrichten",
  markerRotate = "Rotieren",
  markerDrawOnEnts = "Auf Entitäten zeichnen",
  updatePosition = "Position aktualisieren",
  setPosition = "Position festlegen",

  -- v2: Interaction types
  interactionPoint = "Punkt",
  interactionPointDesc = "Einzelner skalierbarer Punkt mit optionalem Marker",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Multi-Koordinaten-Zone für einen spezifischen Interaktionsbereich",
  interactionVehicle = "Fahrzeug",
  interactionVehicleDesc = "Fahrzeugmodell spawnen, ideal für Target- oder 3D-Text-UI-Methoden",
  interactionObject = "Objekt",
  interactionObjectDesc = "Objektmodell spawnen, ideal für Target- oder 3D-Text-UI-Methoden",
  interactionPed = "Ped",
  interactionPedDesc = "Ped-Modell mit optionalem Szenario spawnen, ideal für Target- oder 3D-Text-UI-Methoden",

  -- v2: Import modal
  importLocationsTitle = "Standorte importieren",
  syncStockLabel = "Bestand synchronisieren",
  syncStockDescription = "Fahrzeuge zum Bestand jedes Autohauses basierend auf seinen Kategorien hinzufügen",
  importSourceSelectorDesc = "Sie können entweder Standardstandorte für eine fertige Einrichtung importieren oder Ihre bestehenden Standorte aus Ihrer Konfiguration importieren, wenn Sie von v1 migrieren.",
  importSourceSelectorSkipDesc = "Standorte, die bereits in der Datenbank existieren, werden übersprungen; nur neue Standorte werden importiert.",
  successfullyImported = "Erfolgreich importiert",
  alreadyExist = "Existiert bereits",
  defaultLocations = "Standardstandorte",
  defaultLocationsDesc = "Vorkonfigurierte Autohaus-Standorte importieren (PDM, Luxus, Boote, Luft, LKW)",
  existingConfig = "Bestehende Konfiguration",
  existingConfigDesc = "Standorte aus config.lua importieren (für v1-Migration)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Möchten Sie automatisch Fahrzeuge zum Bestand dieses Autohauses basierend auf den ausgewählten Kategorien hinzufügen?",
  categorySyncEditDesc = "Sie haben die Kategorien für dieses Autohaus geändert. Möchten Sie den Fahrzeugbestand automatisch aktualisieren?",
  addVehicles = "Fahrzeuge hinzufügen",
  removeVehicles = "Fahrzeuge entfernen",
  fromNewCategories = "aus neuen Kategorien",
  fromSelectedCategories = "aus ausgewählten Kategorien",
  fromRemovedCategories = "aus entfernten Kategorien",
  categoriesAdded = "Hinzugefügte Kategorien:",
  categoriesRemoved = "Entfernte Kategorien:",
  skip = "Überspringen",
  syncStock = "Bestand synchronisieren",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Quellverfügbarkeit wird geprüft...",
  vehiclesAvailableToImport = "Fahrzeuge zum Import verfügbar",
  includesDealershipIds = "enthält Autohaus-IDs",
  sourceUnavailable = "Quelle nicht verfügbar",
  noVehiclesAdminDescription = "Sie können Fahrzeuge manuell hinzufügen oder aus Ihrem Framework importieren.",
  appendBehaviour = "Anhängen",
  overwriteBehaviour = "Überschreiben",
  appendDescription = "Nur neue Fahrzeuge hinzufügen, die noch nicht in der Datenbank existieren",
  overwriteDescription = "Alle bestehenden Fahrzeugdaten löschen und neu importieren",
  stockAssignmentMethod = "Bestandszuweisungsmethode",
  useDealershipIdsFromSource = "Autohaus-IDs aus Quelle verwenden",
  matchByVehicleCategory = "Nach Fahrzeugkategorie zuordnen",
  byShopDescription = "Fahrzeuge werden Autohäusern basierend auf dem 'shop'-Feld in den Quelldaten zugewiesen",
  byCategoryDescription = "Fahrzeuge werden Autohäusern mit passenden Kategorien zugewiesen",
  overwriteWarning = "Warnung: Überschreiben löscht alle bestehenden Fahrzeuge, Bestellungen, Ausstellungsfahrzeuge und Verkaufsdaten.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX Fahrzeugtabelle",
  selectCategory = "Kategorie auswählen",

  -- v2: Management menu items
  vehiclesMenu = "Fahrzeuge",
  displayVehiclesMenu = "Ausstellungsfahrzeuge",
  ordersMenu = "Bestellungen",
  salesMenu = "Verkäufe",
  bankAccountMenu = "Bankkonto",
  employeesMenu = "Mitarbeiter",
  couponsMenu = "Gutscheine",
  settingsMenu = "Einstellungen",
  noPermissionAccessManagement = "Sie haben keine Berechtigung, auf Verwaltungsfunktionen zuzugreifen.",
  backToAdmin = "Zurück zur Verwaltung",
  viewingAsAdmin = "ANSICHT ALS ADMIN",

  -- v2: Coupons table
  code = "Code",
  uses = "Verwendungen",
  perPlayer = "Pro Spieler",
  never = "Nie",
  noCoupons = "Keine Gutscheine",
  noCouponsDescription = "Kunden können beim Fahrzeugkauf einen Gutschein eingeben und Geld sparen.",

  -- v2: Coupon modal
  couponCodeLabel = "Gutscheincode",
  couponCodePlaceholder = "z.B. SUMMER2024 oder SAVE10",
  couponCodeHelp = "Geben Sie einen benutzerdefinierten Code ein (max. 25 Zeichen, nur Buchstaben, Zahlen und Bindestriche) oder klicken Sie auf 'Generieren'.",
  maxNumberOfUsesPlaceholder = "Maximale Anzahl der Verwendungen",
  maxUsesPerPlayerPlaceholder = "Maximale Verwendungen pro Spieler",
  vehicleRestrictionsPlaceholder = "Spawn-Codes durch Kommas getrennt eingeben (z.B. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Bei finanzierten Käufen erlauben",
  createCoupon = "Gutschein erstellen",
  updateCoupon = "Gutschein aktualisieren",

  -- v2: Coupon validation messages
  couponCodeRequired = "Gutscheincode ist erforderlich",
  couponCodeMaxLength = "Code darf maximal 25 Zeichen haben",
  couponCodeInvalidChars = "Code darf nur Großbuchstaben, Zahlen und Bindestriche enthalten",
  discountTypeRequired = "Rabattart ist erforderlich",
  discountValueRequired = "Rabattwert ist erforderlich",
  discountValueMin = "Rabattwert muss größer als 0 sein",
  discountValueMaxPercent = "Prozentsatz darf 100 nicht überschreiten",
  maxUsesRequired = "Maximale Verwendungen erforderlich",
  maxUsesMin = "Muss mindestens 1 sein",
  perPlayerLimitRequired = "Limit pro Spieler erforderlich",
  expiryDateRequired = "Ablaufdatum erforderlich",
  vehicleRestrictionsRequired = "Fahrzeugbeschränkungen erforderlich",
  categoryRestrictionsRequired = "Kategoriebeschränkungen erforderlich",
  selectAtLeastOneCategory = "Wählen Sie mindestens eine Kategorie",

  -- v2: Dashboard
  today = "Heute",
  thisMonth = "Diesen Monat",
  allTime = "Gesamt",
  recentSales = "Neueste Verkäufe",
  noSalesYet = "Noch keine Verkäufe!",
  noSalesDescription = "Fahrzeugverkäufe werden hier nach dem ersten Verkauf angezeigt.",
  past7Days = "Letzte 7 Tage",
  past6Months = "Letzte 6 Monate",
  numberOfSales = "Anzahl der Verkäufe",
  noDataAvailableForPeriod = "Keine Daten für diesen Zeitraum verfügbar",

  -- v2: Display vehicles
  displayVehiclesDescription = "Ausstellungsfahrzeuge sind feste Showroom-Modelle, die Ihr Inventar präsentieren und Kunden zum Kauf anregen.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework-Jobs aktiviert",
  frameworkJobsDescription = "Die Mitarbeiterverwaltung erfolgt über das Job-System des Frameworks. Spieler mit dem Autohaus-Job haben automatisch Zugriff basierend auf ihrem Job-Rang. Konfigurieren Sie Job-Berechtigungen in den Standorteinstellungen im Admin-Panel.",
  joinedColumn = "Beigetreten",
  youBadge = "Sie",

  -- v2: Orders
  noOrdersTitle = "Keine Bestellungen",
  noOrdersDescription = "Um eine Bestellung aufzugeben, öffnen Sie die Registerkarte 'Fahrzeuge' und klicken Sie auf 'Bestellen' bei dem Fahrzeug, das Sie nachbestellen möchten.",
  inProgress = "In Bearbeitung",
  awaitingDelivery = "Wartet auf Lieferung",
  orderedBy = "Bestellt von",
  viewDeliveryInfo = "Lieferinfo anzeigen",

  -- v2: Delivery
  startDeliveryMissionTitle = "Liefermission starten",
  startDeliveryDescription = "Sie sind dabei, eine Liefermission für diese Fahrzeugbestellung zu starten. Sie müssen zum Abholort fahren, den Frachtanhänger abholen und zum Autohaus zurückliefern.",
  totalDistanceAndDriveTime = "Gesamtstrecke & Fahrzeit",
  roundTrip = "Hin- und Rückfahrt",
  deliveryCompleteTitle = "Lieferung abgeschlossen",
  deliveryInProgressTitle = "Lieferung läuft",
  deliveredAt = "Geliefert um:",
  startedAt = "Gestartet um:",
  deliveredBy = "Geliefert von:",
  beingDeliveredBy = "Wird geliefert von:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Keine Bestellungen für Lieferung verfügbar. Bestellungen müssen bereit sein und dürfen nicht bereits in einer aktiven Lieferung sein.",
  confirmDeliveryTitle = "Lieferung bestätigen",
  configureDeliveryTitle = "Lieferung konfigurieren",
  trailerCapacityExceeded = "Anhängerkapazität überschritten! Sie haben %{usedSlots} Slots ausgewählt, aber das Maximum ist %{maxSlots} Slots.",
  smallVehiclesSlotInfo = "Hinweis: Kleine Fahrzeuge benötigen 1 Slot, mittlere Fahrzeuge benötigen 1,5 Slots.",
  fetchingRoute = "Wird abgerufen...",
  getRouteButton = "Route abrufen",
  selectTrailerType = "Anhängertyp auswählen",
  carTrailerLabel = "Autotransporter",
  smallMedium = "(Klein/Mittel)",
  containerLabel = "Container",
  large = "(Groß)",
  carTrailerDescription = "Der Autotransporter hat 2 Reihen. Jede Reihe fasst 3 kleine (je 1 Slot) oder 2 mittlere (je 1,5 Slots). Maximal 6 Slots insgesamt.",
  containerDescription = "Container-Anhänger transportiert 1 großes Fahrzeug",
  selectOrdersTitle = "Bestellungen auswählen",
  slots = "Slots",
  noOrdersForTrailerType = "Keine Bestellungen für diesen Anhängertyp verfügbar.",
  qty = "Menge:",
  inTransit = "unterwegs",
  totalVehicles = "Fahrzeuge gesamt:",
  estimatedTime = "Geschätzte Zeit:",
  unknown = "Unbekannt",

  -- v2: Sales
  salesEmptyDescription = "Fahrzeugverkäufe werden hier nach dem ersten Verkauf angezeigt.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Bestellung aufgegeben!",
  orderPlacedTruckingDescription = "Ihre Bestellung ist abholbereit. Gehen Sie zur Bestellseite, um sie abzuholen.",
  orderPlacedTimedDescription = "Ihre Bestellung wird in %{value} Minuten geliefert.",
  goToOrders = "Zu Bestellungen",
  noStockAvailableDescription = "Für dieses Fahrzeug ist kein Bestand verfügbar. Das globale Bestandslimit wurde erreicht.",
  stockUpdatedDescription = "Die Bestandsmenge wurde erfolgreich aktualisiert.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktive Probefahrten",
  tracking = "Verfolgung",
  track = "Verfolgen",
  endButton = "Beenden",
  endTestDriveTitle = "Probefahrt beenden",
  endTestDriveConfirmation = "Sind Sie sicher, dass Sie diese Probefahrt beenden möchten? Das Fahrzeug wird gelöscht und Insassen werden nicht zum Autohaus teleportiert.",
  vehicleLocationOnMap = "Der Fahrzeugstandort wurde auf Ihrer Karte markiert.",
  sell = "Verkaufen",
  couponCodeOptional = "Gutscheincode (Optional)",
  pleaseEnterCouponCode = "Bitte Gutscheincode eingeben",
  invalidCouponCode = "Ungültiger Gutscheincode",
  failedToValidateCoupon = "Gutschein konnte nicht validiert werden",
  apply = "Anwenden",
  applying = "Wird angewendet...",
  allStock = "Gesamter Bestand",
  inStockFilter = "Auf Lager",
  outOfStockFilter = "Nicht auf Lager",
  noResultsFound = "Keine Ergebnisse gefunden",
  noResults = "Keine Ergebnisse",
  noVehiclesMatchSearch = "Keine Fahrzeuge entsprechen Ihrer Suche",
  noVehiclesMatchFilters = "Keine Fahrzeuge entsprechen den aktuellen Filtern",
  noItemsMatchSearch = "Keine Artikel entsprechen Ihrer Suche",
  noItemsMatchFilters = "Keine Artikel entsprechen den aktuellen Filtern",
  selectColour = "Farbe auswählen",
  refreshNearbyPlayers = "Spieler in der Nähe aktualisieren",
  you = "Sie",
  items = "Artikel",
  waitingForCustomerToRespond = "Warten auf Kundenantwort...",
  vehicleSpawnedMessage = "Das Fahrzeug wurde am markierten Punkt gespawnt - bringen Sie den Kunden dorthin.",
  customerDeclinedMessage = "Der Kunde hat die Kaufanfrage abgelehnt.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "HIER UNTERSCHREIBEN",
  acceptAndPurchase = "Akzeptieren & Kaufen",
  couponApplied = "Gutschein %{code} angewendet! Sie sparen %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Mindestens 3 Punkte benötigt! (Aktuell %{value})",
  addPoint = "Punkt hinzufügen",
  removeLast = "Letzten entfernen",
  completeZone = "Zone abschließen",
  spawnPreview = "Spawn-Vorschau",
  up = "Hoch",
  down = "Runter",
  confirm = "Bestätigen",
  placePoint = "Punkt platzieren",
  radius = "Radius",

  -- v2: Blip labels
  soldVehicleLocation = "Standort verkauftes Fahrzeug",
  testDriveVehicleBlip = "Probefahrt-Fahrzeug",

  -- v2: Stock sync
  stockSyncResult = "Bestandssync: %{added} hinzugefügt, %{removed} entfernt",
  stockSyncAdded = "Bestandssync: %{value} Fahrzeuge hinzugefügt",
  importSuccessful = "Import erfolgreich! %{imported} Fahrzeuge importiert (insgesamt %{total})",

  -- v2: Tooltip actions
  findOnMap = "Auf Karte finden",
  adminPanel = "Admin-Panel",

  -- v2: Common dropdown
  selectOne = "Auswählen",
}
