Locales = Locales or {}

Locales['en'] = {
  -- UI
  vehicle = "Vehicle",
  vehicles = "Vehicles",
  dealership = "Dealership",
  dealerships = "Dealerships",
  vehiclesCount = "vehicle(s)",
  dealersCount = "dealer(s)",
  accountBalance = "Account Balance",
  selfServiceDealership = "Self-service dealership",
  bank = "Bank Account",
  cash = "Cash",
  amount = "Amount",
  societyFund = "Society Fund",
  paymentSource = "Payment Source",
  purchase = "Purchase",
  personalPurchase = "Personal Purchase",
  societyPurchase = "Society Purchase",
  purchaseType = "Purchase Type",
  deposit = "Deposit",
  withdraw = "Withdraw",
  all = "All",
  yes = "Yes",
  no = "No",
  add = "Add",
  edit = "Edit",
  id = "ID",
  created = "Created",
  type = "Type",
  name = "Name",
  owner = "Owner",
  bankBalance = "Bank Balance",
  status = "Status",
  back = "Back",
  previous = "Previous",
  next = "Next",
  admin = "Admin",
  vehiclesAdmin = "Vehicles Admin",
  dealershipsAdmin = "Dealerships Admin",
  search = "Search",
  noDealershipsFound = "No dealerships found",
  noVehicles = "No vehicles found",
  page = "Page",
  of = "of",
  every = "every",
  show = "Show",
  active = "Active",
  activeFinance = "Active Finance",
  failed = "Payment Failed",
  removed = "Removed",
  setOwner = "Set Owner",
  manage = "Manage",
  deleteData = "Delete Data",
  deleteVehicle = "Delete Vehicle",
  delete = "Delete",
  deleteConfirmation = "Are you sure?",
  deleteConfirmationDanger = "Are you sure? This action is irreversable.",
  setDealershipOwner = "Set Dealership Owner",
  overwriteDealerPrices = "Overwrite dealership prices",
  nearbyPlayers = "Nearby players",
  noPlayersNearby = "No players nearby",
  selectPlayer = "Select player",
  required = "Required",
  forExample = "For example",
  spawnCode = "Spawn Code",
  brand = "Brand",
  model = "Model",
  category = "Category",
  categories = "Categories",
  price = "Price",
  import = "Import",
  importing = "Importing",
  importBehaviour = "Import Behaviour",
  importVehicles = "Import vehicles",
  importFrom = "Import from",
  dashboard = "Dashboard",
  displayVehicle = "Display Vehicle",
  displayVehicles = "Display Vehicles",
  orders = "Orders",
  sales = "Sales",
  vehiclesOnDisplay = "Vehicles on display",
  employees = "Employees",
  settings = "Settings",
  switchVehicle = "Switch Vehicle",
  remove = "Remove",
  noDisplayVehicles = "No display vehicles",
  selectVehicle = "Select vehicle",
  colour = "Colour",
  placeVehicle = "Place Vehicle",
  orderVehicle = "Order vehicle",
  cancelOrder = "Cancel Order",
  delivery = "Delivery",
  delivered = "Delivered",
  noOrders = "No orders found",
  quantity = "Quantity",
  totalCost = "Total cost",
  totalSales = "Total sales",
  noSales = "No sales found",
  paid = "Paid",
  owed = "Owed",
  dealershipName = "Dealership Name",
  save = "Save Changes",
  cancel = "Cancel",
  notEnoughMoney = "Not enough money",
  placeOrder = "Place Order",
  purchaseCost = "Purchase Cost",
  salePrice = "Sale Price",
  inStock = "In stock",
  placeVehiclePrompt = "Press %{value} to place vehicle. You can make finer adjustments afterwards!",
  remaining = "Remaining",
  prePurchaseRepoWarning = "If you can't keep up with your finance payments, your vehicle will be repossessed.",
  repossessionWarning = "Your last payment failed - your vehicle will be repossessed unless you make a payment now.",
  recurringPayment = "Recurring payment",
  remainingBalance = "Remaining balance",
  remainingPayments = "Remaining payments",
  paymentTakenEvery = "Payment taken every",
  hours = "hours",
  seconds = "seconds",
  nextPayment = "Next payment",
  makePayment = "Make payment",
  vehicleRepossessed = "Vehicle will be repossessed",
  payInFull = "Pay in full",
  earlyPaymentConfirmation = "Are you sure you want to make an early payment of",
  financedVehicles = "Financed Vehicles",
  noFinancedVehicles = "You have no vehicles with active finance",
  financeBreakdown = "Finance Breakdown",
  initialPayment = "Initial payment",
  payments = "Payments",
  length = "Length",
  interest = "Interest",
  totalPayable = "Total payable",
  leaveShowroom = "Leave Showroom",
  handling = "Handling",
  topSpeed = "Top Speed",
  power = "Power",
  torque = "Torque",
  brake = "Brake",
  financing = "Financing",
  financingAvailable = "Financing available",
  paymentsOf = "payments of",
  clear = "Clear",
  testDrive = "Test Drive",
  allCategories = "All Categories",
  sortByName = "Sort by: Name",
  sortByAvailability = "Sort by: Availability",
  sortByCheapest = "Sort by: Cheapest",
  sortByMostExpensive = "Sort by: Most Expensive",
  sortByNewest = "Sort by: Newest",
  purchaseVehicle = "Purchase Vehicle",
  purchaseFor = "Purchase for",
  selectSociety = "Select a society",
  financeOverPayments = "Finance over %{value} payments",
  payToday = "Pay today",
  financeThen = "Then",
  seeFullBreakdown = "See full breakdown",
  testDriveExit = "You can exit your vehicle at any point to end the test drive.",

  -- NOTIFICATIONS
  purchaseSuccess = "Congratulations on your purchase!",
  depositSuccess = "Deposit successful",
  withdrawSuccess = "Withdrawl successful",
  errorNotEnoughMoney = "You don't have enough money",
  errorVehicleOutOfStock = "This vehicle is out of stock",
  errorCannotAffordVehicle = "You cannot afford this vehicle",
  vehicleFinancePaymentMade = "Finance payment made for your vehicle %{value}",
  vehicleFinancePaidOff = "Congratulations, you've paid off and now own your vehicle %{value}",
  vehicleFinancePaymentFailed = "Finance payment failed for your vehicle %{value}",
  vehicleFinanceRepossessedSoon = "You need to make a payment for your vehicle %{value} or your vehicle will be repossessed soon",
  vehicleFinanceRepossessed = "Due to a failure to pay, your vehicle has been repossessed with the plate %{value}",
  dealershipNotEnoughFunds = "Dealership doesn't have enough funds",
  dealershipVehiclesOrdered = "Vehicle(s) have been successfully ordered",
  dealershipOrderCancelled = "Order successfully cancelled",
  errorVehicleWithSpawnCodeExists = "A vehicle with this spawn code already exists",
  errorExitVehicle = "You need to exit your vehicle first",

  -- NEW v1.1
  purchaseRequest = "Purchase Request",
  sendRequest = "Send Request",
  dealer = "Dealer",
  signHere = "Sign here",
  signFirstError = "Please sign first",
  denyRequest = "Deny Request",
  playerTooManyFinancedVehicles = "Player has too many financed vehicles",
  employeePermissionsError = "You don't have the necessary employee permissions",
  managerRole = "Manager",
  supervisorRole = "Supervisor",
  salesRole = "Sales",
  ownerRole = "Owner",
  employmentRequest = "Employment Request",
  accept = "Accept",
  jobOfferDescription = "You have been offered a job at the \"%{value}\" dealership. Would you like to accept?",
  pending = "Pending",
  employeeHiredMsg = "Dealership hire request was accepted!",
  employeeRejectedMsg = "Dealership hire request was rejected",
  sellVehicle = "Sell Vehicle",
  vehicleTerms = "Vehicle terms",
  financePayments = "Finance Payments",
  commission = "Commission",
  role = "Role",
  firedNotification = "You have been fired from the \"%{value}\" dealership",
  dealershipTooFarAway = "You aren't near any dealerships",
  restoreDisplayVehicles = "Restore Showroom",
  customer = "Customer",
  lessThanAMin = "Less than a minute",
  mins = "min(s)",
  notInVehicle = "You are not sat in a vehicle",
  notYourVehicleError = "This vehicle does not belong to you",
  vehicleFinancedError = "You cannot sell this vehicle because it has finance payments remaining",
  dealershipDoesntSellVehicle = "This dealership can't purchase this vehicle",
  dealershipWantsYourVehicle = "Congratulations! This dealership would like to purchase your vehicle.",
  purchasePrice = "Offered price: ",
  
  spawnCodeInvalid = "Spawn code invalid",
  displayVehicleOutsideZone = "Display vehicles must be placed within the dealership zone",
  salesRep = "Sales Rep",
  directSaleAccepted = "Direct sale request accepted! Your commission has been paid.",
  directSaleRejected = "Direct sale request rejected",

  serverAdmin = "Server Admin",
  selfService = "Self Service",
  owned = "Owned",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Invalid payment method",
  paymentMethodNoFinance = "This payment method does not support financing",
  couldNotGeneratePlate = "Could not generate plate",
  invalidCoupon = "Invalid coupon: %{value}",
  tooManyFinancedVehicles = "You have too many financed vehicles",
  couldNotSpawnVehicle = "Could not spawn vehicle",

  -- v2: Permissions
  insufficientPermissions = "Insufficient permissions",

  -- v2: Coupons
  couponCodeAlreadyExists = "Coupon code already exists",
  failedToCreateCoupon = "Failed to create coupon",
  couponCreatedSuccessfully = "Coupon created successfully",
  couponNotFound = "Coupon not found",
  couponUpdatedSuccessfully = "Coupon updated successfully",
  failedToDeleteCoupon = "Failed to delete coupon",
  couponDeletedSuccessfully = "Coupon deleted successfully",
  editCoupon = "Edit Coupon",
  addCoupon = "Add Coupon",
  couponCode = "Coupon Code",
  generating = "Generating...",
  generate = "Generate",
  discountType = "Discount Type",
  percentageOff = "Percentage Off",
  amountOff = "Amount Off",
  discountValue = "Discount Value",
  unlimitedTotalUses = "Unlimited Total Uses",
  unlimitedUsesPerPlayer = "Unlimited Uses Per Player",
  setExpiryDate = "Set Expiry Date",
  restrictToSpecificVehicles = "Restrict to Specific Vehicles",
  restrictToSpecificCategories = "Restrict to Specific Categories",
  allowUseWithFinance = "Allow use with Finance",
  deleteCoupon = "Delete Coupon",
  inactive = "Inactive",
  expired = "Expired",
  maxUses = "Max Uses",
  coupons = "Coupons",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Only server admins can self-hire",
  playerNotFound = "Player not found",
  failedToHireEmployee = "Failed to hire employee",
  failedToFireEmployee = "Failed to fire employee",
  failedToUpdateEmployeeRole = "Failed to update employee role",
  hireEmployee = "Hire Employee",
  fireEmployee = "Fire Employee",
  editRole = "Edit Role",
  fire = "Fire",
  changeRole = "Change Role",
  updateRole = "Update Role",

  -- v2: Test drives
  maxTestDrivesReached = "This dealership has reached the maximum number of active test drives",
  testDriveNotEnabled = "Test drives are not enabled at this dealership",
  noTestDriveSpawnCoords = "No test drive spawn coordinates configured for this dealership",
  couldNotSpawnTestDriveVehicle = "Could not spawn test drive vehicle",
  couldNotGetPlateFromServer = "Could not get plate from server",
  couldNotRegisterTestDriveVehicle = "Could not register test drive vehicle",
  testDriveEndedByEmployee = "The test drive has been ended by another employee",
  trackingVehicleLocation = "Tracking vehicle location...",
  directSaleCancelled = "The sale request was cancelled by the seller",
  testDriveKeysReceived = "You have received the keys for the test drive vehicle",
  testDriveEndedCustomer = "The test drive has ended",
  starting = "Starting...",
  startTestDrive = "Start Test Drive",
  spawningTestDriveVehicle = "Spawning test drive vehicle...",
  testDriveReady = "Test Drive Ready",
  testDriveWalkToVehicle = "The test drive vehicle has spawned at the point on your map. Walk the customer to the vehicle. Once you give the customer the keys, you will need to manually end the test drive when they return.",
  givingKeys = "Giving Keys...",
  continueAndGiveKeys = "Continue & Give Keys",
  endTestDrive = "End Test Drive",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "No stock available for this vehicle",
  globalStockLimitExceeded = "Only %{value} units available",
  orderNotFoundOrFulfilled = "Order not found or already fulfilled",
  priceBelowMinimum = "Price cannot be below %{value}",
  priceAboveMaximum = "Price cannot be above %{value}",
  stockUpdated = "Stock updated",
  changesSaved = "Changes saved",
  noStockAvailable = "No Stock Available",
  outOfStock = "Out of stock",
  orderPlaced = "Order Placed",
  remainingInStock = "remaining in global stock",
  exceedsStockLimit = "Exceeds stock limit",
  setStockQty = "Set Stock Qty",
  invalidStockValue = "Please enter a valid stock value",
  errorSettingStock = "Error setting stock",
  stockQuantity = "Stock Quantity",
  currentStock = "Current stock",
  priceLimitsEnabled = "Enable Price Limits",
  priceLimitsDescription = "When enabled, dealership managers can only set prices within the specified range.",
  minPrice = "Minimum Price",
  maxPrice = "Maximum Price",
  optional = "Optional",
  unlimitedStock = "Unlimited Stock",
  globalStockLimit = "Global Stock Limit",
  globalStockLimitDescription = "Set a maximum number of units that can be ordered across all dealerships.",
  currentlyOrdered = "Currently ordered",
  priceRange = "Price range",
  noMinimum = "No minimum",
  noMaximum = "No maximum",
  vehicleStock = "Vehicle Stock",

  -- v2: Sales
  allSales = "All Sales",
  paidInFull = "Paid in Full",
  financed = "Financed",
  salesVolume = "Sales Volume",
  pastMonth = "Past month",
  pastYear = "Past year",

  -- v2: Management misc
  exploitAttemptDetected = "Stop trying to exploit the script",
  dealershipNoJobConfigured = "Dealership has no job configured",
  modelDoesNotMatchDb = "Vehicle model does not match database",
  importFailed = "Import failed: %{value}",
  notInDealershipZone = "You must be inside a dealership to use this command",
  notAnEmployee = "You are not an employee at this dealership.",
  failedToPrepareDelivery = "Failed to prepare delivery",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Vehicle model does not exist - contact an admin",
  vehiclePlateInvalid = "This vehicle's plate is invalid (hit F8 for more details)",
  currentlyInRagdollState = "You are currently in a ragdoll state",
  vehicleDoesNotExistContactAdmin = "Vehicle does not exist. Please contact an admin!",
  vehicleSecurityBreachDetected = "Vehicle security breach detected",

  -- v2: Admin vehicles
  allVehicles = "All Vehicles",
  unassignedVehicles = "No Dealership",
  searchDealerships = "Search dealerships...",

  -- v2: Trucking mission
  truckingGetInTruck = "Get in the truck at the marked location to start your delivery",
  truckingDriveToDelivery = "Drive to the delivery location",
  truckingCompleteDelivery = "Complete the delivery",
  truckingDeliveryComplete = "Delivery Complete: You have successfully completed the delivery!",
  truckingDeliveryFailed = "Delivery Failed: Something went wrong with the delivery",
  truckingDriveToPickup = "Drive to the pickup location to collect the trailer",
  truckingMissionFailedSpawnCargo = "Mission Failed: Could not spawn cargo trailer",
  truckingMissionFailedFindCargo = "Mission Failed: Could not find spawned cargo",
  truckingVehiclesLoaded = "%{count} vehicle%{s} loaded",
  truckingWrongTrailer = "Wrong trailer! You must attach the correct mission trailer.",
  truckingTrailerAttached = "Trailer attached - ready to continue",
  truckingDriveToPickupLocation = "Drive to the pickup location",
  truckingWaitingForVehicles = "Waiting for vehicles to load...",
  truckingDriveUnderTrailer = "Drive under the trailer to attach it",
  truckingGetInTruckContinue = "Get in the truck to continue",
  truckingMissionStarted = "Trucking Mission Started: Pickup location - %{location}",
  truckingMissionCancelled = "Mission Cancelled: You cancelled the trucking mission",
  truckingNoActiveMission = "No active trucking mission to cancel",
  deliveryNotPrepared = "Delivery not prepared - please try again",
  deliveryConfigMismatch = "Delivery configuration mismatch",
  deliveryPreparationExpired = "Delivery preparation expired - please try again",
  noTruckingVehicleCoordinates = "No trucking vehicle coordinates set",
  pickupLocationUnavailable = "Pickup location no longer available - please try again",
  failedToSpawnTruck = "Failed to spawn truck",
  clientFailedToStartMission = "Client failed to start mission",

  -- v2: Trucking UI/Keys
  keyDismiss = "Dismiss",
  keyDeliverCargo = "Deliver Cargo",
  keyContinueToDelivery = "Continue to delivery",
  startDeliveryMission = "Start Delivery Mission",
  orderDetails = "Order Details",
  pickupLocation = "Pickup Location",
  deliveryStatus = "Delivery Status",
  selectOrders = "Select Orders",
  carTrailer = "Car Trailer",
  container = "Container",
  deliveryRoute = "Delivery Route",
  startDelivery = "Start Delivery",

  -- v2: Direct sales UI
  waitingForCustomer = "Waiting for Customer",
  cancelRequest = "Cancel Request",
  saleComplete = "Sale Complete!",
  done = "Done",
  saleDeclined = "Sale Declined",
  close = "Close",

  -- v2: Display vehicle placement
  movement = "Movement",
  rotate = "Rotate",
  forward = "Forward",
  backward = "Back",
  left = "Left",
  right = "Right",
  rotateLeft = "Rotate left",
  rotateRight = "Rotate right",

  -- v2: Showroom misc
  originalPrice = "Original Price",
  discount = "Discount",
  createInteraction = "Create Interaction",
  viewAll = "View All",
  fetchingPlayers = "Fetching players",
  refresh = "Refresh",
  loadingPlayers = "Loading players...",
  failedToLoadPlayers = "Failed to load players",
  selectAPlayer = "Select a player",
  failedToLoadPlayersRetry = "Failed to load players. Click 'Refresh' to try again.",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Locations",
  createNew = "Create New",
  enable = "Enable",
  disable = "Disable",
  loading = "Loading...",
  errors = "Errors",
  update = "Update",
  create = "Create",

  -- v2: Dealership creation/editing
  createDealership = "Create Dealership",
  editDealership = "Edit Dealership",
  essentials = "Essentials",
  advanced = "Advanced",
  noDealershipLocations = "No Dealership Locations",
  noDealershipLocationsDesc = "You can either add a new location, import from your config (if migrating from v1) or have some default locations added automatically.",

  -- v2: Location sections
  dealershipZone = "Dealership Zone",
  showroomAndManagement = "Showroom & Management",
  openShowroom = "Open Showroom",
  openManagement = "Open Management",
  enableSellVehicle = "Enable Sell Vehicle",
  percentageOfVehicleValue = "Percentage % of vehicle value",
  enablePurchase = "Enable Purchase",
  purchasedVehicleSpawn = "Purchased Vehicle Spawn",
  enableTestDrive = "Enable Test Drive",
  testDriveVehicleSpawn = "Test Drive Vehicle Spawn",
  truckDelivery = "Truck Delivery",
  truckDeliveryVehicleSpawn = "Truck Delivery Vehicle Spawn",

  -- v2: Location advanced settings
  paymentMethods = "Payment Methods",
  supportsFinancing = "(supports financing)",
  enableFinance = "Enable Finance",
  cameraPreset = "Camera",
  preset = "Preset",
  custom = "Custom",
  vehiclePosition = "Vehicle Position",
  zoomPositions = "Zoom Positions (comma separated)",
  zoomPositionsPlaceholder = "example: 5,8,12,8",
  vehicleColour = "Vehicle Colour",
  selectionType = "Selection Type",
  noColourSelection = "No colour selection",
  rgbColourWheel = "RGB Colour Wheel",
  listOfRgbColours = "List of RGB Colours",
  listOfColourIds = "List of Colour IDs",
  accessControl = "Access Control",
  showroomJobWhitelist = "Showroom Job Whitelist",
  showroomGangWhitelist = "Showroom Gang Whitelist",
  societyPurchaseJobWhitelist = "Society Purchase Job Whitelist",
  societyPurchaseGangWhitelist = "Society Purchase Gang Whitelist",
  setInGame = "Set In-Game",
  addNew = "Add New",

  -- v2: Job/Gang whitelist editor
  job = "Job",
  gang = "Gang",
  jobWhitelist = "Job Whitelist",
  gangWhitelist = "Gang Whitelist",
  addJob = "Add Job",
  addGang = "Add Gang",
  editJob = "Edit Job",
  editGang = "Edit Gang",
  manageJobs = "Manage Jobs",
  manageGangs = "Manage Gangs",
  jobName = "Job Name",
  gangName = "Gang Name",
  selectGrades = "Select Grades",
  selectAll = "Select All",
  deselectAll = "Deselect All",
  invalidJobName = "Invalid job name. Please check your framework configuration.",
  invalidGangName = "Invalid gang name. Please check your framework configuration.",
  grades = "Grades",
  noJobsConfigured = "No jobs configured",
  noGangsConfigured = "No gangs configured",
  click = "Click",
  toGetStarted = "to get started.",
  more = "more",
  jobPlaceholder = "For example: cardealer",
  jobOptionalDescription = "Optionally tie dealership roles to a framework job. When employees are hired/fired, their framework job will also be updated.",
  jobRankPermissions = "Job Rank Permissions",
  roleToJobRankMapping = "Role to Job Rank Mapping",
  addPerm = "Add Perm",

  -- v2: Colour selector
  searchColours = "Search colours...",
  noColoursFound = "No colours found",

  -- v2: Interactions creator
  noInteractions = "No interactions",
  highlightInteractions = "Highlight interactions",
  explorationMode = "Exploration Mode",
  pressEsc = "Press ESC",
  toWalkAround = "to walk around",
  toReturnToUI = "to return to UI",
  points = "points",
  location = "location",
  manageLocations = "Manage Locations",

  -- v2: Interaction modal
  interactionType = "Type",
  nicknameOptional = "Nickname (Optional)",
  invalidModel = "Invalid model",
  failedToValidateModel = "Failed to validate model",
  pedScenario = "Ped scenario",
  coords = "Coords",
  size = "Size",
  blip = "Blip",
  enableBlip = "Enable Blip",
  blipIconId = "Blip Icon ID",
  blipColourId = "Blip Colour ID",
  blipSize = "Blip Size",
  marker = "Marker",
  enableMarker = "Enable Marker",
  markerStyleId = "Marker Style ID",
  markerSize = "Marker Size",
  markerColor = "Marker Color",
  markerBobUpAndDown = "Bob Up And Down",
  markerFaceCamera = "Face Camera",
  markerRotate = "Rotate",
  markerDrawOnEnts = "Draw On Entities",
  updatePosition = "Update Position",
  setPosition = "Set Position",

  -- v2: Interaction types
  interactionPoint = "Point",
  interactionPointDesc = "Single resizeable point, with optional marker",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Multi-coordinate zone for creating a specific interaction area",
  interactionVehicle = "Vehicle",
  interactionVehicleDesc = "Spawn a vehicle model, ideal for target or 3D text UI interaction methods",
  interactionObject = "Object",
  interactionObjectDesc = "Spawn an object model, ideal for target or 3D text UI interaction methods",
  interactionPed = "Ped",
  interactionPedDesc = "Spawn a ped model with optional task scenario, ideal for target or 3D text UI interaction methods",

  -- v2: Import modal
  importLocationsTitle = "Import Locations",
  syncStockLabel = "Sync stock",
  syncStockDescription = "Add vehicles to each dealership's stock based on its categories",
  importSourceSelectorDesc = "You can either import a set of default locations for a ready to go setup, or import your existing locations from your config if you're migrating from Dealerships v1.",
  importSourceSelectorSkipDesc = "Locations that already exist in the database will be skipped; only new locations will be imported.",
  successfullyImported = "Successfully Imported",
  alreadyExist = "Already Exist",
  defaultLocations = "Default Locations",
  defaultLocationsDesc = "Import pre-configured dealership locations (PDM, Luxury, Boats, Air, Truck)",
  existingConfig = "Existing Config",
  existingConfigDesc = "Import locations from your config.lua (for v1 migration)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Would you like to automatically add vehicles to this dealership's stock based on the selected categories?",
  categorySyncEditDesc = "You've changed the categories for this dealership. Would you like to automatically update the vehicle stock?",
  addVehicles = "Add vehicles",
  removeVehicles = "Remove vehicles",
  fromNewCategories = "from new categories",
  fromSelectedCategories = "from selected categories",
  fromRemovedCategories = "from removed categories",
  categoriesAdded = "Categories added:",
  categoriesRemoved = "Categories removed:",
  skip = "Skip",
  syncStock = "Sync Stock",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Checking source availability...",
  vehiclesAvailableToImport = "vehicles available to import",
  includesDealershipIds = "includes dealership IDs",
  sourceUnavailable = "Source unavailable",
  noVehiclesAdminDescription = "You can add vehicles manually or import them from your framework.",
  appendBehaviour = "Append",
  overwriteBehaviour = "Overwrite",
  appendDescription = "Only add new vehicles that don't already exist in the database",
  overwriteDescription = "Delete all existing vehicle data and import fresh",
  stockAssignmentMethod = "Stock Assignment Method",
  useDealershipIdsFromSource = "Use dealership IDs from source",
  matchByVehicleCategory = "Match by vehicle category",
  byShopDescription = "Vehicles will be assigned to dealerships based on the 'shop' field in the source data",
  byCategoryDescription = "Vehicles will be assigned to dealerships that have matching categories",
  overwriteWarning = "Warning: Overwriting will delete all existing vehicles, orders, display vehicles and sales data.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX vehicles table",
  selectCategory = "Select a category",

  -- v2: Management menu items
  vehiclesMenu = "Vehicles",
  displayVehiclesMenu = "Display Vehicles",
  ordersMenu = "Orders",
  salesMenu = "Sales",
  bankAccountMenu = "Bank Account",
  employeesMenu = "Employees",
  couponsMenu = "Coupons",
  settingsMenu = "Settings",
  noPermissionAccessManagement = "You don't have permission to access any management features.",
  backToAdmin = "Back to admin",
  viewingAsAdmin = "VIEWING AS ADMIN",

  -- v2: Coupons table
  code = "Code",
  uses = "Uses",
  perPlayer = "Per Player",
  never = "Never",
  noCoupons = "No Coupons",
  noCouponsDescription = "Customers can enter a coupon at the vehicle purchase stage & save money.",

  -- v2: Coupon modal
  couponCodeLabel = "Coupon Code",
  couponCodePlaceholder = "e.g., SUMMER2024 or SAVE10",
  couponCodeHelp = "Enter a custom code (up to 25 characters, letters, numbers, and dashes only) or click 'Generate'.",
  maxNumberOfUsesPlaceholder = "Maximum number of uses",
  maxUsesPerPlayerPlaceholder = "Maximum uses per player",
  vehicleRestrictionsPlaceholder = "Enter spawn codes separated by commas (e.g., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Allow on Financed Purchases",
  createCoupon = "Create Coupon",
  updateCoupon = "Update Coupon",

  -- v2: Coupon validation messages
  couponCodeRequired = "Coupon code is required",
  couponCodeMaxLength = "Code must be 25 characters or less",
  couponCodeInvalidChars = "Code can only contain uppercase letters, numbers, and dashes",
  discountTypeRequired = "Discount type is required",
  discountValueRequired = "Discount value is required",
  discountValueMin = "Discount value must be greater than 0",
  discountValueMaxPercent = "Percentage cannot exceed 100",
  maxUsesRequired = "Max uses is required",
  maxUsesMin = "Must be at least 1",
  perPlayerLimitRequired = "Per player limit is required",
  expiryDateRequired = "Expiry date is required",
  vehicleRestrictionsRequired = "Vehicle restrictions are required",
  categoryRestrictionsRequired = "Category restrictions are required",
  selectAtLeastOneCategory = "Select at least one category",

  -- v2: Dashboard
  today = "Today",
  thisMonth = "This Month",
  allTime = "All Time",
  recentSales = "Recent Sales",
  noSalesYet = "No Sales Yet!",
  noSalesDescription = "Vehicle sales will show here after one has been made.",
  past7Days = "Past 7 days",
  past6Months = "Past 6 months",
  numberOfSales = "Number of Sales",
  noDataAvailableForPeriod = "No data available for this period",

  -- v2: Display vehicles
  displayVehiclesDescription = "Display vehicles are fixed showroom models used to showcase your inventory and help entice customers to make a purchase.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework Jobs Enabled",
  frameworkJobsDescription = "Employee management is handled through the framework's job system. Players with the dealership's job will automatically have access based on their job grade. Configure job permissions in the admin panel's location settings.",
  joinedColumn = "Joined",
  youBadge = "You",

  -- v2: Orders
  noOrdersTitle = "No Orders",
  noOrdersDescription = "To place an order, open the 'Vehicles' tab and click 'Place Order' on the vehicle you want to restock.",
  inProgress = "In Progress",
  awaitingDelivery = "Awaiting Delivery",
  orderedBy = "Ordered By",
  viewDeliveryInfo = "View delivery info",

  -- v2: Delivery
  startDeliveryMissionTitle = "Start Delivery Mission",
  startDeliveryDescription = "You're about to start a delivery mission for this vehicle order. You'll need to drive to the pickup location, collect the cargo trailer, and deliver it back to the dealership.",
  totalDistanceAndDriveTime = "Total Distance & Drive Time",
  roundTrip = "round-trip",
  deliveryCompleteTitle = "Delivery Complete",
  deliveryInProgressTitle = "Delivery In Progress",
  deliveredAt = "Delivered At:",
  startedAt = "Started At:",
  deliveredBy = "Delivered By:",
  beingDeliveredBy = "Being Delivered By:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "No orders are available for delivery. Orders must be ready and not already in an active delivery.",
  confirmDeliveryTitle = "Confirm Delivery",
  configureDeliveryTitle = "Configure Delivery",
  trailerCapacityExceeded = "Trailer capacity exceeded! You have selected %{usedSlots} slots but the maximum is %{maxSlots} slots.",
  smallVehiclesSlotInfo = "Remember: small vehicles use 1 slot, medium vehicles use 1.5 slots.",
  fetchingRoute = "Fetching...",
  getRouteButton = "Get Route",
  selectTrailerType = "Select Trailer Type",
  carTrailerLabel = "Car Trailer",
  smallMedium = "(Small/Medium)",
  containerLabel = "Container",
  large = "(Large)",
  carTrailerDescription = "Car trailer has 2 rows. Each row fits 3 small (1 slot each) or 2 medium (1.5 slots each). Max 6 slots total.",
  containerDescription = "Container trailer carries 1 large vehicle",
  selectOrdersTitle = "Select Orders",
  slots = "slots",
  noOrdersForTrailerType = "No orders available for this trailer type.",
  qty = "Qty:",
  inTransit = "in transit",
  totalVehicles = "Total Vehicles:",
  estimatedTime = "Estimated Time:",
  unknown = "Unknown",

  -- v2: Sales
  salesEmptyDescription = "Vehicle sales will show here after one has been made.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Order Placed!",
  orderPlacedTruckingDescription = "Your order is ready to collect. Go to the orders page to fulfill it.",
  orderPlacedTimedDescription = "It will take %{value} minutes for your order to be delivered.",
  goToOrders = "Go to Orders",
  noStockAvailableDescription = "There is no stock available for this vehicle. The global stock limit has been reached.",
  stockUpdatedDescription = "The stock quantity has been updated successfully.",

  -- v2: Direct sales tablet
  activeTestDrives = "Active Test Drives",
  tracking = "Tracking",
  track = "Track",
  endButton = "End",
  endTestDriveTitle = "End Test Drive",
  endTestDriveConfirmation = "Are you sure you want to end this test drive? The vehicle will be deleted and any occupants in the vehicle will not be teleported back to the dealership.",
  vehicleLocationOnMap = "The vehicle's location has been placed on your map.",
  sell = "Sell",
  couponCodeOptional = "Coupon Code (Optional)",
  pleaseEnterCouponCode = "Please enter a coupon code",
  invalidCouponCode = "Invalid coupon code",
  failedToValidateCoupon = "Failed to validate coupon",
  apply = "Apply",
  applying = "Applying...",
  allStock = "All Stock",
  inStockFilter = "In Stock",
  outOfStockFilter = "Out of Stock",
  noResultsFound = "No Results Found",
  noResults = "No results",
  noVehiclesMatchSearch = "No vehicles match your search query",
  noVehiclesMatchFilters = "No vehicles match your current filters",
  noItemsMatchSearch = "No items match your search query",
  noItemsMatchFilters = "No items match your current filters",
  selectColour = "Select colour",
  refreshNearbyPlayers = "Refresh nearby players",
  you = "You",
  items = "items",
  waitingForCustomerToRespond = "Waiting for customer to accept or decline...",
  vehicleSpawnedMessage = "The vehicle has spawned at the point on your map - take the customer to it.",
  customerDeclinedMessage = "The customer declined the purchase request.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "SIGN HERE",
  acceptAndPurchase = "Accept & Purchase",
  couponApplied = "Coupon %{code} applied! Saving %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Need at least 3 points to complete zone! (Currently have %{value})",
  addPoint = "Add Point",
  removeLast = "Remove Last",
  completeZone = "Complete Zone",
  spawnPreview = "Spawn Preview",
  up = "Up",
  down = "Down",
  confirm = "Confirm",
  placePoint = "Place Point",
  radius = "Radius",

  -- v2: Blip labels
  soldVehicleLocation = "Sold Vehicle Location",
  testDriveVehicleBlip = "Test Drive Vehicle",

  -- v2: Stock sync
  stockSyncResult = "Stock sync: %{added} added, %{removed} removed",
  stockSyncAdded = "Stock sync: %{value} vehicles added",
  importSuccessful = "Import successful! %{imported} vehicles imported (%{total} total)",

  -- v2: Tooltip actions
  findOnMap = "Find on Map",
  adminPanel = "Admin Panel",

  -- v2: Common dropdown
  selectOne = "Select One",
}
