Locales = Locales or {}

Locales['es'] = {
  -- UI
  vehicle = "Vehículo",
  vehicles = "Vehículos",
  dealership = "Concesionario",
  dealerships = "Concesionarios",
  vehiclesCount = "Vehículo(s)",
  dealersCount = "Concesionario(s)",
  accountBalance = "Balance de Cuenta",
  bank = "Cuenta de Banco",
  cash = "Dinero",
  amount = "Cantidad", --Before= Monto
  societyFund = "Fondos de Sociedad",
  paymentSource = "Tipo de Pago",
  purchase = "Comprar",
  personalPurchase = "Compra Personal",
  societyPurchase = "Compra Sociedad",
  purchaseType = "Tipo de Compra",
  deposit = "Depositar",
  withdraw = "Retirar",
  all = "Todos",
  yes = "Si",
  no = "No",
  add = "Añadir",
  edit = "Editar",
  id = "ID",
  created = "Creado",
  type = "Tipo",
  name = "Nombre",
  owner = "Dueño",
  bankBalance = "Saldo Bancario", --Before = Balance Banco
  status = "Estado", --Before = Esatus
  back = "Regresar",
  previous = "Atrás",
  next = "Siguiente",
  admin = "Administrar", --Before = Administar // But if that means Administrator then should be "Administrador"
  vehiclesAdmin = "Administrar Vehículos",
  dealershipsAdmin = "Administrar Concesionarios",
  search = "Buscar",
  noDealershipsFound = "No se encontraron concesionarios",
  noVehicles = "No se encontraron vehículos",
  page = "Página",
  of = "de",
  every = "cada",
  show = "Mostrar", --Before = Mostar
  active = "Activo",
  activeFinance = "Financiaciones Activas", --Before = Finanzas Activas
  failed = "Pago Fallido",
  removed = "Removido",
  setOwner = "Establecer Propietario", --Before = Poner Dueño
  manage = "Gestionar",
  deleteData = "Borrar Datos",
  deleteVehicle = "Borrar Vehículo",
  delete = "Borrar",
  deleteConfirmation = "¿Estás seguro?",
  deleteConfirmationDanger = "¿Estás seguro? Esta acción es irreversible.",
  setDealershipOwner = "Establecer Propietario",
  overwriteDealerPrices = "Sobrescribir Precios",
  nearbyPlayers = "Jugadores Cercanos",
  noPlayersNearby = "NO hay jugadores cercanos",
  selectPlayer = "Seleccionar Jugador",
  required = "Requerido",
  forExample = "Por Ejemplo",
  spawnCode = "Código",
  brand = "Marca",
  model = "Modelo",
  category = "Categoría",
  price = "Precio",
  import = "Importar",
  importing = "Importando",
  importBehaviour = "Comportamiento de Importación",
  importVehicles = "Importar Vehículos",
  importFrom = "Importar de",
  dashboard = "Panel",
  displayVehicle = "Poner Vehículo en Exposición", --Before = Poner vehiculo en display
  displayVehicles = "Vehículos en Exposición", --Before = Vehiculos en display
  orders = "Pedidos", --Before = Ordenes
  sales = "Ventas",
  vehiclesOnDisplay = "Vehículos en Exposición", --Before = Vehiculos en display
  employees = "Empleados",
  settings = "Ajustes",
  switchVehicle = "Cambiar Vehículo",
  remove = "Remover",
  noDisplayVehicles = "No Mostrar Vehículos", --Before = No display vehicles
  selectVehicle = "Seleccionar Vehículo", --Before = Select vehicle
  colour = "Color",
  placeVehicle = "Poner Vehículo",
  orderVehicle = "Ordenar Vehículos",
  cancelOrder = "Cancelar Pedido", --Before = Cancelar Orden
  delivery = "Entregando",
  delivered = "Entregados",
  noOrders = "Pedidos no Encontrados", --Before = Ordenes no encontradas
  quantity = "Cantidad",
  totalCost = "Precio Total", --Before = Costo Total
  totalSales = "Ventas totales",
  noSales = "No hay ventas encontradas", --Before = No ventas encontradas
  paid = "Pagado",
  owed = "Comprado",
  dealershipName = "Nombre Concesionario",
  save = "Guardar Cambios",
  cancel = "Cancelar",
  notEnoughMoney = "Dinero Insuficiente",
  placeOrder = "Realizar Pedido",
  purchaseCost = "Precio de Compra", --Before = Costo de la compra
  salePrice = "Precio de Venta",
  inStock = "En Stock",
  outOfStock = "Agotado",
  placeVehiclePrompt = "Presiona %{value} para colocar el vehículo. ¡Puedes hacer ajustes después!",
  remaining = "Restante",
  prePurchaseRepoWarning = "Si no puedes mantenerte al día con los pagos de financiaminento, tu vehículo será embargado.",
  repossessionWarning = "Su último pago falló: tu vehículo será embargado a menos que realice un pago ahora.",
  recurringPayment = "Pago Recurrente",
  remainingBalance = "Balance Restante",
  remainingPayments = "Pagos Restantes",
  paymentTakenEvery = "Pago Tomado Cada",
  hours = "horas",
  seconds = "segundos",
  nextPayment = "Siguiente Pago",
  makePayment = "Hacer Pago",
  vehicleRepossessed = "El vehículo será embargado",
  payInFull = "Pagar Completo",
  earlyPaymentConfirmation = "¿Estás segur@ de que quieres hacer un pago anticipado de",
  financedVehicles = "Vehículos Financiados",
  noFinancedVehicles = "No tienes vehículos con financiación activa",
  financeBreakdown = "Detalles de Financiación", --Before= Detalles Financiamineto
  initialPayment = "Pago Inicial",
  payments = "Pagos",
  length = "Tiempo",
  interest = "Interés",
  totalPayable = "Total a Pagar",
  leaveShowroom = "Salir de la Sala de Exposición", --Before= Salir del Showroom
  handling = "Manejo",
  topSpeed = "Velocidad Máxima",
  power = "Poder",
  torque = "Torque",
  brake = "Freno",
  financing = "Financiación", --Before= Financiamiento
  financingAvailable = "Financiación Disponible", --Before = Financiamiento disponible
  paymentsOf = "pagos de",
  clear = "Limpiar",
  testDrive = "Prueba de Manejo",
  allCategories = "Todas las Categorías",
  sortByName = "Ordenar por: Nombre",
  sortByAvailability = "Ordenar por: Disponibilidad",
  sortByCheapest = "Ordenar por: Más Barato",
  sortByMostExpensive = "Ordenar por: Más Caro",
  sortByNewest = "Ordenar por: Más reciente",
  purchaseVehicle = "Comprar Vehículo",
  purchaseFor = "Compra Por",
  selectSociety = "Selecciona una Sociedad",
  financeOverPayments = "Financiar por %{value} pagos",
  payToday = "Paga Hoy",
  financeThen = "Después",
  seeFullBreakdown = "Ver Desglose Completo",
  testDriveExit = "Puedes salir del vehículo en cualquier momento para finalizar la prueba de manejo.",

  -- NOTIFICATIONS
  purchaseSuccess = "¡Felicitaciones Por Su Compra!",
  depositSuccess = "Depósito Exitoso",
  withdrawSuccess = "Retiro Exitoso",
  errorNotEnoughMoney = "No tienes suficiente dinero",
  errorVehicleOutOfStock = "Este vehículo está agotado",
  errorCannotAffordVehicle = "No puedes comprar este vehículo",
  vehicleFinancePaymentMade = "Financia el pago realizado por tu vehículo %{value}",
  vehicleFinancePaidOff = "Felicitaciones, ha pagado y ahora es dueño de tu vehículo. %{value}",
  vehicleFinancePaymentFailed = "Pago de financiación fallido para tu vehículo %{value}",
  vehicleFinanceRepossessedSoon = "Necesitas hacer un pago por tu vehículo %{value} o tu vehículo será embargado pronto",
  vehicleFinanceRepossessed = "Por falta de pago, tu vehículo ha sido embargado con la placa %{value}",
  dealershipNotEnoughFunds = "El concesionario no tiene fondos suficientes",
  dealershipVehiclesOrdered = "Vehículos pedidos con éxito",
  dealershipOrderCancelled = "Pedido Cancelado",
  errorVehicleWithSpawnCodeExists = "Ya existe un vehículo con este código de generación",
  errorExitVehicle = "Primero debes salir del vehículo.",

  -- NEW v1.1
  purchaseRequest = "Solicitud de Compra",
  sendRequest = "Enviar Solicitud",
  dealer = "Distribuidor",
  financed = "Financiado",
  signHere = "Firme aquí",
  signFirstError = "Firma Primero",
  denyRequest = "Denegar Solicitud",
  playerTooManyFinancedVehicles = "El jugador tiene demasiados vehículos financiados actualmente",
  employeePermissionsError = "No tiene los permisos necesarios",
  managerRole = "Director",
  supervisorRole = "Supervisor",
  salesRole = "Supervisora",
  ownerRole = "Propietario",
  employmentRequest = "Solicitud de Empleo",
  accept = "Aceptar",
  jobOfferDescription = "Le han ofrecido un puesto de trabajo en el concesionario \"%{value}\". ¿Te gustaría aceptar?",
  pending = "Pendiente",
  employeeHiredMsg = "La solicitud de alquiler del concesionario ha sido aceptada!",
  employeeRejectedMsg = "La solicitud de alquiler del concesionario ha sido rechazada",
  sellVehicle = "Vender Vehículo",
  vehicleTerms = "Condiciones del Vehículo",
  financePayments = "Pagos Financieros",
  commission = "Comisión",
  role = "Rol",
  firedNotification = "Has sido despedido de \"%{value}\".",
  dealershipTooFarAway = "No estás cerca de ningún concesionario",
  restoreDisplayVehicles = "Restaurar Sala de Exposición",
  customer = "Cliente",
  lessThanAMin = "Menos de un Minuto",
  mins = "minuto(s)",
  notInVehicle = "No estás sentado en un vehículo",
  notYourVehicleError = "Este vehículo no te pertenece",
  vehicleFinancedError = "No puedes vender este vehículo porque tiene pagos de financiación pendientes",
  dealershipDoesntSellVehicle = "Este concesionario no puede comprar este vehículo",
  dealershipWantsYourVehicle = "Enhorabuena. Este concesionario desea comprar tu vehículo.",
  purchasePrice = "Precio Ofertado: ",

  spawnCodeInvalid = "Código de generación no válido",
  salesRep = "Sales Rep",
  directSaleAccepted = "Direct sale request accepted! Your commission has been paid.",
  directSaleRejected = "Direct sale request rejected"
}
