Locales = Locales or {}

Locales['es'] = {
  -- UI
  vehicle = "Vehículo",
  vehicles = "Vehículos",
  dealership = "Concesionario",
  dealerships = "Concesionarios",
  vehiclesCount = "Vehículo(s)",
  dealersCount = "Concesionario(s)",
  accountBalance = "Balance de Cuenta",
  bank = "Cuenta de Banco",
  cash = "Dinero",
  amount = "Cantidad", --Before= Monto
  societyFund = "Fondos de Sociedad",
  paymentSource = "Tipo de Pago",
  purchase = "Comprar",
  personalPurchase = "Compra Personal",
  societyPurchase = "Compra Sociedad",
  purchaseType = "Tipo de Compra",
  deposit = "Depositar",
  withdraw = "Retirar",
  all = "Todos",
  yes = "Si",
  no = "No",
  add = "Añadir",
  edit = "Editar",
  id = "ID",
  created = "Creado",
  type = "Tipo",
  name = "Nombre",
  owner = "Dueño",
  bankBalance = "Saldo Bancario", --Before = Balance Banco
  status = "Estado", --Before = Esatus
  back = "Regresar",
  previous = "Atrás",
  next = "Siguiente",
  admin = "Administrar", --Before = Administar // But if that means Administrator then should be "Administrador"
  vehiclesAdmin = "Administrar Vehículos",
  dealershipsAdmin = "Administrar Concesionarios",
  search = "Buscar",
  noDealershipsFound = "No se encontraron concesionarios",
  noVehicles = "No se encontraron vehículos",
  page = "Página",
  of = "de",
  every = "cada",
  show = "Mostrar", --Before = Mostar
  active = "Activo",
  activeFinance = "Financiaciones Activas", --Before = Finanzas Activas
  failed = "Pago Fallido",
  removed = "Removido",
  setOwner = "Establecer Propietario", --Before = Poner Dueño
  manage = "Gestionar",
  deleteData = "Borrar Datos",
  deleteVehicle = "Borrar Vehículo",
  delete = "Borrar",
  deleteConfirmation = "¿Estás seguro?",
  deleteConfirmationDanger = "¿Estás seguro? Esta acción es irreversible.",
  setDealershipOwner = "Establecer Propietario",
  overwriteDealerPrices = "Sobrescribir Precios",
  nearbyPlayers = "Jugadores Cercanos",
  noPlayersNearby = "NO hay jugadores cercanos",
  selectPlayer = "Seleccionar Jugador",
  required = "Requerido",
  forExample = "Por Ejemplo",
  spawnCode = "Código",
  brand = "Marca",
  model = "Modelo",
  category = "Categoría",
  price = "Precio",
  import = "Importar",
  importing = "Importando",
  importBehaviour = "Comportamiento de Importación",
  importVehicles = "Importar Vehículos",
  importFrom = "Importar de",
  dashboard = "Panel",
  displayVehicle = "Poner Vehículo en Exposición", --Before = Poner vehiculo en display
  displayVehicles = "Vehículos en Exposición", --Before = Vehiculos en display
  orders = "Pedidos", --Before = Ordenes
  sales = "Ventas",
  vehiclesOnDisplay = "Vehículos en Exposición", --Before = Vehiculos en display
  employees = "Empleados",
  settings = "Ajustes",
  switchVehicle = "Cambiar Vehículo",
  remove = "Remover",
  noDisplayVehicles = "No Mostrar Vehículos", --Before = No display vehicles
  selectVehicle = "Seleccionar Vehículo", --Before = Select vehicle
  colour = "Color",
  placeVehicle = "Poner Vehículo",
  orderVehicle = "Ordenar Vehículos",
  cancelOrder = "Cancelar Pedido", --Before = Cancelar Orden
  delivery = "Entregando",
  delivered = "Entregados",
  noOrders = "Pedidos no Encontrados", --Before = Ordenes no encontradas
  quantity = "Cantidad",
  totalCost = "Precio Total", --Before = Costo Total
  totalSales = "Ventas totales",
  noSales = "No hay ventas encontradas", --Before = No ventas encontradas
  paid = "Pagado",
  owed = "Comprado",
  dealershipName = "Nombre Concesionario",
  save = "Guardar Cambios",
  cancel = "Cancelar",
  notEnoughMoney = "Dinero Insuficiente",
  placeOrder = "Realizar Pedido",
  purchaseCost = "Precio de Compra", --Before = Costo de la compra
  salePrice = "Precio de Venta",
  inStock = "En Stock",
  outOfStock = "Agotado",
  placeVehiclePrompt = "Presiona %{value} para colocar el vehículo. ¡Puedes hacer ajustes después!",
  remaining = "Restante",
  prePurchaseRepoWarning = "Si no puedes mantenerte al día con los pagos de financiaminento, tu vehículo será embargado.",
  repossessionWarning = "Su último pago falló: tu vehículo será embargado a menos que realice un pago ahora.",
  recurringPayment = "Pago Recurrente",
  remainingBalance = "Balance Restante",
  remainingPayments = "Pagos Restantes",
  paymentTakenEvery = "Pago Tomado Cada",
  hours = "horas",
  seconds = "segundos",
  nextPayment = "Siguiente Pago",
  makePayment = "Hacer Pago",
  vehicleRepossessed = "El vehículo será embargado",
  payInFull = "Pagar Completo",
  earlyPaymentConfirmation = "¿Estás segur@ de que quieres hacer un pago anticipado de",
  financedVehicles = "Vehículos Financiados",
  noFinancedVehicles = "No tienes vehículos con financiación activa",
  financeBreakdown = "Detalles de Financiación", --Before= Detalles Financiamineto
  initialPayment = "Pago Inicial",
  payments = "Pagos",
  length = "Tiempo",
  interest = "Interés",
  totalPayable = "Total a Pagar",
  leaveShowroom = "Salir de la Sala de Exposición", --Before= Salir del Showroom
  handling = "Manejo",
  topSpeed = "Velocidad Máxima",
  power = "Poder",
  torque = "Torque",
  brake = "Freno",
  financing = "Financiación", --Before= Financiamiento
  financingAvailable = "Financiación Disponible", --Before = Financiamiento disponible
  paymentsOf = "pagos de",
  clear = "Limpiar",
  testDrive = "Prueba de Manejo",
  allCategories = "Todas las Categorías",
  sortByName = "Ordenar por: Nombre",
  sortByAvailability = "Ordenar por: Disponibilidad",
  sortByCheapest = "Ordenar por: Más Barato",
  sortByMostExpensive = "Ordenar por: Más Caro",
  sortByNewest = "Ordenar por: Más reciente",
  purchaseVehicle = "Comprar Vehículo",
  purchaseFor = "Compra Por",
  selectSociety = "Selecciona una Sociedad",
  financeOverPayments = "Financiar por %{value} pagos",
  payToday = "Paga Hoy",
  financeThen = "Después",
  seeFullBreakdown = "Ver Desglose Completo",
  testDriveExit = "Puedes salir del vehículo en cualquier momento para finalizar la prueba de manejo.",

  -- NOTIFICATIONS
  purchaseSuccess = "¡Felicitaciones Por Su Compra!",
  depositSuccess = "Depósito Exitoso",
  withdrawSuccess = "Retiro Exitoso",
  errorNotEnoughMoney = "No tienes suficiente dinero",
  errorVehicleOutOfStock = "Este vehículo está agotado",
  errorCannotAffordVehicle = "No puedes comprar este vehículo",
  vehicleFinancePaymentMade = "Financia el pago realizado por tu vehículo %{value}",
  vehicleFinancePaidOff = "Felicitaciones, ha pagado y ahora es dueño de tu vehículo. %{value}",
  vehicleFinancePaymentFailed = "Pago de financiación fallido para tu vehículo %{value}",
  vehicleFinanceRepossessedSoon = "Necesitas hacer un pago por tu vehículo %{value} o tu vehículo será embargado pronto",
  vehicleFinanceRepossessed = "Por falta de pago, tu vehículo ha sido embargado con la placa %{value}",
  dealershipNotEnoughFunds = "El concesionario no tiene fondos suficientes",
  dealershipVehiclesOrdered = "Vehículos pedidos con éxito",
  dealershipOrderCancelled = "Pedido Cancelado",
  errorVehicleWithSpawnCodeExists = "Ya existe un vehículo con este código de generación",
  errorExitVehicle = "Primero debes salir del vehículo.",

  -- NEW v1.1
  purchaseRequest = "Solicitud de Compra",
  sendRequest = "Enviar Solicitud",
  dealer = "Distribuidor",
  financed = "Financiado",
  signHere = "Firme aquí",
  signFirstError = "Firma Primero",
  denyRequest = "Denegar Solicitud",
  playerTooManyFinancedVehicles = "El jugador tiene demasiados vehículos financiados actualmente",
  employeePermissionsError = "No tiene los permisos necesarios",
  managerRole = "Director",
  supervisorRole = "Supervisor",
  salesRole = "Supervisora",
  ownerRole = "Propietario",
  employmentRequest = "Solicitud de Empleo",
  accept = "Aceptar",
  jobOfferDescription = "Le han ofrecido un puesto de trabajo en el concesionario \"%{value}\". ¿Te gustaría aceptar?",
  pending = "Pendiente",
  employeeHiredMsg = "La solicitud de alquiler del concesionario ha sido aceptada!",
  employeeRejectedMsg = "La solicitud de alquiler del concesionario ha sido rechazada",
  sellVehicle = "Vender Vehículo",
  vehicleTerms = "Condiciones del Vehículo",
  financePayments = "Pagos Financieros",
  commission = "Comisión",
  role = "Rol",
  firedNotification = "Has sido despedido de \"%{value}\".",
  dealershipTooFarAway = "No estás cerca de ningún concesionario",
  restoreDisplayVehicles = "Restaurar Sala de Exposición",
  customer = "Cliente",
  lessThanAMin = "Menos de un Minuto",
  mins = "minuto(s)",
  notInVehicle = "No estás sentado en un vehículo",
  notYourVehicleError = "Este vehículo no te pertenece",
  vehicleFinancedError = "No puedes vender este vehículo porque tiene pagos de financiación pendientes",
  dealershipDoesntSellVehicle = "Este concesionario no puede comprar este vehículo",
  dealershipWantsYourVehicle = "Enhorabuena. Este concesionario desea comprar tu vehículo.",
  purchasePrice = "Precio Ofertado: ",

  spawnCodeInvalid = "Código de generación no válido",
  salesRep = "Representante de ventas",
  directSaleAccepted = "¡Solicitud de venta directa aceptada! Tu comisión ha sido pagada.",
  directSaleRejected = "Solicitud de venta directa rechazada",

  displayVehicleOutsideZone = "Los vehículos de exposición deben colocarse dentro de la zona del concesionario",
  serverAdmin = "Admin del Servidor",
  selfService = "Autoservicio",
  owned = "Propio",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Método de pago inválido",
  paymentMethodNoFinance = "Este método de pago no admite financiación",
  couldNotGeneratePlate = "No se pudo generar la matrícula",
  invalidCoupon = "Cupón inválido: %{value}",
  tooManyFinancedVehicles = "Tienes demasiados vehículos financiados",
  couldNotSpawnVehicle = "No se pudo generar el vehículo",

  -- v2: Permissions
  insufficientPermissions = "Permisos insuficientes",

  -- v2: Coupons
  couponCodeAlreadyExists = "El código de cupón ya existe",
  failedToCreateCoupon = "Error al crear el cupón",
  couponCreatedSuccessfully = "Cupón creado correctamente",
  couponNotFound = "Cupón no encontrado",
  couponUpdatedSuccessfully = "Cupón actualizado correctamente",
  failedToDeleteCoupon = "Error al eliminar el cupón",
  couponDeletedSuccessfully = "Cupón eliminado correctamente",
  editCoupon = "Editar cupón",
  addCoupon = "Añadir cupón",
  couponCode = "Código de cupón",
  generating = "Generando...",
  generate = "Generar",
  discountType = "Tipo de descuento",
  percentageOff = "Porcentaje de descuento",
  amountOff = "Cantidad de descuento",
  discountValue = "Valor del descuento",
  unlimitedTotalUses = "Usos totales ilimitados",
  unlimitedUsesPerPlayer = "Usos ilimitados por jugador",
  setExpiryDate = "Establecer fecha de caducidad",
  restrictToSpecificVehicles = "Restringir a vehículos específicos",
  restrictToSpecificCategories = "Restringir a categorías específicas",
  allowUseWithFinance = "Permitir uso con financiación",
  deleteCoupon = "Eliminar cupón",
  inactive = "Inactivo",
  expired = "Caducado",
  maxUses = "Usos máximos",
  coupons = "Cupones",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Solo los administradores del servidor pueden autocontratarse",
  playerNotFound = "Jugador no encontrado",
  failedToHireEmployee = "Error al contratar empleado",
  failedToFireEmployee = "Error al despedir empleado",
  failedToUpdateEmployeeRole = "Error al actualizar el rol del empleado",
  hireEmployee = "Contratar empleado",
  fireEmployee = "Despedir empleado",
  editRole = "Editar rol",
  fire = "Despedir",
  changeRole = "Cambiar rol",
  updateRole = "Actualizar rol",

  -- v2: Test drives
  maxTestDrivesReached = "Este concesionario ha alcanzado el número máximo de pruebas activas",
  testDriveNotEnabled = "Las pruebas de conducción no están habilitadas en este concesionario",
  noTestDriveSpawnCoords = "No hay coordenadas de spawn para pruebas configuradas para este concesionario",
  couldNotSpawnTestDriveVehicle = "No se pudo generar el vehículo de prueba",
  couldNotGetPlateFromServer = "No se pudo obtener la matrícula del servidor",
  couldNotRegisterTestDriveVehicle = "No se pudo registrar el vehículo de prueba",
  testDriveEndedByEmployee = "La prueba de conducción ha sido terminada por otro empleado",
  trackingVehicleLocation = "Rastreando ubicación del vehículo...",
  directSaleCancelled = "La solicitud de venta fue cancelada por el vendedor",
  testDriveKeysReceived = "Has recibido las llaves del vehículo de prueba",
  testDriveEndedCustomer = "La prueba de conducción ha terminado",
  starting = "Iniciando...",
  startTestDrive = "Iniciar prueba",
  spawningTestDriveVehicle = "Generando vehículo de prueba...",
  testDriveReady = "Prueba lista",
  testDriveWalkToVehicle = "El vehículo de prueba ha aparecido en el punto marcado en tu mapa. Acompaña al cliente hasta el vehículo. Una vez que le des las llaves al cliente, tendrás que terminar manualmente la prueba cuando regrese.",
  givingKeys = "Entregando llaves...",
  continueAndGiveKeys = "Continuar y dar llaves",
  endTestDrive = "Terminar prueba",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "No hay stock disponible para este vehículo",
  globalStockLimitExceeded = "Solo %{value} unidades disponibles",
  orderNotFoundOrFulfilled = "Pedido no encontrado o ya completado",
  priceBelowMinimum = "El precio no puede ser inferior a %{value}",
  priceAboveMaximum = "El precio no puede ser superior a %{value}",
  stockUpdated = "Stock actualizado",
  changesSaved = "Cambios guardados",
  noStockAvailable = "Sin stock disponible",
  orderPlaced = "Pedido realizado",
  remainingInStock = "restante en stock global",
  exceedsStockLimit = "Excede el límite de stock",
  setStockQty = "Establecer cantidad de stock",
  invalidStockValue = "Por favor, introduce un valor de stock válido",
  errorSettingStock = "Error al establecer el stock",
  stockQuantity = "Cantidad de stock",
  currentStock = "Stock actual",
  priceLimitsEnabled = "Habilitar límites de precio",
  priceLimitsDescription = "Cuando está habilitado, los gerentes del concesionario solo pueden establecer precios dentro del rango especificado.",
  minPrice = "Precio mínimo",
  maxPrice = "Precio máximo",
  optional = "Opcional",
  unlimitedStock = "Stock ilimitado",
  globalStockLimit = "Límite de stock global",
  globalStockLimitDescription = "Establece un número máximo de unidades que se pueden pedir en todos los concesionarios.",
  currentlyOrdered = "Actualmente pedido",
  priceRange = "Rango de precios",
  noMinimum = "Sin mínimo",
  noMaximum = "Sin máximo",
  vehicleStock = "Stock de vehículos",

  -- v2: Sales
  allSales = "Todas las ventas",
  paidInFull = "Pagado al contado",
  salesVolume = "Volumen de ventas",
  pastMonth = "Mes pasado",
  pastYear = "Año pasado",

  -- v2: Management misc
  exploitAttemptDetected = "Deja de intentar explotar el script",
  dealershipNoJobConfigured = "El concesionario no tiene trabajo configurado",
  modelDoesNotMatchDb = "El modelo del vehículo no coincide con la base de datos",
  importFailed = "Importación fallida: %{value}",
  notInDealershipZone = "Debes estar dentro de un concesionario para usar este comando",
  notAnEmployee = "No eres empleado de este concesionario.",
  failedToPrepareDelivery = "Error al preparar la entrega",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "El modelo del vehículo no existe - contacta con un admin",
  vehiclePlateInvalid = "La matrícula de este vehículo es inválida (pulsa F8 para más detalles)",
  currentlyInRagdollState = "Actualmente estás en estado ragdoll",
  vehicleDoesNotExistContactAdmin = "El vehículo no existe. ¡Contacta con un admin!",
  vehicleSecurityBreachDetected = "Violación de seguridad del vehículo detectada",

  -- v2: Admin vehicles
  allVehicles = "Todos los vehículos",
  unassignedVehicles = "Sin concesionario",
  searchDealerships = "Buscar concesionarios...",

  -- v2: Trucking mission
  truckingGetInTruck = "Sube al camión en la ubicación marcada para iniciar tu entrega",
  truckingDriveToDelivery = "Conduce hasta el lugar de entrega",
  truckingCompleteDelivery = "Completar la entrega",
  truckingDeliveryComplete = "Entrega completada: ¡Has completado la entrega con éxito!",
  truckingDeliveryFailed = "Entrega fallida: Algo salió mal con la entrega",
  truckingDriveToPickup = "Conduce al punto de recogida para recoger el remolque",
  truckingMissionFailedSpawnCargo = "Misión fallida: No se pudo generar el remolque de carga",
  truckingMissionFailedFindCargo = "Misión fallida: No se pudo encontrar la carga generada",
  truckingVehiclesLoaded = "%{count} vehículo%{s} cargado",
  truckingWrongTrailer = "¡Remolque incorrecto! Debes enganchar el remolque de misión correcto.",
  truckingTrailerAttached = "Remolque enganchado - listo para continuar",
  truckingDriveToPickupLocation = "Conduce al punto de recogida",
  truckingWaitingForVehicles = "Esperando a que se carguen los vehículos...",
  truckingDriveUnderTrailer = "Pasa por debajo del remolque para engancharlo",
  truckingGetInTruckContinue = "Sube al camión para continuar",
  truckingMissionStarted = "Misión de transporte iniciada: Punto de recogida - %{location}",
  truckingMissionCancelled = "Misión cancelada: Has cancelado la misión de transporte",
  truckingNoActiveMission = "No hay misión de transporte activa para cancelar",
  deliveryNotPrepared = "Entrega no preparada - por favor, inténtalo de nuevo",
  deliveryConfigMismatch = "Configuración de entrega no coincidente",
  deliveryPreparationExpired = "Preparación de entrega expirada - por favor, inténtalo de nuevo",
  noTruckingVehicleCoordinates = "No hay coordenadas de vehículo de transporte establecidas",
  pickupLocationUnavailable = "Punto de recogida ya no disponible - por favor, inténtalo de nuevo",
  failedToSpawnTruck = "Error al generar el camión",
  clientFailedToStartMission = "El cliente no pudo iniciar la misión",

  -- v2: Trucking UI/Keys
  keyDismiss = "Cerrar",
  keyDeliverCargo = "Entregar carga",
  keyContinueToDelivery = "Continuar a la entrega",
  startDeliveryMission = "Iniciar misión de entrega",
  orderDetails = "Detalles del pedido",
  pickupLocation = "Punto de recogida",
  deliveryStatus = "Estado de entrega",
  selectOrders = "Seleccionar pedidos",
  carTrailer = "Portacoches",
  container = "Contenedor",
  deliveryRoute = "Ruta de entrega",
  startDelivery = "Iniciar entrega",

  -- v2: Direct sales UI
  waitingForCustomer = "Esperando al cliente",
  cancelRequest = "Cancelar solicitud",
  saleComplete = "¡Venta completada!",
  done = "Hecho",
  saleDeclined = "Venta rechazada",
  close = "Cerrar",

  -- v2: Display vehicle placement
  movement = "Movimiento",
  rotate = "Rotar",
  forward = "Adelante",
  backward = "Atrás",
  left = "Izquierda",
  right = "Derecha",
  rotateLeft = "Rotar izquierda",
  rotateRight = "Rotar derecha",

  -- v2: Showroom misc
  originalPrice = "Precio original",
  discount = "Descuento",
  createInteraction = "Crear interacción",
  viewAll = "Ver todo",
  fetchingPlayers = "Obteniendo jugadores",
  refresh = "Actualizar",
}
