Locales = Locales or {}

Locales['es'] = {
  -- UI
  vehicle = "Vehículo",
  vehicles = "Vehículos",
  dealership = "Concesionario",
  dealerships = "Concesionarios",
  vehiclesCount = "Vehículo(s)",
  dealersCount = "Concesionario(s)",
  accountBalance = "Balance de Cuenta",
  bank = "Cuenta de Banco",
  cash = "Dinero",
  amount = "Cantidad", --Before= Monto
  societyFund = "Fondos de Sociedad",
  paymentSource = "Tipo de Pago",
  purchase = "Comprar",
  personalPurchase = "Compra Personal",
  societyPurchase = "Compra Sociedad",
  purchaseType = "Tipo de Compra",
  deposit = "Depositar",
  withdraw = "Retirar",
  all = "Todos",
  yes = "Si",
  no = "No",
  add = "Añadir",
  edit = "Editar",
  id = "ID",
  created = "Creado",
  type = "Tipo",
  name = "Nombre",
  owner = "Dueño",
  bankBalance = "Saldo Bancario", --Before = Balance Banco
  status = "Estado", --Before = Esatus
  back = "Regresar",
  previous = "Atrás",
  next = "Siguiente",
  admin = "Administrar", --Before = Administar // But if that means Administrator then should be "Administrador"
  vehiclesAdmin = "Administrar Vehículos",
  dealershipsAdmin = "Administrar Concesionarios",
  search = "Buscar",
  noDealershipsFound = "No se encontraron concesionarios",
  noVehicles = "No se encontraron vehículos",
  page = "Página",
  of = "de",
  every = "cada",
  show = "Mostrar", --Before = Mostar
  active = "Activo",
  activeFinance = "Financiaciones Activas", --Before = Finanzas Activas
  failed = "Pago Fallido",
  removed = "Removido",
  setOwner = "Establecer Propietario", --Before = Poner Dueño
  manage = "Gestionar",
  deleteData = "Borrar Datos",
  deleteVehicle = "Borrar Vehículo",
  delete = "Borrar",
  deleteConfirmation = "¿Estás seguro?",
  deleteConfirmationDanger = "¿Estás seguro? Esta acción es irreversible.",
  setDealershipOwner = "Establecer Propietario",
  overwriteDealerPrices = "Sobrescribir Precios",
  nearbyPlayers = "Jugadores Cercanos",
  noPlayersNearby = "NO hay jugadores cercanos",
  selectPlayer = "Seleccionar Jugador",
  required = "Requerido",
  forExample = "Por Ejemplo",
  spawnCode = "Código",
  brand = "Marca",
  model = "Modelo",
  category = "Categoría",
  price = "Precio",
  import = "Importar",
  importing = "Importando",
  importBehaviour = "Comportamiento de Importación",
  importVehicles = "Importar Vehículos",
  importFrom = "Importar de",
  dashboard = "Panel",
  displayVehicle = "Poner Vehículo en Exposición", --Before = Poner vehiculo en display
  displayVehicles = "Vehículos en Exposición", --Before = Vehiculos en display
  orders = "Pedidos", --Before = Ordenes
  sales = "Ventas",
  vehiclesOnDisplay = "Vehículos en Exposición", --Before = Vehiculos en display
  employees = "Empleados",
  settings = "Ajustes",
  switchVehicle = "Cambiar Vehículo",
  remove = "Remover",
  noDisplayVehicles = "No Mostrar Vehículos", --Before = No display vehicles
  selectVehicle = "Seleccionar Vehículo", --Before = Select vehicle
  colour = "Color",
  placeVehicle = "Poner Vehículo",
  orderVehicle = "Ordenar Vehículos",
  cancelOrder = "Cancelar Pedido", --Before = Cancelar Orden
  delivery = "Entregando",
  delivered = "Entregados",
  noOrders = "Pedidos no Encontrados", --Before = Ordenes no encontradas
  quantity = "Cantidad",
  totalCost = "Precio Total", --Before = Costo Total
  totalSales = "Ventas totales",
  noSales = "No hay ventas encontradas", --Before = No ventas encontradas
  paid = "Pagado",
  owed = "Comprado",
  dealershipName = "Nombre Concesionario",
  save = "Guardar Cambios",
  cancel = "Cancelar",
  notEnoughMoney = "Dinero Insuficiente",
  placeOrder = "Realizar Pedido",
  purchaseCost = "Precio de Compra", --Before = Costo de la compra
  salePrice = "Precio de Venta",
  inStock = "En Stock",
  outOfStock = "Agotado",
  placeVehiclePrompt = "Presiona %{value} para colocar el vehículo. ¡Puedes hacer ajustes después!",
  remaining = "Restante",
  prePurchaseRepoWarning = "Si no puedes mantenerte al día con los pagos de financiaminento, tu vehículo será embargado.",
  repossessionWarning = "Su último pago falló: tu vehículo será embargado a menos que realice un pago ahora.",
  recurringPayment = "Pago Recurrente",
  remainingBalance = "Balance Restante",
  remainingPayments = "Pagos Restantes",
  paymentTakenEvery = "Pago Tomado Cada",
  hours = "horas",
  seconds = "segundos",
  nextPayment = "Siguiente Pago",
  makePayment = "Hacer Pago",
  vehicleRepossessed = "El vehículo será embargado",
  payInFull = "Pagar Completo",
  earlyPaymentConfirmation = "¿Estás segur@ de que quieres hacer un pago anticipado de",
  financedVehicles = "Vehículos Financiados",
  noFinancedVehicles = "No tienes vehículos con financiación activa",
  financeBreakdown = "Detalles de Financiación", --Before= Detalles Financiamineto
  initialPayment = "Pago Inicial",
  payments = "Pagos",
  length = "Tiempo",
  interest = "Interés",
  totalPayable = "Total a Pagar",
  leaveShowroom = "Salir de la Sala de Exposición", --Before= Salir del Showroom
  handling = "Manejo",
  topSpeed = "Velocidad Máxima",
  power = "Poder",
  torque = "Torque",
  brake = "Freno",
  financing = "Financiación", --Before= Financiamiento
  financingAvailable = "Financiación Disponible", --Before = Financiamiento disponible
  paymentsOf = "pagos de",
  clear = "Limpiar",
  testDrive = "Prueba de Manejo",
  allCategories = "Todas las Categorías",
  sortByName = "Ordenar por: Nombre",
  sortByAvailability = "Ordenar por: Disponibilidad",
  sortByCheapest = "Ordenar por: Más Barato",
  sortByMostExpensive = "Ordenar por: Más Caro",
  sortByNewest = "Ordenar por: Más reciente",
  purchaseVehicle = "Comprar Vehículo",
  purchaseFor = "Compra Por",
  selectSociety = "Selecciona una Sociedad",
  financeOverPayments = "Financiar por %{value} pagos",
  payToday = "Paga Hoy",
  financeThen = "Después",
  seeFullBreakdown = "Ver Desglose Completo",
  testDriveExit = "Puedes salir del vehículo en cualquier momento para finalizar la prueba de manejo.",

  -- NOTIFICATIONS
  purchaseSuccess = "¡Felicitaciones Por Su Compra!",
  depositSuccess = "Depósito Exitoso",
  withdrawSuccess = "Retiro Exitoso",
  errorNotEnoughMoney = "No tienes suficiente dinero",
  errorVehicleOutOfStock = "Este vehículo está agotado",
  errorCannotAffordVehicle = "No puedes comprar este vehículo",
  vehicleFinancePaymentMade = "Financia el pago realizado por tu vehículo %{value}",
  vehicleFinancePaidOff = "Felicitaciones, ha pagado y ahora es dueño de tu vehículo. %{value}",
  vehicleFinancePaymentFailed = "Pago de financiación fallido para tu vehículo %{value}",
  vehicleFinanceRepossessedSoon = "Necesitas hacer un pago por tu vehículo %{value} o tu vehículo será embargado pronto",
  vehicleFinanceRepossessed = "Por falta de pago, tu vehículo ha sido embargado con la placa %{value}",
  dealershipNotEnoughFunds = "El concesionario no tiene fondos suficientes",
  dealershipVehiclesOrdered = "Vehículos pedidos con éxito",
  dealershipOrderCancelled = "Pedido Cancelado",
  errorVehicleWithSpawnCodeExists = "Ya existe un vehículo con este código de generación",
  errorExitVehicle = "Primero debes salir del vehículo.",

  -- NEW v1.1
  purchaseRequest = "Solicitud de Compra",
  sendRequest = "Enviar Solicitud",
  dealer = "Distribuidor",
  financed = "Financiado",
  signHere = "Firme aquí",
  signFirstError = "Firma Primero",
  denyRequest = "Denegar Solicitud",
  playerTooManyFinancedVehicles = "El jugador tiene demasiados vehículos financiados actualmente",
  employeePermissionsError = "No tiene los permisos necesarios",
  managerRole = "Director",
  supervisorRole = "Supervisor",
  salesRole = "Supervisora",
  ownerRole = "Propietario",
  employmentRequest = "Solicitud de Empleo",
  accept = "Aceptar",
  jobOfferDescription = "Le han ofrecido un puesto de trabajo en el concesionario \"%{value}\". ¿Te gustaría aceptar?",
  pending = "Pendiente",
  employeeHiredMsg = "La solicitud de alquiler del concesionario ha sido aceptada!",
  employeeRejectedMsg = "La solicitud de alquiler del concesionario ha sido rechazada",
  sellVehicle = "Vender Vehículo",
  vehicleTerms = "Condiciones del Vehículo",
  financePayments = "Pagos Financieros",
  commission = "Comisión",
  role = "Rol",
  firedNotification = "Has sido despedido de \"%{value}\".",
  dealershipTooFarAway = "No estás cerca de ningún concesionario",
  restoreDisplayVehicles = "Restaurar Sala de Exposición",
  customer = "Cliente",
  lessThanAMin = "Menos de un Minuto",
  mins = "minuto(s)",
  notInVehicle = "No estás sentado en un vehículo",
  notYourVehicleError = "Este vehículo no te pertenece",
  vehicleFinancedError = "No puedes vender este vehículo porque tiene pagos de financiación pendientes",
  dealershipDoesntSellVehicle = "Este concesionario no puede comprar este vehículo",
  dealershipWantsYourVehicle = "Enhorabuena. Este concesionario desea comprar tu vehículo.",
  purchasePrice = "Precio Ofertado: ",

  spawnCodeInvalid = "Código de generación no válido",
  salesRep = "Representante de ventas",
  directSaleAccepted = "¡Solicitud de venta directa aceptada! Tu comisión ha sido pagada.",
  directSaleRejected = "Solicitud de venta directa rechazada",

  displayVehicleOutsideZone = "Los vehículos de exposición deben colocarse dentro de la zona del concesionario",
  serverAdmin = "Admin del Servidor",
  selfService = "Autoservicio",
  owned = "Propio",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Método de pago inválido",
  paymentMethodNoFinance = "Este método de pago no admite financiación",
  couldNotGeneratePlate = "No se pudo generar la matrícula",
  invalidCoupon = "Cupón inválido: %{value}",
  tooManyFinancedVehicles = "Tienes demasiados vehículos financiados",
  couldNotSpawnVehicle = "No se pudo generar el vehículo",

  -- v2: Permissions
  insufficientPermissions = "Permisos insuficientes",

  -- v2: Coupons
  couponCodeAlreadyExists = "El código de cupón ya existe",
  failedToCreateCoupon = "Error al crear el cupón",
  couponCreatedSuccessfully = "Cupón creado correctamente",
  couponNotFound = "Cupón no encontrado",
  couponUpdatedSuccessfully = "Cupón actualizado correctamente",
  failedToDeleteCoupon = "Error al eliminar el cupón",
  couponDeletedSuccessfully = "Cupón eliminado correctamente",
  editCoupon = "Editar cupón",
  addCoupon = "Añadir cupón",
  couponCode = "Código de cupón",
  generating = "Generando...",
  generate = "Generar",
  discountType = "Tipo de descuento",
  percentageOff = "Porcentaje de descuento",
  amountOff = "Cantidad de descuento",
  discountValue = "Valor del descuento",
  unlimitedTotalUses = "Usos totales ilimitados",
  unlimitedUsesPerPlayer = "Usos ilimitados por jugador",
  setExpiryDate = "Establecer fecha de caducidad",
  restrictToSpecificVehicles = "Restringir a vehículos específicos",
  restrictToSpecificCategories = "Restringir a categorías específicas",
  allowUseWithFinance = "Permitir uso con financiación",
  deleteCoupon = "Eliminar cupón",
  inactive = "Inactivo",
  expired = "Caducado",
  maxUses = "Usos máximos",
  coupons = "Cupones",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Solo los administradores del servidor pueden autocontratarse",
  playerNotFound = "Jugador no encontrado",
  failedToHireEmployee = "Error al contratar empleado",
  failedToFireEmployee = "Error al despedir empleado",
  failedToUpdateEmployeeRole = "Error al actualizar el rol del empleado",
  hireEmployee = "Contratar empleado",
  fireEmployee = "Despedir empleado",
  editRole = "Editar rol",
  fire = "Despedir",
  changeRole = "Cambiar rol",
  updateRole = "Actualizar rol",

  -- v2: Test drives
  maxTestDrivesReached = "Este concesionario ha alcanzado el número máximo de pruebas activas",
  testDriveNotEnabled = "Las pruebas de conducción no están habilitadas en este concesionario",
  noTestDriveSpawnCoords = "No hay coordenadas de spawn para pruebas configuradas para este concesionario",
  couldNotSpawnTestDriveVehicle = "No se pudo generar el vehículo de prueba",
  couldNotGetPlateFromServer = "No se pudo obtener la matrícula del servidor",
  couldNotRegisterTestDriveVehicle = "No se pudo registrar el vehículo de prueba",
  testDriveEndedByEmployee = "La prueba de conducción ha sido terminada por otro empleado",
  trackingVehicleLocation = "Rastreando ubicación del vehículo...",
  directSaleCancelled = "La solicitud de venta fue cancelada por el vendedor",
  testDriveKeysReceived = "Has recibido las llaves del vehículo de prueba",
  testDriveEndedCustomer = "La prueba de conducción ha terminado",
  starting = "Iniciando...",
  startTestDrive = "Iniciar prueba",
  spawningTestDriveVehicle = "Generando vehículo de prueba...",
  testDriveReady = "Prueba lista",
  testDriveWalkToVehicle = "El vehículo de prueba ha aparecido en el punto marcado en tu mapa. Acompaña al cliente hasta el vehículo. Una vez que le des las llaves al cliente, tendrás que terminar manualmente la prueba cuando regrese.",
  givingKeys = "Entregando llaves...",
  continueAndGiveKeys = "Continuar y dar llaves",
  endTestDrive = "Terminar prueba",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "No hay stock disponible para este vehículo",
  globalStockLimitExceeded = "Solo %{value} unidades disponibles",
  orderNotFoundOrFulfilled = "Pedido no encontrado o ya completado",
  priceBelowMinimum = "El precio no puede ser inferior a %{value}",
  priceAboveMaximum = "El precio no puede ser superior a %{value}",
  stockUpdated = "Stock actualizado",
  changesSaved = "Cambios guardados",
  noStockAvailable = "Sin stock disponible",
  orderPlaced = "Pedido realizado",
  remainingInStock = "restante en stock global",
  exceedsStockLimit = "Excede el límite de stock",
  setStockQty = "Establecer cantidad de stock",
  invalidStockValue = "Por favor, introduce un valor de stock válido",
  errorSettingStock = "Error al establecer el stock",
  stockQuantity = "Cantidad de stock",
  currentStock = "Stock actual",
  priceLimitsEnabled = "Habilitar límites de precio",
  priceLimitsDescription = "Cuando está habilitado, los gerentes del concesionario solo pueden establecer precios dentro del rango especificado.",
  minPrice = "Precio mínimo",
  maxPrice = "Precio máximo",
  optional = "Opcional",
  unlimitedStock = "Stock ilimitado",
  globalStockLimit = "Límite de stock global",
  globalStockLimitDescription = "Establece un número máximo de unidades que se pueden pedir en todos los concesionarios.",
  currentlyOrdered = "Actualmente pedido",
  priceRange = "Rango de precios",
  noMinimum = "Sin mínimo",
  noMaximum = "Sin máximo",
  vehicleStock = "Stock de vehículos",

  -- v2: Sales
  allSales = "Todas las ventas",
  paidInFull = "Pagado al contado",
  salesVolume = "Volumen de ventas",
  pastMonth = "Mes pasado",
  pastYear = "Año pasado",

  -- v2: Management misc
  exploitAttemptDetected = "Deja de intentar explotar el script",
  dealershipNoJobConfigured = "El concesionario no tiene trabajo configurado",
  modelDoesNotMatchDb = "El modelo del vehículo no coincide con la base de datos",
  importFailed = "Importación fallida: %{value}",
  notInDealershipZone = "Debes estar dentro de un concesionario para usar este comando",
  notAnEmployee = "No eres empleado de este concesionario.",
  failedToPrepareDelivery = "Error al preparar la entrega",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "El modelo del vehículo no existe - contacta con un admin",
  vehiclePlateInvalid = "La matrícula de este vehículo es inválida (pulsa F8 para más detalles)",
  currentlyInRagdollState = "Actualmente estás en estado ragdoll",
  vehicleDoesNotExistContactAdmin = "El vehículo no existe. ¡Contacta con un admin!",
  vehicleSecurityBreachDetected = "Violación de seguridad del vehículo detectada",

  -- v2: Admin vehicles
  allVehicles = "Todos los vehículos",
  unassignedVehicles = "Sin concesionario",
  searchDealerships = "Buscar concesionarios...",

  -- v2: Trucking mission
  truckingGetInTruck = "Sube al camión en la ubicación marcada para iniciar tu entrega",
  truckingDriveToDelivery = "Conduce hasta el lugar de entrega",
  truckingCompleteDelivery = "Completar la entrega",
  truckingDeliveryComplete = "Entrega completada: ¡Has completado la entrega con éxito!",
  truckingDeliveryFailed = "Entrega fallida: Algo salió mal con la entrega",
  truckingDriveToPickup = "Conduce al punto de recogida para recoger el remolque",
  truckingMissionFailedSpawnCargo = "Misión fallida: No se pudo generar el remolque de carga",
  truckingMissionFailedFindCargo = "Misión fallida: No se pudo encontrar la carga generada",
  truckingVehiclesLoaded = "%{count} vehículo%{s} cargado",
  truckingWrongTrailer = "¡Remolque incorrecto! Debes enganchar el remolque de misión correcto.",
  truckingTrailerAttached = "Remolque enganchado - listo para continuar",
  truckingDriveToPickupLocation = "Conduce al punto de recogida",
  truckingWaitingForVehicles = "Esperando a que se carguen los vehículos...",
  truckingDriveUnderTrailer = "Pasa por debajo del remolque para engancharlo",
  truckingGetInTruckContinue = "Sube al camión para continuar",
  truckingMissionStarted = "Misión de transporte iniciada: Punto de recogida - %{location}",
  truckingMissionCancelled = "Misión cancelada: Has cancelado la misión de transporte",
  truckingNoActiveMission = "No hay misión de transporte activa para cancelar",
  deliveryNotPrepared = "Entrega no preparada - por favor, inténtalo de nuevo",
  deliveryConfigMismatch = "Configuración de entrega no coincidente",
  deliveryPreparationExpired = "Preparación de entrega expirada - por favor, inténtalo de nuevo",
  noTruckingVehicleCoordinates = "No hay coordenadas de vehículo de transporte establecidas",
  pickupLocationUnavailable = "Punto de recogida ya no disponible - por favor, inténtalo de nuevo",
  failedToSpawnTruck = "Error al generar el camión",
  clientFailedToStartMission = "El cliente no pudo iniciar la misión",

  -- v2: Trucking UI/Keys
  keyDismiss = "Cerrar",
  keyDeliverCargo = "Entregar carga",
  keyContinueToDelivery = "Continuar a la entrega",
  startDeliveryMission = "Iniciar misión de entrega",
  orderDetails = "Detalles del pedido",
  pickupLocation = "Punto de recogida",
  deliveryStatus = "Estado de entrega",
  selectOrders = "Seleccionar pedidos",
  carTrailer = "Portacoches",
  container = "Contenedor",
  deliveryRoute = "Ruta de entrega",
  startDelivery = "Iniciar entrega",

  -- v2: Direct sales UI
  waitingForCustomer = "Esperando al cliente",
  cancelRequest = "Cancelar solicitud",
  saleComplete = "¡Venta completada!",
  done = "Hecho",
  saleDeclined = "Venta rechazada",
  close = "Cerrar",

  -- v2: Display vehicle placement
  movement = "Movimiento",
  rotate = "Rotar",
  forward = "Adelante",
  backward = "Atrás",
  left = "Izquierda",
  right = "Derecha",
  rotateLeft = "Rotar izquierda",
  rotateRight = "Rotar derecha",

  -- v2: Showroom misc
  originalPrice = "Precio original",
  discount = "Descuento",
  createInteraction = "Crear interacción",
  viewAll = "Ver todo",
  fetchingPlayers = "Obteniendo jugadores",
  refresh = "Actualizar",
  loadingPlayers = "Cargando jugadores...",
  failedToLoadPlayers = "Error al cargar jugadores",
  selectAPlayer = "Seleccionar un jugador",
  failedToLoadPlayersRetry = "Error al cargar jugadores. Haz clic en 'Actualizar' para intentarlo de nuevo.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Concesionario de autoservicio",
  categories = "Categorías",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Ubicaciones",
  createNew = "Crear nuevo",
  enable = "Habilitar",
  disable = "Deshabilitar",
  loading = "Cargando...",
  errors = "Errores",
  update = "Actualizar",
  create = "Crear",

  -- v2: Dealership creation/editing
  createDealership = "Crear concesionario",
  editDealership = "Editar concesionario",
  essentials = "Esenciales",
  advanced = "Avanzado",
  noDealershipLocations = "Sin ubicaciones de concesionario",
  noDealershipLocationsDesc = "Puedes agregar una nueva ubicación, importar desde tu configuración (si migras desde v1) o agregar ubicaciones predeterminadas automáticamente.",

  -- v2: Location sections
  dealershipZone = "Zona del concesionario",
  showroomAndManagement = "Showroom y gestión",
  openShowroom = "Abrir showroom",
  openManagement = "Abrir gestión",
  enableSellVehicle = "Habilitar venta de vehículos",
  percentageOfVehicleValue = "Porcentaje % del valor del vehículo",
  enablePurchase = "Habilitar compra",
  purchasedVehicleSpawn = "Spawn de vehículo comprado",
  enableTestDrive = "Habilitar prueba de manejo",
  testDriveVehicleSpawn = "Spawn de vehículo de prueba",
  truckDelivery = "Entrega por camión",
  truckDeliveryVehicleSpawn = "Spawn de vehículo de entrega",

  -- v2: Location advanced settings
  paymentMethods = "Métodos de pago",
  supportsFinancing = "(soporta financiamiento)",
  enableFinance = "Habilitar financiamiento",
  cameraPreset = "Cámara",
  preset = "Predeterminado",
  custom = "Personalizado",
  vehiclePosition = "Posición del vehículo",
  zoomPositions = "Posiciones de zoom (separadas por coma)",
  zoomPositionsPlaceholder = "ejemplo: 5,8,12,8",
  vehicleColour = "Color del vehículo",
  selectionType = "Tipo de selección",
  noColourSelection = "Sin selección de color",
  rgbColourWheel = "Rueda de colores RGB",
  listOfRgbColours = "Lista de colores RGB",
  listOfColourIds = "Lista de IDs de color",
  accessControl = "Control de acceso",
  showroomJobWhitelist = "Lista blanca de trabajos del showroom",
  showroomGangWhitelist = "Lista blanca de bandas del showroom",
  societyPurchaseJobWhitelist = "Lista blanca de trabajos para compra de sociedad",
  societyPurchaseGangWhitelist = "Lista blanca de bandas para compra de sociedad",
  setInGame = "Configurar en juego",
  addNew = "Agregar nuevo",

  -- v2: Job/Gang whitelist editor
  job = "Trabajo",
  gang = "Banda",
  jobWhitelist = "Lista blanca de trabajos",
  gangWhitelist = "Lista blanca de bandas",
  addJob = "Agregar trabajo",
  addGang = "Agregar banda",
  editJob = "Editar trabajo",
  editGang = "Editar banda",
  manageJobs = "Gestionar trabajos",
  manageGangs = "Gestionar bandas",
  jobName = "Nombre del trabajo",
  gangName = "Nombre de la banda",
  selectGrades = "Seleccionar rangos",
  selectAll = "Seleccionar todo",
  deselectAll = "Deseleccionar todo",
  invalidJobName = "Nombre de trabajo inválido. Por favor revisa la configuración de tu framework.",
  invalidGangName = "Nombre de banda inválido. Por favor revisa la configuración de tu framework.",
  grades = "Rangos",
  noJobsConfigured = "No hay trabajos configurados",
  noGangsConfigured = "No hay bandas configuradas",
  click = "Clic",
  toGetStarted = "para comenzar.",
  more = "más",
  jobPlaceholder = "Por ejemplo: cardealer",
  jobOptionalDescription = "Opcionalmente vincula roles del concesionario a un trabajo del framework. Cuando los empleados son contratados/despedidos, su trabajo del framework también se actualizará.",
  jobRankPermissions = "Permisos de rango de trabajo",
  roleToJobRankMapping = "Mapeo de rol a rango de trabajo",
  addPerm = "Agregar permiso",

  -- v2: Colour selector
  searchColours = "Buscar colores...",
  noColoursFound = "No se encontraron colores",

  -- v2: Interactions creator
  noInteractions = "Sin interacciones",
  highlightInteractions = "Resaltar interacciones",
  explorationMode = "Modo exploración",
  pressEsc = "Presiona ESC",
  toWalkAround = "para caminar",
  toReturnToUI = "para volver a la UI",
  points = "puntos",
  location = "ubicación",
  manageLocations = "Gestionar ubicaciones",

  -- v2: Interaction modal
  interactionType = "Tipo",
  nicknameOptional = "Apodo (Opcional)",
  invalidModel = "Modelo inválido",
  failedToValidateModel = "Error al validar modelo",
  pedScenario = "Escenario de ped",
  coords = "Coordenadas",
  size = "Tamaño",
  blip = "Marcador",
  enableBlip = "Habilitar marcador",
  blipIconId = "ID del icono del marcador",
  blipColourId = "ID del color del marcador",
  blipSize = "Tamaño del marcador",
  marker = "Indicador",
  enableMarker = "Habilitar indicador",
  markerStyleId = "ID de estilo del indicador",
  markerSize = "Tamaño del indicador",
  markerColor = "Color del indicador",
  markerBobUpAndDown = "Flotar arriba y abajo",
  markerFaceCamera = "Mirar a la cámara",
  markerRotate = "Rotar",
  markerDrawOnEnts = "Dibujar en entidades",
  updatePosition = "Actualizar posición",
  setPosition = "Establecer posición",

  -- v2: Interaction types
  interactionPoint = "Punto",
  interactionPointDesc = "Punto único redimensionable, con indicador opcional",
  interactionPolyzone = "Polyzona",
  interactionPolyzoneDesc = "Zona de múltiples coordenadas para crear un área de interacción específica",
  interactionVehicle = "Vehículo",
  interactionVehicleDesc = "Generar un modelo de vehículo, ideal para métodos de interacción target o texto 3D",
  interactionObject = "Objeto",
  interactionObjectDesc = "Generar un modelo de objeto, ideal para métodos de interacción target o texto 3D",
  interactionPed = "Ped",
  interactionPedDesc = "Generar un modelo de ped con escenario opcional, ideal para métodos de interacción target o texto 3D",

  -- v2: Import modal
  importLocationsTitle = "Importar ubicaciones",
  syncStockLabel = "Sincronizar inventario",
  syncStockDescription = "Agregar vehículos al inventario de cada concesionario según sus categorías",
  importSourceSelectorDesc = "Puedes importar un conjunto de ubicaciones predeterminadas para una configuración lista, o importar tus ubicaciones existentes desde tu configuración si estás migrando desde Dealerships v1.",
  importSourceSelectorSkipDesc = "Las ubicaciones que ya existan en la base de datos serán omitidas; solo se importarán ubicaciones nuevas.",
  successfullyImported = "Importado exitosamente",
  alreadyExist = "Ya existe",
  defaultLocations = "Ubicaciones predeterminadas",
  defaultLocationsDesc = "Importar ubicaciones de concesionarios preconfiguradas (PDM, Lujo, Barcos, Aéreo, Camiones)",
  existingConfig = "Configuración existente",
  existingConfigDesc = "Importar ubicaciones desde tu config.lua (para migración v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "¿Deseas agregar automáticamente vehículos al inventario de este concesionario según las categorías seleccionadas?",
  categorySyncEditDesc = "Has cambiado las categorías de este concesionario. ¿Deseas actualizar automáticamente el inventario de vehículos?",
  addVehicles = "Agregar vehículos",
  removeVehicles = "Eliminar vehículos",
  fromNewCategories = "de nuevas categorías",
  fromSelectedCategories = "de categorías seleccionadas",
  fromRemovedCategories = "de categorías eliminadas",
  categoriesAdded = "Categorías agregadas:",
  categoriesRemoved = "Categorías eliminadas:",
  skip = "Omitir",
  syncStock = "Sincronizar inventario",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Verificando disponibilidad de fuente...",
  vehiclesAvailableToImport = "vehículos disponibles para importar",
  includesDealershipIds = "incluye IDs de concesionario",
  sourceUnavailable = "Fuente no disponible",
  noVehiclesAdminDescription = "Puedes agregar vehículos manualmente o importarlos desde tu framework.",
  appendBehaviour = "Añadir",
  overwriteBehaviour = "Sobrescribir",
  appendDescription = "Solo agregar vehículos nuevos que no existan en la base de datos",
  overwriteDescription = "Eliminar todos los datos de vehículos existentes e importar nuevos",
  stockAssignmentMethod = "Método de asignación de inventario",
  useDealershipIdsFromSource = "Usar IDs de concesionario de la fuente",
  matchByVehicleCategory = "Coincidir por categoría de vehículo",
  byShopDescription = "Los vehículos serán asignados a concesionarios según el campo 'shop' en los datos de origen",
  byCategoryDescription = "Los vehículos serán asignados a concesionarios que tengan categorías coincidentes",
  overwriteWarning = "Advertencia: Sobrescribir eliminará todos los vehículos existentes, pedidos, vehículos en exhibición y datos de ventas.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "Tabla de vehículos ESX",
  selectCategory = "Seleccionar una categoría",

  -- v2: Management menu items
  vehiclesMenu = "Vehículos",
  displayVehiclesMenu = "Vehículos en exhibición",
  ordersMenu = "Pedidos",
  salesMenu = "Ventas",
  bankAccountMenu = "Cuenta bancaria",
  employeesMenu = "Empleados",
  couponsMenu = "Cupones",
  settingsMenu = "Configuración",
  noPermissionAccessManagement = "No tienes permiso para acceder a funciones de gestión.",
  backToAdmin = "Volver a administración",
  viewingAsAdmin = "VIENDO COMO ADMIN",

  -- v2: Coupons table
  code = "Código",
  uses = "Usos",
  perPlayer = "Por jugador",
  never = "Nunca",
  noCoupons = "Sin cupones",
  noCouponsDescription = "Los clientes pueden ingresar un cupón en la etapa de compra de vehículos y ahorrar dinero.",

  -- v2: Coupon modal
  couponCodeLabel = "Código de cupón",
  couponCodePlaceholder = "ej., VERANO2024 o AHORRA10",
  couponCodeHelp = "Ingresa un código personalizado (hasta 25 caracteres, solo letras, números y guiones) o haz clic en 'Generar'.",
  maxNumberOfUsesPlaceholder = "Número máximo de usos",
  maxUsesPerPlayerPlaceholder = "Máximo de usos por jugador",
  vehicleRestrictionsPlaceholder = "Ingresa códigos de spawn separados por comas (ej., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Permitir en compras financiadas",
  createCoupon = "Crear cupón",
  updateCoupon = "Actualizar cupón",

  -- v2: Coupon validation messages
  couponCodeRequired = "El código de cupón es requerido",
  couponCodeMaxLength = "El código debe tener 25 caracteres o menos",
  couponCodeInvalidChars = "El código solo puede contener letras mayúsculas, números y guiones",
  discountTypeRequired = "El tipo de descuento es requerido",
  discountValueRequired = "El valor del descuento es requerido",
  discountValueMin = "El valor del descuento debe ser mayor que 0",
  discountValueMaxPercent = "El porcentaje no puede exceder 100",
  maxUsesRequired = "Máximo de usos es requerido",
  maxUsesMin = "Debe ser al menos 1",
  perPlayerLimitRequired = "Límite por jugador es requerido",
  expiryDateRequired = "Fecha de expiración es requerida",
  vehicleRestrictionsRequired = "Restricciones de vehículos son requeridas",
  categoryRestrictionsRequired = "Restricciones de categorías son requeridas",
  selectAtLeastOneCategory = "Selecciona al menos una categoría",

  -- v2: Dashboard
  today = "Hoy",
  thisMonth = "Este mes",
  allTime = "Todo el tiempo",
  recentSales = "Ventas recientes",
  noSalesYet = "¡Sin ventas aún!",
  noSalesDescription = "Las ventas de vehículos aparecerán aquí después de realizar una.",
  past7Days = "Últimos 7 días",
  past6Months = "Últimos 6 meses",
  numberOfSales = "Número de ventas",
  noDataAvailableForPeriod = "No hay datos disponibles para este período",

  -- v2: Display vehicles
  displayVehiclesDescription = "Los vehículos en exhibición son modelos fijos del showroom usados para mostrar tu inventario y atraer clientes a realizar una compra.",

  -- v2: Employees
  frameworkJobsEnabled = "Trabajos del framework habilitados",
  frameworkJobsDescription = "La gestión de empleados se maneja a través del sistema de trabajos del framework. Los jugadores con el trabajo del concesionario tendrán acceso automáticamente según su rango de trabajo. Configura los permisos de trabajo en la configuración de ubicación del panel de administración.",
  joinedColumn = "Ingresó",
  youBadge = "Tú",

  -- v2: Orders
  noOrdersTitle = "Sin pedidos",
  noOrdersDescription = "Para realizar un pedido, abre la pestaña 'Vehículos' y haz clic en 'Realizar pedido' en el vehículo que deseas reabastecer.",
  inProgress = "En progreso",
  awaitingDelivery = "Esperando entrega",
  orderedBy = "Pedido por",
  viewDeliveryInfo = "Ver info de entrega",

  -- v2: Delivery
  startDeliveryMissionTitle = "Iniciar misión de entrega",
  startDeliveryDescription = "Estás a punto de iniciar una misión de entrega para este pedido de vehículo. Necesitarás conducir hasta la ubicación de recogida, recoger el remolque de carga y entregarlo de vuelta al concesionario.",
  totalDistanceAndDriveTime = "Distancia total y tiempo de conducción",
  roundTrip = "ida y vuelta",
  deliveryCompleteTitle = "Entrega completa",
  deliveryInProgressTitle = "Entrega en progreso",
  deliveredAt = "Entregado en:",
  startedAt = "Iniciado en:",
  deliveredBy = "Entregado por:",
  beingDeliveredBy = "Siendo entregado por:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "No hay pedidos disponibles para entrega. Los pedidos deben estar listos y no estar en una entrega activa.",
  confirmDeliveryTitle = "Confirmar entrega",
  configureDeliveryTitle = "Configurar entrega",
  trailerCapacityExceeded = "¡Capacidad del remolque excedida! Has seleccionado %{usedSlots} espacios pero el máximo es %{maxSlots} espacios.",
  smallVehiclesSlotInfo = "Recuerda: los vehículos pequeños usan 1 espacio, los vehículos medianos usan 1.5 espacios.",
  fetchingRoute = "Obteniendo...",
  getRouteButton = "Obtener ruta",
  selectTrailerType = "Seleccionar tipo de remolque",
  carTrailerLabel = "Portacoches",
  smallMedium = "(Pequeño/Mediano)",
  containerLabel = "Contenedor",
  large = "(Grande)",
  carTrailerDescription = "El portacoches tiene 2 filas. Cada fila cabe 3 pequeños (1 espacio cada uno) o 2 medianos (1.5 espacios cada uno). Máximo 6 espacios en total.",
  containerDescription = "El remolque contenedor transporta 1 vehículo grande",
  selectOrdersTitle = "Seleccionar pedidos",
  slots = "espacios",
  noOrdersForTrailerType = "No hay pedidos disponibles para este tipo de remolque.",
  qty = "Cant:",
  inTransit = "en tránsito",
  totalVehicles = "Total de vehículos:",
  estimatedTime = "Tiempo estimado:",
  unknown = "Desconocido",

  -- v2: Sales
  salesEmptyDescription = "Las ventas de vehículos aparecerán aquí después de realizar una.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "¡Pedido realizado!",
  orderPlacedTruckingDescription = "Tu pedido está listo para recoger. Ve a la página de pedidos para completarlo.",
  orderPlacedTimedDescription = "Tu pedido será entregado en %{value} minutos.",
  goToOrders = "Ir a pedidos",
  noStockAvailableDescription = "No hay inventario disponible para este vehículo. Se ha alcanzado el límite de inventario global.",
  stockUpdatedDescription = "La cantidad de inventario se ha actualizado exitosamente.",

  -- v2: Direct sales tablet
  activeTestDrives = "Pruebas de manejo activas",
  tracking = "Rastreo",
  track = "Rastrear",
  endButton = "Terminar",
  endTestDriveTitle = "Terminar prueba de manejo",
  endTestDriveConfirmation = "¿Estás seguro de que deseas terminar esta prueba de manejo? El vehículo será eliminado y los ocupantes del vehículo no serán teletransportados de vuelta al concesionario.",
  vehicleLocationOnMap = "La ubicación del vehículo ha sido marcada en tu mapa.",
  sell = "Vender",
  couponCodeOptional = "Código de cupón (Opcional)",
  pleaseEnterCouponCode = "Por favor ingresa un código de cupón",
  invalidCouponCode = "Código de cupón inválido",
  failedToValidateCoupon = "Error al validar cupón",
  apply = "Aplicar",
  applying = "Aplicando...",
  allStock = "Todo el inventario",
  inStockFilter = "En stock",
  outOfStockFilter = "Agotado",
  noResultsFound = "No se encontraron resultados",
  noResults = "Sin resultados",
  noVehiclesMatchSearch = "No hay vehículos que coincidan con tu búsqueda",
  noVehiclesMatchFilters = "No hay vehículos que coincidan con tus filtros actuales",
  noItemsMatchSearch = "No hay artículos que coincidan con tu búsqueda",
  noItemsMatchFilters = "No hay artículos que coincidan con tus filtros actuales",
  selectColour = "Seleccionar color",
  refreshNearbyPlayers = "Actualizar jugadores cercanos",
  you = "Tú",
  items = "artículos",
  waitingForCustomerToRespond = "Esperando a que el cliente acepte o rechace...",
  vehicleSpawnedMessage = "El vehículo ha aparecido en el punto de tu mapa - lleva al cliente hacia él.",
  customerDeclinedMessage = "El cliente rechazó la solicitud de compra.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "FIRMA AQUÍ",
  acceptAndPurchase = "Aceptar y comprar",
  couponApplied = "¡Cupón %{code} aplicado! Ahorrando %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "¡Necesitas al menos 3 puntos para completar la zona! (Actualmente tienes %{value})",
  addPoint = "Agregar punto",
  removeLast = "Eliminar último",
  completeZone = "Completar zona",
  spawnPreview = "Vista previa de spawn",
  up = "Arriba",
  down = "Abajo",
  confirm = "Confirmar",
  placePoint = "Colocar punto",
  radius = "Radio",

  -- v2: Blip labels
  soldVehicleLocation = "Ubicación de vehículo vendido",
  testDriveVehicleBlip = "Vehículo de prueba de manejo",

  -- v2: Stock sync
  stockSyncResult = "Sincronización de inventario: %{added} agregados, %{removed} eliminados",
  stockSyncAdded = "Sincronización de inventario: %{value} vehículos agregados",
  importSuccessful = "¡Importación exitosa! %{imported} vehículos importados (%{total} en total)",

  -- v2: Tooltip actions
  findOnMap = "Encontrar en el mapa",
  adminPanel = "Panel de administración",

  -- v2: Common dropdown
  selectOne = "Seleccionar uno",
}
