
Locales = Locales or {}

Locales['fr'] = {
  -- UI
  vehicle = "Véhicule",
  vehicles = "Véhicules",
  dealership = "Concessionnaire",
  dealerships = "Concessionnaires",
  vehiclesCount = "véhicule(s)",
  dealersCount = "Concessionnaire(s)",
  accountBalance = "Solde du compte",
  bank = "Compte bancaire",
  cash = "Argent liquide",
  amount = "Montant",
  societyFund = "Fonds de la société",
  paymentSource = "Source du paiement",
  purchase = "Achat",
  personalPurchase = "Achat personnel",
  societyPurchase = "Achat de la société",
  purchaseType = "Type d'achat",
  deposit = "Dépôt",
  withdraw = "Retirer",
  all = "Tout",
  yes = "Oui",
  no = "Non",
  add = "Ajouter",
  edit = "Éditer",
  id = "ID",
  created = "Crée",
  type = "Type",
  name = "Nom",
  owner = "Propriétaire",
  bankBalance = "Solde bancaire",
  status = "Statut",
  back = "Retour",
  previous = "Précédent",
  next = "Suivant",
  admin = "Administrateur",
  vehiclesAdmin = "Administration des véhicules",
  dealershipsAdmin = "Administration des concessionnaires",
  search = "Recherche",
  noDealershipsFound = "Aucun concessionnaire trouvé",
  noVehicles = "Aucun véhicule trouvé",
  page = "Page",
  of = "de",
  every = "tous",
  show = "Afficher",
  active = "Actif",
  activeFinance = "Financement actif",
  failed = "Échec du paiement",
  removed = "Supprimé",
  setOwner = "Choisir Propriétaire",
  manage = "Gérer",
  deleteData = "Supprimer les données",
  deleteVehicle = "Supprimer un véhicule",
  delete = "Supprimer",
  deleteConfirmation = "Êtes-vous sûr?",
  deleteConfirmationDanger = "En êtes-vous sûr? Cette action est irréversible.",
  setDealershipOwner = "Choisir Propriétaire du Concessionnaire",
  overwriteDealerPrices = "Remplacer les prix des concessionnaires",
  nearbyPlayers = "Joueurs à proximité",
  noPlayersNearby = "Pas de joueurs à proximité",
  selectPlayer = "Sélectionner un joueur",
  required = "Exigée",
  forExample = "Par exemple",
  spawnCode = "Spawn Code",
  brand = "Marque",
  model = "Modèle",
  category = "Catégorie",
  price = "Prix",
  import = "Importation",
  importing = "Importation",
  importBehaviour = "Comportement d'importation",
  importVehicles = "Véhicules importés",
  importFrom = "Importer de",
  dashboard = "Tableau de bord",
  displayVehicle = "Véhicule d'affichage",
  displayVehicles = "Véhicules d'exposition",
  orders = "Commandes",
  sales = "Vente",
  vehiclesOnDisplay = "Véhicules exposés",
  employees = "Salariés",
  settings = "Paramètres",
  switchVehicle = "Changement de véhicule",
  remove = "Retirer",
  noDisplayVehicles = "Pas de véhicules d'exposition",
  selectVehicle = "Sélectionner un véhicule",
  colour = "Couleur",
  placeVehicle = "Placer le véhicule",
  orderVehicle = "Commander un véhicule",
  cancelOrder = "Annuler la commande",
  delivery = "Livraison",
  delivered = "Livré",
  noOrders = "Aucune commande trouvée",
  quantity = "Quantité",
  totalCost = "Coût total",
  totalSales = "Ventes totales",
  noSales = "Aucune vente trouvée",
  paid = "Payé",
  owed = "dû",
  dealershipName = "Nom du concessionnaire",
  save = "Enregistrer les modifications",
  cancel = "Annuler",
  notEnoughMoney = "Pas assez d'argent",
  placeOrder = "Passer une commande",
  purchaseCost = "Prix D'achat",
  salePrice = "Prix de vente",
  inStock = "En stock",
  outOfStock = "Rupture de stock",
  placeVehiclePrompt = "Appuyer sur %{value} pour placer le véhicule. Vous pourrez faire des réglages plus fins par la suite!",
  remaining = "Restant",
  prePurchaseRepoWarning = "Si vous ne pouvez pas suivre vos paiements financiers, votre véhicule sera repris.",
  repossessionWarning = "Votre dernier paiement a échoué : votre véhicule sera repris à moins que vous n'effectuiez un paiement maintenant!",
  recurringPayment = "Paiement récurrent",
  remainingBalance = "Solde restant",
  remainingPayments = "Paiements restants",
  paymentTakenEvery = "Paiement effectué chaque",
  hours = "heures",
  seconds = "secondes",
  nextPayment = "Prochain paiement",
  makePayment = "Effectuer le paiement",
  vehicleRepossessed = "Le véhicule sera repris",
  payInFull = "Payer intégralement",
  earlyPaymentConfirmation = "Etes-vous sûr de vouloir effectuer un paiement anticipé de",
  financedVehicles = "Véhicules financés",
  noFinancedVehicles = "Vous n'avez aucun véhicule avec un financement actif",
  financeBreakdown = "Répartition des finances",
  initialPayment = "Paiement initialt",
  payments = "Paiements",
  length = "Longueur",
  interest = "Intérêt",
  totalPayable = "Total à payer",
  leaveShowroom = "Quitter la salle d'exposition",
  handling = "Conduite",
  topSpeed = "Vitesse maximale",
  power = "Puissance",
  torque = "Torque",
  brake = "Freinage",
  financing = "Financement",
  financingAvailable = "Financement disponible",
  paymentsOf = "paiements de",
  clear = "Nettoyer",
  testDrive = "Essai routier",
  allCategories = "Toutes les catégories",
  sortByName = "Trier par : Nom",
  sortByAvailability = "Trier par : Disponibilité",
  sortByCheapest = "Trier par : le moins cher",
  sortByMostExpensive = "Trier par : Les plus chers",
  sortByNewest = "Trier par : Les plus récents",
  purchaseVehicle = "Acheter un véhicule",
  purchaseFor = "Acheter pour",
  selectSociety = "Sélectionnez une société",
  financeOverPayments = "Financement sur %{value} paiements",
  payToday = "Payez aujourd'hui",
  financeThen = "Alors",
  seeFullBreakdown = "Voir la répartition complète",
  testDriveExit = "Vous pouvez sortir de votre véhicule à tout moment pour terminer l’essai routier.",

  -- NOTIFICATIONS
  purchaseSuccess = "Félicitations pour votre achat!",
  depositSuccess = "Dépôt réussi",
  withdrawSuccess = "Retrait réussi",
  errorNotEnoughMoney = "Vous n'avez pas assez d'argent",
  errorVehicleOutOfStock = "Ce véhicule est en rupture de stock",
  errorCannotAffordVehicle = "Vous ne pouvez pas vous permettre ce véhicule",
  vehicleFinancePaymentMade = "Paiement financier effectué pour votre véhicule %{value}",
  vehicleFinancePaidOff = "Félicitations, vous avez payé et êtes désormais propriétaire de votre véhicule %{value}",
  vehicleFinancePaymentFailed = "Échec du paiement du financement pour votre véhicule %{value}",
  vehicleFinanceRepossessedSoon = "Vous devez effectuer un paiement pour votre véhicule %{value}, sinon votre véhicule sera bientôt repris",
  vehicleFinanceRepossessed = "Suite à un défaut de paiement, votre véhicule a été repris avec la plaque %{value}",
  dealershipNotEnoughFunds = "Le concessionnaire n'a pas assez de fonds",
  dealershipVehiclesOrdered = "Le(s) véhicule(s) ont été commandés avec succès",
  dealershipOrderCancelled = "Commande annulée avec succès",
  errorVehicleWithSpawnCodeExists = "Un véhicule avec ce spawnCode existe déjà",
  errorExitVehicle = "Vous devez d'abord sortir de votre véhicule",

  -- NEW v1.1
  purchaseRequest = "Demande d'achat",
  sendRequest = "Envoyer la demande",
  dealer = "Vendeur",
  financed = "Financé",
  signHere = "Signez ici",
  signFirstError = "Veuillez d'abord signer",
  denyRequest = "Refuser la demande",
  playerTooManyFinancedVehicles = "Le joueur a trop de véhicules financés",
  employeePermissionsError = "Vous ne disposez pas des autorisations d'employé nécessaires",
  managerRole = "Directeur",
  supervisorRole = "Superviseur",
  salesRole = "Ventes",
  ownerRole = "Propriétaire",
  employmentRequest = "Offre d'emploi",
  accept = "Accepter",
  jobOfferDescription = "On vous a proposé un emploi chez le concessionnaire \"%{value}\". Souhaitez-vous accepter ?",
  pending = "En attente",
  employeeHiredMsg = "L'offre d'emploi du concessionnaire a été acceptée !",
  employeeRejectedMsg = "La demande d'embauche d'un concessionnaire a été rejetée",
  sellVehicle = "Vendre un véhicule",
  vehicleTerms = "Conditions relatives aux véhicules",
  financePayments = "Paiements financiers",
  commission = "Commission",
  role = "Rôle",
  firedNotification = "Vous avez été licencié de la concession \"%{value}\"",
  dealershipTooFarAway = "Vous n'êtes à proximité d'aucun concessionnaire",
  restoreDisplayVehicles = "Restaurer la salle d'exposition",
  customer = "Client",
  lessThanAMin = "Moins d'une minute",
  mins = "minute(s)",
  notInVehicle = "Vous n'êtes pas assis dans un véhicule",
  notYourVehicleError = "Ce véhicule ne vous appartient pas",
  vehicleFinancedError = "Vous ne pouvez pas vendre ce véhicule car il lui reste des paiements financiers.",
  dealershipDoesntSellVehicle = "Ce concessionnaire ne peut pas acheter ce véhicule",
  dealershipWantsYourVehicle = "Félicitations! Ce concessionnaire souhaite acheter votre véhicule.",
  purchasePrice = "Prix ​​proposé :",
  
  spawnCodeInvalid = "SpawnCode invalide",
  salesRep = "Représentant des ventes",
  directSaleAccepted = "Demande de vente directe acceptée ! Votre commission a été payée.",
  directSaleRejected = "Demande de vente directe rejetée",

  displayVehicleOutsideZone = "Les véhicules d'exposition doivent être placés dans la zone du concessionnaire",
  serverAdmin = "Admin Serveur",
  selfService = "Libre-service",
  owned = "Possédé",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Méthode de paiement invalide",
  paymentMethodNoFinance = "Cette méthode de paiement ne supporte pas le financement",
  couldNotGeneratePlate = "Impossible de générer la plaque",
  invalidCoupon = "Coupon invalide: %{value}",
  tooManyFinancedVehicles = "Vous avez trop de véhicules financés",
  couldNotSpawnVehicle = "Impossible de faire apparaître le véhicule",

  -- v2: Permissions
  insufficientPermissions = "Permissions insuffisantes",

  -- v2: Coupons
  couponCodeAlreadyExists = "Ce code de coupon existe déjà",
  failedToCreateCoupon = "Échec de la création du coupon",
  couponCreatedSuccessfully = "Coupon créé avec succès",
  couponNotFound = "Coupon introuvable",
  couponUpdatedSuccessfully = "Coupon mis à jour avec succès",
  failedToDeleteCoupon = "Échec de la suppression du coupon",
  couponDeletedSuccessfully = "Coupon supprimé avec succès",
  editCoupon = "Modifier le coupon",
  addCoupon = "Ajouter un coupon",
  couponCode = "Code du coupon",
  generating = "Génération...",
  generate = "Générer",
  discountType = "Type de remise",
  percentageOff = "Pourcentage de réduction",
  amountOff = "Montant de réduction",
  discountValue = "Valeur de la remise",
  unlimitedTotalUses = "Utilisations totales illimitées",
  unlimitedUsesPerPlayer = "Utilisations illimitées par joueur",
  setExpiryDate = "Définir la date d'expiration",
  restrictToSpecificVehicles = "Restreindre à des véhicules spécifiques",
  restrictToSpecificCategories = "Restreindre à des catégories spécifiques",
  allowUseWithFinance = "Autoriser l'utilisation avec le financement",
  deleteCoupon = "Supprimer le coupon",
  inactive = "Inactif",
  expired = "Expiré",
  maxUses = "Utilisations max",
  coupons = "Coupons",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Seuls les admins serveur peuvent s'auto-embaucher",
  playerNotFound = "Joueur introuvable",
  failedToHireEmployee = "Échec de l'embauche de l'employé",
  failedToFireEmployee = "Échec du licenciement de l'employé",
  failedToUpdateEmployeeRole = "Échec de la mise à jour du rôle de l'employé",
  hireEmployee = "Embaucher un employé",
  fireEmployee = "Licencier un employé",
  editRole = "Modifier le rôle",
  fire = "Licencier",
  changeRole = "Changer le rôle",
  updateRole = "Mettre à jour le rôle",

  -- v2: Test drives
  maxTestDrivesReached = "Ce concessionnaire a atteint le nombre maximum d'essais actifs",
  testDriveNotEnabled = "Les essais ne sont pas activés dans ce concessionnaire",
  noTestDriveSpawnCoords = "Aucune coordonnée de spawn pour les essais configurée pour ce concessionnaire",
  couldNotSpawnTestDriveVehicle = "Impossible de faire apparaître le véhicule d'essai",
  couldNotGetPlateFromServer = "Impossible d'obtenir la plaque du serveur",
  couldNotRegisterTestDriveVehicle = "Impossible d'enregistrer le véhicule d'essai",
  testDriveEndedByEmployee = "L'essai a été terminé par un autre employé",
  trackingVehicleLocation = "Suivi de la position du véhicule...",
  directSaleCancelled = "La demande de vente a été annulée par le vendeur",
  testDriveKeysReceived = "Vous avez reçu les clés du véhicule d'essai",
  testDriveEndedCustomer = "L'essai est terminé",
  starting = "Démarrage...",
  startTestDrive = "Démarrer l'essai",
  spawningTestDriveVehicle = "Apparition du véhicule d'essai...",
  testDriveReady = "Essai prêt",
  testDriveWalkToVehicle = "Le véhicule d'essai est apparu au point marqué sur votre carte. Accompagnez le client jusqu'au véhicule. Une fois les clés remises au client, vous devrez terminer manuellement l'essai lorsqu'il reviendra.",
  givingKeys = "Remise des clés...",
  continueAndGiveKeys = "Continuer et donner les clés",
  endTestDrive = "Terminer l'essai",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Aucun stock disponible pour ce véhicule",
  globalStockLimitExceeded = "Seulement %{value} unités disponibles",
  orderNotFoundOrFulfilled = "Commande introuvable ou déjà traitée",
  priceBelowMinimum = "Le prix ne peut pas être inférieur à %{value}",
  priceAboveMaximum = "Le prix ne peut pas être supérieur à %{value}",
  stockUpdated = "Stock mis à jour",
  changesSaved = "Modifications enregistrées",
  noStockAvailable = "Aucun stock disponible",
  orderPlaced = "Commande passée",
  remainingInStock = "restant en stock global",
  exceedsStockLimit = "Dépasse la limite de stock",
  setStockQty = "Définir la quantité de stock",
  invalidStockValue = "Veuillez entrer une valeur de stock valide",
  errorSettingStock = "Erreur lors de la définition du stock",
  stockQuantity = "Quantité de stock",
  currentStock = "Stock actuel",
  priceLimitsEnabled = "Activer les limites de prix",
  priceLimitsDescription = "Lorsqu'activé, les gestionnaires de concessionnaire ne peuvent définir que des prix dans la plage spécifiée.",
  minPrice = "Prix minimum",
  maxPrice = "Prix maximum",
  optional = "Optionnel",
  unlimitedStock = "Stock illimité",
  globalStockLimit = "Limite de stock globale",
  globalStockLimitDescription = "Définir un nombre maximum d'unités pouvant être commandées dans tous les concessionnaires.",
  currentlyOrdered = "Actuellement commandé",
  priceRange = "Fourchette de prix",
  noMinimum = "Pas de minimum",
  noMaximum = "Pas de maximum",
  vehicleStock = "Stock de véhicules",

  -- v2: Sales
  allSales = "Toutes les ventes",
  paidInFull = "Payé intégralement",
  salesVolume = "Volume des ventes",
  pastMonth = "Mois dernier",
  pastYear = "Année dernière",

  -- v2: Management misc
  exploitAttemptDetected = "Arrêtez d'essayer d'exploiter le script",
  dealershipNoJobConfigured = "Le concessionnaire n'a pas de métier configuré",
  modelDoesNotMatchDb = "Le modèle de véhicule ne correspond pas à la base de données",
  importFailed = "Échec de l'importation: %{value}",
  notInDealershipZone = "Vous devez être dans un concessionnaire pour utiliser cette commande",
  notAnEmployee = "Vous n'êtes pas employé dans ce concessionnaire.",
  failedToPrepareDelivery = "Échec de la préparation de la livraison",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Le modèle de véhicule n'existe pas - contactez un admin",
  vehiclePlateInvalid = "La plaque de ce véhicule est invalide (appuyez sur F8 pour plus de détails)",
  currentlyInRagdollState = "Vous êtes actuellement en état de ragdoll",
  vehicleDoesNotExistContactAdmin = "Le véhicule n'existe pas. Veuillez contacter un admin!",
  vehicleSecurityBreachDetected = "Violation de sécurité du véhicule détectée",

  -- v2: Admin vehicles
  allVehicles = "Tous les véhicules",
  unassignedVehicles = "Aucun concessionnaire",
  searchDealerships = "Rechercher des concessionnaires...",

  -- v2: Trucking mission
  truckingGetInTruck = "Montez dans le camion à l'emplacement marqué pour commencer votre livraison",
  truckingDriveToDelivery = "Conduisez jusqu'au lieu de livraison",
  truckingCompleteDelivery = "Terminer la livraison",
  truckingDeliveryComplete = "Livraison terminée: Vous avez terminé la livraison avec succès!",
  truckingDeliveryFailed = "Livraison échouée: Un problème est survenu avec la livraison",
  truckingDriveToPickup = "Conduisez jusqu'au point de collecte pour récupérer la remorque",
  truckingMissionFailedSpawnCargo = "Mission échouée: Impossible de faire apparaître la remorque de fret",
  truckingMissionFailedFindCargo = "Mission échouée: Impossible de trouver le fret apparu",
  truckingVehiclesLoaded = "%{count} véhicule%{s} chargé",
  truckingWrongTrailer = "Mauvaise remorque! Vous devez attacher la bonne remorque de mission.",
  truckingTrailerAttached = "Remorque attachée - prêt à continuer",
  truckingDriveToPickupLocation = "Conduisez jusqu'au point de collecte",
  truckingWaitingForVehicles = "En attente du chargement des véhicules...",
  truckingDriveUnderTrailer = "Passez sous la remorque pour l'attacher",
  truckingGetInTruckContinue = "Montez dans le camion pour continuer",
  truckingMissionStarted = "Mission de transport démarrée: Point de collecte - %{location}",
  truckingMissionCancelled = "Mission annulée: Vous avez annulé la mission de transport",
  truckingNoActiveMission = "Aucune mission de transport active à annuler",
  deliveryNotPrepared = "Livraison non préparée - veuillez réessayer",
  deliveryConfigMismatch = "Configuration de livraison non concordante",
  deliveryPreparationExpired = "Préparation de la livraison expirée - veuillez réessayer",
  noTruckingVehicleCoordinates = "Aucune coordonnée de véhicule de transport définie",
  pickupLocationUnavailable = "Point de collecte plus disponible - veuillez réessayer",
  failedToSpawnTruck = "Échec de l'apparition du camion",
  clientFailedToStartMission = "Le client n'a pas pu démarrer la mission",

  -- v2: Trucking UI/Keys
  keyDismiss = "Fermer",
  keyDeliverCargo = "Livrer le fret",
  keyContinueToDelivery = "Continuer vers la livraison",
  startDeliveryMission = "Démarrer la mission de livraison",
  orderDetails = "Détails de la commande",
  pickupLocation = "Point de collecte",
  deliveryStatus = "Statut de livraison",
  selectOrders = "Sélectionner les commandes",
  carTrailer = "Porte-voitures",
  container = "Conteneur",
  deliveryRoute = "Itinéraire de livraison",
  startDelivery = "Démarrer la livraison",

  -- v2: Direct sales UI
  waitingForCustomer = "En attente du client",
  cancelRequest = "Annuler la demande",
  saleComplete = "Vente terminée!",
  done = "Terminé",
  saleDeclined = "Vente refusée",
  close = "Fermer",

  -- v2: Display vehicle placement
  movement = "Mouvement",
  rotate = "Rotation",
  forward = "Avant",
  backward = "Arrière",
  left = "Gauche",
  right = "Droite",
  rotateLeft = "Tourner à gauche",
  rotateRight = "Tourner à droite",

  -- v2: Showroom misc
  originalPrice = "Prix original",
  discount = "Remise",
  createInteraction = "Créer une interaction",
  viewAll = "Voir tout",
  fetchingPlayers = "Récupération des joueurs",
  refresh = "Actualiser",
  loadingPlayers = "Chargement des joueurs...",
  failedToLoadPlayers = "Échec du chargement des joueurs",
  selectAPlayer = "Sélectionner un joueur",
  failedToLoadPlayersRetry = "Échec du chargement des joueurs. Cliquez sur 'Actualiser' pour réessayer.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Concessionnaire en libre-service",
  categories = "Catégories",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Emplacements",
  createNew = "Créer nouveau",
  enable = "Activer",
  disable = "Désactiver",
  loading = "Chargement...",
  errors = "Erreurs",
  update = "Mettre à jour",
  create = "Créer",

  -- v2: Dealership creation/editing
  createDealership = "Créer un concessionnaire",
  editDealership = "Modifier le concessionnaire",
  essentials = "Essentiels",
  advanced = "Avancé",
  noDealershipLocations = "Aucun emplacement de concessionnaire",
  noDealershipLocationsDesc = "Vous pouvez ajouter un nouvel emplacement, importer depuis votre configuration (si vous migrez depuis v1) ou ajouter automatiquement des emplacements par défaut.",

  -- v2: Location sections
  dealershipZone = "Zone du concessionnaire",
  showroomAndManagement = "Showroom et gestion",
  openShowroom = "Ouvrir le showroom",
  openManagement = "Ouvrir la gestion",
  enableSellVehicle = "Activer la vente de véhicules",
  percentageOfVehicleValue = "Pourcentage % de la valeur du véhicule",
  enablePurchase = "Activer l'achat",
  purchasedVehicleSpawn = "Spawn du véhicule acheté",
  enableTestDrive = "Activer l'essai routier",
  testDriveVehicleSpawn = "Spawn du véhicule d'essai",
  truckDelivery = "Livraison par camion",
  truckDeliveryVehicleSpawn = "Spawn du véhicule de livraison",

  -- v2: Location advanced settings
  paymentMethods = "Méthodes de paiement",
  supportsFinancing = "(supporte le financement)",
  enableFinance = "Activer le financement",
  cameraPreset = "Caméra",
  preset = "Prédéfini",
  custom = "Personnalisé",
  vehiclePosition = "Position du véhicule",
  zoomPositions = "Positions de zoom (séparées par virgule)",
  zoomPositionsPlaceholder = "exemple: 5,8,12,8",
  vehicleColour = "Couleur du véhicule",
  selectionType = "Type de sélection",
  noColourSelection = "Pas de sélection de couleur",
  rgbColourWheel = "Roue des couleurs RVB",
  listOfRgbColours = "Liste des couleurs RVB",
  listOfColourIds = "Liste des IDs de couleur",
  accessControl = "Contrôle d'accès",
  showroomJobWhitelist = "Liste blanche des métiers du showroom",
  showroomGangWhitelist = "Liste blanche des gangs du showroom",
  societyPurchaseJobWhitelist = "Liste blanche des métiers pour achat société",
  societyPurchaseGangWhitelist = "Liste blanche des gangs pour achat société",
  setInGame = "Définir en jeu",
  addNew = "Ajouter nouveau",

  -- v2: Job/Gang whitelist editor
  job = "Métier",
  gang = "Gang",
  jobWhitelist = "Liste blanche des métiers",
  gangWhitelist = "Liste blanche des gangs",
  addJob = "Ajouter un métier",
  addGang = "Ajouter un gang",
  editJob = "Modifier le métier",
  editGang = "Modifier le gang",
  manageJobs = "Gérer les métiers",
  manageGangs = "Gérer les gangs",
  jobName = "Nom du métier",
  gangName = "Nom du gang",
  selectGrades = "Sélectionner les grades",
  selectAll = "Tout sélectionner",
  deselectAll = "Tout désélectionner",
  invalidJobName = "Nom de métier invalide. Veuillez vérifier la configuration de votre framework.",
  invalidGangName = "Nom de gang invalide. Veuillez vérifier la configuration de votre framework.",
  grades = "Grades",
  noJobsConfigured = "Aucun métier configuré",
  noGangsConfigured = "Aucun gang configuré",
  click = "Cliquez",
  toGetStarted = "pour commencer.",
  more = "plus",
  jobPlaceholder = "Par exemple: cardealer",
  jobOptionalDescription = "Liez optionnellement les rôles du concessionnaire à un métier du framework. Lorsque les employés sont embauchés/licenciés, leur métier framework sera également mis à jour.",
  jobRankPermissions = "Permissions de rang de métier",
  roleToJobRankMapping = "Correspondance rôle vers rang de métier",
  addPerm = "Ajouter permission",

  -- v2: Colour selector
  searchColours = "Rechercher des couleurs...",
  noColoursFound = "Aucune couleur trouvée",

  -- v2: Interactions creator
  noInteractions = "Aucune interaction",
  highlightInteractions = "Mettre en surbrillance les interactions",
  explorationMode = "Mode exploration",
  pressEsc = "Appuyez sur ESC",
  toWalkAround = "pour se déplacer",
  toReturnToUI = "pour revenir à l'interface",
  points = "points",
  location = "emplacement",
  manageLocations = "Gérer les emplacements",

  -- v2: Interaction modal
  interactionType = "Type",
  nicknameOptional = "Surnom (Optionnel)",
  invalidModel = "Modèle invalide",
  failedToValidateModel = "Échec de la validation du modèle",
  pedScenario = "Scénario de ped",
  coords = "Coordonnées",
  size = "Taille",
  blip = "Blip",
  enableBlip = "Activer le blip",
  blipIconId = "ID d'icône du blip",
  blipColourId = "ID de couleur du blip",
  blipSize = "Taille du blip",
  marker = "Marqueur",
  enableMarker = "Activer le marqueur",
  markerStyleId = "ID de style du marqueur",
  markerSize = "Taille du marqueur",
  markerColor = "Couleur du marqueur",
  markerBobUpAndDown = "Flotter de haut en bas",
  markerFaceCamera = "Face à la caméra",
  markerRotate = "Rotation",
  markerDrawOnEnts = "Dessiner sur les entités",
  updatePosition = "Mettre à jour la position",
  setPosition = "Définir la position",

  -- v2: Interaction types
  interactionPoint = "Point",
  interactionPointDesc = "Point unique redimensionnable, avec marqueur optionnel",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Zone multi-coordonnées pour créer une zone d'interaction spécifique",
  interactionVehicle = "Véhicule",
  interactionVehicleDesc = "Faire apparaître un modèle de véhicule, idéal pour les méthodes d'interaction target ou texte 3D",
  interactionObject = "Objet",
  interactionObjectDesc = "Faire apparaître un modèle d'objet, idéal pour les méthodes d'interaction target ou texte 3D",
  interactionPed = "Ped",
  interactionPedDesc = "Faire apparaître un modèle de ped avec scénario optionnel, idéal pour les méthodes d'interaction target ou texte 3D",

  -- v2: Import modal
  importLocationsTitle = "Importer des emplacements",
  syncStockLabel = "Synchroniser le stock",
  syncStockDescription = "Ajouter des véhicules au stock de chaque concessionnaire selon ses catégories",
  importSourceSelectorDesc = "Vous pouvez importer un ensemble d'emplacements par défaut pour une configuration prête à l'emploi, ou importer vos emplacements existants depuis votre configuration si vous migrez depuis Dealerships v1.",
  importSourceSelectorSkipDesc = "Les emplacements qui existent déjà dans la base de données seront ignorés; seuls les nouveaux emplacements seront importés.",
  successfullyImported = "Importé avec succès",
  alreadyExist = "Existe déjà",
  defaultLocations = "Emplacements par défaut",
  defaultLocationsDesc = "Importer des emplacements de concessionnaires préconfigurés (PDM, Luxe, Bateaux, Aérien, Camions)",
  existingConfig = "Configuration existante",
  existingConfigDesc = "Importer des emplacements depuis votre config.lua (pour migration v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Voulez-vous ajouter automatiquement des véhicules au stock de ce concessionnaire selon les catégories sélectionnées?",
  categorySyncEditDesc = "Vous avez modifié les catégories de ce concessionnaire. Voulez-vous mettre à jour automatiquement le stock de véhicules?",
  addVehicles = "Ajouter des véhicules",
  removeVehicles = "Supprimer des véhicules",
  fromNewCategories = "des nouvelles catégories",
  fromSelectedCategories = "des catégories sélectionnées",
  fromRemovedCategories = "des catégories supprimées",
  categoriesAdded = "Catégories ajoutées:",
  categoriesRemoved = "Catégories supprimées:",
  skip = "Ignorer",
  syncStock = "Synchroniser le stock",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Vérification de la disponibilité de la source...",
  vehiclesAvailableToImport = "véhicules disponibles à importer",
  includesDealershipIds = "inclut les IDs de concessionnaires",
  sourceUnavailable = "Source non disponible",
  noVehiclesAdminDescription = "Vous pouvez ajouter des véhicules manuellement ou les importer depuis votre framework.",
  appendBehaviour = "Ajouter",
  overwriteBehaviour = "Écraser",
  appendDescription = "Ajouter uniquement les nouveaux véhicules qui n'existent pas déjà dans la base de données",
  overwriteDescription = "Supprimer toutes les données de véhicules existantes et importer à nouveau",
  stockAssignmentMethod = "Méthode d'attribution du stock",
  useDealershipIdsFromSource = "Utiliser les IDs de concessionnaires de la source",
  matchByVehicleCategory = "Correspondance par catégorie de véhicule",
  byShopDescription = "Les véhicules seront attribués aux concessionnaires selon le champ 'shop' dans les données sources",
  byCategoryDescription = "Les véhicules seront attribués aux concessionnaires ayant des catégories correspondantes",
  overwriteWarning = "Attention: L'écrasement supprimera tous les véhicules existants, commandes, véhicules d'exposition et données de ventes.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "Table de véhicules ESX",
  selectCategory = "Sélectionner une catégorie",

  -- v2: Management menu items
  vehiclesMenu = "Véhicules",
  displayVehiclesMenu = "Véhicules d'exposition",
  ordersMenu = "Commandes",
  salesMenu = "Ventes",
  bankAccountMenu = "Compte bancaire",
  employeesMenu = "Employés",
  couponsMenu = "Coupons",
  settingsMenu = "Paramètres",
  noPermissionAccessManagement = "Vous n'avez pas la permission d'accéder aux fonctionnalités de gestion.",
  backToAdmin = "Retour à l'administration",
  viewingAsAdmin = "VUE EN TANT QU'ADMIN",

  -- v2: Coupons table
  code = "Code",
  uses = "Utilisations",
  perPlayer = "Par joueur",
  never = "Jamais",
  noCoupons = "Aucun coupon",
  noCouponsDescription = "Les clients peuvent entrer un coupon lors de l'achat d'un véhicule et économiser de l'argent.",

  -- v2: Coupon modal
  couponCodeLabel = "Code coupon",
  couponCodePlaceholder = "ex., ETE2024 ou ECONOMISE10",
  couponCodeHelp = "Entrez un code personnalisé (jusqu'à 25 caractères, lettres, chiffres et tirets uniquement) ou cliquez sur 'Générer'.",
  maxNumberOfUsesPlaceholder = "Nombre maximum d'utilisations",
  maxUsesPerPlayerPlaceholder = "Maximum d'utilisations par joueur",
  vehicleRestrictionsPlaceholder = "Entrez les codes de spawn séparés par des virgules (ex., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Autoriser sur les achats financés",
  createCoupon = "Créer un coupon",
  updateCoupon = "Mettre à jour le coupon",

  -- v2: Coupon validation messages
  couponCodeRequired = "Le code coupon est requis",
  couponCodeMaxLength = "Le code doit contenir 25 caractères ou moins",
  couponCodeInvalidChars = "Le code ne peut contenir que des lettres majuscules, des chiffres et des tirets",
  discountTypeRequired = "Le type de remise est requis",
  discountValueRequired = "La valeur de la remise est requise",
  discountValueMin = "La valeur de la remise doit être supérieure à 0",
  discountValueMaxPercent = "Le pourcentage ne peut pas dépasser 100",
  maxUsesRequired = "Le nombre maximum d'utilisations est requis",
  maxUsesMin = "Doit être au moins 1",
  perPlayerLimitRequired = "La limite par joueur est requise",
  expiryDateRequired = "La date d'expiration est requise",
  vehicleRestrictionsRequired = "Les restrictions de véhicules sont requises",
  categoryRestrictionsRequired = "Les restrictions de catégories sont requises",
  selectAtLeastOneCategory = "Sélectionnez au moins une catégorie",

  -- v2: Dashboard
  today = "Aujourd'hui",
  thisMonth = "Ce mois",
  allTime = "Tout le temps",
  recentSales = "Ventes récentes",
  noSalesYet = "Pas encore de ventes!",
  noSalesDescription = "Les ventes de véhicules apparaîtront ici après en avoir effectué une.",
  past7Days = "7 derniers jours",
  past6Months = "6 derniers mois",
  numberOfSales = "Nombre de ventes",
  noDataAvailableForPeriod = "Aucune donnée disponible pour cette période",

  -- v2: Display vehicles
  displayVehiclesDescription = "Les véhicules d'exposition sont des modèles fixes du showroom utilisés pour présenter votre inventaire et attirer les clients à effectuer un achat.",

  -- v2: Employees
  frameworkJobsEnabled = "Métiers framework activés",
  frameworkJobsDescription = "La gestion des employés est gérée via le système de métiers du framework. Les joueurs avec le métier du concessionnaire auront automatiquement accès selon leur grade. Configurez les permissions de métier dans les paramètres d'emplacement du panneau d'administration.",
  joinedColumn = "Rejoint",
  youBadge = "Vous",

  -- v2: Orders
  noOrdersTitle = "Aucune commande",
  noOrdersDescription = "Pour passer une commande, ouvrez l'onglet 'Véhicules' et cliquez sur 'Commander' sur le véhicule que vous souhaitez réapprovisionner.",
  inProgress = "En cours",
  awaitingDelivery = "En attente de livraison",
  orderedBy = "Commandé par",
  viewDeliveryInfo = "Voir les infos de livraison",

  -- v2: Delivery
  startDeliveryMissionTitle = "Démarrer la mission de livraison",
  startDeliveryDescription = "Vous êtes sur le point de démarrer une mission de livraison pour cette commande de véhicule. Vous devrez conduire jusqu'au point de collecte, récupérer la remorque de fret et la livrer au concessionnaire.",
  totalDistanceAndDriveTime = "Distance totale et temps de trajet",
  roundTrip = "aller-retour",
  deliveryCompleteTitle = "Livraison terminée",
  deliveryInProgressTitle = "Livraison en cours",
  deliveredAt = "Livré à:",
  startedAt = "Démarré à:",
  deliveredBy = "Livré par:",
  beingDeliveredBy = "En cours de livraison par:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Aucune commande disponible pour la livraison. Les commandes doivent être prêtes et ne pas être déjà en livraison active.",
  confirmDeliveryTitle = "Confirmer la livraison",
  configureDeliveryTitle = "Configurer la livraison",
  trailerCapacityExceeded = "Capacité de la remorque dépassée! Vous avez sélectionné %{usedSlots} emplacements mais le maximum est %{maxSlots} emplacements.",
  smallVehiclesSlotInfo = "Rappel: les petits véhicules utilisent 1 emplacement, les véhicules moyens utilisent 1.5 emplacements.",
  fetchingRoute = "Récupération...",
  getRouteButton = "Obtenir l'itinéraire",
  selectTrailerType = "Sélectionner le type de remorque",
  carTrailerLabel = "Porte-voitures",
  smallMedium = "(Petit/Moyen)",
  containerLabel = "Conteneur",
  large = "(Grand)",
  carTrailerDescription = "Le porte-voitures a 2 rangées. Chaque rangée peut contenir 3 petits (1 emplacement chacun) ou 2 moyens (1.5 emplacements chacun). Maximum 6 emplacements au total.",
  containerDescription = "La remorque conteneur transporte 1 grand véhicule",
  selectOrdersTitle = "Sélectionner les commandes",
  slots = "emplacements",
  noOrdersForTrailerType = "Aucune commande disponible pour ce type de remorque.",
  qty = "Qté:",
  inTransit = "en transit",
  totalVehicles = "Total véhicules:",
  estimatedTime = "Temps estimé:",
  unknown = "Inconnu",

  -- v2: Sales
  salesEmptyDescription = "Les ventes de véhicules apparaîtront ici après en avoir effectué une.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Commande passée!",
  orderPlacedTruckingDescription = "Votre commande est prête à être récupérée. Allez à la page des commandes pour la compléter.",
  orderPlacedTimedDescription = "Votre commande sera livrée dans %{value} minutes.",
  goToOrders = "Aller aux commandes",
  noStockAvailableDescription = "Il n'y a pas de stock disponible pour ce véhicule. La limite de stock globale a été atteinte.",
  stockUpdatedDescription = "La quantité de stock a été mise à jour avec succès.",

  -- v2: Direct sales tablet
  activeTestDrives = "Essais routiers actifs",
  tracking = "Suivi",
  track = "Suivre",
  endButton = "Terminer",
  endTestDriveTitle = "Terminer l'essai routier",
  endTestDriveConfirmation = "Êtes-vous sûr de vouloir terminer cet essai routier? Le véhicule sera supprimé et les occupants du véhicule ne seront pas téléportés au concessionnaire.",
  vehicleLocationOnMap = "L'emplacement du véhicule a été placé sur votre carte.",
  sell = "Vendre",
  couponCodeOptional = "Code coupon (Optionnel)",
  pleaseEnterCouponCode = "Veuillez entrer un code coupon",
  invalidCouponCode = "Code coupon invalide",
  failedToValidateCoupon = "Échec de la validation du coupon",
  apply = "Appliquer",
  applying = "Application...",
  allStock = "Tout le stock",
  inStockFilter = "En stock",
  outOfStockFilter = "Rupture de stock",
  noResultsFound = "Aucun résultat trouvé",
  noResults = "Aucun résultat",
  noVehiclesMatchSearch = "Aucun véhicule ne correspond à votre recherche",
  noVehiclesMatchFilters = "Aucun véhicule ne correspond à vos filtres actuels",
  noItemsMatchSearch = "Aucun article ne correspond à votre recherche",
  noItemsMatchFilters = "Aucun article ne correspond à vos filtres actuels",
  selectColour = "Sélectionner la couleur",
  refreshNearbyPlayers = "Actualiser les joueurs à proximité",
  you = "Vous",
  items = "articles",
  waitingForCustomerToRespond = "En attente de la réponse du client...",
  vehicleSpawnedMessage = "Le véhicule est apparu au point sur votre carte - accompagnez le client.",
  customerDeclinedMessage = "Le client a refusé la demande d'achat.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "SIGNEZ ICI",
  acceptAndPurchase = "Accepter et acheter",
  couponApplied = "Coupon %{code} appliqué! Économie de %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Il faut au moins 3 points pour compléter la zone! (Actuellement %{value})",
  addPoint = "Ajouter un point",
  removeLast = "Supprimer le dernier",
  completeZone = "Compléter la zone",
  spawnPreview = "Aperçu du spawn",
  up = "Haut",
  down = "Bas",
  confirm = "Confirmer",
  placePoint = "Placer un point",
  radius = "Rayon",

  -- v2: Blip labels
  soldVehicleLocation = "Emplacement du véhicule vendu",
  testDriveVehicleBlip = "Véhicule d'essai routier",

  -- v2: Stock sync
  stockSyncResult = "Synchronisation du stock: %{added} ajoutés, %{removed} supprimés",
  stockSyncAdded = "Synchronisation du stock: %{value} véhicules ajoutés",
  importSuccessful = "Importation réussie! %{imported} véhicules importés (%{total} au total)",

  -- v2: Tooltip actions
  findOnMap = "Trouver sur la carte",
  adminPanel = "Panneau d'administration",

  -- v2: Common dropdown
  selectOne = "Sélectionner un",
}
-- Translated by @Diamond_h4
