Locales = Locales or {}

Locales['hu'] = {
  -- UI
  vehicle = "Jármü",
  vehicles = "Jármüvek",
  dealership = "Kereskedés",
  dealerships = "Kereskedések",
  vehiclesCount = "jármü(vek)",
  dealersCount = "kereskedés(ek)",
  accountBalance = "Számla egyenleg",
  bank = "Bank egyenleg",
  cash = "Készpénz",
  amount = "Összeg",
  societyFund = "Céges kassza",
  paymentSource = "Fizetésimód",
  purchase = "Vásárlás",
  personalPurchase = "Vásárlás",
  societyPurchase = "Céges vásárlás",
  purchaseType = "Vásárlási mód",
  deposit = "Befizetés",
  withdraw = "Kifizetés",
  all = "Mind",
  yes = "Igen",
  no = "Nem",
  add = "Hozzáadás",
  edit = "Módositás",
  id = "ID",
  created = "Létrehozva",
  type = "Tipus",
  name = "Név",
  owner = "Tulajdonos",
  bankBalance = "Banki egyenleg",
  status = "Státusz",
  back = "Vissza",
  previous = "Elözö",
  next = "Következö",
  admin = "Admin",
  vehiclesAdmin = "Jármü adminisztráció",
  dealershipsAdmin = "Kereskedés adminisztráció",
  search = "Keresés",
  noDealershipsFound = "Kereskedés nem található",
  noVehicles = "Jármü nem található",
  page = "Oldal",
  of = "of",
  every = "minden",
  show = "Show",
  active = "Aktiv",
  activeFinance = "Akti részletfizetés",
  failed = "Sikertelen fizetés",
  removed = "Eltávolitva",
  setOwner = "Tulaj beállitása",
  manage = "Management",
  deleteData = "Adat törlése",
  deleteVehicle = "Jármü törlése",
  delete = "Törlés",
  deleteConfirmation = "Biztos vagy benne?",
  deleteConfirmationDanger = "Biztos vagy benne? Ez a müvelet nem visszavonható.",
  setDealershipOwner = "Kereskedés tulajdonos beállitása",
  overwriteDealerPrices = "Kereskedési árak megváltoztatása",
  nearbyPlayers = "Játékosok a közeledben",
  noPlayersNearby = "Nincs játékos a közeledben",
  selectPlayer = "Játékos kiválasztása",
  required = "Szükséges",
  forExample = "Például",
  spawnCode = "Lehivókód",
  brand = "Márka",
  model = "Modell",
  category = "Kategória",
  price = "Ár",
  import = "Import",
  importing = "Importálás",
  importBehaviour = "Import fajtája",
  importVehicles = "Jármü import",
  importFrom = "Importálva innen:",
  dashboard = "Kezelöfelület",
  displayVehicle = "Jármü bemutatása",
  displayVehicles = "Jármüvek bemutatása",
  orders = "Rendelések",
  sales = "Eladások",
  vehiclesOnDisplay = "Bemutatott jármüvek",
  employees = "Alkalmazottak",
  settings = "Beállitások",
  switchVehicle = "Jármü váltás",
  remove = "Elvesz",
  noDisplayVehicles = "Nincsenek bemutató jármüvek",
  selectVehicle = "Jármü választás",
  colour = "Szin",
  placeVehicle = "Jármü elhelyezése",
  orderVehicle = "Jármü rendelése",
  cancelOrder = "Rendelés visszavonása",
  delivery = "Szállitás",
  delivered = "Kiszállitva",
  noOrders = "Nincs rendelés",
  quantity = "Mennyiség",
  totalCost = "Teljes költség",
  totalSales = "Összes eladás",
  noSales = "Nincsenek eladások",
  paid = "Fizetve",
  owed = "Tartozott",
  dealershipName = "Kereskedés neve",
  save = "Változtatások mentése",
  cancel = "Mégse",
  notEnoughMoney = "Nincs elég pénzed",
  placeOrder = "Rendelés leadása",
  purchaseCost = "Költség",
  salePrice = "Eladási ár",
  inStock = "Készleten",
  outOfStock = "Nincs készleten",
  placeVehiclePrompt = "Nyomj %{value} gombot a jármü elhelyezéshez. Késöbb tudsz módosítani!",
  remaining = "Maradt",
  prePurchaseRepoWarning = "Ha nem törleszted a részletfizetést a jármü autómatikusan visszavételre kerül.",
  repossessionWarning = "Nem tudtad fedezni az utolsó részletet, fizess most vagy a jármü visszavételre kerül.",
  recurringPayment = "Részletfizetés",
  remainingBalance = "Hátralévö összeg",
  remainingPayments = "Hátralévö részlet",
  paymentTakenEvery = "A részlet minden",
  hours = "óra",
  seconds = "másodperc",
  nextPayment = "Következö részlet",
  makePayment = "Részlet kifizetése",
  vehicleRepossessed = "A jármü visszavételre kerül",
  payInFull = "Kifizetés egyben",
  earlyPaymentConfirmation = "Biztosan elöbb kifizeted a részletét",
  financedVehicles = "Lizingelt jármüvek",
  noFinancedVehicles = "Nincs jármüved aktiv részletfizetéssel",
  financeBreakdown = "Lizing megszakitása",
  initialPayment = "Elsö részlet",
  payments = "Kifizetések",
  length = "Futamidö",
  interest = "Érdeklödés",
  totalPayable = "Teljes összeg",
  leaveShowroom = "Bemutató elhagyása",
  handling = "Kezelhetöség",
  topSpeed = "Végsebesség",
  power = "Löerö",
  torque = "Nyomaték",
  brake = "Fékerö",
  financing = "Részletfizetés",
  financingAvailable = "Részletfizetés elérhetö",
  paymentsOf = "költsége",
  clear = "Töröl",
  testDrive = "Teszt vezetés",
  allCategories = "Összes kategória",
  sortByName = "Rendezés: Név",
  sortByAvailability = "Rendezés: Elérhetö",
  sortByCheapest = "Rendezés: Legolcsóbb",
  sortByMostExpensive = "Rendezés: Legdrágább",
  sortByNewest = "Rendezés: Legújabb",
  purchaseVehicle = "Jármü megvásárlása",
  purchaseFor = "Vásárlás",
  selectSociety = "Válassz ki egy céget",
  financeOverPayments = "Vásárlás %{value} részletben",
  payToday = "Most fizetek",
  financeThen = "Késöbb",
  seeFullBreakdown = "Teljes lebontás megtekintése",
  testDriveExit = "Bármikor kiszállhatsz tesztvezetés közben.",

  -- NOTIFICATIONS
  purchaseSuccess = "Gratulálunk a vásárlásodhoz!",
  depositSuccess = "Sikeres befizetés",
  withdrawSuccess = "Sikeres kifizetés",
  errorNotEnoughMoney = "Nincs elég pénzed",
  errorVehicleOutOfStock = "Nincs készleten a jármü",
  errorCannotAffordVehicle = "Nincs elég pénzed erre a jármüre",
  vehicleFinancePaymentMade = "Részletfizetés választva a jármüre %{value}",
  vehicleFinancePaidOff = "Gratulálunk! A %{value} minden részlete kilett fizetve!",
  vehicleFinancePaymentFailed = "Sikertelen részlet beszedés %{value}",
  vehicleFinanceRepossessedSoon = "Fizesd a %{value} részletét vagy vissza lesz véve a tulajdonodból!",
  vehicleFinanceRepossessed = "Mivel nem fizetted a részletit igy vissza lett véve a %{value} rendszámú jármüved",
  dealershipNotEnoughFunds = "Nincs elég pénze a kereskedésnek",
  dealershipVehiclesOrdered = "Sikeresen megrendelted a jármüvet(jármüveket)",
  dealershipOrderCancelled = "Sikeres rendelés visszavonás",
  errorVehicleWithSpawnCodeExists = "Már van egy autó kinálatban ezzel a lehívó kóddal",
  errorExitVehicle = "Szállj ki a jármüvedböl elöször",

  -- NEW v1.1
  purchaseRequest = "Vásárlási kérelem",
  sendRequest = "Kérelem küldése",
  dealer = "Kereskedő",
  financed = "Finanszírozott",
  signHere = "Itt írja alá",
  signFirstError = "Kérjük, először írja alá",
  denyRequest = "Kérelem elutasítása",
  playerTooManyFinancedVehicles = "A játékosnak túl sok finanszírozott járműve van",
  employeePermissionsError = "Nem rendelkezik a szükséges munkavállalói jogosultságokkal",
  managerRole = "Menedzser",
  supervisorRole = "Felügyelő",
  salesRole = "Értékesítés",
  ownerRole = "Tulajdonos",
  employmentRequest = "Foglalkoztatási kérelem",
  accept = "Elfogadom",
  jobOfferDescription = "Önnek állást ajánlottak a \"%{érték}\" márkakereskedésben. Szeretné elfogadni?",
  pending = "Függőben",
  employeeHiredMsg = "A márkakereskedő bérleti kérelmét elfogadták!",
  employeeRejectedMsg = "A márkakereskedő bérleti kérelmét elutasították",
  sellVehicle = "Eladni jármű",
  vehicleTerms = "Járművekre vonatkozó feltételek",
  financePayments = "Pénzügyi kifizetések",
  commission = "Bizottság",
  role = "Szerepvállalás",
  firedNotification = "Önt kirúgták a \"%{value}\" kereskedésből.",
  dealershipTooFarAway = "Nem vagy közel egyetlen kereskedőhöz sem",
  restoreDisplayVehicles = "Restore bemutatóterem",
  customer = "Ügyfél",
  lessThanAMin = "Kevesebb, mint egy perc",
  mins = "perc(ek)",
  notInVehicle = "Ön nem ül egy járműben",
  notYourVehicleError = "Ez a jármű nem az Ön tulajdona",
  vehicleFinancedError = "Ezt a járművet nem tudja eladni, mert még finanszírozási törlesztőrészletei vannak.",
  dealershipDoesntSellVehicle = "Ez a kereskedés nem tudja megvásárolni ezt a járművet",
  dealershipWantsYourVehicle = "Gratulálunk! Ez a kereskedés szeretné megvásárolni az Ön járművét.",
  purchasePrice = "Kínált ár: ",

  spawnCodeInvalid = "Érvénytelen spawn kód",
  salesRep = "Értékesítési képviselő",
  directSaleAccepted = "Közvetlen eladási kérés elfogadva! A jutalékod ki lett fizetve.",
  directSaleRejected = "Közvetlen eladási kérés elutasítva",

  displayVehicleOutsideZone = "A kiállított járműveket a kereskedés területén belül kell elhelyezni",
  serverAdmin = "Szerver admin",
  selfService = "Önkiszolgáló",
  owned = "Tulajdonolt",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Érvénytelen fizetési mód",
  paymentMethodNoFinance = "Ez a fizetési mód nem támogatja a finanszírozást",
  couldNotGeneratePlate = "Nem sikerült rendszámot generálni",
  invalidCoupon = "Érvénytelen kupon: %{value}",
  tooManyFinancedVehicles = "Túl sok finanszírozott járműved van",
  couldNotSpawnVehicle = "Nem sikerült a járművet létrehozni",

  -- v2: Permissions
  insufficientPermissions = "Elégtelen jogosultságok",

  -- v2: Coupons
  couponCodeAlreadyExists = "Ez a kuponkód már létezik",
  failedToCreateCoupon = "Nem sikerült a kupon létrehozása",
  couponCreatedSuccessfully = "Kupon sikeresen létrehozva",
  couponNotFound = "Kupon nem található",
  couponUpdatedSuccessfully = "Kupon sikeresen frissítve",
  failedToDeleteCoupon = "Nem sikerült a kupon törlése",
  couponDeletedSuccessfully = "Kupon sikeresen törölve",
  editCoupon = "Kupon szerkesztése",
  addCoupon = "Kupon hozzáadása",
  couponCode = "Kuponkód",
  generating = "Generálás...",
  generate = "Generálás",
  discountType = "Kedvezmény típusa",
  percentageOff = "Százalékos kedvezmény",
  amountOff = "Összeg kedvezmény",
  discountValue = "Kedvezmény értéke",
  unlimitedTotalUses = "Korlátlan összes felhasználás",
  unlimitedUsesPerPlayer = "Korlátlan felhasználás játékosonként",
  setExpiryDate = "Lejárati dátum beállítása",
  restrictToSpecificVehicles = "Korlátozás meghatározott járművekre",
  restrictToSpecificCategories = "Korlátozás meghatározott kategóriákra",
  allowUseWithFinance = "Finanszírozással való használat engedélyezése",
  deleteCoupon = "Kupon törlése",
  inactive = "Inaktív",
  expired = "Lejárt",
  maxUses = "Maximális felhasználás",
  coupons = "Kuponok",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Csak szerver adminok alkalmazhatják magukat",
  playerNotFound = "Játékos nem található",
  failedToHireEmployee = "Nem sikerült az alkalmazott felvétele",
  failedToFireEmployee = "Nem sikerült az alkalmazott elbocsátása",
  failedToUpdateEmployeeRole = "Nem sikerült az alkalmazott szerepének frissítése",
  hireEmployee = "Alkalmazott felvétele",
  fireEmployee = "Alkalmazott elbocsátása",
  editRole = "Szerep szerkesztése",
  fire = "Elbocsátás",
  changeRole = "Szerep módosítása",
  updateRole = "Szerep frissítése",

  -- v2: Test drives
  maxTestDrivesReached = "Ez a kereskedés elérte az aktív tesztvezetések maximális számát",
  testDriveNotEnabled = "A tesztvezetések nincsenek engedélyezve ennél a kereskedésnél",
  noTestDriveSpawnCoords = "Nincsenek tesztvezetés spawn koordináták beállítva ehhez a kereskedéshez",
  couldNotSpawnTestDriveVehicle = "Nem sikerült a tesztvezetés járművet létrehozni",
  couldNotGetPlateFromServer = "Nem sikerült rendszámot kapni a szervertől",
  couldNotRegisterTestDriveVehicle = "Nem sikerült a tesztvezetés járművet regisztrálni",
  testDriveEndedByEmployee = "A tesztvezetést egy másik alkalmazott befejezte",
  trackingVehicleLocation = "Jármű helyzet követése...",
  directSaleCancelled = "Az eladási kérést az eladó törölte",
  testDriveKeysReceived = "Megkaptad a tesztvezetés jármű kulcsait",
  testDriveEndedCustomer = "A tesztvezetés befejeződött",
  starting = "Indítás...",
  startTestDrive = "Tesztvezetés indítása",
  spawningTestDriveVehicle = "Tesztvezetés jármű létrehozása...",
  testDriveReady = "Tesztvezetés kész",
  testDriveWalkToVehicle = "A tesztvezetés jármű létrejött a térképeden jelölt helyen. Kísérd el az ügyfelet a járműhöz. Miután átadtad a kulcsokat az ügyfélnek, manuálisan kell befejezned a tesztvezetést, amikor visszatér.",
  givingKeys = "Kulcsok átadása...",
  continueAndGiveKeys = "Folytatás és kulcsok átadása",
  endTestDrive = "Tesztvezetés befejezése",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Nincs készlet ehhez a járműhöz",
  globalStockLimitExceeded = "Csak %{value} darab elérhető",
  orderNotFoundOrFulfilled = "Rendelés nem található vagy már teljesítve",
  priceBelowMinimum = "Az ár nem lehet alacsonyabb mint %{value}",
  priceAboveMaximum = "Az ár nem lehet magasabb mint %{value}",
  stockUpdated = "Készlet frissítve",
  changesSaved = "Változások mentve",
  noStockAvailable = "Nincs elérhető készlet",
  orderPlaced = "Rendelés leadva",
  remainingInStock = "marad a globális készletben",
  exceedsStockLimit = "Meghaladja a készlet limitet",
  setStockQty = "Készlet mennyiség beállítása",
  invalidStockValue = "Kérjük, adj meg érvényes készlet értéket",
  errorSettingStock = "Hiba a készlet beállításakor",
  stockQuantity = "Készlet mennyiség",
  currentStock = "Jelenlegi készlet",
  priceLimitsEnabled = "Ár limitek engedélyezése",
  priceLimitsDescription = "Ha engedélyezve van, a kereskedés menedzserei csak a megadott tartományon belül állíthatnak be árakat.",
  minPrice = "Minimum ár",
  maxPrice = "Maximum ár",
  optional = "Opcionális",
  unlimitedStock = "Korlátlan készlet",
  globalStockLimit = "Globális készlet limit",
  globalStockLimitDescription = "Állítsd be a maximálisan rendelhető egységek számát az összes kereskedésben.",
  currentlyOrdered = "Jelenleg rendelve",
  priceRange = "Ártartomány",
  noMinimum = "Nincs minimum",
  noMaximum = "Nincs maximum",
  vehicleStock = "Jármű készlet",

  -- v2: Sales
  allSales = "Összes eladás",
  paidInFull = "Teljesen kifizetve",
  salesVolume = "Eladási volumen",
  pastMonth = "Elmúlt hónap",
  pastYear = "Elmúlt év",

  -- v2: Management misc
  exploitAttemptDetected = "Hagyd abba a szkript kihasználási kísérletét",
  dealershipNoJobConfigured = "A kereskedésnek nincs beállított munkája",
  modelDoesNotMatchDb = "A jármű modell nem egyezik az adatbázissal",
  importFailed = "Importálás sikertelen: %{value}",
  notInDealershipZone = "A parancs használatához egy kereskedésen belül kell lenned",
  notAnEmployee = "Nem vagy alkalmazottja ennek a kereskedésnek.",
  failedToPrepareDelivery = "Nem sikerült a szállítás előkészítése",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "A jármű modell nem létezik - lépj kapcsolatba egy adminnal",
  vehiclePlateInvalid = "Ennek a járműnek a rendszáma érvénytelen (nyomd meg az F8-at a részletekért)",
  currentlyInRagdollState = "Jelenleg ragdoll állapotban vagy",
  vehicleDoesNotExistContactAdmin = "A jármű nem létezik. Kérjük, lépj kapcsolatba egy adminnal!",
  vehicleSecurityBreachDetected = "Jármű biztonsági behatolás észlelve",

  -- v2: Admin vehicles
  allVehicles = "Összes jármű",
  unassignedVehicles = "Nincs kereskedés",
  searchDealerships = "Kereskedések keresése...",

  -- v2: Trucking mission
  truckingGetInTruck = "Szállj be a kamionba a jelölt helyen a szállítás megkezdéséhez",
  truckingDriveToDelivery = "Hajts a szállítási helyre",
  truckingCompleteDelivery = "Szállítás befejezése",
  truckingDeliveryComplete = "Szállítás befejezve: Sikeresen befejezted a szállítást!",
  truckingDeliveryFailed = "Szállítás sikertelen: Valami hiba történt a szállítás során",
  truckingDriveToPickup = "Hajts a felvételi ponthoz a pótkocsiért",
  truckingMissionFailedSpawnCargo = "Küldetés sikertelen: Nem sikerült a rakomány pótkocsit létrehozni",
  truckingMissionFailedFindCargo = "Küldetés sikertelen: Nem sikerült megtalálni a létrehozott rakományt",
  truckingVehiclesLoaded = "%{count} jármű berakodva",
  truckingWrongTrailer = "Rossz pótkocsi! A megfelelő küldetés pótkocsit kell csatlakoztatnod.",
  truckingTrailerAttached = "Pótkocsi csatlakoztatva - kész a folytatásra",
  truckingDriveToPickupLocation = "Hajts a felvételi pontra",
  truckingWaitingForVehicles = "Várakozás a járművek berakodására...",
  truckingDriveUnderTrailer = "Hajts a pótkocsi alá a csatlakoztatáshoz",
  truckingGetInTruckContinue = "Szállj be a kamionba a folytatáshoz",
  truckingMissionStarted = "Szállítási küldetés elindult: Felvételi pont - %{location}",
  truckingMissionCancelled = "Küldetés törölve: Törölted a szállítási küldetést",
  truckingNoActiveMission = "Nincs aktív szállítási küldetés a törléshez",
  deliveryNotPrepared = "Szállítás nincs előkészítve - próbáld újra",
  deliveryConfigMismatch = "Szállítási konfiguráció nem egyezik",
  deliveryPreparationExpired = "Szállítás előkészítés lejárt - próbáld újra",
  noTruckingVehicleCoordinates = "Szállító jármű koordináták nincsenek beállítva",
  pickupLocationUnavailable = "Felvételi pont már nem elérhető - próbáld újra",
  failedToSpawnTruck = "Nem sikerült a kamion létrehozása",
  clientFailedToStartMission = "A kliens nem tudta elindítani a küldetést",

  -- v2: Trucking UI/Keys
  keyDismiss = "Bezárás",
  keyDeliverCargo = "Rakomány szállítása",
  keyContinueToDelivery = "Folytatás a szállításhoz",
  startDeliveryMission = "Szállítási küldetés indítása",
  orderDetails = "Rendelés részletei",
  pickupLocation = "Felvételi pont",
  deliveryStatus = "Szállítási állapot",
  selectOrders = "Rendelések kiválasztása",
  carTrailer = "Autószállító",
  container = "Konténer",
  deliveryRoute = "Szállítási útvonal",
  startDelivery = "Szállítás indítása",

  -- v2: Direct sales UI
  waitingForCustomer = "Várakozás az ügyfélre",
  cancelRequest = "Kérés törlése",
  saleComplete = "Eladás befejezve!",
  done = "Kész",
  saleDeclined = "Eladás elutasítva",
  close = "Bezárás",

  -- v2: Display vehicle placement
  movement = "Mozgás",
  rotate = "Forgatás",
  forward = "Előre",
  backward = "Hátra",
  left = "Balra",
  right = "Jobbra",
  rotateLeft = "Balra forgatás",
  rotateRight = "Jobbra forgatás",

  -- v2: Showroom misc
  originalPrice = "Eredeti ár",
  discount = "Kedvezmény",
  createInteraction = "Interakció létrehozása",
  viewAll = "Összes megtekintése",
  fetchingPlayers = "Játékosok lekérése",
  refresh = "Frissítés",
  loadingPlayers = "Játékosok betöltése...",
  failedToLoadPlayers = "Nem sikerült betölteni a játékosokat",
  selectAPlayer = "Válassz játékost",
  failedToLoadPlayersRetry = "Nem sikerült betölteni a játékosokat. Kattints a 'Frissítés' gombra az újrapróbálkozáshoz.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Önkiszolgáló kereskedés",
  categories = "Kategóriák",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Helyszínek",
  createNew = "Új létrehozása",
  enable = "Engedélyezés",
  disable = "Letiltás",
  loading = "Betöltés...",
  errors = "Hibák",
  update = "Frissítés",
  create = "Létrehozás",

  -- v2: Dealership creation/editing
  createDealership = "Kereskedés létrehozása",
  editDealership = "Kereskedés szerkesztése",
  essentials = "Alapok",
  advanced = "Haladó",
  noDealershipLocations = "Nincsenek kereskedési helyszínek",
  noDealershipLocationsDesc = "Hozzáadhatsz új helyszínt, importálhatsz a konfigurációdból (ha v1-ről migrálsz) vagy automatikusan hozzáadhatod az alapértelmezett helyszíneket.",

  -- v2: Location sections
  dealershipZone = "Kereskedési zóna",
  showroomAndManagement = "Showroom és kezelés",
  openShowroom = "Showroom megnyitása",
  openManagement = "Kezelés megnyitása",
  enableSellVehicle = "Járműeladás engedélyezése",
  percentageOfVehicleValue = "Járműérték %-a",
  enablePurchase = "Vásárlás engedélyezése",
  purchasedVehicleSpawn = "Megvásárolt jármű spawn",
  enableTestDrive = "Tesztvezetés engedélyezése",
  testDriveVehicleSpawn = "Tesztvezetés jármű spawn",
  truckDelivery = "Kamionos szállítás",
  truckDeliveryVehicleSpawn = "Szállító jármű spawn",

  -- v2: Location advanced settings
  paymentMethods = "Fizetési módok",
  supportsFinancing = "(támogatja a finanszírozást)",
  enableFinance = "Finanszírozás engedélyezése",
  cameraPreset = "Kamera",
  preset = "Előre beállított",
  custom = "Egyéni",
  vehiclePosition = "Jármű pozíció",
  zoomPositions = "Zoom pozíciók (vesszővel elválasztva)",
  zoomPositionsPlaceholder = "példa: 5,8,12,8",
  vehicleColour = "Jármű szín",
  selectionType = "Kiválasztás típusa",
  noColourSelection = "Nincs színválasztás",
  rgbColourWheel = "RGB színkerék",
  listOfRgbColours = "RGB színek listája",
  listOfColourIds = "Szín ID-k listája",
  accessControl = "Hozzáférés-vezérlés",
  showroomJobWhitelist = "Showroom munka fehérlista",
  showroomGangWhitelist = "Showroom banda fehérlista",
  societyPurchaseJobWhitelist = "Társasági vásárlás munka fehérlista",
  societyPurchaseGangWhitelist = "Társasági vásárlás banda fehérlista",
  setInGame = "Beállítás játékban",
  addNew = "Új hozzáadása",

  -- v2: Job/Gang whitelist editor
  job = "Munka",
  gang = "Banda",
  jobWhitelist = "Munka fehérlista",
  gangWhitelist = "Banda fehérlista",
  addJob = "Munka hozzáadása",
  addGang = "Banda hozzáadása",
  editJob = "Munka szerkesztése",
  editGang = "Banda szerkesztése",
  manageJobs = "Munkák kezelése",
  manageGangs = "Bandák kezelése",
  jobName = "Munka neve",
  gangName = "Banda neve",
  selectGrades = "Rangok kiválasztása",
  selectAll = "Összes kiválasztása",
  deselectAll = "Összes kijelölés törlése",
  invalidJobName = "Érvénytelen munkanév. Ellenőrizd a framework konfigurációdat.",
  invalidGangName = "Érvénytelen bandanév. Ellenőrizd a framework konfigurációdat.",
  grades = "Rangok",
  noJobsConfigured = "Nincsenek konfigurált munkák",
  noGangsConfigured = "Nincsenek konfigurált bandák",
  click = "Kattints",
  toGetStarted = "a kezdéshez.",
  more = "további",
  jobPlaceholder = "Például: cardealer",
  jobOptionalDescription = "Opcionálisan kösd össze a kereskedési szerepeket egy framework munkával. Amikor alkalmazottak felvétele/elbocsátása történik, a framework munkájuk is frissül.",
  jobRankPermissions = "Munka rang engedélyek",
  roleToJobRankMapping = "Szerep munka rang hozzárendelése",
  addPerm = "Engedély hozzáadása",

  -- v2: Colour selector
  searchColours = "Színek keresése...",
  noColoursFound = "Nem található szín",

  -- v2: Interactions creator
  noInteractions = "Nincsenek interakciók",
  highlightInteractions = "Interakciók kiemelése",
  explorationMode = "Felfedezési mód",
  pressEsc = "Nyomd meg az ESC-et",
  toWalkAround = "a sétáláshoz",
  toReturnToUI = "a felületre való visszatéréshez",
  points = "pontok",
  location = "helyszín",
  manageLocations = "Helyszínek kezelése",

  -- v2: Interaction modal
  interactionType = "Típus",
  nicknameOptional = "Becenév (Opcionális)",
  invalidModel = "Érvénytelen modell",
  failedToValidateModel = "Nem sikerült érvényesíteni a modellt",
  pedScenario = "Ped forgatókönyv",
  coords = "Koordináták",
  size = "Méret",
  blip = "Blip",
  enableBlip = "Blip engedélyezése",
  blipIconId = "Blip ikon ID",
  blipColourId = "Blip szín ID",
  blipSize = "Blip méret",
  marker = "Jelölő",
  enableMarker = "Jelölő engedélyezése",
  markerStyleId = "Jelölő stílus ID",
  markerSize = "Jelölő méret",
  markerColor = "Jelölő szín",
  markerBobUpAndDown = "Fel-le lebegés",
  markerFaceCamera = "Kamerára nézés",
  markerRotate = "Forgatás",
  markerDrawOnEnts = "Entitásokra rajzolás",
  updatePosition = "Pozíció frissítése",
  setPosition = "Pozíció beállítása",

  -- v2: Interaction types
  interactionPoint = "Pont",
  interactionPointDesc = "Egyetlen átméretezhető pont, opcionális jelölővel",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Több koordinátás zóna specifikus interakciós terület létrehozásához",
  interactionVehicle = "Jármű",
  interactionVehicleDesc = "Jármű modell spawnolása, ideális target vagy 3D szöveg UI interakciós módszerekhez",
  interactionObject = "Objektum",
  interactionObjectDesc = "Objektum modell spawnolása, ideális target vagy 3D szöveg UI interakciós módszerekhez",
  interactionPed = "Ped",
  interactionPedDesc = "Ped modell spawnolása opcionális forgatókönyvvel, ideális target vagy 3D szöveg UI interakciós módszerekhez",

  -- v2: Import modal
  importLocationsTitle = "Helyszínek importálása",
  syncStockLabel = "Készlet szinkronizálása",
  syncStockDescription = "Járművek hozzáadása minden kereskedés készletéhez a kategóriái alapján",
  importSourceSelectorDesc = "Importálhatsz alapértelmezett helyszíneket a kész beállításhoz, vagy importálhatod a meglévő helyszíneidet a konfigurációdból, ha Dealerships v1-ről migrálsz.",
  importSourceSelectorSkipDesc = "A már létező helyszínek átugrásra kerülnek; csak az új helyszínek lesznek importálva.",
  successfullyImported = "Sikeresen importálva",
  alreadyExist = "Már létezik",
  defaultLocations = "Alapértelmezett helyszínek",
  defaultLocationsDesc = "Előre konfigurált kereskedési helyszínek importálása (PDM, Luxus, Hajók, Légi, Teherautó)",
  existingConfig = "Meglévő konfiguráció",
  existingConfigDesc = "Helyszínek importálása a config.lua-ból (v1 migrációhoz)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Szeretnéd automatikusan hozzáadni a járműveket ennek a kereskedésnek a készletéhez a kiválasztott kategóriák alapján?",
  categorySyncEditDesc = "Megváltoztattad ennek a kereskedésnek a kategóriáit. Szeretnéd automatikusan frissíteni a járműkészletet?",
  addVehicles = "Járművek hozzáadása",
  removeVehicles = "Járművek eltávolítása",
  fromNewCategories = "új kategóriákból",
  fromSelectedCategories = "kiválasztott kategóriákból",
  fromRemovedCategories = "eltávolított kategóriákból",
  categoriesAdded = "Hozzáadott kategóriák:",
  categoriesRemoved = "Eltávolított kategóriák:",
  skip = "Kihagyás",
  syncStock = "Készlet szinkronizálása",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Forrás elérhetőségének ellenőrzése...",
  vehiclesAvailableToImport = "járművek importálásra elérhetőek",
  includesDealershipIds = "tartalmazza a kereskedési ID-kat",
  sourceUnavailable = "Forrás nem elérhető",
  noVehiclesAdminDescription = "Járműveket manuálisan adhatsz hozzá vagy importálhatod őket a framework-ödből.",
  appendBehaviour = "Hozzáfűzés",
  overwriteBehaviour = "Felülírás",
  appendDescription = "Csak új járművek hozzáadása, amelyek még nem léteznek az adatbázisban",
  overwriteDescription = "Minden meglévő járműadat törlése és új importálás",
  stockAssignmentMethod = "Készlet hozzárendelési módszer",
  useDealershipIdsFromSource = "Kereskedési ID-k használata a forrásból",
  matchByVehicleCategory = "Egyeztetés járműkategória szerint",
  byShopDescription = "A járművek a forrásadatok 'shop' mezője alapján lesznek kereskedésekhez rendelve",
  byCategoryDescription = "A járművek egyező kategóriájú kereskedésekhez lesznek rendelve",
  overwriteWarning = "Figyelmeztetés: A felülírás törli az összes meglévő járművet, rendelést, kiállított járművet és értékesítési adatot.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX járművek tábla",
  selectCategory = "Válassz kategóriát",

  -- v2: Management menu items
  vehiclesMenu = "Járművek",
  displayVehiclesMenu = "Kiállított járművek",
  ordersMenu = "Rendelések",
  salesMenu = "Eladások",
  bankAccountMenu = "Bankszámla",
  employeesMenu = "Alkalmazottak",
  couponsMenu = "Kuponok",
  settingsMenu = "Beállítások",
  noPermissionAccessManagement = "Nincs jogosultságod a kezelési funkciókhoz.",
  backToAdmin = "Vissza az adminhoz",
  viewingAsAdmin = "ADMIN NÉZETBEN",

  -- v2: Coupons table
  code = "Kód",
  uses = "Használat",
  perPlayer = "Játékosonként",
  never = "Soha",
  noCoupons = "Nincsenek kuponok",
  noCouponsDescription = "A vásárlók kuponkódot adhatnak meg a járművásárlásnál és pénzt takaríthatnak meg.",

  -- v2: Coupon modal
  couponCodeLabel = "Kuponkód",
  couponCodePlaceholder = "pl. NYAR2024 vagy SPROLJ10",
  couponCodeHelp = "Adj meg egy egyéni kódot (max. 25 karakter, csak betűk, számok és kötőjelek) vagy kattints a 'Generálás' gombra.",
  maxNumberOfUsesPlaceholder = "Maximális felhasználások száma",
  maxUsesPerPlayerPlaceholder = "Maximális felhasználás játékosonként",
  vehicleRestrictionsPlaceholder = "Add meg a spawn kódokat vesszővel elválasztva (pl. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Engedélyezés finanszírozott vásárlásnál",
  createCoupon = "Kupon létrehozása",
  updateCoupon = "Kupon frissítése",

  -- v2: Coupon validation messages
  couponCodeRequired = "A kuponkód kötelező",
  couponCodeMaxLength = "A kód maximum 25 karakter lehet",
  couponCodeInvalidChars = "A kód csak nagybetűket, számokat és kötőjeleket tartalmazhat",
  discountTypeRequired = "A kedvezmény típusa kötelező",
  discountValueRequired = "A kedvezmény értéke kötelező",
  discountValueMin = "A kedvezmény értékének 0-nál nagyobbnak kell lennie",
  discountValueMaxPercent = "A százalék nem haladhatja meg a 100-at",
  maxUsesRequired = "A maximális felhasználás kötelező",
  maxUsesMin = "Legalább 1 kell legyen",
  perPlayerLimitRequired = "A játékosonkénti limit kötelező",
  expiryDateRequired = "A lejárati dátum kötelező",
  vehicleRestrictionsRequired = "A járműkorlátozások kötelezőek",
  categoryRestrictionsRequired = "A kategória korlátozások kötelezőek",
  selectAtLeastOneCategory = "Válassz legalább egy kategóriát",

  -- v2: Dashboard
  today = "Ma",
  thisMonth = "Ez a hónap",
  allTime = "Összesen",
  recentSales = "Legutóbbi eladások",
  noSalesYet = "Még nincsenek eladások!",
  noSalesDescription = "A járműeladások itt jelennek meg az első eladás után.",
  past7Days = "Elmúlt 7 nap",
  past6Months = "Elmúlt 6 hónap",
  numberOfSales = "Eladások száma",
  noDataAvailableForPeriod = "Nincs elérhető adat erre az időszakra",

  -- v2: Display vehicles
  displayVehiclesDescription = "A kiállított járművek fix showroom modellek, amelyek a készleted bemutatására és a vásárlók vásárlásra ösztönzésére szolgálnak.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework munkák engedélyezve",
  frameworkJobsDescription = "Az alkalmazottak kezelése a framework munkarendszerén keresztül történik. A kereskedési munkával rendelkező játékosok automatikusan hozzáférést kapnak a rangjuk alapján. Konfiguráld a munka engedélyeket az admin panel helyszín beállításaiban.",
  joinedColumn = "Csatlakozott",
  youBadge = "Te",

  -- v2: Orders
  noOrdersTitle = "Nincsenek rendelések",
  noOrdersDescription = "Rendelés leadásához nyisd meg a 'Járművek' fület és kattints a 'Rendelés' gombra az újratölteni kívánt járműnél.",
  inProgress = "Folyamatban",
  awaitingDelivery = "Szállításra vár",
  orderedBy = "Rendelte",
  viewDeliveryInfo = "Szállítási info megtekintése",

  -- v2: Delivery
  startDeliveryMissionTitle = "Szállítási küldetés indítása",
  startDeliveryDescription = "Szállítási küldetést indítasz ehhez a járműrendeléshez. El kell vezetned a felvételi pontra, fel kell venned a rakományt és vissza kell szállítanod a kereskedésbe.",
  totalDistanceAndDriveTime = "Teljes távolság és vezetési idő",
  roundTrip = "oda-vissza",
  deliveryCompleteTitle = "Szállítás befejezve",
  deliveryInProgressTitle = "Szállítás folyamatban",
  deliveredAt = "Kiszállítva:",
  startedAt = "Elkezdve:",
  deliveredBy = "Kiszállította:",
  beingDeliveredBy = "Szállítja:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Nincsenek szállítható rendelések. A rendeléseknek késznek kell lenniük és nem lehetnek aktív szállításban.",
  confirmDeliveryTitle = "Szállítás megerősítése",
  configureDeliveryTitle = "Szállítás konfigurálása",
  trailerCapacityExceeded = "Pótkocsi kapacitás túllépve! %{usedSlots} helyet választottál, de a maximum %{maxSlots} hely.",
  smallVehiclesSlotInfo = "Ne feledd: a kis járművek 1 helyet, a közepes járművek 1.5 helyet foglalnak.",
  fetchingRoute = "Lekérés...",
  getRouteButton = "Útvonal lekérése",
  selectTrailerType = "Válassz pótkocsi típust",
  carTrailerLabel = "Autószállító",
  smallMedium = "(Kicsi/Közepes)",
  containerLabel = "Konténer",
  large = "(Nagy)",
  carTrailerDescription = "Az autószállítónak 2 sora van. Minden sor 3 kicsit (egyenként 1 hely) vagy 2 közepeset (egyenként 1.5 hely) tud szállítani. Maximum 6 hely összesen.",
  containerDescription = "A konténer pótkocsi 1 nagy járművet szállít",
  selectOrdersTitle = "Rendelések kiválasztása",
  slots = "helyek",
  noOrdersForTrailerType = "Nincsenek elérhető rendelések ehhez a pótkocsi típushoz.",
  qty = "Mennyiség:",
  inTransit = "úton",
  totalVehicles = "Összes jármű:",
  estimatedTime = "Becsült idő:",
  unknown = "Ismeretlen",

  -- v2: Sales
  salesEmptyDescription = "A járműeladások itt jelennek meg az első eladás után.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Rendelés leadva!",
  orderPlacedTruckingDescription = "A rendelésed készen áll a felvételre. Menj a rendelések oldalra a teljesítéshez.",
  orderPlacedTimedDescription = "A rendelésed %{value} perc múlva érkezik.",
  goToOrders = "Rendelésekhez",
  noStockAvailableDescription = "Nincs elérhető készlet ehhez a járműhöz. A globális készletlimit elérve.",
  stockUpdatedDescription = "A készletmennyiség sikeresen frissítve.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktív tesztvezetések",
  tracking = "Követés",
  track = "Követ",
  endButton = "Befejezés",
  endTestDriveTitle = "Tesztvezetés befejezése",
  endTestDriveConfirmation = "Biztosan befejezed ezt a tesztvezetést? A jármű törlődik és az utasok nem lesznek visszateleportálva a kereskedésbe.",
  vehicleLocationOnMap = "A jármű helye meg lett jelölve a térképeden.",
  sell = "Eladás",
  couponCodeOptional = "Kuponkód (Opcionális)",
  pleaseEnterCouponCode = "Kérlek adj meg kuponkódot",
  invalidCouponCode = "Érvénytelen kuponkód",
  failedToValidateCoupon = "Nem sikerült érvényesíteni a kupont",
  apply = "Alkalmaz",
  applying = "Alkalmazás...",
  allStock = "Teljes készlet",
  inStockFilter = "Készleten",
  outOfStockFilter = "Elfogyott",
  noResultsFound = "Nem találhatók eredmények",
  noResults = "Nincs eredmény",
  noVehiclesMatchSearch = "Nincs a keresésednek megfelelő jármű",
  noVehiclesMatchFilters = "Nincs a jelenlegi szűrőidnek megfelelő jármű",
  noItemsMatchSearch = "Nincs a keresésednek megfelelő elem",
  noItemsMatchFilters = "Nincs a jelenlegi szűrőidnek megfelelő elem",
  selectColour = "Válassz színt",
  refreshNearbyPlayers = "Közeli játékosok frissítése",
  you = "Te",
  items = "elemek",
  waitingForCustomerToRespond = "Várakozás az ügyfél válaszára...",
  vehicleSpawnedMessage = "A jármű megjelent a térképeden jelzett pontnál - vidd oda az ügyfelet.",
  customerDeclinedMessage = "Az ügyfél elutasította a vásárlási kérelmet.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "ALÁÍRÁS ITT",
  acceptAndPurchase = "Elfogadás és vásárlás",
  couponApplied = "%{code} kupon alkalmazva! Megtakarítás %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Legalább 3 pont szükséges a zóna befejezéséhez! (Jelenleg %{value})",
  addPoint = "Pont hozzáadása",
  removeLast = "Utolsó eltávolítása",
  completeZone = "Zóna befejezése",
  spawnPreview = "Spawn előnézet",
  up = "Fel",
  down = "Le",
  confirm = "Megerősítés",
  placePoint = "Pont elhelyezése",
  radius = "Sugár",

  -- v2: Blip labels
  soldVehicleLocation = "Eladott jármű helye",
  testDriveVehicleBlip = "Tesztvezetés jármű",

  -- v2: Stock sync
  stockSyncResult = "Készlet szinkronizálás: %{added} hozzáadva, %{removed} eltávolítva",
  stockSyncAdded = "Készlet szinkronizálás: %{value} jármű hozzáadva",
  importSuccessful = "Importálás sikeres! %{imported} jármű importálva (összesen %{total})",

  -- v2: Tooltip actions
  findOnMap = "Keresés a térképen",
  adminPanel = "Admin panel",

  -- v2: Common dropdown
  selectOne = "Válassz egyet",
}
