Locales = Locales or {}

Locales['it'] = {
  -- UI
  vehicle = "Veicolo",
  vehicles = "Veicoli",
  dealership = "Concessionario",
  dealerships = "Concessionari",
  vehiclesCount = "veicolo/i",
  dealersCount = "concessionario/i",
  accountBalance = "Bilancio Conto",
  bank = "Conto Bancario",
  cash = "Contanti",
  amount = "Quantità",
  societyFund = "Fondo Società",
  paymentSource = "Fonte Pagamento",
  purchase = "Compra",
  personalPurchase = "Compra Personale",
  societyPurchase = "Compra Società",
  purchaseType = "Tipo Acquisto",
  deposit = "Deposita",
  withdraw = "Preleva",
  all = "Tutti",
  yes = "Si",
  no = "No",
  add = "Aggiungi",
  edit = "Modifica",
  id = "ID",
  created = "Creato",
  type = "Tipo",
  name = "Nome",
  owner = "Proprietario",
  bankBalance = "Bilancio Banca",
  status = "Status",
  back = "Indietro",
  previous = "Precedente",
  next = "Prossimo",
  admin = "Admin",
  vehiclesAdmin = "Veicoli Admin",
  dealershipsAdmin = "Concessionari Admin",
  search = "Cerca",
  noDealershipsFound = "Nessuna concessionaria trovata",
  noVehicles = "Nessun veicolo trovato",
  page = "Pagina",
  of = "di",
  every = "ogni",
  show = "Mostra",
  active = "Attiva",
  activeFinance = "Attiva Rateizzazione",
  failed = "Pagamento Fallito",
  removed = "Rimossa",
  setOwner = "Imposta Proprietario",
  manage = "Gestisci",
  deleteData = "Elimina Dati",
  deleteVehicle = "Elimina Veicolo",
  delete = "Elimina",
  deleteConfirmation = "Sei sicuro?",
  deleteConfirmationDanger = "Sei sicuro? Questa azione è irreversibile.",
  setDealershipOwner = "Imposta Proprietario Concessionario",
  overwriteDealerPrices = "Sovrascrivi prezzi concessionario",
  nearbyPlayers = "Player vicini",
  noPlayersNearby = "Nessun player vicino",
  selectPlayer = "Seleziona player",
  required = "Richiesto",
  forExample = "Per esempio",
  spawnCode = "Codice Spawn",
  brand = "Marchio",
  model = "Modello",
  category = "Categoria",
  price = "Prezzo",
  import = "Importa",
  importing = "Importando",
  importBehaviour = "Tipo Importazione",
  importVehicles = "Importa veicoli",
  importFrom = "Importa da",
  dashboard = "Dashboard",
  displayVehicle = "Mostra Veicolo",
  displayVehicles = "Mostra Veicoli",
  orders = "Ordini",
  sales = "Vendite",
  vehiclesOnDisplay = "Veicoli in mostra",
  employees = "Impiegati",
  settings = "Impostazioni",
  switchVehicle = "Cambia Veicolo",
  remove = "Rimuovi",
  noDisplayVehicles = "Nessun veicolo in mostra",
  selectVehicle = "Seleziona veicolo",
  colour = "Colore",
  placeVehicle = "Posiziona Veicolo",
  orderVehicle = "Ordina veicolo",
  cancelOrder = "Annulla Ordine",
  delivery = "Consegna",
  delivered = "Consegnato",
  noOrders = "Nessun ordine trovato",
  quantity = "Quantità",
  totalCost = "Costo totale",
  totalSales = "Totale vendite",
  noSales = "Nessuna vendita trovata",
  paid = "Pagato",
  owed = "Dovuto",
  dealershipName = "Nome Concessionario",
  save = "Salva Cambiamenti",
  cancel = "Annulla",
  notEnoughMoney = "Non hai abbastanza soldi",
  placeOrder = "Piazza Ordine",
  purchaseCost = "Costo Acquisto",
  salePrice = "Costo Vendita",
  inStock = "In stock",
  outOfStock = "Fuori stock",
  placeVehiclePrompt = "Premi %{value} per posizionare il veicolo. Successivamente puoi apportare modifiche più precise!",
  remaining = "Rimanenti",
  prePurchaseRepoWarning = "Se non riesci a far fronte alle rate del finanziamento, il tuo veicolo verrà pignorato.",
  repossessionWarning = "L'ultimo pagamento è fallito - se non effettui un pagamento ora, il tuo veicolo verrà pignorato.",
  recurringPayment = "Pagamento ricorrente",
  remainingBalance = "Bilancio rimanente",
  remainingPayments = "Pagamenti rimanenti",
  paymentTakenEvery = "Pagamento preso ogni",
  hours = "ore",
  seconds = "secondi",
  nextPayment = "Prossimo pagamento",
  makePayment = "Effettua pagamento",
  vehicleRepossessed = "Il veicolo verrà pignorato",
  payInFull = "Paga per intero",
  earlyPaymentConfirmation = "Sei sicuro di voler effettuare un pagamento anticipato di",
  financedVehicles = "Veicoli Rateizzati",
  noFinancedVehicles = "Non hai veicoli con rateizzazione attiva",
  financeBreakdown = "Ripartizione Finanziaria",
  initialPayment = "Pagamento iniziale",
  payments = "Pagamenti",
  length = "Rate",
  interest = "Interessi",
  totalPayable = "Prezzo Totale",
  leaveShowroom = "Lascia Showroom",
  handling = "Manovrabilità",
  topSpeed = "Velocità Max",
  power = "Potenza",
  torque = "Coppia",
  brake = "Freno",
  financing = "Rateizzazione",
  financingAvailable = "Rateizzazione disponibile",
  paymentsOf = "pagamenti di",
  clear = "Resetta",
  testDrive = "Test Drive",
  allCategories = "Tutte Categorie",
  sortByName = "Ordina per: Nome",
  sortByAvailability = "Ordina per: Disponibilità",
  sortByCheapest = "Ordina per: Più Economica",
  sortByMostExpensive = "Ordina per: Più Costosa",
  sortByNewest = "Ordina per: Più Nuova",
  purchaseVehicle = "Acquista Veicolo",
  purchaseFor = "Acquista per",
  selectSociety = "Seleziona una società",
  financeOverPayments = "Rateizza in %{value} pagamenti",
  payToday = "Paga oggi",
  financeThen = "Poi",
  seeFullBreakdown = "Vedi ripartizione completa",
  testDriveExit = "Puoi uscire dal veicolo in qualsiasi momento per terminare il test drive.",

  -- NOTIFICATIONS
  purchaseSuccess = "Congratulazioni per il tuo acquisto!",
  depositSuccess = "Depositato con successo",
  withdrawSuccess = "Prelevato con successo",
  errorNotEnoughMoney = "Non hai abbastanza soldi",
  errorVehicleOutOfStock = "Il veicolo non è in magazzino",
  errorCannotAffordVehicle = "Non ti puoi permettere questo veicolo",
  vehicleFinancePaymentMade = "Pagamento rata fatto per il tuo veicolo %{value}",
  vehicleFinancePaidOff = "Congratulazioni, hai pagato e ora possiedi il tuo veicolo %{value}",
  vehicleFinancePaymentFailed = "Pagamento rata fallito per il tuo veicolo %{value}",
  vehicleFinanceRepossessedSoon = "Devi pagare la rata del veicolo %{value} o verrà presto pignorato",
  vehicleFinanceRepossessed = "A causa del mancato pagamento, il tuo veicolo è stato pignorato con la targa %{value}",
  dealershipNotEnoughFunds = "Concessionario non ha abbastanza fondi",
  dealershipVehiclesOrdered = "Veicolo/i ordinato/i con successo",
  dealershipOrderCancelled = "Ordine annullato con successo",
  errorVehicleWithSpawnCodeExists = "Esiste già un veicolo con questo codice spawn",
  errorExitVehicle = "Devi prima uscire dal veicolo",
  errorPlacementCollision = "Non puoi piazzare il veicolo qui",

  -- NEW v1.1
  purchaseRequest = "Richiesta Acquisto",
  sendRequest = "Invia Richiesta",
  dealer = "Venditore",
  financed = "Rateizzata",
  signHere = "Firma qui",
  signFirstError = "Prima firma",
  denyRequest = "Rifiuta Richiesta",
  playerTooManyFinancedVehicles = "Il giocatore ha troppi veicoli rateizzati",
  employeePermissionsError = "Non hai i permessi impiegato necessari",
  managerRole = "Manager",
  supervisorRole = "Supervisore",
  salesRole = "Vendite",
  ownerRole = "Proprietario",
  employmentRequest = "Richiesta di Impiego",
  accept = "Accetta",
  jobOfferDescription = "Ti è stato offerto un lavoro al Concessionario \"%{value}\". Vuoi accettarlo?",
  pending = "In attesa",
  employeeHiredMsg = "Richiesta di assunzione nel concessionario accettata!",
  employeeRejectedMsg = "Richiesta di assunzione nel concessionario rifiutata",
  sellVehicle = "Vendi Veicolo",
  vehicleTerms = "Termini Veicolo",
  financePayments = "Rateizza Pagamenti",
  commission = "Commissione",
  role = "Ruolo",
  firedNotification = "Sei stato licenziato dal concessionario \"%{value}\"",
  dealershipTooFarAway = "Non sei vicino a nessun concessionario",
  restoreDisplayVehicles = "Ripristina Showroom",
  customer = "Cliente",
  lessThanAMin = "Meno di un minuto",
  mins = "minuto/i",
  notInVehicle = "Non sei seduto in un veicolo",
  notYourVehicleError = "Questo veicolo non ti appartiene",
  vehicleFinancedError = "Non puoi vendere questo veicolo perché ha rate in sospeso",
  dealershipDoesntSellVehicle = "Questo concessionario non può acquistare questo veicolo",
  dealershipWantsYourVehicle = "Congratulazioni! Questo concessionario vorrebbe acquistare il tuo veicolo.",
  purchasePrice = "Prezzo offerto: ",

  spawnCodeInvalid = "Codice spawn non valido",
  salesRep = "Resp. Vendite",
  directSaleAccepted = "Richiesta di vendita diretta accettata! La tua commissione è stata pagata.",
  directSaleRejected = "Richiesta di vendita diretta rifiutata!",

  displayVehicleOutsideZone = "I veicoli in esposizione devono essere posizionati all'interno della zona della concessionaria",
  serverAdmin = "Admin del Server",
  selfService = "Self-service",
  owned = "Di proprietà",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Metodo di pagamento non valido",
  paymentMethodNoFinance = "Questo metodo di pagamento non supporta il finanziamento",
  couldNotGeneratePlate = "Impossibile generare la targa",
  invalidCoupon = "Coupon non valido: %{value}",
  tooManyFinancedVehicles = "Hai troppi veicoli finanziati",
  couldNotSpawnVehicle = "Impossibile generare il veicolo",

  -- v2: Permissions
  insufficientPermissions = "Permessi insufficienti",

  -- v2: Coupons
  couponCodeAlreadyExists = "Il codice coupon esiste già",
  failedToCreateCoupon = "Impossibile creare il coupon",
  couponCreatedSuccessfully = "Coupon creato con successo",
  couponNotFound = "Coupon non trovato",
  couponUpdatedSuccessfully = "Coupon aggiornato con successo",
  failedToDeleteCoupon = "Impossibile eliminare il coupon",
  couponDeletedSuccessfully = "Coupon eliminato con successo",
  editCoupon = "Modifica coupon",
  addCoupon = "Aggiungi coupon",
  couponCode = "Codice coupon",
  generating = "Generazione...",
  generate = "Genera",
  discountType = "Tipo di sconto",
  percentageOff = "Percentuale di sconto",
  amountOff = "Importo di sconto",
  discountValue = "Valore dello sconto",
  unlimitedTotalUses = "Utilizzi totali illimitati",
  unlimitedUsesPerPlayer = "Utilizzi illimitati per giocatore",
  setExpiryDate = "Imposta data di scadenza",
  restrictToSpecificVehicles = "Limita a veicoli specifici",
  restrictToSpecificCategories = "Limita a categorie specifiche",
  allowUseWithFinance = "Consenti utilizzo con finanziamento",
  deleteCoupon = "Elimina coupon",
  inactive = "Inattivo",
  expired = "Scaduto",
  maxUses = "Utilizzi massimi",
  coupons = "Coupon",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Solo gli amministratori del server possono auto-assumersi",
  playerNotFound = "Giocatore non trovato",
  failedToHireEmployee = "Impossibile assumere il dipendente",
  failedToFireEmployee = "Impossibile licenziare il dipendente",
  failedToUpdateEmployeeRole = "Impossibile aggiornare il ruolo del dipendente",
  hireEmployee = "Assumi dipendente",
  fireEmployee = "Licenzia dipendente",
  editRole = "Modifica ruolo",
  fire = "Licenzia",
  changeRole = "Cambia ruolo",
  updateRole = "Aggiorna ruolo",

  -- v2: Test drives
  maxTestDrivesReached = "Questa concessionaria ha raggiunto il numero massimo di test drive attivi",
  testDriveNotEnabled = "I test drive non sono abilitati in questa concessionaria",
  noTestDriveSpawnCoords = "Nessuna coordinata di spawn per test drive configurata per questa concessionaria",
  couldNotSpawnTestDriveVehicle = "Impossibile generare il veicolo per il test drive",
  couldNotGetPlateFromServer = "Impossibile ottenere la targa dal server",
  couldNotRegisterTestDriveVehicle = "Impossibile registrare il veicolo per il test drive",
  testDriveEndedByEmployee = "Il test drive è stato terminato da un altro dipendente",
  trackingVehicleLocation = "Tracciamento posizione veicolo...",
  directSaleCancelled = "La richiesta di vendita è stata annullata dal venditore",
  testDriveKeysReceived = "Hai ricevuto le chiavi del veicolo per il test drive",
  testDriveEndedCustomer = "Il test drive è terminato",
  starting = "Avvio...",
  startTestDrive = "Inizia test drive",
  spawningTestDriveVehicle = "Generazione veicolo per test drive...",
  testDriveReady = "Test drive pronto",
  testDriveWalkToVehicle = "Il veicolo per il test drive è stato generato nel punto indicato sulla tua mappa. Accompagna il cliente al veicolo. Dopo aver consegnato le chiavi al cliente, dovrai terminare manualmente il test drive quando tornerà.",
  givingKeys = "Consegna chiavi...",
  continueAndGiveKeys = "Continua e consegna chiavi",
  endTestDrive = "Termina test drive",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Nessuna disponibilità per questo veicolo",
  globalStockLimitExceeded = "Solo %{value} unità disponibili",
  orderNotFoundOrFulfilled = "Ordine non trovato o già evaso",
  priceBelowMinimum = "Il prezzo non può essere inferiore a %{value}",
  priceAboveMaximum = "Il prezzo non può essere superiore a %{value}",
  stockUpdated = "Stock aggiornato",
  changesSaved = "Modifiche salvate",
  noStockAvailable = "Nessuna disponibilità",
  orderPlaced = "Ordine effettuato",
  remainingInStock = "rimanenti in stock globale",
  exceedsStockLimit = "Supera il limite di stock",
  setStockQty = "Imposta quantità stock",
  invalidStockValue = "Inserisci un valore di stock valido",
  errorSettingStock = "Errore nell'impostazione dello stock",
  stockQuantity = "Quantità stock",
  currentStock = "Stock attuale",
  priceLimitsEnabled = "Abilita limiti di prezzo",
  priceLimitsDescription = "Quando abilitato, i gestori della concessionaria possono impostare prezzi solo entro l'intervallo specificato.",
  minPrice = "Prezzo minimo",
  maxPrice = "Prezzo massimo",
  optional = "Opzionale",
  unlimitedStock = "Stock illimitato",
  globalStockLimit = "Limite stock globale",
  globalStockLimitDescription = "Imposta un numero massimo di unità che possono essere ordinate in tutte le concessionarie.",
  currentlyOrdered = "Attualmente ordinato",
  priceRange = "Fascia di prezzo",
  noMinimum = "Nessun minimo",
  noMaximum = "Nessun massimo",
  vehicleStock = "Stock veicoli",

  -- v2: Sales
  allSales = "Tutte le vendite",
  paidInFull = "Pagato per intero",
  salesVolume = "Volume vendite",
  pastMonth = "Mese scorso",
  pastYear = "Anno scorso",

  -- v2: Management misc
  exploitAttemptDetected = "Smetti di cercare di sfruttare lo script",
  dealershipNoJobConfigured = "La concessionaria non ha un lavoro configurato",
  modelDoesNotMatchDb = "Il modello del veicolo non corrisponde al database",
  importFailed = "Importazione fallita: %{value}",
  notInDealershipZone = "Devi trovarti all'interno di una concessionaria per usare questo comando",
  notAnEmployee = "Non sei un dipendente di questa concessionaria.",
  failedToPrepareDelivery = "Impossibile preparare la consegna",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Il modello del veicolo non esiste - contatta un admin",
  vehiclePlateInvalid = "La targa di questo veicolo non è valida (premi F8 per maggiori dettagli)",
  currentlyInRagdollState = "Sei attualmente in stato ragdoll",
  vehicleDoesNotExistContactAdmin = "Il veicolo non esiste. Contatta un admin!",
  vehicleSecurityBreachDetected = "Rilevata violazione della sicurezza del veicolo",

  -- v2: Admin vehicles
  allVehicles = "Tutti i veicoli",
  unassignedVehicles = "Senza concessionaria",
  searchDealerships = "Cerca concessionarie...",

  -- v2: Trucking mission
  truckingGetInTruck = "Sali sul camion nella posizione indicata per iniziare la consegna",
  truckingDriveToDelivery = "Guida fino al punto di consegna",
  truckingCompleteDelivery = "Completa la consegna",
  truckingDeliveryComplete = "Consegna completata: Hai completato la consegna con successo!",
  truckingDeliveryFailed = "Consegna fallita: Qualcosa è andato storto con la consegna",
  truckingDriveToPickup = "Guida fino al punto di ritiro per ritirare il rimorchio",
  truckingMissionFailedSpawnCargo = "Missione fallita: Impossibile generare il rimorchio cargo",
  truckingMissionFailedFindCargo = "Missione fallita: Impossibile trovare il cargo generato",
  truckingVehiclesLoaded = "%{count} veicol%{s} caricato",
  truckingWrongTrailer = "Rimorchio sbagliato! Devi agganciare il rimorchio della missione corretto.",
  truckingTrailerAttached = "Rimorchio agganciato - pronto a proseguire",
  truckingDriveToPickupLocation = "Guida fino al punto di ritiro",
  truckingWaitingForVehicles = "In attesa del caricamento dei veicoli...",
  truckingDriveUnderTrailer = "Passa sotto il rimorchio per agganciarlo",
  truckingGetInTruckContinue = "Sali sul camion per continuare",
  truckingMissionStarted = "Missione di trasporto avviata: Punto di ritiro - %{location}",
  truckingMissionCancelled = "Missione annullata: Hai annullato la missione di trasporto",
  truckingNoActiveMission = "Nessuna missione di trasporto attiva da annullare",
  deliveryNotPrepared = "Consegna non preparata - riprova",
  deliveryConfigMismatch = "Configurazione consegna non corrispondente",
  deliveryPreparationExpired = "Preparazione consegna scaduta - riprova",
  noTruckingVehicleCoordinates = "Coordinate veicolo trasporto non impostate",
  pickupLocationUnavailable = "Punto di ritiro non più disponibile - riprova",
  failedToSpawnTruck = "Impossibile generare il camion",
  clientFailedToStartMission = "Il client non è riuscito ad avviare la missione",

  -- v2: Trucking UI/Keys
  keyDismiss = "Chiudi",
  keyDeliverCargo = "Consegna cargo",
  keyContinueToDelivery = "Continua alla consegna",
  startDeliveryMission = "Inizia missione di consegna",
  orderDetails = "Dettagli ordine",
  pickupLocation = "Punto di ritiro",
  deliveryStatus = "Stato consegna",
  selectOrders = "Seleziona ordini",
  carTrailer = "Bisarca",
  container = "Container",
  deliveryRoute = "Percorso di consegna",
  startDelivery = "Inizia consegna",

  -- v2: Direct sales UI
  waitingForCustomer = "In attesa del cliente",
  cancelRequest = "Annulla richiesta",
  saleComplete = "Vendita completata!",
  done = "Fatto",
  saleDeclined = "Vendita rifiutata",
  close = "Chiudi",

  -- v2: Display vehicle placement
  movement = "Movimento",
  rotate = "Ruota",
  forward = "Avanti",
  backward = "Indietro",
  left = "Sinistra",
  right = "Destra",
  rotateLeft = "Ruota a sinistra",
  rotateRight = "Ruota a destra",

  -- v2: Showroom misc
  originalPrice = "Prezzo originale",
  discount = "Sconto",
  createInteraction = "Crea interazione",
  viewAll = "Visualizza tutto",
  fetchingPlayers = "Recupero giocatori",
  refresh = "Aggiorna",
  loadingPlayers = "Caricamento giocatori...",
  failedToLoadPlayers = "Impossibile caricare i giocatori",
  selectAPlayer = "Seleziona un giocatore",
  failedToLoadPlayersRetry = "Impossibile caricare i giocatori. Clicca 'Aggiorna' per riprovare.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Concessionaria self-service",
  categories = "Categorie",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Posizioni",
  createNew = "Crea nuovo",
  enable = "Abilita",
  disable = "Disabilita",
  loading = "Caricamento...",
  errors = "Errori",
  update = "Aggiorna",
  create = "Crea",

  -- v2: Dealership creation/editing
  createDealership = "Crea concessionaria",
  editDealership = "Modifica concessionaria",
  essentials = "Essenziali",
  advanced = "Avanzato",
  noDealershipLocations = "Nessuna posizione concessionaria",
  noDealershipLocationsDesc = "Puoi aggiungere una nuova posizione, importare dalla tua configurazione (se stai migrando dalla v1) o aggiungere automaticamente posizioni predefinite.",

  -- v2: Location sections
  dealershipZone = "Zona concessionaria",
  showroomAndManagement = "Showroom e gestione",
  openShowroom = "Apri showroom",
  openManagement = "Apri gestione",
  enableSellVehicle = "Abilita vendita veicoli",
  percentageOfVehicleValue = "Percentuale % del valore del veicolo",
  enablePurchase = "Abilita acquisto",
  purchasedVehicleSpawn = "Spawn veicolo acquistato",
  enableTestDrive = "Abilita test drive",
  testDriveVehicleSpawn = "Spawn veicolo test drive",
  truckDelivery = "Consegna camion",
  truckDeliveryVehicleSpawn = "Spawn veicolo consegna",

  -- v2: Location advanced settings
  paymentMethods = "Metodi di pagamento",
  supportsFinancing = "(supporta finanziamento)",
  enableFinance = "Abilita finanziamento",
  cameraPreset = "Telecamera",
  preset = "Predefinito",
  custom = "Personalizzato",
  vehiclePosition = "Posizione veicolo",
  zoomPositions = "Posizioni zoom (separate da virgola)",
  zoomPositionsPlaceholder = "esempio: 5,8,12,8",
  vehicleColour = "Colore veicolo",
  selectionType = "Tipo di selezione",
  noColourSelection = "Nessuna selezione colore",
  rgbColourWheel = "Ruota colori RGB",
  listOfRgbColours = "Lista colori RGB",
  listOfColourIds = "Lista ID colori",
  accessControl = "Controllo accessi",
  showroomJobWhitelist = "Whitelist lavori showroom",
  showroomGangWhitelist = "Whitelist gang showroom",
  societyPurchaseJobWhitelist = "Whitelist lavori acquisto società",
  societyPurchaseGangWhitelist = "Whitelist gang acquisto società",
  setInGame = "Imposta in gioco",
  addNew = "Aggiungi nuovo",

  -- v2: Job/Gang whitelist editor
  job = "Lavoro",
  gang = "Gang",
  jobWhitelist = "Whitelist lavori",
  gangWhitelist = "Whitelist gang",
  addJob = "Aggiungi lavoro",
  addGang = "Aggiungi gang",
  editJob = "Modifica lavoro",
  editGang = "Modifica gang",
  manageJobs = "Gestisci lavori",
  manageGangs = "Gestisci gang",
  jobName = "Nome lavoro",
  gangName = "Nome gang",
  selectGrades = "Seleziona gradi",
  selectAll = "Seleziona tutto",
  deselectAll = "Deseleziona tutto",
  invalidJobName = "Nome lavoro non valido. Controlla la configurazione del tuo framework.",
  invalidGangName = "Nome gang non valido. Controlla la configurazione del tuo framework.",
  grades = "Gradi",
  noJobsConfigured = "Nessun lavoro configurato",
  noGangsConfigured = "Nessuna gang configurata",
  click = "Clicca",
  toGetStarted = "per iniziare.",
  more = "altro",
  jobPlaceholder = "Per esempio: cardealer",
  jobOptionalDescription = "Collega opzionalmente i ruoli della concessionaria a un lavoro del framework. Quando i dipendenti vengono assunti/licenziati, anche il loro lavoro framework verrà aggiornato.",
  jobRankPermissions = "Permessi grado lavoro",
  roleToJobRankMapping = "Mappatura ruolo a grado lavoro",
  addPerm = "Aggiungi permesso",

  -- v2: Colour selector
  searchColours = "Cerca colori...",
  noColoursFound = "Nessun colore trovato",

  -- v2: Interactions creator
  noInteractions = "Nessuna interazione",
  highlightInteractions = "Evidenzia interazioni",
  explorationMode = "Modalità esplorazione",
  pressEsc = "Premi ESC",
  toWalkAround = "per camminare",
  toReturnToUI = "per tornare all'interfaccia",
  points = "punti",
  location = "posizione",
  manageLocations = "Gestisci posizioni",

  -- v2: Interaction modal
  interactionType = "Tipo",
  nicknameOptional = "Soprannome (Opzionale)",
  invalidModel = "Modello non valido",
  failedToValidateModel = "Impossibile validare il modello",
  pedScenario = "Scenario ped",
  coords = "Coordinate",
  size = "Dimensione",
  blip = "Blip",
  enableBlip = "Abilita blip",
  blipIconId = "ID icona blip",
  blipColourId = "ID colore blip",
  blipSize = "Dimensione blip",
  marker = "Marcatore",
  enableMarker = "Abilita marcatore",
  markerStyleId = "ID stile marcatore",
  markerSize = "Dimensione marcatore",
  markerColor = "Colore marcatore",
  markerBobUpAndDown = "Oscilla su e giù",
  markerFaceCamera = "Rivolto alla telecamera",
  markerRotate = "Ruota",
  markerDrawOnEnts = "Disegna su entità",
  updatePosition = "Aggiorna posizione",
  setPosition = "Imposta posizione",

  -- v2: Interaction types
  interactionPoint = "Punto",
  interactionPointDesc = "Punto singolo ridimensionabile, con marcatore opzionale",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Zona multi-coordinate per creare un'area di interazione specifica",
  interactionVehicle = "Veicolo",
  interactionVehicleDesc = "Genera un modello di veicolo, ideale per metodi di interazione target o testo 3D",
  interactionObject = "Oggetto",
  interactionObjectDesc = "Genera un modello di oggetto, ideale per metodi di interazione target o testo 3D",
  interactionPed = "Ped",
  interactionPedDesc = "Genera un modello di ped con scenario opzionale, ideale per metodi di interazione target o testo 3D",

  -- v2: Import modal
  importLocationsTitle = "Importa posizioni",
  syncStockLabel = "Sincronizza stock",
  syncStockDescription = "Aggiungi veicoli allo stock di ogni concessionaria in base alle sue categorie",
  importSourceSelectorDesc = "Puoi importare un set di posizioni predefinite per una configurazione pronta, o importare le tue posizioni esistenti dalla configurazione se stai migrando da Dealerships v1.",
  importSourceSelectorSkipDesc = "Le posizioni già esistenti nel database verranno saltate; verranno importate solo le nuove posizioni.",
  successfullyImported = "Importato con successo",
  alreadyExist = "Esiste già",
  defaultLocations = "Posizioni predefinite",
  defaultLocationsDesc = "Importa posizioni concessionarie preconfigurate (PDM, Lusso, Barche, Aerei, Camion)",
  existingConfig = "Configurazione esistente",
  existingConfigDesc = "Importa posizioni dal tuo config.lua (per migrazione v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Vuoi aggiungere automaticamente veicoli allo stock di questa concessionaria in base alle categorie selezionate?",
  categorySyncEditDesc = "Hai cambiato le categorie per questa concessionaria. Vuoi aggiornare automaticamente lo stock veicoli?",
  addVehicles = "Aggiungi veicoli",
  removeVehicles = "Rimuovi veicoli",
  fromNewCategories = "dalle nuove categorie",
  fromSelectedCategories = "dalle categorie selezionate",
  fromRemovedCategories = "dalle categorie rimosse",
  categoriesAdded = "Categorie aggiunte:",
  categoriesRemoved = "Categorie rimosse:",
  skip = "Salta",
  syncStock = "Sincronizza stock",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Verifica disponibilità sorgente...",
  vehiclesAvailableToImport = "veicoli disponibili per l'importazione",
  includesDealershipIds = "include ID concessionarie",
  sourceUnavailable = "Sorgente non disponibile",
  noVehiclesAdminDescription = "Puoi aggiungere veicoli manualmente o importarli dal tuo framework.",
  appendBehaviour = "Aggiungi",
  overwriteBehaviour = "Sovrascrivi",
  appendDescription = "Aggiungi solo nuovi veicoli che non esistono già nel database",
  overwriteDescription = "Elimina tutti i dati veicoli esistenti e importa da capo",
  stockAssignmentMethod = "Metodo assegnazione stock",
  useDealershipIdsFromSource = "Usa ID concessionarie dalla sorgente",
  matchByVehicleCategory = "Abbina per categoria veicolo",
  byShopDescription = "I veicoli verranno assegnati alle concessionarie in base al campo 'shop' nei dati sorgente",
  byCategoryDescription = "I veicoli verranno assegnati alle concessionarie con categorie corrispondenti",
  overwriteWarning = "Attenzione: La sovrascrittura eliminerà tutti i veicoli esistenti, ordini, veicoli esposti e dati vendite.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "Tabella veicoli ESX",
  selectCategory = "Seleziona una categoria",

  -- v2: Management menu items
  vehiclesMenu = "Veicoli",
  displayVehiclesMenu = "Veicoli esposti",
  ordersMenu = "Ordini",
  salesMenu = "Vendite",
  bankAccountMenu = "Conto bancario",
  employeesMenu = "Dipendenti",
  couponsMenu = "Coupon",
  settingsMenu = "Impostazioni",
  noPermissionAccessManagement = "Non hai il permesso di accedere alle funzionalità di gestione.",
  backToAdmin = "Torna all'amministrazione",
  viewingAsAdmin = "VISUALIZZAZIONE COME ADMIN",

  -- v2: Coupons table
  code = "Codice",
  uses = "Utilizzi",
  perPlayer = "Per giocatore",
  never = "Mai",
  noCoupons = "Nessun coupon",
  noCouponsDescription = "I clienti possono inserire un coupon nella fase di acquisto del veicolo e risparmiare denaro.",

  -- v2: Coupon modal
  couponCodeLabel = "Codice coupon",
  couponCodePlaceholder = "es., ESTATE2024 o RISPARMIA10",
  couponCodeHelp = "Inserisci un codice personalizzato (max 25 caratteri, solo lettere, numeri e trattini) o clicca 'Genera'.",
  maxNumberOfUsesPlaceholder = "Numero massimo di utilizzi",
  maxUsesPerPlayerPlaceholder = "Utilizzi massimi per giocatore",
  vehicleRestrictionsPlaceholder = "Inserisci codici spawn separati da virgole (es., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Consenti su acquisti finanziati",
  createCoupon = "Crea coupon",
  updateCoupon = "Aggiorna coupon",

  -- v2: Coupon validation messages
  couponCodeRequired = "Il codice coupon è obbligatorio",
  couponCodeMaxLength = "Il codice deve avere 25 caratteri o meno",
  couponCodeInvalidChars = "Il codice può contenere solo lettere maiuscole, numeri e trattini",
  discountTypeRequired = "Il tipo di sconto è obbligatorio",
  discountValueRequired = "Il valore dello sconto è obbligatorio",
  discountValueMin = "Il valore dello sconto deve essere maggiore di 0",
  discountValueMaxPercent = "La percentuale non può superare 100",
  maxUsesRequired = "Utilizzi massimi obbligatori",
  maxUsesMin = "Deve essere almeno 1",
  perPlayerLimitRequired = "Limite per giocatore obbligatorio",
  expiryDateRequired = "Data di scadenza obbligatoria",
  vehicleRestrictionsRequired = "Restrizioni veicoli obbligatorie",
  categoryRestrictionsRequired = "Restrizioni categorie obbligatorie",
  selectAtLeastOneCategory = "Seleziona almeno una categoria",

  -- v2: Dashboard
  today = "Oggi",
  thisMonth = "Questo mese",
  allTime = "Sempre",
  recentSales = "Vendite recenti",
  noSalesYet = "Nessuna vendita ancora!",
  noSalesDescription = "Le vendite di veicoli appariranno qui dopo averne effettuata una.",
  past7Days = "Ultimi 7 giorni",
  past6Months = "Ultimi 6 mesi",
  numberOfSales = "Numero di vendite",
  noDataAvailableForPeriod = "Nessun dato disponibile per questo periodo",

  -- v2: Display vehicles
  displayVehiclesDescription = "I veicoli esposti sono modelli fissi dello showroom usati per mostrare il tuo inventario e attirare i clienti all'acquisto.",

  -- v2: Employees
  frameworkJobsEnabled = "Lavori framework abilitati",
  frameworkJobsDescription = "La gestione dei dipendenti è gestita tramite il sistema lavori del framework. I giocatori con il lavoro della concessionaria avranno automaticamente accesso in base al loro grado. Configura i permessi lavoro nelle impostazioni posizione del pannello admin.",
  joinedColumn = "Iscritto",
  youBadge = "Tu",

  -- v2: Orders
  noOrdersTitle = "Nessun ordine",
  noOrdersDescription = "Per effettuare un ordine, apri la scheda 'Veicoli' e clicca 'Ordina' sul veicolo che vuoi rifornire.",
  inProgress = "In corso",
  awaitingDelivery = "In attesa di consegna",
  orderedBy = "Ordinato da",
  viewDeliveryInfo = "Vedi info consegna",

  -- v2: Delivery
  startDeliveryMissionTitle = "Inizia missione di consegna",
  startDeliveryDescription = "Stai per iniziare una missione di consegna per questo ordine veicolo. Dovrai guidare fino al punto di ritiro, raccogliere il rimorchio cargo e consegnarlo alla concessionaria.",
  totalDistanceAndDriveTime = "Distanza totale e tempo di guida",
  roundTrip = "andata e ritorno",
  deliveryCompleteTitle = "Consegna completata",
  deliveryInProgressTitle = "Consegna in corso",
  deliveredAt = "Consegnato alle:",
  startedAt = "Iniziato alle:",
  deliveredBy = "Consegnato da:",
  beingDeliveredBy = "In consegna da:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Nessun ordine disponibile per la consegna. Gli ordini devono essere pronti e non già in una consegna attiva.",
  confirmDeliveryTitle = "Conferma consegna",
  configureDeliveryTitle = "Configura consegna",
  trailerCapacityExceeded = "Capacità rimorchio superata! Hai selezionato %{usedSlots} slot ma il massimo è %{maxSlots} slot.",
  smallVehiclesSlotInfo = "Ricorda: i veicoli piccoli usano 1 slot, i veicoli medi usano 1.5 slot.",
  fetchingRoute = "Recupero...",
  getRouteButton = "Ottieni percorso",
  selectTrailerType = "Seleziona tipo rimorchio",
  carTrailerLabel = "Bisarca",
  smallMedium = "(Piccolo/Medio)",
  containerLabel = "Container",
  large = "(Grande)",
  carTrailerDescription = "La bisarca ha 2 file. Ogni fila può contenere 3 piccoli (1 slot ciascuno) o 2 medi (1.5 slot ciascuno). Massimo 6 slot totali.",
  containerDescription = "Il rimorchio container trasporta 1 veicolo grande",
  selectOrdersTitle = "Seleziona ordini",
  slots = "slot",
  noOrdersForTrailerType = "Nessun ordine disponibile per questo tipo di rimorchio.",
  qty = "Qtà:",
  inTransit = "in transito",
  totalVehicles = "Veicoli totali:",
  estimatedTime = "Tempo stimato:",
  unknown = "Sconosciuto",

  -- v2: Sales
  salesEmptyDescription = "Le vendite di veicoli appariranno qui dopo averne effettuata una.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Ordine effettuato!",
  orderPlacedTruckingDescription = "Il tuo ordine è pronto per il ritiro. Vai alla pagina ordini per completarlo.",
  orderPlacedTimedDescription = "Il tuo ordine sarà consegnato in %{value} minuti.",
  goToOrders = "Vai agli ordini",
  noStockAvailableDescription = "Non c'è stock disponibile per questo veicolo. Il limite stock globale è stato raggiunto.",
  stockUpdatedDescription = "La quantità stock è stata aggiornata con successo.",

  -- v2: Direct sales tablet
  activeTestDrives = "Test drive attivi",
  tracking = "Tracciamento",
  track = "Traccia",
  endButton = "Termina",
  endTestDriveTitle = "Termina test drive",
  endTestDriveConfirmation = "Sei sicuro di voler terminare questo test drive? Il veicolo verrà eliminato e gli occupanti del veicolo non verranno teletrasportati alla concessionaria.",
  vehicleLocationOnMap = "La posizione del veicolo è stata segnata sulla tua mappa.",
  sell = "Vendi",
  couponCodeOptional = "Codice coupon (Opzionale)",
  pleaseEnterCouponCode = "Inserisci un codice coupon",
  invalidCouponCode = "Codice coupon non valido",
  failedToValidateCoupon = "Impossibile validare il coupon",
  apply = "Applica",
  applying = "Applicazione...",
  allStock = "Tutto lo stock",
  inStockFilter = "Disponibile",
  outOfStockFilter = "Esaurito",
  noResultsFound = "Nessun risultato trovato",
  noResults = "Nessun risultato",
  noVehiclesMatchSearch = "Nessun veicolo corrisponde alla tua ricerca",
  noVehiclesMatchFilters = "Nessun veicolo corrisponde ai tuoi filtri attuali",
  noItemsMatchSearch = "Nessun articolo corrisponde alla tua ricerca",
  noItemsMatchFilters = "Nessun articolo corrisponde ai tuoi filtri attuali",
  selectColour = "Seleziona colore",
  refreshNearbyPlayers = "Aggiorna giocatori vicini",
  you = "Tu",
  items = "articoli",
  waitingForCustomerToRespond = "In attesa della risposta del cliente...",
  vehicleSpawnedMessage = "Il veicolo è apparso nel punto sulla tua mappa - porta il cliente da esso.",
  customerDeclinedMessage = "Il cliente ha rifiutato la richiesta di acquisto.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "FIRMA QUI",
  acceptAndPurchase = "Accetta e acquista",
  couponApplied = "Coupon %{code} applicato! Risparmi %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Servono almeno 3 punti per completare la zona! (Attualmente %{value})",
  addPoint = "Aggiungi punto",
  removeLast = "Rimuovi ultimo",
  completeZone = "Completa zona",
  spawnPreview = "Anteprima spawn",
  up = "Su",
  down = "Giù",
  confirm = "Conferma",
  placePoint = "Posiziona punto",
  radius = "Raggio",

  -- v2: Blip labels
  soldVehicleLocation = "Posizione veicolo venduto",
  testDriveVehicleBlip = "Veicolo test drive",

  -- v2: Stock sync
  stockSyncResult = "Sincronizzazione stock: %{added} aggiunti, %{removed} rimossi",
  stockSyncAdded = "Sincronizzazione stock: %{value} veicoli aggiunti",
  importSuccessful = "Importazione riuscita! %{imported} veicoli importati (%{total} totali)",

  -- v2: Tooltip actions
  findOnMap = "Trova sulla mappa",
  adminPanel = "Pannello admin",

  -- v2: Common dropdown
  selectOne = "Seleziona uno",
}
