Locales['ja'] = {
  -- UI
  vehicle = "車両",
  vehicles = "車両",
  dealership = "ディーラー",
  dealerships = "ディーラー",
  vehiclesCount = "台の車両",
  dealersCount = "件のディーラー",
  accountBalance = "口座残高",
  bank = "銀行口座",
  cash = "現金",
  amount = "金額",
  societyFund = "社会資金",
  paymentSource = "支払元",
  purchase = "購入",
  personalPurchase = "個人購入",
  societyPurchase = "社会購入",
  purchaseType = "購入タイプ",
  deposit = "入金",
  withdraw = "出金",
  all = "すべて",
  yes = "はい",
  no = "いいえ",
  add = "追加",
  edit = "編集",
  id = "ID",
  created = "作成日",
  type = "タイプ",
  name = "名前",
  owner = "オーナー",
  bankBalance = "銀行残高",
  status = "ステータス",
  back = "戻る",
  previous = "前へ",
  next = "次へ",
  admin = "管理者",
  vehiclesAdmin = "車両管理者",
  dealershipsAdmin = "ディーラー管理者",
  search = "検索",
  noDealershipsFound = "ディーラーが見つかりません",
  noVehicles = "車両が見つかりません",
  page = "ページ",
  of = "の",
  every = "毎",
  show = "表示",
  active = "アクティブ",
  activeFinance = "アクティブな支払い",
  failed = "支払い失敗",
  removed = "削除されました",
  setOwner = "オーナー設定",
  manage = "管理",
  deleteData = "データ削除",
  deleteVehicle = "車両削除",
  delete = "削除",
  deleteConfirmation = "本当に削除してもよろしいですか？",
  deleteConfirmationDanger = "本当に削除してもよろしいですか？ この操作は元に戻せません。",
  setDealershipOwner = "ディーラーオーナー設定",
  overwriteDealerPrices = "ディーラー価格の上書き",
  nearbyPlayers = "近くのプレイヤー",
  noPlayersNearby = "近くにプレイヤーがいません",
  selectPlayer = "プレイヤーを選択",
  required = "必須",
  forExample = "例として",
  spawnCode = "スポーンコード(座標)",
  brand = "ブランド",
  model = "モデル",
  category = "カテゴリー",
  price = "価格",
  import = "インポート",
  importing = "インポート中",
  importBehaviour = "インポート動作",
  importVehicles = "車両をインポート",
  importFrom = "インポート元",
  dashboard = "ダッシュボード",
  displayVehicle = "表示車両",
  displayVehicles = "表示車両",
  orders = "注文",
  sales = "販売",
  vehiclesOnDisplay = "展示車両",
  employees = "従業員",
  settings = "設定",
  switchVehicle = "車両を変更",
  remove = "削除",
  noDisplayVehicles = "表示車両がありません",
  selectVehicle = "車両を選択",
  colour = "色",
  placeVehicle = "車両を配置",
  orderVehicle = "車両を注文",
  cancelOrder = "注文キャンセル",
  delivery = "配送",
  delivered = "配達済み",
  noOrders = "注文がありません",
  quantity = "数量",
  totalCost = "総費用",
  totalSales = "総販売",
  noSales = "販売がありません",
  paid = "支払い済み",
  owed = "未払い",
  dealershipName = "ディーラー名",
  save = "変更を保存",
  cancel = "キャンセル",
  notEnoughMoney = "お金が足りません",
  placeOrder = "注文を確定",
  purchaseCost = "購入費用",
  salePrice = "販売価格",
  inStock = "在庫あり",
  outOfStock = "在庫切れ",
  placeVehiclePrompt = "車両を配置するには、%{value} を押してください。その後、細かい調整が可能です。",
  remaining = "残り",
  prePurchaseRepoWarning = "支払いができない場合、車両は即座に差し押さえられます。",
  repossessionWarning = "最後の支払いが失敗しました - すぐに支払わないと車両が差し押さえられます。",
  recurringPayment = "定期的な支払い",
  remainingBalance = "残りの残高",
  remainingPayments = "残りの支払い回数",
  paymentTakenEvery = "毎回支払い",
  hours = "時間",
  seconds = "秒",
  nextPayment = "次の支払い",
  makePayment = "支払いを行う",
  vehicleRepossessed = "車両は差し押さえられました",
  payInFull = "全額支払う",
  earlyPaymentConfirmation = "本当に早期支払いを行いますか？",
  financedVehicles = "ファイナンス車両",
  noFinancedVehicles = "ファイナンス中の車両はありません",
  financeBreakdown = "ファイナンス詳細",
  initialPayment = "初回支払い",
  payments = "支払い回数",
  length = "期間",
  interest = "利息",
  totalPayable = "総支払額",
  leaveShowroom = "ショールームを出る",
  handling = "ハンドリング",
  topSpeed = "最高速度",
  power = "馬力",
  torque = "トルク",
  brake = "ブレーキ",
  financing = "ファイナンス中",
  financingAvailable = "ファイナンス利用可能",
  paymentsOf = "の支払い回数",
  clear = "クリア",
  testDrive = "試乗",
  allCategories = "すべてのカテゴリー",
  sortByName = "並び替え: 名前順",
  sortByAvailability = "並び替え: 在庫順",
  sortByCheapest = "並び替え: 安い順",
  sortByMostExpensive = "並び替え: 高い順",
  sortByNewest = "並び替え: 新しい順",
  purchaseVehicle = "車両を購入",
  purchaseFor = "購入金額",
  selectSociety = "社会を選択",
  financeOverPayments = "%{value}回の支払いでファイナンス",
  payToday = "今日支払う",
  financeThen = "その後",
  seeFullBreakdown = "詳細を見る",
  testDriveExit = "試乗を終了するには、車両から降りることができます。",

  -- NOTIFICATIONS
  purchaseSuccess = "購入おめでとうございます！",
  depositSuccess = "入金成功",
  withdrawSuccess = "出金成功",
  errorNotEnoughMoney = "お金が足りません",
  errorVehicleOutOfStock = "この車両は在庫切れです",
  errorCannotAffordVehicle = "この車両は購入できません",
  vehicleFinancePaymentMade = "車両のファイナンス支払いが完了しました %{value}",
  vehicleFinancePaidOff = "おめでとうございます、車両 %{value} のファイナンスが完済され、所有権が移転されました",
  vehicleFinancePaymentFailed = "車両のファイナンス支払いが失敗しました %{value}",
  vehicleFinanceRepossessedSoon = "車両 %{value} の支払いが未済です。今すぐ支払わないと差し押さえされます。",
  vehicleFinanceRepossessed = "支払い失敗により、車両 %{value} は差し押さえられました。",
  dealershipNotEnoughFunds = "ディーラーに十分な資金がありません",
  dealershipVehiclesOrdered = "車両が正常に注文されました",
  dealershipOrderCancelled = "注文が正常にキャンセルされました",
  errorVehicleWithSpawnCodeExists = "このスポーンコードの車両は既に存在します",
  errorExitVehicle = "まず車両から降りてください",

  -- NEW v1.1
  purchaseRequest = "購入リクエスト",
  sendRequest = "リクエスト送信",
  dealer = "ディーラー",
  financed = "ファイナンス済み",
  signHere = "ここにサイン",
  signFirstError = "最初にサインしてください",
  denyRequest = "リクエスト拒否",
  playerTooManyFinancedVehicles = "プレイヤーはファイナンス中の車両が多すぎます",
  employeePermissionsError = "必要な従業員権限がありません",
  managerRole = "マネージャー",
  supervisorRole = "スーパーバイザー",
  salesRole = "営業",
  ownerRole = "オーナー",
  employmentRequest = "雇用リクエスト",
  accept = "承認",
  jobOfferDescription = "\"%{value}\" ディーラーでの職を提供されています。受け入れますか？",
  pending = "保留中",
  employeeHiredMsg = "ディーラーの雇用リクエストが承認されました！",
  employeeRejectedMsg = "ディーラーの雇用リクエストが拒否されました",
  sellVehicle = "車両を売る",
  vehicleTerms = "車両契約条件",
  financePayments = "ファイナンス支払い",
  commission = "手数料",
  role = "役職",
  firedNotification = "\"%{value}\" ディーラーから解雇されました",
  dealershipTooFarAway = "ディーラーが遠すぎます",
  restoreDisplayVehicles = "ショールームを復元",
  customer = "顧客",
  lessThanAMin = "1分未満",
  mins = "分",
  notInVehicle = "車両に乗っていません",
  notYourVehicleError = "この車両はあなたのものではありません",
  vehicleFinancedError = "この車両はファイナンス支払いが残っているため、販売できません",
  dealershipDoesntSellVehicle = "このディーラーはこの車両を購入できません",
  dealershipWantsYourVehicle = "おめでとうございます！ このディーラーはあなたの車両を購入したいと言っています。",
  purchasePrice = "提示価格: ",
  
  spawnCodeInvalid = "スポーンコード無効",
  salesRep = "営業担当",
  directSaleAccepted = "直販リクエストが承認されました！ 手数料が支払われました。",
  directSaleRejected = "直販リクエストが拒否されました",

  displayVehicleOutsideZone = "展示車両はディーラーゾーン内に配置する必要があります",
  serverAdmin = "サーバー管理者",
  selfService = "セルフサービス",
  owned = "所有済み",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "無効な支払い方法",
  paymentMethodNoFinance = "この支払い方法はファイナンスに対応していません",
  couldNotGeneratePlate = "ナンバープレートを生成できませんでした",
  invalidCoupon = "無効なクーポン: %{value}",
  tooManyFinancedVehicles = "ファイナンス中の車両が多すぎます",
  couldNotSpawnVehicle = "車両を生成できませんでした",

  -- v2: Permissions
  insufficientPermissions = "権限が不足しています",

  -- v2: Coupons
  couponCodeAlreadyExists = "このクーポンコードは既に存在します",
  failedToCreateCoupon = "クーポンの作成に失敗しました",
  couponCreatedSuccessfully = "クーポンが正常に作成されました",
  couponNotFound = "クーポンが見つかりません",
  couponUpdatedSuccessfully = "クーポンが正常に更新されました",
  failedToDeleteCoupon = "クーポンの削除に失敗しました",
  couponDeletedSuccessfully = "クーポンが正常に削除されました",
  editCoupon = "クーポンを編集",
  addCoupon = "クーポンを追加",
  couponCode = "クーポンコード",
  generating = "生成中...",
  generate = "生成",
  discountType = "割引タイプ",
  percentageOff = "パーセント割引",
  amountOff = "金額割引",
  discountValue = "割引値",
  unlimitedTotalUses = "総使用回数無制限",
  unlimitedUsesPerPlayer = "プレイヤーあたり無制限",
  setExpiryDate = "有効期限を設定",
  restrictToSpecificVehicles = "特定の車両に制限",
  restrictToSpecificCategories = "特定のカテゴリに制限",
  allowUseWithFinance = "ファイナンスでの使用を許可",
  deleteCoupon = "クーポンを削除",
  inactive = "非アクティブ",
  expired = "期限切れ",
  maxUses = "最大使用回数",
  coupons = "クーポン",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "サーバー管理者のみが自己雇用できます",
  playerNotFound = "プレイヤーが見つかりません",
  failedToHireEmployee = "従業員の雇用に失敗しました",
  failedToFireEmployee = "従業員の解雇に失敗しました",
  failedToUpdateEmployeeRole = "従業員の役職更新に失敗しました",
  hireEmployee = "従業員を雇用",
  fireEmployee = "従業員を解雇",
  editRole = "役職を編集",
  fire = "解雇",
  changeRole = "役職を変更",
  updateRole = "役職を更新",

  -- v2: Test drives
  maxTestDrivesReached = "このディーラーはアクティブな試乗の最大数に達しました",
  testDriveNotEnabled = "このディーラーでは試乗が有効になっていません",
  noTestDriveSpawnCoords = "このディーラーには試乗用のスポーン座標が設定されていません",
  couldNotSpawnTestDriveVehicle = "試乗車両を生成できませんでした",
  couldNotGetPlateFromServer = "サーバーからナンバープレートを取得できませんでした",
  couldNotRegisterTestDriveVehicle = "試乗車両を登録できませんでした",
  testDriveEndedByEmployee = "試乗は他の従業員によって終了されました",
  trackingVehicleLocation = "車両位置を追跡中...",
  directSaleCancelled = "販売リクエストは販売員によってキャンセルされました",
  testDriveKeysReceived = "試乗車両の鍵を受け取りました",
  testDriveEndedCustomer = "試乗が終了しました",
  starting = "開始中...",
  startTestDrive = "試乗を開始",
  spawningTestDriveVehicle = "試乗車両を生成中...",
  testDriveReady = "試乗準備完了",
  testDriveWalkToVehicle = "試乗車両がマップ上のマーク位置に生成されました。お客様を車両まで案内してください。鍵を渡した後、お客様が戻ってきたら手動で試乗を終了する必要があります。",
  givingKeys = "鍵を渡しています...",
  continueAndGiveKeys = "続行して鍵を渡す",
  endTestDrive = "試乗を終了",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "この車両の在庫がありません",
  globalStockLimitExceeded = "%{value}台のみ利用可能",
  orderNotFoundOrFulfilled = "注文が見つからないか、既に処理済みです",
  priceBelowMinimum = "価格は%{value}未満にできません",
  priceAboveMaximum = "価格は%{value}を超えることができません",
  stockUpdated = "在庫が更新されました",
  changesSaved = "変更が保存されました",
  noStockAvailable = "在庫がありません",
  orderPlaced = "注文が完了しました",
  remainingInStock = "グローバル在庫残り",
  exceedsStockLimit = "在庫制限を超過",
  setStockQty = "在庫数を設定",
  invalidStockValue = "有効な在庫値を入力してください",
  errorSettingStock = "在庫設定エラー",
  stockQuantity = "在庫数量",
  currentStock = "現在の在庫",
  priceLimitsEnabled = "価格制限を有効化",
  priceLimitsDescription = "有効にすると、ディーラー管理者は指定された範囲内でのみ価格を設定できます。",
  minPrice = "最低価格",
  maxPrice = "最高価格",
  optional = "オプション",
  unlimitedStock = "在庫無制限",
  globalStockLimit = "グローバル在庫制限",
  globalStockLimitDescription = "すべてのディーラーで注文できる最大ユニット数を設定します。",
  currentlyOrdered = "現在注文済み",
  priceRange = "価格範囲",
  noMinimum = "最低なし",
  noMaximum = "最高なし",
  vehicleStock = "車両在庫",

  -- v2: Sales
  allSales = "全売上",
  paidInFull = "全額支払い",
  salesVolume = "販売量",
  pastMonth = "先月",
  pastYear = "昨年",

  -- v2: Management misc
  exploitAttemptDetected = "スクリプトを悪用しようとするのをやめてください",
  dealershipNoJobConfigured = "ディーラーには職業が設定されていません",
  modelDoesNotMatchDb = "車両モデルがデータベースと一致しません",
  importFailed = "インポート失敗: %{value}",
  notInDealershipZone = "このコマンドを使用するにはディーラー内にいる必要があります",
  notAnEmployee = "あなたはこのディーラーの従業員ではありません。",
  failedToPrepareDelivery = "配送準備に失敗しました",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "車両モデルが存在しません - 管理者に連絡してください",
  vehiclePlateInvalid = "この車両のナンバープレートが無効です（詳細はF8を押してください）",
  currentlyInRagdollState = "現在ラグドール状態です",
  vehicleDoesNotExistContactAdmin = "車両が存在しません。管理者に連絡してください！",
  vehicleSecurityBreachDetected = "車両セキュリティ違反を検出しました",

  -- v2: Admin vehicles
  allVehicles = "全車両",
  unassignedVehicles = "ディーラー未割り当て",
  searchDealerships = "ディーラーを検索...",

  -- v2: Trucking mission
  truckingGetInTruck = "マークされた場所のトラックに乗って配送を開始してください",
  truckingDriveToDelivery = "配送場所まで運転",
  truckingCompleteDelivery = "配送を完了",
  truckingDeliveryComplete = "配送完了: 配送が正常に完了しました！",
  truckingDeliveryFailed = "配送失敗: 配送中に問題が発生しました",
  truckingDriveToPickup = "ピックアップポイントまで運転してトレーラーを取得",
  truckingMissionFailedSpawnCargo = "ミッション失敗: カーゴトレーラーを生成できませんでした",
  truckingMissionFailedFindCargo = "ミッション失敗: 生成されたカーゴが見つかりませんでした",
  truckingVehiclesLoaded = "%{count}台の車両を積載",
  truckingWrongTrailer = "間違ったトレーラーです！正しいミッショントレーラーを接続してください。",
  truckingTrailerAttached = "トレーラー接続完了 - 続行準備完了",
  truckingDriveToPickupLocation = "ピックアップポイントまで運転",
  truckingWaitingForVehicles = "車両の積載を待っています...",
  truckingDriveUnderTrailer = "トレーラーの下に入って接続",
  truckingGetInTruckContinue = "トラックに乗って続行",
  truckingMissionStarted = "輸送ミッション開始: ピックアップポイント - %{location}",
  truckingMissionCancelled = "ミッションキャンセル: 輸送ミッションをキャンセルしました",
  truckingNoActiveMission = "キャンセルする輸送ミッションがありません",
  deliveryNotPrepared = "配送準備ができていません - もう一度お試しください",
  deliveryConfigMismatch = "配送設定が一致しません",
  deliveryPreparationExpired = "配送準備が期限切れです - もう一度お試しください",
  noTruckingVehicleCoordinates = "輸送車両の座標が設定されていません",
  pickupLocationUnavailable = "ピックアップポイントが利用できなくなりました - もう一度お試しください",
  failedToSpawnTruck = "トラックの生成に失敗しました",
  clientFailedToStartMission = "クライアントがミッションを開始できませんでした",

  -- v2: Trucking UI/Keys
  keyDismiss = "閉じる",
  keyDeliverCargo = "カーゴを配送",
  keyContinueToDelivery = "配送を続行",
  startDeliveryMission = "配送ミッションを開始",
  orderDetails = "注文詳細",
  pickupLocation = "ピックアップポイント",
  deliveryStatus = "配送状況",
  selectOrders = "注文を選択",
  carTrailer = "カーキャリア",
  container = "コンテナ",
  deliveryRoute = "配送ルート",
  startDelivery = "配送を開始",

  -- v2: Direct sales UI
  waitingForCustomer = "お客様を待っています",
  cancelRequest = "リクエストをキャンセル",
  saleComplete = "販売完了！",
  done = "完了",
  saleDeclined = "販売拒否",
  close = "閉じる",

  -- v2: Display vehicle placement
  movement = "移動",
  rotate = "回転",
  forward = "前進",
  backward = "後退",
  left = "左",
  right = "右",
  rotateLeft = "左に回転",
  rotateRight = "右に回転",

  -- v2: Showroom misc
  originalPrice = "元の価格",
  discount = "割引",
  createInteraction = "インタラクションを作成",
  viewAll = "すべて表示",
  fetchingPlayers = "プレイヤーを取得中",
  refresh = "更新",
  loadingPlayers = "プレイヤーを読み込み中...",
  failedToLoadPlayers = "プレイヤーの読み込みに失敗しました",
  selectAPlayer = "プレイヤーを選択",
  failedToLoadPlayersRetry = "プレイヤーの読み込みに失敗しました。「更新」をクリックして再試行してください。",

  -- v2: Self-service & Categories
  selfServiceDealership = "セルフサービスディーラー",
  categories = "カテゴリー",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "ロケーション",
  createNew = "新規作成",
  enable = "有効化",
  disable = "無効化",
  loading = "読み込み中...",
  errors = "エラー",
  update = "更新",
  create = "作成",

  -- v2: Dealership creation/editing
  createDealership = "ディーラーを作成",
  editDealership = "ディーラーを編集",
  essentials = "基本",
  advanced = "詳細",
  noDealershipLocations = "ディーラーロケーションがありません",
  noDealershipLocationsDesc = "新しいロケーションを追加するか、設定からインポート（v1から移行する場合）するか、デフォルトのロケーションを自動的に追加できます。",

  -- v2: Location sections
  dealershipZone = "ディーラーゾーン",
  showroomAndManagement = "ショールームと管理",
  openShowroom = "ショールームを開く",
  openManagement = "管理を開く",
  enableSellVehicle = "車両販売を有効化",
  percentageOfVehicleValue = "車両価値の%",
  enablePurchase = "購入を有効化",
  purchasedVehicleSpawn = "購入車両スポーン",
  enableTestDrive = "試乗を有効化",
  testDriveVehicleSpawn = "試乗車両スポーン",
  truckDelivery = "トラック配送",
  truckDeliveryVehicleSpawn = "配送車両スポーン",

  -- v2: Location advanced settings
  paymentMethods = "支払い方法",
  supportsFinancing = "(ファイナンス対応)",
  enableFinance = "ファイナンスを有効化",
  cameraPreset = "カメラ",
  preset = "プリセット",
  custom = "カスタム",
  vehiclePosition = "車両位置",
  zoomPositions = "ズーム位置（カンマ区切り）",
  zoomPositionsPlaceholder = "例：5,8,12,8",
  vehicleColour = "車両カラー",
  selectionType = "選択タイプ",
  noColourSelection = "カラー選択なし",
  rgbColourWheel = "RGBカラーホイール",
  listOfRgbColours = "RGBカラーリスト",
  listOfColourIds = "カラーIDリスト",
  accessControl = "アクセス制御",
  showroomJobWhitelist = "ショールーム職業ホワイトリスト",
  showroomGangWhitelist = "ショールームギャングホワイトリスト",
  societyPurchaseJobWhitelist = "組織購入職業ホワイトリスト",
  societyPurchaseGangWhitelist = "組織購入ギャングホワイトリスト",
  setInGame = "ゲーム内で設定",
  addNew = "新規追加",

  -- v2: Job/Gang whitelist editor
  job = "職業",
  gang = "ギャング",
  jobWhitelist = "職業ホワイトリスト",
  gangWhitelist = "ギャングホワイトリスト",
  addJob = "職業を追加",
  addGang = "ギャングを追加",
  editJob = "職業を編集",
  editGang = "ギャングを編集",
  manageJobs = "職業を管理",
  manageGangs = "ギャングを管理",
  jobName = "職業名",
  gangName = "ギャング名",
  selectGrades = "ランクを選択",
  selectAll = "すべて選択",
  deselectAll = "すべて解除",
  invalidJobName = "無効な職業名です。フレームワークの設定を確認してください。",
  invalidGangName = "無効なギャング名です。フレームワークの設定を確認してください。",
  grades = "ランク",
  noJobsConfigured = "設定された職業がありません",
  noGangsConfigured = "設定されたギャングがありません",
  click = "クリック",
  toGetStarted = "して開始します。",
  more = "その他",
  jobPlaceholder = "例：cardealer",
  jobOptionalDescription = "オプションでディーラーの役割をフレームワークの職業に紐付けます。従業員が雇用/解雇されると、フレームワークの職業も更新されます。",
  jobRankPermissions = "職業ランク権限",
  roleToJobRankMapping = "役割から職業ランクへのマッピング",
  addPerm = "権限を追加",

  -- v2: Colour selector
  searchColours = "カラーを検索...",
  noColoursFound = "カラーが見つかりません",

  -- v2: Interactions creator
  noInteractions = "インタラクションがありません",
  highlightInteractions = "インタラクションをハイライト",
  explorationMode = "探索モード",
  pressEsc = "ESCを押す",
  toWalkAround = "と歩き回れます",
  toReturnToUI = "とUIに戻ります",
  points = "ポイント",
  location = "ロケーション",
  manageLocations = "ロケーションを管理",

  -- v2: Interaction modal
  interactionType = "タイプ",
  nicknameOptional = "ニックネーム（オプション）",
  invalidModel = "無効なモデル",
  failedToValidateModel = "モデルの検証に失敗しました",
  pedScenario = "Pedシナリオ",
  coords = "座標",
  size = "サイズ",
  blip = "ブリップ",
  enableBlip = "ブリップを有効化",
  blipIconId = "ブリップアイコンID",
  blipColourId = "ブリップカラーID",
  blipSize = "ブリップサイズ",
  marker = "マーカー",
  enableMarker = "マーカーを有効化",
  markerStyleId = "マーカースタイルID",
  markerSize = "マーカーサイズ",
  markerColor = "マーカーカラー",
  markerBobUpAndDown = "上下に浮遊",
  markerFaceCamera = "カメラに向く",
  markerRotate = "回転",
  markerDrawOnEnts = "エンティティに描画",
  updatePosition = "位置を更新",
  setPosition = "位置を設定",

  -- v2: Interaction types
  interactionPoint = "ポイント",
  interactionPointDesc = "オプションのマーカー付きの単一のリサイズ可能なポイント",
  interactionPolyzone = "ポリゾーン",
  interactionPolyzoneDesc = "特定のインタラクションエリアを作成するための複数座標ゾーン",
  interactionVehicle = "車両",
  interactionVehicleDesc = "車両モデルをスポーン、ターゲットまたは3DテキストUIインタラクション方法に最適",
  interactionObject = "オブジェクト",
  interactionObjectDesc = "オブジェクトモデルをスポーン、ターゲットまたは3DテキストUIインタラクション方法に最適",
  interactionPed = "Ped",
  interactionPedDesc = "オプションのシナリオ付きのPedモデルをスポーン、ターゲットまたは3DテキストUIインタラクション方法に最適",

  -- v2: Import modal
  importLocationsTitle = "ロケーションをインポート",
  syncStockLabel = "在庫を同期",
  syncStockDescription = "各ディーラーのカテゴリーに基づいて在庫に車両を追加",
  importSourceSelectorDesc = "すぐに使えるデフォルトロケーションをインポートするか、Dealerships v1から移行する場合は既存のロケーションを設定からインポートできます。",
  importSourceSelectorSkipDesc = "データベースに既に存在するロケーションはスキップされます。新しいロケーションのみがインポートされます。",
  successfullyImported = "正常にインポートされました",
  alreadyExist = "既に存在します",
  defaultLocations = "デフォルトロケーション",
  defaultLocationsDesc = "事前設定されたディーラーロケーションをインポート（PDM、ラグジュアリー、ボート、エア、トラック）",
  existingConfig = "既存の設定",
  existingConfigDesc = "config.luaからロケーションをインポート（v1移行用）",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "選択したカテゴリーに基づいて、このディーラーの在庫に自動的に車両を追加しますか？",
  categorySyncEditDesc = "このディーラーのカテゴリーを変更しました。車両在庫を自動的に更新しますか？",
  addVehicles = "車両を追加",
  removeVehicles = "車両を削除",
  fromNewCategories = "新しいカテゴリーから",
  fromSelectedCategories = "選択したカテゴリーから",
  fromRemovedCategories = "削除したカテゴリーから",
  categoriesAdded = "追加されたカテゴリー：",
  categoriesRemoved = "削除されたカテゴリー：",
  skip = "スキップ",
  syncStock = "在庫を同期",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "ソースの可用性を確認中...",
  vehiclesAvailableToImport = "台のインポート可能な車両",
  includesDealershipIds = "ディーラーIDを含む",
  sourceUnavailable = "ソースが利用できません",
  noVehiclesAdminDescription = "車両を手動で追加するか、フレームワークからインポートできます。",
  appendBehaviour = "追加",
  overwriteBehaviour = "上書き",
  appendDescription = "データベースに存在しない新しい車両のみを追加",
  overwriteDescription = "既存のすべての車両データを削除して新規インポート",
  stockAssignmentMethod = "在庫割り当て方法",
  useDealershipIdsFromSource = "ソースからディーラーIDを使用",
  matchByVehicleCategory = "車両カテゴリーでマッチ",
  byShopDescription = "車両はソースデータの「shop」フィールドに基づいてディーラーに割り当てられます",
  byCategoryDescription = "車両は一致するカテゴリーを持つディーラーに割り当てられます",
  overwriteWarning = "警告：上書きすると、既存のすべての車両、注文、展示車両、販売データが削除されます。",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX車両テーブル",
  selectCategory = "カテゴリーを選択",

  -- v2: Management menu items
  vehiclesMenu = "車両",
  displayVehiclesMenu = "展示車両",
  ordersMenu = "注文",
  salesMenu = "販売",
  bankAccountMenu = "銀行口座",
  employeesMenu = "従業員",
  couponsMenu = "クーポン",
  settingsMenu = "設定",
  noPermissionAccessManagement = "管理機能にアクセスする権限がありません。",
  backToAdmin = "管理に戻る",
  viewingAsAdmin = "管理者として表示中",

  -- v2: Coupons table
  code = "コード",
  uses = "使用回数",
  perPlayer = "プレイヤーごと",
  never = "なし",
  noCoupons = "クーポンがありません",
  noCouponsDescription = "顧客は車両購入時にクーポンを入力してお金を節約できます。",

  -- v2: Coupon modal
  couponCodeLabel = "クーポンコード",
  couponCodePlaceholder = "例：SUMMER2024またはSAVE10",
  couponCodeHelp = "カスタムコードを入力（最大25文字、文字、数字、ハイフンのみ）するか、「生成」をクリックしてください。",
  maxNumberOfUsesPlaceholder = "最大使用回数",
  maxUsesPerPlayerPlaceholder = "プレイヤーごとの最大使用回数",
  vehicleRestrictionsPlaceholder = "スポーンコードをカンマで区切って入力（例：adder, t20, zentorno）",
  allowOnFinancedPurchases = "ファイナンス購入で許可",
  createCoupon = "クーポンを作成",
  updateCoupon = "クーポンを更新",

  -- v2: Coupon validation messages
  couponCodeRequired = "クーポンコードは必須です",
  couponCodeMaxLength = "コードは25文字以下にしてください",
  couponCodeInvalidChars = "コードには大文字、数字、ハイフンのみ使用できます",
  discountTypeRequired = "割引タイプは必須です",
  discountValueRequired = "割引値は必須です",
  discountValueMin = "割引値は0より大きくする必要があります",
  discountValueMaxPercent = "パーセンテージは100を超えることはできません",
  maxUsesRequired = "最大使用回数は必須です",
  maxUsesMin = "少なくとも1以上にしてください",
  perPlayerLimitRequired = "プレイヤーごとの制限は必須です",
  expiryDateRequired = "有効期限は必須です",
  vehicleRestrictionsRequired = "車両制限は必須です",
  categoryRestrictionsRequired = "カテゴリー制限は必須です",
  selectAtLeastOneCategory = "少なくとも1つのカテゴリーを選択してください",

  -- v2: Dashboard
  today = "今日",
  thisMonth = "今月",
  allTime = "全期間",
  recentSales = "最近の販売",
  noSalesYet = "まだ販売がありません！",
  noSalesDescription = "車両の販売はここに表示されます。",
  past7Days = "過去7日間",
  past6Months = "過去6ヶ月",
  numberOfSales = "販売数",
  noDataAvailableForPeriod = "この期間のデータはありません",

  -- v2: Display vehicles
  displayVehiclesDescription = "展示車両は、在庫を紹介し、顧客の購入を促すために使用される固定のショールームモデルです。",

  -- v2: Employees
  frameworkJobsEnabled = "フレームワーク職業が有効",
  frameworkJobsDescription = "従業員管理はフレームワークの職業システムで処理されます。ディーラーの職業を持つプレイヤーは、ランクに基づいて自動的にアクセスできます。管理パネルのロケーション設定で職業権限を設定してください。",
  joinedColumn = "参加日",
  youBadge = "あなた",

  -- v2: Orders
  noOrdersTitle = "注文がありません",
  noOrdersDescription = "注文するには、「車両」タブを開き、在庫を補充したい車両の「注文」をクリックしてください。",
  inProgress = "進行中",
  awaitingDelivery = "配送待ち",
  orderedBy = "注文者",
  viewDeliveryInfo = "配送情報を表示",

  -- v2: Delivery
  startDeliveryMissionTitle = "配送ミッションを開始",
  startDeliveryDescription = "この車両注文の配送ミッションを開始します。ピックアップポイントまで運転し、カーゴトレーラーを受け取り、ディーラーに届ける必要があります。",
  totalDistanceAndDriveTime = "総距離と運転時間",
  roundTrip = "往復",
  deliveryCompleteTitle = "配送完了",
  deliveryInProgressTitle = "配送中",
  deliveredAt = "配達時刻：",
  startedAt = "開始時刻：",
  deliveredBy = "配達者：",
  beingDeliveredBy = "配達中：",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "配送可能な注文がありません。注文は準備完了で、アクティブな配送中でない必要があります。",
  confirmDeliveryTitle = "配送を確認",
  configureDeliveryTitle = "配送を設定",
  trailerCapacityExceeded = "トレーラー容量を超えました！%{usedSlots}スロットを選択しましたが、最大は%{maxSlots}スロットです。",
  smallVehiclesSlotInfo = "注意：小型車両は1スロット、中型車両は1.5スロットを使用します。",
  fetchingRoute = "取得中...",
  getRouteButton = "ルートを取得",
  selectTrailerType = "トレーラータイプを選択",
  carTrailerLabel = "カーキャリア",
  smallMedium = "（小型/中型）",
  containerLabel = "コンテナ",
  large = "（大型）",
  carTrailerDescription = "カーキャリアには2列あります。各列には小型3台（各1スロット）または中型2台（各1.5スロット）が収まります。最大6スロット。",
  containerDescription = "コンテナトレーラーは大型車両1台を運搬します",
  selectOrdersTitle = "注文を選択",
  slots = "スロット",
  noOrdersForTrailerType = "このトレーラータイプに対応する注文がありません。",
  qty = "数量：",
  inTransit = "輸送中",
  totalVehicles = "車両合計：",
  estimatedTime = "推定時間：",
  unknown = "不明",

  -- v2: Sales
  salesEmptyDescription = "車両の販売はここに表示されます。",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "注文完了！",
  orderPlacedTruckingDescription = "注文の準備ができました。注文ページに移動して完了してください。",
  orderPlacedTimedDescription = "注文は%{value}分で配達されます。",
  goToOrders = "注文へ",
  noStockAvailableDescription = "この車両の在庫がありません。グローバル在庫制限に達しました。",
  stockUpdatedDescription = "在庫数量が正常に更新されました。",

  -- v2: Direct sales tablet
  activeTestDrives = "アクティブな試乗",
  tracking = "追跡",
  track = "追跡する",
  endButton = "終了",
  endTestDriveTitle = "試乗を終了",
  endTestDriveConfirmation = "この試乗を終了してもよろしいですか？車両は削除され、乗客はディーラーにテレポートされません。",
  vehicleLocationOnMap = "車両の位置がマップに表示されました。",
  sell = "販売",
  couponCodeOptional = "クーポンコード（オプション）",
  pleaseEnterCouponCode = "クーポンコードを入力してください",
  invalidCouponCode = "無効なクーポンコード",
  failedToValidateCoupon = "クーポンの検証に失敗しました",
  apply = "適用",
  applying = "適用中...",
  allStock = "全在庫",
  inStockFilter = "在庫あり",
  outOfStockFilter = "在庫切れ",
  noResultsFound = "結果が見つかりません",
  noResults = "結果なし",
  noVehiclesMatchSearch = "検索に一致する車両がありません",
  noVehiclesMatchFilters = "現在のフィルターに一致する車両がありません",
  noItemsMatchSearch = "検索に一致するアイテムがありません",
  noItemsMatchFilters = "現在のフィルターに一致するアイテムがありません",
  selectColour = "色を選択",
  refreshNearbyPlayers = "近くのプレイヤーを更新",
  you = "あなた",
  items = "アイテム",
  waitingForCustomerToRespond = "顧客の応答を待っています...",
  vehicleSpawnedMessage = "車両がマップ上のポイントにスポーンしました - 顧客をそこに連れて行ってください。",
  customerDeclinedMessage = "顧客が購入リクエストを拒否しました。",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "ここに署名",
  acceptAndPurchase = "承認して購入",
  couponApplied = "クーポン%{code}が適用されました！%{discount}節約",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "ゾーンを完成させるには少なくとも3ポイントが必要です！（現在%{value}）",
  addPoint = "ポイントを追加",
  removeLast = "最後を削除",
  completeZone = "ゾーンを完成",
  spawnPreview = "スポーンプレビュー",
  up = "上",
  down = "下",
  confirm = "確認",
  placePoint = "ポイントを配置",
  radius = "半径",

  -- v2: Blip labels
  soldVehicleLocation = "販売車両の位置",
  testDriveVehicleBlip = "試乗車両",

  -- v2: Stock sync
  stockSyncResult = "在庫同期：%{added}追加、%{removed}削除",
  stockSyncAdded = "在庫同期：%{value}台の車両を追加",
  importSuccessful = "インポート成功！%{imported}台の車両をインポート（合計%{total}）",

  -- v2: Tooltip actions
  findOnMap = "マップで検索",
  adminPanel = "管理パネル",

  -- v2: Common dropdown
  selectOne = "1つ選択",
}
