Locales = Locales or {}

Locales['lt'] = {
  -- UI
  vehicle = "Tr.priemonė",
  vehicles = "Tr.priemonės",
  dealership = "Salonas",
  dealerships = "Salonas",
  vehiclesCount = "Tr.priemonė(s)",
  dealersCount = "Tr.priemonių parduotuvė(s)",
  accountBalance = "Paskyros Balansas",
  bank = "Banko Sąskaita",
  cash = "Grynieji",
  amount = "Suma",
  societyFund = "Bendrijos Fondas",
  paymentSource = "Pajamų Šaltinis",
  purchase = "Pirkti",
  personalPurchase = "Asmeninis Pirkimas",
  societyPurchase = "Bendrijos Pirkimas",
  purchaseType = "Pirkimo Tipas",
  deposit = "Įnešti",
  withdraw = "Išgryninti",
  all = "Visi",
  yes = "Taip",
  no = "Ne",
  add = "Pridėti",
  edit = "Keisti",
  id = "ID",
  created = "Sūkurtas",
  type = "Tipas",
  name = "Vardas",
  owner = "Savininkas",
  bankBalance = "Banko Likutis",
  status = "Statusas",
  back = "Atgal",
  previous = "Ankstesnis",
  next = "Kitas",
  admin = "Admin",
  vehiclesAdmin = "Tr.priemonės admin",
  dealershipsAdmin = "Tr.priemonių parduotuvės admin",
  search = "Ieškoti",
  noDealershipsFound = "Tr.priemonių parduotuvės nerasta",
  noVehicles = "Tr.priemonės nerastos",
  page = "Puslapis",
  of = "Iš",
  every = "Visi",
  show = "Rodyti",
  active = "Aktyvus",
  activeFinance = "Jūsų aktyvus finansas",
  failed = "Pavedimas nepavyko",
  removed = "Pašalintas",
  setOwner = "Paskirti savininką",
  manage = "Tvarkyti",
  deleteData = "Ištrinti duomenis",
  deleteVehicle = "Ištrinti tr.priemonę",
  delete = "Ištrinti",
  deleteConfirmation = "Ar esate įsitikinęs?",
  deleteConfirmationDanger = "Ar esate įsitikinęs? šio veiksmo atšaukti negalėsite.",
  setDealershipOwner = "Paskirti tr.priemonių parduotuvės savininką",
  overwriteDealerPrices = "Pakeisti tr.priemonių parduotuvės kainas",
  nearbyPlayers = "Šalia esantys asmenys",
  noPlayersNearby = "Šalia nieko nėra",
  selectPlayer = "Pasirinkti Asmenį",
  required = "Reikiamas",
  forExample = "Pavyzdžiui",
  spawnCode = "Kodas",
  brand = "Markė",
  model = "Modelis",
  category = "Kategorija",
  price = "Kaina",
  import = "Įkelti",
  importing = "Įkeliama",
  importBehaviour = "Import Behaviour",
  importVehicles = "Įkelti tr.priemones",
  importFrom = "Įkelt iš",
  dashboard = "Prietaisų Skydelis",
  displayVehicle = "Rodyti tr.priemonę",
  displayVehicles = "Rodyti tr.priemones",
  orders = "Užsakymai",
  sales = "Pardavimai",
  vehiclesOnDisplay = "Eksponuojamos tr.priemonės",
  employees = "Darbuotojai",
  settings = "Nustatymai",
  switchVehicle = "Pakeisti tr.priemonę",
  remove = "Pašalinti",
  noDisplayVehicles = "Nėra eksponuojamų tr.priemonių",
  selectVehicle = "Pasirinkti tr. priemonę",
  colour = "Spalva",
  placeVehicle = "Pastatyti tr.priemonę",
  orderVehicle = "Užsakyti tr.priemonę",
  cancelOrder = "Atšaukti Užsakymą",
  delivery = "Pristatymas",
  delivered = "Pristatyta",
  noOrders = "Užsakymu nerasta",
  quantity = "Kiekis",
  totalCost = "Visa kaina",
  totalSales = "Visi pardavimai",
  noSales = "Pardavimų nerasta",
  paid = "Sumokėta",
  owed = "Įsiskolinta",
  dealershipName = "tr.priemonių Parduotuvės Pavadinimas",
  save = "Išsaugoti Pakeitimus",
  cancel = "Atšaukti",
  notEnoughMoney = "Nepakankamas pinigų kiekis",
  placeOrder = "Pateikti Užsakymą",
  purchaseCost = "Pirkimo Kaina",
  salePrice = "Pardavimo Kaina",
  inStock = "Turimas kiekis",
  outOfStock = "Išparduota",
  placeVehiclePrompt = "Paspauskite %{value} ,kad pastatytumėte tr.priemonę. Pakeitimus galėsite daryti vėliau!",
  remaining = "Likę",
  prePurchaseRepoWarning = "Jei negalite atsiskaityti su finansiniais mokėjimais, jūsų transporto priemonė bus grąžinta.",
  repossessionWarning = "Paskutinis mokėjimas nepavyko jūsų transporto priemonė bus grąžinta, nebent mokėsite dabar.",
  recurringPayment = "Pasikartojantis mokėjimas",
  remainingBalance = "Esamas likutis",
  remainingPayments = "Likę mokėjimai",
  paymentTakenEvery = "PMokėjimas imamas kas",
  hours = "valandos",
  seconds = "sekundės",
  nextPayment = "Kitas mokėjimas",
  makePayment = "Sumokėti",
  vehicleRepossessed = "Transporto priemonė bus atimta",
  payInFull = "Mokėti pilnai",
  earlyPaymentConfirmation = "Ar tikrai norite atlikti išankstinį mokėjimą?",
  financedVehicles = "Finansuojamos transporto priemonės",
  noFinancedVehicles = "Jūs neturite tr.priemonių už kurias reikėtų mokėti",
  financeBreakdown = "Finansų suskirstymas",
  initialPayment = "Pradinis mokėjimas",
  payments = "Mokėjimai",
  length = "Ilgis",
  interest = "Palūkanos",
  totalPayable = "Iš viso mokėtina",
  leaveShowroom = "Palikti",
  handling = "Tvarkymas",
  topSpeed = "Didžiausias greitis",
  power = "Galia",
  torque = "Sukimo momentas",
  brake = "Stabdymas",
  financing = "Finansavimas",
  financingAvailable = "Galimas finansavimas",
  paymentsOf = "mokėjimai iš",
  clear = "Clear",
  testDrive = "Bandomasis Važiavimas",
  allCategories = "Visos Kategotijos",
  sortByName = "Rušioti pagal: Pavadinimą",
  sortByAvailability = "Rūšiuoti pagal: Prieinamumą",
  sortByCheapest = "Rūšiuoti pagal: Pigiausias",
  sortByMostExpensive = "Rūšiuoti pagal: Brangiausias",
  sortByNewest = "Rūšiuoti pagal: Naujausias",
  purchaseVehicle = "Pirkti tr.priemonę",
  purchaseFor = "Pirkti už",
  selectSociety = "Pasirinkite Bendriją",
  financeOverPayments = "Finansuokite daugiau nei %{value} mokėjimų",
  payToday = "Mokėkite šiandien",
  financeThen = "Tada",
  seeFullBreakdown = "Žiūrėti visą suskirstymą",
  testDriveExit = "Galite bet kada išlipti iš transporto priemonės, kad baigtumėte bandomąjį važiavimą.",

  -- NOTIFICATIONS
  purchaseSuccess = "Sveikiname įsigijus pirkinį!",
  depositSuccess = "Depozitas sėkmingas",
  withdrawSuccess = "Išėmimas sėkmingas",
  errorNotEnoughMoney = "Jūs neturite pakankamai pinigų",
  errorVehicleOutOfStock = "Šios tr.priemonės nėra sandėlyje",
  errorCannotAffordVehicle = "Jūs negalite sau leisti šios transporto priemonės",
  vehicleFinancePaymentMade = "Pavedimas už tr.priemonę sėkmingas  %{value}",
  vehicleFinancePaidOff = "Sveikiname, jūs sumokėjote ir dabar turite nuosavą transporto priemonę %{value}",
  vehicleFinancePaymentFailed = "Nepavyko nuskaičiuoti pinigų už tr.priemonę %{value}",
  vehicleFinanceRepossessedSoon = "Turite sumokėti už savo tr.priemonę %{value} arba jūsų tr.priemonė netrukus bus grąžinta",
  vehicleFinanceRepossessed = "Dėl nemokėjimo jūsų transporto priemonė buvo atimta su valstybiniu numeriu %{value}",
  dealershipNotEnoughFunds = "Tr.priemonių parduotuvė neturi pakankamai lėšų",
  dealershipVehiclesOrdered = "Transporto priemonė(s) sėkmingai užsakyta(os).",
  dealershipOrderCancelled = "Užsakymas sėkmingai atšauktas",
  errorVehicleWithSpawnCodeExists = "Transporto priemonė su šiuo kodu jau yra",
  errorExitVehicle = "Pirmiausia turite išlipti iš transporto priemonės",

    -- NEW v1.1
  purchaseRequest = "Pirkimo užklausa",
  sendRequest = "Siųsti užklausą",
  dealer = "Automobilių salonas",
  financed = "Finansuojamas",
  signHere = "Pasirašykite čia",
  signFirstError = "Pirmiausia turite pasirašyti",
  denyRequest = "Atmesti užklausą",
  playerTooManyFinancedVehicles = "Žaidėjas turi per daug finansuojamų transporto priemonių",
  employeePermissionsError = "Neturite reikiamų darbuotojo teisių",
  managerRole = "Vadybininkas",
  supervisorRole = "Prižiūrėtojas",
  salesRole = "Pardavėjas",
  ownerRole = "Savininkas",
  employmentRequest = "Įdarbinimo užklausa",
  accept = "Priimti",
  jobOfferDescription = "Jums pasiūlytas darbas \"%{value}\" salone. Ar norite priimti?",
  pending = "Laukiama",
  employeeHiredMsg = "Automobilių salono įdarbinimo užklausa priimta!",
  employeeRejectedMsg = "Automobilių salono įdarbinimo užklausa atmesta",
  sellVehicle = "Parduoti transporto priemonę",
  vehicleTerms = "Transporto priemonės sąlygos",
  financePayments = "Finansavimo mokėjimai",
  commission = "Komisiniai",
  role = "Pareigos",
  firedNotification = "Jūs buvote atleistas iš \"%{value}\" salono",
  dealershipTooFarAway = "Nesate prie jokio automobilių salono",
  restoreDisplayVehicles = "Atstatyti ekspoziciją",
  customer = "Klientas",
  lessThanAMin = "Mažiau nei minutė",
  mins = "min.",
  notInVehicle = "Nesėdite transporto priemonėje",
  notYourVehicleError = "Ši transporto priemonė jums nepriklauso",
  vehicleFinancedError = "Negalite parduoti šios transporto priemonės, nes liko neapmokėtų finansavimo įmokų",
  dealershipDoesntSellVehicle = "Šis salonas negali nupirkti šios transporto priemonės",
  dealershipWantsYourVehicle = "Sveikiname! Šis salonas nori nupirkti jūsų transporto priemonę.",
  purchasePrice = "Siūloma kaina: ",

  spawnCodeInvalid = "Neteisingas spawn kodas",
  salesRep = "Pardavimų atstovas",
  directSaleAccepted = "Tiesioginio pardavimo užklausa priimta! Jūsų komisiniai išmokėti.",
  directSaleRejected = "Tiesioginio pardavimo užklausa atmesta",

  displayVehicleOutsideZone = "Parodomos transporto priemonės turi būti pastatytos atstovybės zonoje",
  serverAdmin = "Serverio administratorius",
  selfService = "Savitarna",
  owned = "Priklausanti",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Neteisingas mokėjimo būdas",
  paymentMethodNoFinance = "Šis mokėjimo būdas nepalaiko finansavimo",
  couldNotGeneratePlate = "Nepavyko sugeneruoti valstybinio numerio",
  invalidCoupon = "Neteisingas kuponas: %{value}",
  tooManyFinancedVehicles = "Turite per daug finansuojamų transporto priemonių",
  couldNotSpawnVehicle = "Nepavyko sukurti transporto priemonės",

  -- v2: Permissions
  insufficientPermissions = "Nepakankamos teisės",

  -- v2: Coupons
  couponCodeAlreadyExists = "Šis kupono kodas jau egzistuoja",
  failedToCreateCoupon = "Nepavyko sukurti kupono",
  couponCreatedSuccessfully = "Kuponas sėkmingai sukurtas",
  couponNotFound = "Kuponas nerastas",
  couponUpdatedSuccessfully = "Kuponas sėkmingai atnaujintas",
  failedToDeleteCoupon = "Nepavyko ištrinti kupono",
  couponDeletedSuccessfully = "Kuponas sėkmingai ištrintas",
  editCoupon = "Redaguoti kuponą",
  addCoupon = "Pridėti kuponą",
  couponCode = "Kupono kodas",
  generating = "Generuojama...",
  generate = "Generuoti",
  discountType = "Nuolaidos tipas",
  percentageOff = "Procentinė nuolaida",
  amountOff = "Sumos nuolaida",
  discountValue = "Nuolaidos vertė",
  unlimitedTotalUses = "Neribota bendra naudojimo skaičius",
  unlimitedUsesPerPlayer = "Neribota naudojimų skaičius žaidėjui",
  setExpiryDate = "Nustatyti galiojimo datą",
  restrictToSpecificVehicles = "Apriboti konkrečioms transporto priemonėms",
  restrictToSpecificCategories = "Apriboti konkrečioms kategorijoms",
  allowUseWithFinance = "Leisti naudoti su finansavimu",
  deleteCoupon = "Ištrinti kuponą",
  inactive = "Neaktyvus",
  expired = "Pasibaigęs",
  maxUses = "Maksimalus naudojimų skaičius",
  coupons = "Kuponai",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Tik serverio administratoriai gali įsidarbinti patys",
  playerNotFound = "Žaidėjas nerastas",
  failedToHireEmployee = "Nepavyko priimti darbuotojo",
  failedToFireEmployee = "Nepavyko atleisti darbuotojo",
  failedToUpdateEmployeeRole = "Nepavyko atnaujinti darbuotojo pareigų",
  hireEmployee = "Priimti darbuotoją",
  fireEmployee = "Atleisti darbuotoją",
  editRole = "Redaguoti pareigas",
  fire = "Atleisti",
  changeRole = "Pakeisti pareigas",
  updateRole = "Atnaujinti pareigas",

  -- v2: Test drives
  maxTestDrivesReached = "Ši atstovybė pasiekė maksimalų aktyvių bandomųjų važiavimų skaičių",
  testDriveNotEnabled = "Bandomieji važiavimai šioje atstovybėje neįjungti",
  noTestDriveSpawnCoords = "Šiai atstovybei nesukonfigūruotos bandomojo važiavimo spawn koordinatės",
  couldNotSpawnTestDriveVehicle = "Nepavyko sukurti bandomojo važiavimo transporto priemonės",
  couldNotGetPlateFromServer = "Nepavyko gauti valstybinio numerio iš serverio",
  couldNotRegisterTestDriveVehicle = "Nepavyko užregistruoti bandomojo važiavimo transporto priemonės",
  testDriveEndedByEmployee = "Bandomąjį važiavimą baigė kitas darbuotojas",
  trackingVehicleLocation = "Sekama transporto priemonės vieta...",
  directSaleCancelled = "Pardavimo užklausą atšaukė pardavėjas",
  testDriveKeysReceived = "Gavote bandomojo važiavimo transporto priemonės raktus",
  testDriveEndedCustomer = "Bandomasis važiavimas baigėsi",
  starting = "Paleidžiama...",
  startTestDrive = "Pradėti bandomąjį važiavimą",
  spawningTestDriveVehicle = "Kuriama bandomojo važiavimo transporto priemonė...",
  testDriveReady = "Bandomasis važiavimas paruoštas",
  testDriveWalkToVehicle = "Bandomojo važiavimo transporto priemonė sukurta pažymėtoje vietoje jūsų žemėlapyje. Palydėkite klientą prie transporto priemonės. Perdavę raktus klientui, turėsite rankiniu būdu baigti bandomąjį važiavimą, kai jis grįš.",
  givingKeys = "Perduodami raktai...",
  continueAndGiveKeys = "Tęsti ir perduoti raktus",
  endTestDrive = "Baigti bandomąjį važiavimą",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Šios transporto priemonės nėra sandėlyje",
  globalStockLimitExceeded = "Galima tik %{value} vienetų",
  orderNotFoundOrFulfilled = "Užsakymas nerastas arba jau įvykdytas",
  priceBelowMinimum = "Kaina negali būti mažesnė nei %{value}",
  priceAboveMaximum = "Kaina negali būti didesnė nei %{value}",
  stockUpdated = "Sandėlis atnaujintas",
  changesSaved = "Pakeitimai išsaugoti",
  noStockAvailable = "Sandėlyje nėra",
  orderPlaced = "Užsakymas pateiktas",
  remainingInStock = "liko bendrame sandėlyje",
  exceedsStockLimit = "Viršija sandėlio limitą",
  setStockQty = "Nustatyti sandėlio kiekį",
  invalidStockValue = "Įveskite teisingą sandėlio vertę",
  errorSettingStock = "Klaida nustatant sandėlį",
  stockQuantity = "Sandėlio kiekis",
  currentStock = "Dabartinis sandėlis",
  priceLimitsEnabled = "Įjungti kainų limitus",
  priceLimitsDescription = "Įjungus, atstovybės vadovai gali nustatyti kainas tik nurodytame intervale.",
  minPrice = "Minimali kaina",
  maxPrice = "Maksimali kaina",
  optional = "Neprivaloma",
  unlimitedStock = "Neribotas sandėlis",
  globalStockLimit = "Bendras sandėlio limitas",
  globalStockLimitDescription = "Nustatykite maksimalų vienetų skaičių, kuris gali būti užsakytas visose atstovybėse.",
  currentlyOrdered = "Šiuo metu užsakyta",
  priceRange = "Kainų intervalas",
  noMinimum = "Nėra minimumo",
  noMaximum = "Nėra maksimumo",
  vehicleStock = "Transporto priemonių sandėlis",

  -- v2: Sales
  allSales = "Visi pardavimai",
  paidInFull = "Pilnai apmokėta",
  salesVolume = "Pardavimų apimtis",
  pastMonth = "Praėjęs mėnuo",
  pastYear = "Praėję metai",

  -- v2: Management misc
  exploitAttemptDetected = "Nustokite bandyti išnaudoti skriptą",
  dealershipNoJobConfigured = "Atstovybė neturi sukonfigūruoto darbo",
  modelDoesNotMatchDb = "Transporto priemonės modelis neatitinka duomenų bazės",
  importFailed = "Importas nepavyko: %{value}",
  notInDealershipZone = "Norėdami naudoti šią komandą, turite būti atstovybėje",
  notAnEmployee = "Jūs nesate šios atstovybės darbuotojas.",
  failedToPrepareDelivery = "Nepavyko paruošti pristatymo",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Transporto priemonės modelis neegzistuoja - susisiekite su administratoriumi",
  vehiclePlateInvalid = "Šios transporto priemonės valstybinis numeris neteisingas (paspauskite F8 daugiau informacijos)",
  currentlyInRagdollState = "Šiuo metu esate ragdoll būsenoje",
  vehicleDoesNotExistContactAdmin = "Transporto priemonė neegzistuoja. Susisiekite su administratoriumi!",
  vehicleSecurityBreachDetected = "Aptiktas transporto priemonės saugumo pažeidimas",

  -- v2: Admin vehicles
  allVehicles = "Visos transporto priemonės",
  unassignedVehicles = "Be atstovybės",
  searchDealerships = "Ieškoti atstovybių...",

  -- v2: Trucking mission
  truckingGetInTruck = "Sėskite į sunkvežimį pažymėtoje vietoje, kad pradėtumėte pristatymą",
  truckingDriveToDelivery = "Važiuokite į pristatymo vietą",
  truckingCompleteDelivery = "Užbaigti pristatymą",
  truckingDeliveryComplete = "Pristatymas užbaigtas: Sėkmingai užbaigėte pristatymą!",
  truckingDeliveryFailed = "Pristatymas nepavyko: Kažkas nutiko ne taip su pristatymu",
  truckingDriveToPickup = "Važiuokite į paėmimo tašką paimti priekabą",
  truckingMissionFailedSpawnCargo = "Misija nepavyko: Nepavyko sukurti krovinio priekabos",
  truckingMissionFailedFindCargo = "Misija nepavyko: Nepavyko rasti sukurto krovinio",
  truckingVehiclesLoaded = "%{count} transporto priemonė(-ės) pakrauta",
  truckingWrongTrailer = "Neteisinga priekaba! Turite prijungti teisingą misijos priekabą.",
  truckingTrailerAttached = "Priekaba prijungta - pasiruošę tęsti",
  truckingDriveToPickupLocation = "Važiuokite į paėmimo tašką",
  truckingWaitingForVehicles = "Laukiama transporto priemonių pakrovimo...",
  truckingDriveUnderTrailer = "Įvažiuokite po priekaba, kad ją prijungtumėte",
  truckingGetInTruckContinue = "Sėskite į sunkvežimį, kad tęstumėte",
  truckingMissionStarted = "Transportavimo misija pradėta: Paėmimo taškas - %{location}",
  truckingMissionCancelled = "Misija atšaukta: Atšaukėte transportavimo misiją",
  truckingNoActiveMission = "Nėra aktyvios transportavimo misijos atšaukimui",
  deliveryNotPrepared = "Pristatymas nepasiruošęs - bandykite dar kartą",
  deliveryConfigMismatch = "Pristatymo konfigūracija nesutampa",
  deliveryPreparationExpired = "Pristatymo paruošimas pasibaigė - bandykite dar kartą",
  noTruckingVehicleCoordinates = "Transportavimo transporto priemonės koordinatės nenustatytos",
  pickupLocationUnavailable = "Paėmimo taškas nebeprieinamas - bandykite dar kartą",
  failedToSpawnTruck = "Nepavyko sukurti sunkvežimio",
  clientFailedToStartMission = "Klientas nepavyko pradėti misijos",

  -- v2: Trucking UI/Keys
  keyDismiss = "Uždaryti",
  keyDeliverCargo = "Pristatyti krovinį",
  keyContinueToDelivery = "Tęsti pristatymą",
  startDeliveryMission = "Pradėti pristatymo misiją",
  orderDetails = "Užsakymo detalės",
  pickupLocation = "Paėmimo taškas",
  deliveryStatus = "Pristatymo būsena",
  selectOrders = "Pasirinkti užsakymus",
  carTrailer = "Autovežis",
  container = "Konteineris",
  deliveryRoute = "Pristatymo maršrutas",
  startDelivery = "Pradėti pristatymą",

  -- v2: Direct sales UI
  waitingForCustomer = "Laukiama kliento",
  cancelRequest = "Atšaukti užklausą",
  saleComplete = "Pardavimas užbaigtas!",
  done = "Atlikta",
  saleDeclined = "Pardavimas atmestas",
  close = "Uždaryti",

  -- v2: Display vehicle placement
  movement = "Judėjimas",
  rotate = "Sukti",
  forward = "Pirmyn",
  backward = "Atgal",
  left = "Kairėn",
  right = "Dešinėn",
  rotateLeft = "Sukti kairėn",
  rotateRight = "Sukti dešinėn",

  -- v2: Showroom misc
  originalPrice = "Pradinė kaina",
  discount = "Nuolaida",
  createInteraction = "Sukurti sąveiką",
  viewAll = "Rodyti viską",
  fetchingPlayers = "Gaunami žaidėjai",
  refresh = "Atnaujinti",
  loadingPlayers = "Įkeliami žaidėjai...",
  failedToLoadPlayers = "Nepavyko įkelti žaidėjų",
  selectAPlayer = "Pasirinkti žaidėją",
  failedToLoadPlayersRetry = "Nepavyko įkelti žaidėjų. Spustelėkite 'Atnaujinti', kad bandytumėte dar kartą.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Savitarnos autocentras",
  categories = "Kategorijos",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Vietos",
  createNew = "Sukurti naują",
  enable = "Įjungti",
  disable = "Išjungti",
  loading = "Įkeliama...",
  errors = "Klaidos",
  update = "Atnaujinti",
  create = "Sukurti",

  -- v2: Dealership creation/editing
  createDealership = "Sukurti autocentrą",
  editDealership = "Redaguoti autocentrą",
  essentials = "Pagrindiniai",
  advanced = "Išplėstiniai",
  noDealershipLocations = "Nėra autocentro vietų",
  noDealershipLocationsDesc = "Galite pridėti naują vietą, importuoti iš konfigūracijos (jei migruojate iš v1) arba automatiškai pridėti numatytas vietas.",

  -- v2: Location sections
  dealershipZone = "Autocentro zona",
  showroomAndManagement = "Salonas ir valdymas",
  openShowroom = "Atidaryti saloną",
  openManagement = "Atidaryti valdymą",
  enableSellVehicle = "Įjungti transporto priemonių pardavimą",
  percentageOfVehicleValue = "Procentas % nuo transporto priemonės vertės",
  enablePurchase = "Įjungti pirkimą",
  purchasedVehicleSpawn = "Nupirktos transporto priemonės atsiradimas",
  enableTestDrive = "Įjungti bandomąjį važiavimą",
  testDriveVehicleSpawn = "Bandomojo važiavimo transporto priemonės atsiradimas",
  truckDelivery = "Sunkvežimio pristatymas",
  truckDeliveryVehicleSpawn = "Pristatymo transporto priemonės atsiradimas",

  -- v2: Location advanced settings
  paymentMethods = "Mokėjimo būdai",
  supportsFinancing = "(palaiko finansavimą)",
  enableFinance = "Įjungti finansavimą",
  cameraPreset = "Kamera",
  preset = "Nustatymas",
  custom = "Pasirinktinis",
  vehiclePosition = "Transporto priemonės pozicija",
  zoomPositions = "Artinimo pozicijos (atskirtos kableliais)",
  zoomPositionsPlaceholder = "pavyzdys: 5,8,12,8",
  vehicleColour = "Transporto priemonės spalva",
  selectionType = "Pasirinkimo tipas",
  noColourSelection = "Nėra spalvos pasirinkimo",
  rgbColourWheel = "RGB spalvų ratas",
  listOfRgbColours = "RGB spalvų sąrašas",
  listOfColourIds = "Spalvų ID sąrašas",
  accessControl = "Prieigos kontrolė",
  showroomJobWhitelist = "Salono darbų sąrašas",
  showroomGangWhitelist = "Salono gaujų sąrašas",
  societyPurchaseJobWhitelist = "Organizacijos pirkimo darbų sąrašas",
  societyPurchaseGangWhitelist = "Organizacijos pirkimo gaujų sąrašas",
  setInGame = "Nustatyti žaidime",
  addNew = "Pridėti naują",

  -- v2: Job/Gang whitelist editor
  job = "Darbas",
  gang = "Gauja",
  jobWhitelist = "Darbų sąrašas",
  gangWhitelist = "Gaujų sąrašas",
  addJob = "Pridėti darbą",
  addGang = "Pridėti gaują",
  editJob = "Redaguoti darbą",
  editGang = "Redaguoti gaują",
  manageJobs = "Valdyti darbus",
  manageGangs = "Valdyti gaujas",
  jobName = "Darbo pavadinimas",
  gangName = "Gaujos pavadinimas",
  selectGrades = "Pasirinkti rangus",
  selectAll = "Pasirinkti viską",
  deselectAll = "Atžymėti viską",
  invalidJobName = "Neteisingas darbo pavadinimas. Patikrinkite savo framework konfigūraciją.",
  invalidGangName = "Neteisingas gaujos pavadinimas. Patikrinkite savo framework konfigūraciją.",
  grades = "Rangai",
  noJobsConfigured = "Nėra sukonfigūruotų darbų",
  noGangsConfigured = "Nėra sukonfigūruotų gaujų",
  click = "Spustelėkite",
  toGetStarted = "norėdami pradėti.",
  more = "daugiau",
  jobPlaceholder = "Pavyzdžiui: cardealer",
  jobOptionalDescription = "Pasirinktinai susiekite autocentro vaidmenis su framework darbu. Kai darbuotojai įdarbinami/atleidžiami, jų framework darbas taip pat bus atnaujintas.",
  jobRankPermissions = "Darbo rango leidimai",
  roleToJobRankMapping = "Vaidmens susiejimas su darbo rangu",
  addPerm = "Pridėti leidimą",

  -- v2: Colour selector
  searchColours = "Ieškoti spalvų...",
  noColoursFound = "Spalvų nerasta",

  -- v2: Interactions creator
  noInteractions = "Nėra sąveikų",
  highlightInteractions = "Paryškinti sąveikas",
  explorationMode = "Tyrinėjimo režimas",
  pressEsc = "Paspauskite ESC",
  toWalkAround = "norėdami vaikščioti",
  toReturnToUI = "norėdami grįžti į UI",
  points = "taškai",
  location = "vieta",
  manageLocations = "Valdyti vietas",

  -- v2: Interaction modal
  interactionType = "Tipas",
  nicknameOptional = "Slapyvardis (Neprivaloma)",
  invalidModel = "Neteisingas modelis",
  failedToValidateModel = "Nepavyko patvirtinti modelio",
  pedScenario = "Ped scenarijus",
  coords = "Koordinatės",
  size = "Dydis",
  blip = "Blipas",
  enableBlip = "Įjungti blipą",
  blipIconId = "Blipo piktogramos ID",
  blipColourId = "Blipo spalvos ID",
  blipSize = "Blipo dydis",
  marker = "Žymeklis",
  enableMarker = "Įjungti žymeklį",
  markerStyleId = "Žymeklio stiliaus ID",
  markerSize = "Žymeklio dydis",
  markerColor = "Žymeklio spalva",
  markerBobUpAndDown = "Plaukioti aukštyn ir žemyn",
  markerFaceCamera = "Žiūrėti į kamerą",
  markerRotate = "Sukti",
  markerDrawOnEnts = "Piešti ant objektų",
  updatePosition = "Atnaujinti poziciją",
  setPosition = "Nustatyti poziciją",

  -- v2: Interaction types
  interactionPoint = "Taškas",
  interactionPointDesc = "Vienas keičiamo dydžio taškas su pasirinktiniu žymekliu",
  interactionPolyzone = "Polizona",
  interactionPolyzoneDesc = "Daugelio koordinačių zona specifinei sąveikos zonai sukurti",
  interactionVehicle = "Transporto priemonė",
  interactionVehicleDesc = "Sukurti transporto priemonės modelį, idealiai tinka target arba 3D teksto UI sąveikos metodams",
  interactionObject = "Objektas",
  interactionObjectDesc = "Sukurti objekto modelį, idealiai tinka target arba 3D teksto UI sąveikos metodams",
  interactionPed = "Ped",
  interactionPedDesc = "Sukurti ped modelį su pasirinktiniu scenarijumi, idealiai tinka target arba 3D teksto UI sąveikos metodams",

  -- v2: Import modal
  importLocationsTitle = "Importuoti vietas",
  syncStockLabel = "Sinchronizuoti atsargas",
  syncStockDescription = "Pridėti transporto priemones prie kiekvieno autocentro atsargų pagal jo kategorijas",
  importSourceSelectorDesc = "Galite importuoti numatytų vietų rinkinį paruoštai sąrankai arba importuoti esamas vietas iš konfigūracijos, jei migruojate iš Dealerships v1.",
  importSourceSelectorSkipDesc = "Vietos, kurios jau egzistuoja duomenų bazėje, bus praleistos; bus importuotos tik naujos vietos.",
  successfullyImported = "Sėkmingai importuota",
  alreadyExist = "Jau egzistuoja",
  defaultLocations = "Numatytos vietos",
  defaultLocationsDesc = "Importuoti iš anksto sukonfigūruotas autocentro vietas (PDM, Prabanga, Valtys, Oro, Sunkvežimiai)",
  existingConfig = "Esama konfigūracija",
  existingConfigDesc = "Importuoti vietas iš config.lua (v1 migracijai)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Ar norite automatiškai pridėti transporto priemones prie šio autocentro atsargų pagal pasirinktas kategorijas?",
  categorySyncEditDesc = "Pakeitėte šio autocentro kategorijas. Ar norite automatiškai atnaujinti transporto priemonių atsargas?",
  addVehicles = "Pridėti transporto priemones",
  removeVehicles = "Pašalinti transporto priemones",
  fromNewCategories = "iš naujų kategorijų",
  fromSelectedCategories = "iš pasirinktų kategorijų",
  fromRemovedCategories = "iš pašalintų kategorijų",
  categoriesAdded = "Pridėtos kategorijos:",
  categoriesRemoved = "Pašalintos kategorijos:",
  skip = "Praleisti",
  syncStock = "Sinchronizuoti atsargas",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Tikrinama šaltinio prieinamumas...",
  vehiclesAvailableToImport = "transporto priemonių galima importuoti",
  includesDealershipIds = "apima autocentro ID",
  sourceUnavailable = "Šaltinis neprieinamas",
  noVehiclesAdminDescription = "Galite pridėti transporto priemones rankiniu būdu arba importuoti jas iš savo framework.",
  appendBehaviour = "Pridėti",
  overwriteBehaviour = "Perrašyti",
  appendDescription = "Pridėti tik naujas transporto priemones, kurių dar nėra duomenų bazėje",
  overwriteDescription = "Ištrinti visus esamus transporto priemonių duomenis ir importuoti iš naujo",
  stockAssignmentMethod = "Atsargų priskyrimo metodas",
  useDealershipIdsFromSource = "Naudoti autocentro ID iš šaltinio",
  matchByVehicleCategory = "Suderinti pagal transporto priemonės kategoriją",
  byShopDescription = "Transporto priemonės bus priskirtos autocentrams pagal 'shop' lauką šaltinio duomenyse",
  byCategoryDescription = "Transporto priemonės bus priskirtos autocentrams su atitinkančiomis kategorijomis",
  overwriteWarning = "Įspėjimas: Perrašymas ištrins visas esamas transporto priemones, užsakymus, rodomas transporto priemones ir pardavimų duomenis.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX transporto priemonių lentelė",
  selectCategory = "Pasirinkite kategoriją",

  -- v2: Management menu items
  vehiclesMenu = "Transporto priemonės",
  displayVehiclesMenu = "Rodomos transporto priemonės",
  ordersMenu = "Užsakymai",
  salesMenu = "Pardavimai",
  bankAccountMenu = "Banko sąskaita",
  employeesMenu = "Darbuotojai",
  couponsMenu = "Kuponai",
  settingsMenu = "Nustatymai",
  noPermissionAccessManagement = "Neturite leidimo pasiekti valdymo funkcijas.",
  backToAdmin = "Grįžti į administratorių",
  viewingAsAdmin = "ŽIŪRIMA KAIP ADMINISTRATORIUS",

  -- v2: Coupons table
  code = "Kodas",
  uses = "Panaudojimai",
  perPlayer = "Žaidėjui",
  never = "Niekada",
  noCoupons = "Nėra kuponų",
  noCouponsDescription = "Klientai gali įvesti kuponą transporto priemonės pirkimo metu ir sutaupyti pinigų.",

  -- v2: Coupon modal
  couponCodeLabel = "Kupono kodas",
  couponCodePlaceholder = "pvz., VASARA2024 arba SUTAUPYK10",
  couponCodeHelp = "Įveskite pasirinktinį kodą (iki 25 simbolių, tik raidės, skaičiai ir brūkšniai) arba spustelėkite 'Generuoti'.",
  maxNumberOfUsesPlaceholder = "Maksimalus panaudojimų skaičius",
  maxUsesPerPlayerPlaceholder = "Maksimalus panaudojimų skaičius žaidėjui",
  vehicleRestrictionsPlaceholder = "Įveskite spawn kodus, atskirtus kableliais (pvz., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Leisti finansuojamiems pirkimams",
  createCoupon = "Sukurti kuponą",
  updateCoupon = "Atnaujinti kuponą",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kupono kodas privalomas",
  couponCodeMaxLength = "Kodas turi būti 25 simbolių ar mažiau",
  couponCodeInvalidChars = "Kodas gali turėti tik didžiąsias raides, skaičius ir brūkšnius",
  discountTypeRequired = "Nuolaidos tipas privalomas",
  discountValueRequired = "Nuolaidos vertė privaloma",
  discountValueMin = "Nuolaidos vertė turi būti didesnė nei 0",
  discountValueMaxPercent = "Procentas negali viršyti 100",
  maxUsesRequired = "Maksimalus panaudojimų skaičius privalomas",
  maxUsesMin = "Turi būti bent 1",
  perPlayerLimitRequired = "Limitas žaidėjui privalomas",
  expiryDateRequired = "Galiojimo data privaloma",
  vehicleRestrictionsRequired = "Transporto priemonių apribojimai privalomi",
  categoryRestrictionsRequired = "Kategorijų apribojimai privalomi",
  selectAtLeastOneCategory = "Pasirinkite bent vieną kategoriją",

  -- v2: Dashboard
  today = "Šiandien",
  thisMonth = "Šį mėnesį",
  allTime = "Visą laiką",
  recentSales = "Naujausi pardavimai",
  noSalesYet = "Dar nėra pardavimų!",
  noSalesDescription = "Transporto priemonių pardavimai bus rodomi čia po pirmo pardavimo.",
  past7Days = "Per paskutines 7 dienas",
  past6Months = "Per paskutinius 6 mėnesius",
  numberOfSales = "Pardavimų skaičius",
  noDataAvailableForPeriod = "Nėra duomenų šiam laikotarpiui",

  -- v2: Display vehicles
  displayVehiclesDescription = "Rodomos transporto priemonės yra fiksuoti salono modeliai, naudojami jūsų inventoriui pristatyti ir klientams paskatinti pirkti.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework darbai įjungti",
  frameworkJobsDescription = "Darbuotojų valdymas atliekamas per framework darbo sistemą. Žaidėjai su autocentro darbu automatiškai turės prieigą pagal savo darbo rangą. Konfigūruokite darbo leidimus administratoriaus skydelio vietos nustatymuose.",
  joinedColumn = "Prisijungė",
  youBadge = "Tu",

  -- v2: Orders
  noOrdersTitle = "Nėra užsakymų",
  noOrdersDescription = "Norėdami pateikti užsakymą, atidarykite 'Transporto priemonės' skirtuką ir spustelėkite 'Užsakyti' prie transporto priemonės, kurią norite papildyti.",
  inProgress = "Vykdoma",
  awaitingDelivery = "Laukia pristatymo",
  orderedBy = "Užsakė",
  viewDeliveryInfo = "Peržiūrėti pristatymo informaciją",

  -- v2: Delivery
  startDeliveryMissionTitle = "Pradėti pristatymo misiją",
  startDeliveryDescription = "Jūs ketinate pradėti pristatymo misiją šiam transporto priemonės užsakymui. Turėsite nuvažiuoti iki paėmimo vietos, paimti krovinio priekabą ir pristatyti ją atgal į autocentrą.",
  totalDistanceAndDriveTime = "Bendras atstumas ir važiavimo laikas",
  roundTrip = "pirmyn ir atgal",
  deliveryCompleteTitle = "Pristatymas baigtas",
  deliveryInProgressTitle = "Pristatymas vykdomas",
  deliveredAt = "Pristatyta:",
  startedAt = "Pradėta:",
  deliveredBy = "Pristatė:",
  beingDeliveredBy = "Pristato:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Nėra užsakymų pristatymui. Užsakymai turi būti paruošti ir ne aktyvaus pristatymo metu.",
  confirmDeliveryTitle = "Patvirtinti pristatymą",
  configureDeliveryTitle = "Konfigūruoti pristatymą",
  trailerCapacityExceeded = "Priekabos talpa viršyta! Pasirinkote %{usedSlots} vietų, bet maksimumas yra %{maxSlots} vietų.",
  smallVehiclesSlotInfo = "Atminkite: mažos transporto priemonės užima 1 vietą, vidutinės - 1,5 vietos.",
  fetchingRoute = "Gaunama...",
  getRouteButton = "Gauti maršrutą",
  selectTrailerType = "Pasirinkti priekabos tipą",
  carTrailerLabel = "Autovežis",
  smallMedium = "(Mažas/Vidutinis)",
  containerLabel = "Konteineris",
  large = "(Didelis)",
  carTrailerDescription = "Autovežis turi 2 eiles. Kiekviena eilė talpina 3 mažas (po 1 vietą) arba 2 vidutines (po 1,5 vietos). Maksimum 6 vietos.",
  containerDescription = "Konteinerio priekaba veža 1 didelę transporto priemonę",
  selectOrdersTitle = "Pasirinkti užsakymus",
  slots = "vietos",
  noOrdersForTrailerType = "Nėra užsakymų šiam priekabos tipui.",
  qty = "Kiekis:",
  inTransit = "kelyje",
  totalVehicles = "Iš viso transporto priemonių:",
  estimatedTime = "Numatomas laikas:",
  unknown = "Nežinomas",

  -- v2: Sales
  salesEmptyDescription = "Transporto priemonių pardavimai bus rodomi čia po pirmo pardavimo.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Užsakymas pateiktas!",
  orderPlacedTruckingDescription = "Jūsų užsakymas paruoštas paimti. Eikite į užsakymų puslapį jį įvykdyti.",
  orderPlacedTimedDescription = "Jūsų užsakymas bus pristatytas per %{value} minučių.",
  goToOrders = "Eiti į užsakymus",
  noStockAvailableDescription = "Šiai transporto priemonei nėra atsargų. Pasiektas globalus atsargų limitas.",
  stockUpdatedDescription = "Atsargų kiekis sėkmingai atnaujintas.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktyvūs bandomieji važiavimai",
  tracking = "Sekimas",
  track = "Sekti",
  endButton = "Baigti",
  endTestDriveTitle = "Baigti bandomąjį važiavimą",
  endTestDriveConfirmation = "Ar tikrai norite baigti šį bandomąjį važiavimą? Transporto priemonė bus ištrinta ir keleiviai nebus teleportuoti atgal į autocentrą.",
  vehicleLocationOnMap = "Transporto priemonės vieta pažymėta jūsų žemėlapyje.",
  sell = "Parduoti",
  couponCodeOptional = "Kupono kodas (Neprivaloma)",
  pleaseEnterCouponCode = "Įveskite kupono kodą",
  invalidCouponCode = "Neteisingas kupono kodas",
  failedToValidateCoupon = "Nepavyko patvirtinti kupono",
  apply = "Taikyti",
  applying = "Taikoma...",
  allStock = "Visos atsargos",
  inStockFilter = "Yra sandėlyje",
  outOfStockFilter = "Nėra sandėlyje",
  noResultsFound = "Rezultatų nerasta",
  noResults = "Nėra rezultatų",
  noVehiclesMatchSearch = "Nėra transporto priemonių, atitinkančių jūsų paiešką",
  noVehiclesMatchFilters = "Nėra transporto priemonių, atitinkančių jūsų dabartines filtrus",
  noItemsMatchSearch = "Nėra elementų, atitinkančių jūsų paiešką",
  noItemsMatchFilters = "Nėra elementų, atitinkančių jūsų dabartines filtrus",
  selectColour = "Pasirinkti spalvą",
  refreshNearbyPlayers = "Atnaujinti netoliese esančius žaidėjus",
  you = "Tu",
  items = "elementai",
  waitingForCustomerToRespond = "Laukiama kliento atsakymo...",
  vehicleSpawnedMessage = "Transporto priemonė atsirado jūsų žemėlapyje pažymėtame taške - nuvesk klientą ten.",
  customerDeclinedMessage = "Klientas atmetė pirkimo užklausą.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "PASIRAŠYKITE ČIA",
  acceptAndPurchase = "Priimti ir pirkti",
  couponApplied = "Kuponas %{code} pritaikytas! Sutaupote %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Reikia bent 3 taškų zonai užbaigti! (Šiuo metu yra %{value})",
  addPoint = "Pridėti tašką",
  removeLast = "Pašalinti paskutinį",
  completeZone = "Užbaigti zoną",
  spawnPreview = "Atsiradimo peržiūra",
  up = "Aukštyn",
  down = "Žemyn",
  confirm = "Patvirtinti",
  placePoint = "Padėti tašką",
  radius = "Spindulys",

  -- v2: Blip labels
  soldVehicleLocation = "Parduotos transporto priemonės vieta",
  testDriveVehicleBlip = "Bandomojo važiavimo transporto priemonė",

  -- v2: Stock sync
  stockSyncResult = "Atsargų sinchronizacija: %{added} pridėta, %{removed} pašalinta",
  stockSyncAdded = "Atsargų sinchronizacija: %{value} transporto priemonių pridėta",
  importSuccessful = "Importavimas sėkmingas! %{imported} transporto priemonių importuota (iš viso %{total})",

  -- v2: Tooltip actions
  findOnMap = "Rasti žemėlapyje",
  adminPanel = "Administratoriaus skydelis",

  -- v2: Common dropdown
  selectOne = "Pasirinkite vieną",
}
