Locales = Locales or {}

Locales['nl'] = {
  -- UI
  vehicle = "Voertuig",
  vehicles = "Voertuigen",
  dealership = "Autodealer",
  dealerships = "Autodealers",
  vehiclesCount = "Aantal voertuigen",
  dealersCount = "Aantal dealers",
  accountBalance = "Rekeningsaldo",
  bank = "Bank",
  cash = "Contant geld",
  amount = "Bedrag",
  societyFund = "Maatschappelijk fonds",
  paymentSource = "Betaalbron",
  purchase = "Aankoop",
  personalPurchase = "Persoonlijke aankoop",
  societyPurchase = "Maatschappelijke aankoop",
  purchaseType = "Type aankoop",
  deposit = "Storting",
  withdraw = "Opname",
  all = "Alle",
  yes = "Ja",
  no = "Nee",
  add = "Toevoegen",
  edit = "Bewerken",
  id = "ID",
  created = "Aangemaakt",
  type = "Type",
  name = "Naam",
  owner = "Eigenaar",
  bankBalance = "Banksaldo",
  status = "Status",
  back = "Terug",
  previous = "Vorige",
  next = "Volgende",
  admin = "Beheerder",
  vehiclesAdmin = "Voertuigbeheerder",
  dealershipsAdmin = "Autodealer beheerder",
  search = "Zoeken",
  noDealershipsFound = "Geen autodealers gevonden",
  noVehicles = "Geen voertuigen gevonden",
  page = "Pagina",
  of = "van",
  every = "elke",
  show = "Weergeven",
  active = "Actief",
  activeFinance = "Actieve financiering",
  failed = "Betaling mislukt",
  removed = "Verwijderd",
  setOwner = "Eigenaar instellen",
  manage = "Beheren",
  deleteData = "Gegevens verwijderen",
  deleteVehicle = "Voertuig verwijderen",
  delete = "Verwijderen",
  deleteConfirmation = "Weet je het zeker?",
  deleteConfirmationDanger = "Weet je het zeker? Deze actie kan niet ongedaan worden gemaakt.",
  setDealershipOwner = "Autodealer eigenaar instellen",
  overwriteDealerPrices = "Dealerprijzen overschrijven",
  nearbyPlayers = "Spelers in de buurt",
  noPlayersNearby = "Geen spelers in de buurt",
  selectPlayer = "Speler selecteren",
  required = "Vereist",
  forExample = "Bijvoorbeeld",
  spawnCode = "Spawn-code",
  brand = "Merk",
  model = "Model",
  category = "Categorie",
  price = "Prijs",
  import = "Importeren",
  importing = "Importeren",
  importBehaviour = "Importgedrag",
  importVehicles = "Voertuigen importeren",
  importFrom = "Importeren van",
  dashboard = "Dashboard",
  displayVehicle = "Voertuig weergeven",
  displayVehicles = "Voertuigen weergeven",
  orders = "Bestellingen",
  sales = "Verkoop",
  vehiclesOnDisplay = "Voertuigen op display",
  employees = "Werknemers",
  settings = "Instellingen",
  switchVehicle = "Voertuig wisselen",
  remove = "Verwijderen",
  noDisplayVehicles = "Geen voertuigen op display",
  selectVehicle = "Voertuig selecteren",
  colour = "Kleur",
  placeVehicle = "Voertuig plaatsen",
  orderVehicle = "Voertuig bestellen",
  cancelOrder = "Bestelling annuleren",
  delivery = "Levering",
  delivered = "Geleverd",
  noOrders = "Geen bestellingen",
  quantity = "Hoeveelheid",
  totalCost = "Totale kosten",
  totalSales = "Totale verkoop",
  noSales = "Geen verkoop gevonden",
  paid = "Betaald",
  owed = "Verschuldigd",
  dealershipName = "Naam autodealer",
  save = "Wijzigingen opslaan",
  cancel = "Annuleren",
  notEnoughMoney = "Niet genoeg geld",
  placeOrder = "Bestelling plaatsen",
  purchaseCost = "Aankoopprijs",
  salePrice = "Verkoopprijs",
  inStock = "Op voorraad",
  outOfStock = "Niet op voorraad",
  placeVehiclePrompt = "Druk op %{value} om het voertuig te plaatsen. Daarna kun je verdere aanpassingen maken!",
  remaining = "Resterend",
  prePurchaseRepoWarning = "Als je je kredietbetalingen niet volgt, wordt je voertuig in beslag genomen.",
  repossessionWarning = "Je laatste betaling is mislukt - als je nu niet betaalt, wordt je voertuig binnenkort in beslag genomen.",
  recurringPayment = "Terugkerende betaling",
  remainingBalance = "Resterend saldo",
  remainingPayments = "Resterende betalingen",
  paymentTakenEvery = "Betaling genomen om de",
  hours = "Uur",
  seconds = "Seconden",
  nextPayment = "Volgende betaling",
  makePayment = "Betaling doen",
  vehicleRepossessed = "Voertuig wordt in beslag genomen",
  payInFull = "Volledig betalen",
  earlyPaymentConfirmation = "Weet je zeker dat je eerder wilt betalen?",
  financedVehicles = "Gefinancierde voertuigen",
  noFinancedVehicles = "Je hebt geen actieve gefinancierde voertuigen",
  financeBreakdown = "Financiële breakdown",
  initialPayment = "Eerste betaling",
  payments = "Betalingen",
  length = "Lengte",
  interest = "Rente",
  totalPayable = "Totaal te betalen",
  leaveShowroom = "Showroom verlaten",
  handling = "Besturing",
  topSpeed = "Topsnelheid",
  power = "Vermogen",
  torque = "Koppel",
  brake = "Rem",
  financing = "Financiering",
  financingAvailable = "Financiering beschikbaar",
  paymentsOf = "betalingen van",
  clear = "Wis",
  testDrive = "Proefrit",
  allCategories = "Alle categorieën",
  sortByName = "Sorteer op naam",
  sortByAvailability = "Sorteer op beschikbaarheid",
  sortByCheapest = "Sorteer op goedkoopste",
  sortByMostExpensive = "Sorteer op duurste",
  sortByNewest = "Sorteer op nieuwste",
  purchaseVehicle = "Voertuig kopen",
  purchaseFor = "Kopen voor",
  selectSociety = "Selecteer een samenleving",
  financeOverPayments = "%{value} betalingen over financiering",
  payToday = "Vandaag betalen",
  financeThen = "Dan",
  seeFullBreakdown = "Bekijk de volledige breakdown",
  testDriveExit = "Je kunt op elk moment uit je voertuig stappen om de proefrit te beëindigen.",

  -- NOTIFICATIONS
  purchaseSuccess = "Bedankt voor je aankoop!",
  depositSuccess = "Storting succesvol",
  withdrawSuccess = "Opname succesvol",
  errorNotEnoughMoney = "Niet genoeg geld",
  errorVehicleOutOfStock = "Dit voertuig is niet op voorraad",
  errorCannotAffordVehicle = "Je kunt dit voertuig niet betalen",
  vehicleFinancePaymentMade = "Betaling van %{value} voor je voertuig is gelukt",
  vehicleFinancePaidOff = "Gefeliciteerd, je hebt je voertuig volledig afbetaald! %{value}",
  vehicleFinancePaymentFailed = "Betaling van %{value} voor je voertuig is mislukt",
  vehicleFinanceRepossessedSoon = "Je moet betalen voor je voertuig %{value}, anders wordt het binnenkort in beslag genomen",
  vehicleFinanceRepossessed = "Vanwege niet-betaling is je voertuig met kenteken %{value} in beslag genomen.",
  dealershipNotEnoughFunds = "De autodealer heeft niet genoeg fondsen",
  dealershipVehiclesOrdered = "Voertuigen succesvol besteld bij de autodealer",
  dealershipOrderCancelled = "Bestelling bij de autodealer succesvol geannuleerd",
  errorVehicleWithSpawnCodeExists = "Er bestaat al een voertuig met deze spawn-code",
  errorExitVehicle = "Je moet eerst uit je voertuig stappen",

  -- NEW v1.1
  purchaseRequest = "Aankoopverzoek",
  sendRequest = "Verzoek versturen",
  dealer = "Dealer",
  financed = "Gefinancierd",
  signHere = "Onderteken hier",
  signFirstError = "Onderteken eerst alsjeblieft",
  denyRequest = "Verzoek afwijzen",
  playerTooManyFinancedVehicles = "Deze speler heeft te veel gefinancierde voertuigen",
  employeePermissionsError = "Je hebt niet de vereiste rechten als werknemer",
  managerRole = "Manager",
  supervisorRole = "Supervisor",
  salesRole = "Verkoop",
  ownerRole = "Eigenaar",
  employmentRequest = "Verzoek tot aanstelling",
  accept = "Accepteren",
  jobOfferDescription = "Je hebt een baanaanbieding ontvangen van \"%{value}\" autodealer. Wil je het accepteren?",
  pending = "In behandeling",
  employeeHiredMsg = "Je bent aangenomen bij de autodealer!",
  employeeRejectedMsg = "Je verzoek tot aanstelling bij de autodealer is afgewezen",
  sellVehicle = "Voertuig verkopen",
  vehicleTerms = "Voorwaarden voertuig",
  financePayments = "Financiële betalingen",
  commission = "Commissie",
  role = "Rol",
  firedNotification = "Je bent ontslagen bij de autodealer \"%{value}\"",
  dealershipTooFarAway = "Je bent te ver verwijderd van een autodealer",
  restoreDisplayVehicles = "Toon voertuigen",
  customer = "Klant",
  lessThanAMin = "Minder dan een minuut",
  mins = "minuten",
  notInVehicle = "Je zit niet in een voertuig",
  notYourVehicleError = "Dit voertuig is niet van jou",
  vehicleFinancedError = "Je kunt dit voertuig niet verkopen omdat er nog resterende financieringsbetalingen zijn",
  dealershipDoesntSellVehicle = "Deze autodealer verkoopt dit voertuig niet",
  dealershipWantsYourVehicle = "Gefeliciteerd! Deze autodealer wil je voertuig kopen.",
  purchasePrice = "Aangeboden prijs: ",
  
  spawnCodeInvalid = "Ongeldige spawn code",
  salesRep = "Verkoper",
  directSaleAccepted = "Directe verkoopaanvraag geaccepteerd! Je commissie is betaald.",
  directSaleRejected = "Directe verkoopaanvraag afgewezen",

  displayVehicleOutsideZone = "Showroom voertuigen moeten binnen de dealerzone worden geplaatst",
  serverAdmin = "Server Admin",
  selfService = "Zelfbediening",
  owned = "In bezit",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Ongeldige betaalmethode",
  paymentMethodNoFinance = "Deze betaalmethode ondersteunt geen financiering",
  couldNotGeneratePlate = "Kon kenteken niet genereren",
  invalidCoupon = "Ongeldige kortingscode: %{value}",
  tooManyFinancedVehicles = "Je hebt te veel gefinancierde voertuigen",
  couldNotSpawnVehicle = "Kon voertuig niet spawnen",

  -- v2: Permissions
  insufficientPermissions = "Onvoldoende rechten",

  -- v2: Coupons
  couponCodeAlreadyExists = "Deze kortingscode bestaat al",
  failedToCreateCoupon = "Kon kortingscode niet aanmaken",
  couponCreatedSuccessfully = "Kortingscode succesvol aangemaakt",
  couponNotFound = "Kortingscode niet gevonden",
  couponUpdatedSuccessfully = "Kortingscode succesvol bijgewerkt",
  failedToDeleteCoupon = "Kon kortingscode niet verwijderen",
  couponDeletedSuccessfully = "Kortingscode succesvol verwijderd",
  editCoupon = "Kortingscode bewerken",
  addCoupon = "Kortingscode toevoegen",
  couponCode = "Kortingscode",
  generating = "Genereren...",
  generate = "Genereren",
  discountType = "Type korting",
  percentageOff = "Percentage korting",
  amountOff = "Bedrag korting",
  discountValue = "Kortingswaarde",
  unlimitedTotalUses = "Onbeperkt totaal gebruik",
  unlimitedUsesPerPlayer = "Onbeperkt gebruik per speler",
  setExpiryDate = "Vervaldatum instellen",
  restrictToSpecificVehicles = "Beperken tot specifieke voertuigen",
  restrictToSpecificCategories = "Beperken tot specifieke categorieën",
  allowUseWithFinance = "Gebruik met financiering toestaan",
  deleteCoupon = "Kortingscode verwijderen",
  inactive = "Inactief",
  expired = "Verlopen",
  maxUses = "Maximum gebruik",
  coupons = "Kortingscodes",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Alleen server admins kunnen zichzelf aannemen",
  playerNotFound = "Speler niet gevonden",
  failedToHireEmployee = "Kon medewerker niet aannemen",
  failedToFireEmployee = "Kon medewerker niet ontslaan",
  failedToUpdateEmployeeRole = "Kon rol van medewerker niet bijwerken",
  hireEmployee = "Medewerker aannemen",
  fireEmployee = "Medewerker ontslaan",
  editRole = "Rol bewerken",
  fire = "Ontslaan",
  changeRole = "Rol wijzigen",
  updateRole = "Rol bijwerken",

  -- v2: Test drives
  maxTestDrivesReached = "Deze dealer heeft het maximum aantal actieve proefritten bereikt",
  testDriveNotEnabled = "Proefritten zijn niet ingeschakeld bij deze dealer",
  noTestDriveSpawnCoords = "Geen proefrit spawn coördinaten geconfigureerd voor deze dealer",
  couldNotSpawnTestDriveVehicle = "Kon proefrit voertuig niet spawnen",
  couldNotGetPlateFromServer = "Kon kenteken niet ophalen van server",
  couldNotRegisterTestDriveVehicle = "Kon proefrit voertuig niet registreren",
  testDriveEndedByEmployee = "De proefrit is beëindigd door een andere medewerker",
  trackingVehicleLocation = "Voertuiglocatie volgen...",
  directSaleCancelled = "Het verkoopverzoek is geannuleerd door de verkoper",
  testDriveKeysReceived = "Je hebt de sleutels van het proefrit voertuig ontvangen",
  testDriveEndedCustomer = "De proefrit is beëindigd",
  starting = "Starten...",
  startTestDrive = "Start proefrit",
  spawningTestDriveVehicle = "Proefrit voertuig spawnen...",
  testDriveReady = "Proefrit gereed",
  testDriveWalkToVehicle = "Het proefrit voertuig is gespawned op de gemarkeerde locatie op je kaart. Loop met de klant naar het voertuig. Nadat je de sleutels aan de klant hebt gegeven, moet je de proefrit handmatig beëindigen wanneer ze terugkeren.",
  givingKeys = "Sleutels geven...",
  continueAndGiveKeys = "Doorgaan en sleutels geven",
  endTestDrive = "Proefrit beëindigen",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Geen voorraad beschikbaar voor dit voertuig",
  globalStockLimitExceeded = "Slechts %{value} eenheden beschikbaar",
  orderNotFoundOrFulfilled = "Bestelling niet gevonden of al afgehandeld",
  priceBelowMinimum = "Prijs kan niet lager zijn dan %{value}",
  priceAboveMaximum = "Prijs kan niet hoger zijn dan %{value}",
  stockUpdated = "Voorraad bijgewerkt",
  changesSaved = "Wijzigingen opgeslagen",
  noStockAvailable = "Geen voorraad beschikbaar",
  orderPlaced = "Bestelling geplaatst",
  remainingInStock = "resterend in globale voorraad",
  exceedsStockLimit = "Overschrijdt voorraadlimiet",
  setStockQty = "Voorraad aantal instellen",
  invalidStockValue = "Voer een geldige voorraadwaarde in",
  errorSettingStock = "Fout bij instellen voorraad",
  stockQuantity = "Voorraad aantal",
  currentStock = "Huidige voorraad",
  priceLimitsEnabled = "Prijslimieten inschakelen",
  priceLimitsDescription = "Wanneer ingeschakeld kunnen dealermanagers alleen prijzen instellen binnen het opgegeven bereik.",
  minPrice = "Minimumprijs",
  maxPrice = "Maximumprijs",
  optional = "Optioneel",
  unlimitedStock = "Onbeperkte voorraad",
  globalStockLimit = "Globale voorraadlimiet",
  globalStockLimitDescription = "Stel een maximum aantal eenheden in dat kan worden besteld bij alle dealers.",
  currentlyOrdered = "Momenteel besteld",
  priceRange = "Prijsbereik",
  noMinimum = "Geen minimum",
  noMaximum = "Geen maximum",
  vehicleStock = "Voertuigvoorraad",

  -- v2: Sales
  allSales = "Alle verkopen",
  paidInFull = "Volledig betaald",
  salesVolume = "Verkoopvolume",
  pastMonth = "Afgelopen maand",
  pastYear = "Afgelopen jaar",

  -- v2: Management misc
  exploitAttemptDetected = "Stop met het misbruiken van het script",
  dealershipNoJobConfigured = "De dealer heeft geen baan geconfigureerd",
  modelDoesNotMatchDb = "Voertuigmodel komt niet overeen met database",
  importFailed = "Import mislukt: %{value}",
  notInDealershipZone = "Je moet binnen een dealer zone zijn om dit commando te gebruiken",
  notAnEmployee = "Je bent geen medewerker van deze dealer.",
  failedToPrepareDelivery = "Kon levering niet voorbereiden",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Het voertuigmodel bestaat niet - neem contact op met een admin",
  vehiclePlateInvalid = "Het kenteken van dit voertuig is ongeldig (druk op F8 voor meer details)",
  currentlyInRagdollState = "Je bent momenteel in ragdoll status",
  vehicleDoesNotExistContactAdmin = "Het voertuig bestaat niet. Neem contact op met een admin!",
  vehicleSecurityBreachDetected = "Voertuig beveiligingsinbreuk gedetecteerd",

  -- v2: Admin vehicles
  allVehicles = "Alle voertuigen",
  unassignedVehicles = "Geen dealer",
  searchDealerships = "Dealers zoeken...",

  -- v2: Trucking mission
  truckingGetInTruck = "Stap in de vrachtwagen op de gemarkeerde locatie om je levering te starten",
  truckingDriveToDelivery = "Rijd naar de afleverlocatie",
  truckingCompleteDelivery = "Voltooi de levering",
  truckingDeliveryComplete = "Levering voltooid: Je hebt de levering succesvol voltooid!",
  truckingDeliveryFailed = "Levering mislukt: Er ging iets mis met de levering",
  truckingDriveToPickup = "Rijd naar het ophaalpunt om de trailer op te halen",
  truckingMissionFailedSpawnCargo = "Missie mislukt: Kon de cargo trailer niet spawnen",
  truckingMissionFailedFindCargo = "Missie mislukt: Kon de gespawnde cargo niet vinden",
  truckingVehiclesLoaded = "%{count} voertuig%{s} geladen",
  truckingWrongTrailer = "Verkeerde trailer! Je moet de juiste missie trailer aankoppelen.",
  truckingTrailerAttached = "Trailer aangekoppeld - klaar om verder te gaan",
  truckingDriveToPickupLocation = "Rijd naar het ophaalpunt",
  truckingWaitingForVehicles = "Wachten op het laden van voertuigen...",
  truckingDriveUnderTrailer = "Rijd onder de trailer om hem aan te koppelen",
  truckingGetInTruckContinue = "Stap in de vrachtwagen om verder te gaan",
  truckingMissionStarted = "Transport missie gestart: Ophaalpunt - %{location}",
  truckingMissionCancelled = "Missie geannuleerd: Je hebt de transport missie geannuleerd",
  truckingNoActiveMission = "Geen actieve transport missie om te annuleren",
  deliveryNotPrepared = "Levering niet voorbereid - probeer het opnieuw",
  deliveryConfigMismatch = "Levering configuratie komt niet overeen",
  deliveryPreparationExpired = "Leveringsvoorbereiding verlopen - probeer het opnieuw",
  noTruckingVehicleCoordinates = "Geen transport voertuig coördinaten ingesteld",
  pickupLocationUnavailable = "Ophaalpunt niet meer beschikbaar - probeer het opnieuw",
  failedToSpawnTruck = "Kon vrachtwagen niet spawnen",
  clientFailedToStartMission = "Client kon missie niet starten",

  -- v2: Trucking UI/Keys
  keyDismiss = "Sluiten",
  keyDeliverCargo = "Lever cargo af",
  keyContinueToDelivery = "Doorgaan naar levering",
  startDeliveryMission = "Start leveringsmissie",
  orderDetails = "Besteldetails",
  pickupLocation = "Ophaalpunt",
  deliveryStatus = "Leveringsstatus",
  selectOrders = "Selecteer bestellingen",
  carTrailer = "Autotransporter",
  container = "Container",
  deliveryRoute = "Leveringsroute",
  startDelivery = "Start levering",

  -- v2: Direct sales UI
  waitingForCustomer = "Wachten op klant",
  cancelRequest = "Annuleer aanvraag",
  saleComplete = "Verkoop voltooid!",
  done = "Klaar",
  saleDeclined = "Verkoop afgewezen",
  close = "Sluiten",

  -- v2: Display vehicle placement
  movement = "Beweging",
  rotate = "Roteren",
  forward = "Vooruit",
  backward = "Achteruit",
  left = "Links",
  right = "Rechts",
  rotateLeft = "Naar links draaien",
  rotateRight = "Naar rechts draaien",

  -- v2: Showroom misc
  originalPrice = "Originele prijs",
  discount = "Korting",
  createInteraction = "Interactie aanmaken",
  viewAll = "Alles bekijken",
  fetchingPlayers = "Spelers ophalen",
  refresh = "Vernieuwen",
  loadingPlayers = "Spelers laden...",
  failedToLoadPlayers = "Kon spelers niet laden",
  selectAPlayer = "Selecteer een speler",
  failedToLoadPlayersRetry = "Kon spelers niet laden. Klik op 'Vernieuwen' om opnieuw te proberen.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Zelfbedienings-dealer",
  categories = "Categorieën",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Locaties",
  createNew = "Nieuw aanmaken",
  enable = "Inschakelen",
  disable = "Uitschakelen",
  loading = "Laden...",
  errors = "Fouten",
  update = "Bijwerken",
  create = "Aanmaken",

  -- v2: Dealership creation/editing
  createDealership = "Dealer aanmaken",
  editDealership = "Dealer bewerken",
  essentials = "Essentieel",
  advanced = "Geavanceerd",
  noDealershipLocations = "Geen dealerlocaties",
  noDealershipLocationsDesc = "U kunt een nieuwe locatie toevoegen, importeren vanuit uw configuratie (als u migreert van v1) of automatisch standaardlocaties laten toevoegen.",

  -- v2: Location sections
  dealershipZone = "Dealerzone",
  showroomAndManagement = "Showroom en beheer",
  openShowroom = "Open showroom",
  openManagement = "Open beheer",
  enableSellVehicle = "Voertuigverkoop inschakelen",
  percentageOfVehicleValue = "Percentage % van voertuigwaarde",
  enablePurchase = "Aankoop inschakelen",
  purchasedVehicleSpawn = "Spawn gekocht voertuig",
  enableTestDrive = "Proefrit inschakelen",
  testDriveVehicleSpawn = "Spawn proefrit voertuig",
  truckDelivery = "Vrachtwagenlevering",
  truckDeliveryVehicleSpawn = "Spawn leveringsvoertuig",

  -- v2: Location advanced settings
  paymentMethods = "Betaalmethoden",
  supportsFinancing = "(ondersteunt financiering)",
  enableFinance = "Financiering inschakelen",
  cameraPreset = "Camera",
  preset = "Voorinstelling",
  custom = "Aangepast",
  vehiclePosition = "Voertuigpositie",
  zoomPositions = "Zoomposities (komma-gescheiden)",
  zoomPositionsPlaceholder = "voorbeeld: 5,8,12,8",
  vehicleColour = "Voertuigkleur",
  selectionType = "Selectietype",
  noColourSelection = "Geen kleurselectie",
  rgbColourWheel = "RGB-kleurenwiel",
  listOfRgbColours = "Lijst van RGB-kleuren",
  listOfColourIds = "Lijst van kleur-ID's",
  accessControl = "Toegangscontrole",
  showroomJobWhitelist = "Showroom baan-whitelist",
  showroomGangWhitelist = "Showroom gang-whitelist",
  societyPurchaseJobWhitelist = "Organisatie-aankoop baan-whitelist",
  societyPurchaseGangWhitelist = "Organisatie-aankoop gang-whitelist",
  setInGame = "In-game instellen",
  addNew = "Nieuw toevoegen",

  -- v2: Job/Gang whitelist editor
  job = "Baan",
  gang = "Gang",
  jobWhitelist = "Baan-whitelist",
  gangWhitelist = "Gang-whitelist",
  addJob = "Baan toevoegen",
  addGang = "Gang toevoegen",
  editJob = "Baan bewerken",
  editGang = "Gang bewerken",
  manageJobs = "Banen beheren",
  manageGangs = "Gangs beheren",
  jobName = "Baannaam",
  gangName = "Gangnaam",
  selectGrades = "Selecteer rangen",
  selectAll = "Alles selecteren",
  deselectAll = "Alles deselecteren",
  invalidJobName = "Ongeldige baannaam. Controleer uw framework-configuratie.",
  invalidGangName = "Ongeldige gangnaam. Controleer uw framework-configuratie.",
  grades = "Rangen",
  noJobsConfigured = "Geen banen geconfigureerd",
  noGangsConfigured = "Geen gangs geconfigureerd",
  click = "Klik",
  toGetStarted = "om te beginnen.",
  more = "meer",
  jobPlaceholder = "Bijvoorbeeld: cardealer",
  jobOptionalDescription = "Koppel optioneel dealerrollen aan een framework-baan. Wanneer werknemers worden aangenomen/ontslagen, wordt hun framework-baan ook bijgewerkt.",
  jobRankPermissions = "Baan-rang machtigingen",
  roleToJobRankMapping = "Rol-naar-baan-rang toewijzing",
  addPerm = "Machtiging toevoegen",

  -- v2: Colour selector
  searchColours = "Zoek kleuren...",
  noColoursFound = "Geen kleuren gevonden",

  -- v2: Interactions creator
  noInteractions = "Geen interacties",
  highlightInteractions = "Interacties markeren",
  explorationMode = "Verkenningmodus",
  pressEsc = "Druk op ESC",
  toWalkAround = "om rond te lopen",
  toReturnToUI = "om terug te keren naar UI",
  points = "punten",
  location = "locatie",
  manageLocations = "Locaties beheren",

  -- v2: Interaction modal
  interactionType = "Type",
  nicknameOptional = "Bijnaam (Optioneel)",
  invalidModel = "Ongeldig model",
  failedToValidateModel = "Kon model niet valideren",
  pedScenario = "Ped-scenario",
  coords = "Coördinaten",
  size = "Grootte",
  blip = "Blip",
  enableBlip = "Blip inschakelen",
  blipIconId = "Blip-icoon-ID",
  blipColourId = "Blip-kleur-ID",
  blipSize = "Blip-grootte",
  marker = "Marker",
  enableMarker = "Marker inschakelen",
  markerStyleId = "Marker-stijl-ID",
  markerSize = "Marker-grootte",
  markerColor = "Marker-kleur",
  markerBobUpAndDown = "Op en neer bewegen",
  markerFaceCamera = "Naar camera gericht",
  markerRotate = "Roteren",
  markerDrawOnEnts = "Tekenen op entiteiten",
  updatePosition = "Positie bijwerken",
  setPosition = "Positie instellen",

  -- v2: Interaction types
  interactionPoint = "Punt",
  interactionPointDesc = "Enkel verstelbaar punt, met optionele marker",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Multi-coördinaat zone voor het maken van een specifiek interactiegebied",
  interactionVehicle = "Voertuig",
  interactionVehicleDesc = "Spawn een voertuigmodel, ideaal voor target of 3D-tekst UI interactiemethoden",
  interactionObject = "Object",
  interactionObjectDesc = "Spawn een objectmodel, ideaal voor target of 3D-tekst UI interactiemethoden",
  interactionPed = "Ped",
  interactionPedDesc = "Spawn een ped-model met optioneel scenario, ideaal voor target of 3D-tekst UI interactiemethoden",

  -- v2: Import modal
  importLocationsTitle = "Locaties importeren",
  syncStockLabel = "Voorraad synchroniseren",
  syncStockDescription = "Voertuigen toevoegen aan voorraad van elke dealer op basis van categorieën",
  importSourceSelectorDesc = "U kunt een set standaardlocaties importeren voor een kant-en-klare setup, of uw bestaande locaties importeren vanuit uw configuratie als u migreert van Dealerships v1.",
  importSourceSelectorSkipDesc = "Locaties die al bestaan in de database worden overgeslagen; alleen nieuwe locaties worden geïmporteerd.",
  successfullyImported = "Succesvol geïmporteerd",
  alreadyExist = "Bestaat al",
  defaultLocations = "Standaardlocaties",
  defaultLocationsDesc = "Importeer vooraf geconfigureerde dealerlocaties (PDM, Luxe, Boten, Lucht, Vracht)",
  existingConfig = "Bestaande configuratie",
  existingConfigDesc = "Importeer locaties vanuit uw config.lua (voor v1-migratie)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Wilt u automatisch voertuigen toevoegen aan de voorraad van deze dealer op basis van geselecteerde categorieën?",
  categorySyncEditDesc = "U heeft de categorieën voor deze dealer gewijzigd. Wilt u de voertuigvoorraad automatisch bijwerken?",
  addVehicles = "Voertuigen toevoegen",
  removeVehicles = "Voertuigen verwijderen",
  fromNewCategories = "van nieuwe categorieën",
  fromSelectedCategories = "van geselecteerde categorieën",
  fromRemovedCategories = "van verwijderde categorieën",
  categoriesAdded = "Categorieën toegevoegd:",
  categoriesRemoved = "Categorieën verwijderd:",
  skip = "Overslaan",
  syncStock = "Voorraad synchroniseren",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Bronbeschikbaarheid controleren...",
  vehiclesAvailableToImport = "voertuigen beschikbaar om te importeren",
  includesDealershipIds = "bevat dealer-ID's",
  sourceUnavailable = "Bron niet beschikbaar",
  noVehiclesAdminDescription = "U kunt voertuigen handmatig toevoegen of importeren vanuit uw framework.",
  appendBehaviour = "Toevoegen",
  overwriteBehaviour = "Overschrijven",
  appendDescription = "Alleen nieuwe voertuigen toevoegen die nog niet in de database bestaan",
  overwriteDescription = "Alle bestaande voertuiggegevens verwijderen en opnieuw importeren",
  stockAssignmentMethod = "Voorraadtoewijzingsmethode",
  useDealershipIdsFromSource = "Dealer-ID's van bron gebruiken",
  matchByVehicleCategory = "Matchen op voertuigcategorie",
  byShopDescription = "Voertuigen worden toegewezen aan dealers op basis van het 'shop'-veld in de brongegevens",
  byCategoryDescription = "Voertuigen worden toegewezen aan dealers met overeenkomende categorieën",
  overwriteWarning = "Waarschuwing: Overschrijven verwijdert alle bestaande voertuigen, bestellingen, showroomvoertuigen en verkoopgegevens.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX voertuigentabel",
  selectCategory = "Selecteer een categorie",

  -- v2: Management menu items
  vehiclesMenu = "Voertuigen",
  displayVehiclesMenu = "Showroomvoertuigen",
  ordersMenu = "Bestellingen",
  salesMenu = "Verkopen",
  bankAccountMenu = "Bankrekening",
  employeesMenu = "Werknemers",
  couponsMenu = "Kortingsbonnen",
  settingsMenu = "Instellingen",
  noPermissionAccessManagement = "U heeft geen toestemming om beheersfuncties te openen.",
  backToAdmin = "Terug naar beheer",
  viewingAsAdmin = "WEERGAVE ALS ADMIN",

  -- v2: Coupons table
  code = "Code",
  uses = "Gebruik",
  perPlayer = "Per speler",
  never = "Nooit",
  noCoupons = "Geen kortingsbonnen",
  noCouponsDescription = "Klanten kunnen een kortingsbon invoeren bij de voertuigaankoop en geld besparen.",

  -- v2: Coupon modal
  couponCodeLabel = "Kortingscode",
  couponCodePlaceholder = "bijv. ZOMER2024 of BESPAAR10",
  couponCodeHelp = "Voer een aangepaste code in (max. 25 tekens, alleen letters, cijfers en streepjes) of klik op 'Genereren'.",
  maxNumberOfUsesPlaceholder = "Maximum aantal keren gebruik",
  maxUsesPerPlayerPlaceholder = "Maximum gebruik per speler",
  vehicleRestrictionsPlaceholder = "Voer spawncodes in gescheiden door komma's (bijv. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Toestaan bij gefinancierde aankopen",
  createCoupon = "Kortingsbon aanmaken",
  updateCoupon = "Kortingsbon bijwerken",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kortingscode is vereist",
  couponCodeMaxLength = "Code mag maximaal 25 tekens bevatten",
  couponCodeInvalidChars = "Code mag alleen hoofdletters, cijfers en streepjes bevatten",
  discountTypeRequired = "Kortingstype is vereist",
  discountValueRequired = "Kortingswaarde is vereist",
  discountValueMin = "Kortingswaarde moet groter zijn dan 0",
  discountValueMaxPercent = "Percentage mag niet hoger zijn dan 100",
  maxUsesRequired = "Maximum gebruik is vereist",
  maxUsesMin = "Moet minimaal 1 zijn",
  perPlayerLimitRequired = "Limiet per speler is vereist",
  expiryDateRequired = "Vervaldatum is vereist",
  vehicleRestrictionsRequired = "Voertuigbeperkingen zijn vereist",
  categoryRestrictionsRequired = "Categoriebeperkingen zijn vereist",
  selectAtLeastOneCategory = "Selecteer minimaal één categorie",

  -- v2: Dashboard
  today = "Vandaag",
  thisMonth = "Deze maand",
  allTime = "Altijd",
  recentSales = "Recente verkopen",
  noSalesYet = "Nog geen verkopen!",
  noSalesDescription = "Voertuigverkopen verschijnen hier nadat er een is gemaakt.",
  past7Days = "Afgelopen 7 dagen",
  past6Months = "Afgelopen 6 maanden",
  numberOfSales = "Aantal verkopen",
  noDataAvailableForPeriod = "Geen gegevens beschikbaar voor deze periode",

  -- v2: Display vehicles
  displayVehiclesDescription = "Showroomvoertuigen zijn vaste showroommodellen die worden gebruikt om uw inventaris te tonen en klanten aan te moedigen tot aankoop.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework-banen ingeschakeld",
  frameworkJobsDescription = "Werknemersbeheer wordt afgehandeld via het baansysteem van het framework. Spelers met de dealerbaan krijgen automatisch toegang op basis van hun rang. Configureer baanmachtigingen in de locatie-instellingen van het beheerpaneel.",
  joinedColumn = "Toegetreden",
  youBadge = "Jij",

  -- v2: Orders
  noOrdersTitle = "Geen bestellingen",
  noOrdersDescription = "Om een bestelling te plaatsen, open het tabblad 'Voertuigen' en klik op 'Bestellen' bij het voertuig dat u wilt aanvullen.",
  inProgress = "In behandeling",
  awaitingDelivery = "Wachten op levering",
  orderedBy = "Besteld door",
  viewDeliveryInfo = "Leveringsinfo bekijken",

  -- v2: Delivery
  startDeliveryMissionTitle = "Start leveringsmissie",
  startDeliveryDescription = "U staat op het punt een leveringsmissie te starten voor deze voertuigbestelling. U moet naar het ophaalpunt rijden, de vrachttrailer ophalen en terugleveren aan de dealer.",
  totalDistanceAndDriveTime = "Totale afstand en rijtijd",
  roundTrip = "retour",
  deliveryCompleteTitle = "Levering voltooid",
  deliveryInProgressTitle = "Levering bezig",
  deliveredAt = "Geleverd om:",
  startedAt = "Gestart om:",
  deliveredBy = "Geleverd door:",
  beingDeliveredBy = "Wordt geleverd door:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Geen bestellingen beschikbaar voor levering. Bestellingen moeten klaar zijn en niet al in een actieve levering.",
  confirmDeliveryTitle = "Levering bevestigen",
  configureDeliveryTitle = "Levering configureren",
  trailerCapacityExceeded = "Trailercapaciteit overschreden! U heeft %{usedSlots} slots geselecteerd maar het maximum is %{maxSlots} slots.",
  smallVehiclesSlotInfo = "Onthoud: kleine voertuigen gebruiken 1 slot, middelgrote voertuigen gebruiken 1.5 slots.",
  fetchingRoute = "Ophalen...",
  getRouteButton = "Route ophalen",
  selectTrailerType = "Selecteer trailertype",
  carTrailerLabel = "Autotransporter",
  smallMedium = "(Klein/Middel)",
  containerLabel = "Container",
  large = "(Groot)",
  carTrailerDescription = "Autotransporter heeft 2 rijen. Elke rij past 3 kleine (1 slot elk) of 2 middelgrote (1.5 slots elk). Maximaal 6 slots totaal.",
  containerDescription = "Containertrailer vervoert 1 groot voertuig",
  selectOrdersTitle = "Selecteer bestellingen",
  slots = "slots",
  noOrdersForTrailerType = "Geen bestellingen beschikbaar voor dit trailertype.",
  qty = "Aant:",
  inTransit = "onderweg",
  totalVehicles = "Totaal voertuigen:",
  estimatedTime = "Geschatte tijd:",
  unknown = "Onbekend",

  -- v2: Sales
  salesEmptyDescription = "Voertuigverkopen verschijnen hier nadat er een is gemaakt.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Bestelling geplaatst!",
  orderPlacedTruckingDescription = "Uw bestelling is klaar om op te halen. Ga naar de bestellingenpagina om deze te voltooien.",
  orderPlacedTimedDescription = "Uw bestelling wordt binnen %{value} minuten geleverd.",
  goToOrders = "Naar bestellingen",
  noStockAvailableDescription = "Er is geen voorraad beschikbaar voor dit voertuig. De globale voorraadlimiet is bereikt.",
  stockUpdatedDescription = "De voorraadhoeveelheid is succesvol bijgewerkt.",

  -- v2: Direct sales tablet
  activeTestDrives = "Actieve proefritten",
  tracking = "Tracking",
  track = "Volgen",
  endButton = "Beëindigen",
  endTestDriveTitle = "Proefrit beëindigen",
  endTestDriveConfirmation = "Weet u zeker dat u deze proefrit wilt beëindigen? Het voertuig wordt verwijderd en inzittenden worden niet teruggeteleporteerd naar de dealer.",
  vehicleLocationOnMap = "De voertuiglocatie is op uw kaart geplaatst.",
  sell = "Verkopen",
  couponCodeOptional = "Kortingscode (Optioneel)",
  pleaseEnterCouponCode = "Voer een kortingscode in",
  invalidCouponCode = "Ongeldige kortingscode",
  failedToValidateCoupon = "Kon kortingsbon niet valideren",
  apply = "Toepassen",
  applying = "Toepassen...",
  allStock = "Alle voorraad",
  inStockFilter = "Op voorraad",
  outOfStockFilter = "Niet op voorraad",
  noResultsFound = "Geen resultaten gevonden",
  noResults = "Geen resultaten",
  noVehiclesMatchSearch = "Geen voertuigen komen overeen met uw zoekopdracht",
  noVehiclesMatchFilters = "Geen voertuigen komen overeen met uw huidige filters",
  noItemsMatchSearch = "Geen items komen overeen met uw zoekopdracht",
  noItemsMatchFilters = "Geen items komen overeen met uw huidige filters",
  selectColour = "Selecteer kleur",
  refreshNearbyPlayers = "Spelers in de buurt vernieuwen",
  you = "Jij",
  items = "items",
  waitingForCustomerToRespond = "Wachten op reactie van klant...",
  vehicleSpawnedMessage = "Het voertuig is gespawnd op het punt op uw kaart - breng de klant ernaartoe.",
  customerDeclinedMessage = "De klant heeft het aankoopverzoek afgewezen.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "HIER TEKENEN",
  acceptAndPurchase = "Accepteren en kopen",
  couponApplied = "Kortingsbon %{code} toegepast! Besparing %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Minimaal 3 punten nodig om zone te voltooien! (Momenteel %{value})",
  addPoint = "Punt toevoegen",
  removeLast = "Laatste verwijderen",
  completeZone = "Zone voltooien",
  spawnPreview = "Spawn-voorbeeld",
  up = "Omhoog",
  down = "Omlaag",
  confirm = "Bevestigen",
  placePoint = "Punt plaatsen",
  radius = "Straal",

  -- v2: Blip labels
  soldVehicleLocation = "Locatie verkocht voertuig",
  testDriveVehicleBlip = "Proefrit voertuig",

  -- v2: Stock sync
  stockSyncResult = "Voorraadsynchronisatie: %{added} toegevoegd, %{removed} verwijderd",
  stockSyncAdded = "Voorraadsynchronisatie: %{value} voertuigen toegevoegd",
  importSuccessful = "Import succesvol! %{imported} voertuigen geïmporteerd (%{total} totaal)",

  -- v2: Tooltip actions
  findOnMap = "Vind op kaart",
  adminPanel = "Beheerpaneel",

  -- v2: Common dropdown
  selectOne = "Selecteer één",
}
