Locales = Locales or {}

Locales['no'] = {
  -- UI
  vehicle = "Kjøretøy",
  vehicles = "Kjøretøy",
  dealership = "Forhandler",
  dealerships = "Forhandlere",
  vehiclesCount = "Kjøretøy",
  dealersCount = "Forhandlere",
  accountBalance = "Saldo",
  bank = "Bankkonto",
  cash = "Kontant",
  amount = "Beløp",
  societyFund = "Bedriftskonto",
  paymentSource = "Betalingsmetode",
  purchase = "Kjøp",
  personalPurchase = "Personlig Kjøp",
  societyPurchase = "Bedrifts Kjøp",
  purchaseType = "Kjøpstype",
  deposit = "Innskudd",
  withdraw = "Uttak",
  all = "Alle",
  yes = "Ja",
  no = "Nei",
  add = "Legg til",
  edit = "Endre",
  id = "ID",
  created = "Opprettet",
  type = "Type",
  name = "Navn",
  owner = "Eier",
  bankBalance = "Saldo",
  status = "Status",
  back = "Tilbake",
  previous = "tidligere",
  next = "Neste",
  admin = "Admin Meny",
  vehiclesAdmin = "Kjøretøy Admin",
  dealershipsAdmin = "Forhandler Admin",
  search = "Søk",
  noDealershipsFound = "Ingen forhandlere funnet",
  noVehicles = "Ingen kjøretøy funnet",
  page = "Side",
  of = "av",
  every = "hver",
  show = "Vis",
  active = "Aktiv",
  activeFinance = "Aktiv Finansiering",
  failed = "Betaling Feilet",
  removed = "Fjernet",
  setOwner = "Velg Eier",
  manage = "Administrere",
  deleteData = "Fjern Data",
  deleteVehicle = "Slett Kjøretøy",
  delete = "Slett",
  deleteConfirmation = "Er du sikker?",
  deleteConfirmationDanger = "Er du sikker? Denne handlingen kan ikke reverseres.",
  setDealershipOwner = "Velg Forhandler Eier",
  overwriteDealerPrices = "Overkjør forhandlerpriser",
  nearbyPlayers = "Personer i nærheten",
  noPlayersNearby = "Ingen personer i nærheten",
  selectPlayer = "Velg spiller",
  required = "Påkrevd",
  forExample = "For eksempel",
  spawnCode = "Spawn Kode",
  brand = "Merke",
  model = "Modell",
  category = "Kategori",
  price = "Pris",
  import = "Importer",
  importing = "Importerer",
  importBehaviour = "Import Metode",
  importVehicles = "Importer kjøretøy",
  importFrom = "Importer Fra",
  dashboard = "Hovedmeny",
  displayVehicle = "Still ut kjøretøy",
  displayVehicles = "Still ut kjøretøy",
  orders = "Ordre",
  sales = "Salg",
  vehiclesOnDisplay = "Kjøretøy på utstilling",
  employees = "Ansatte",
  settings = "Instillinger",
  switchVehicle = "Bytt kjøretøy",
  remove = "Fjern",
  noDisplayVehicles = "Ingen kjøretøy på utstilling",
  selectVehicle = "Velg kjøretøy",
  colour = "Farge",
  placeVehicle = "Plasser kjøretøy",
  orderVehicle = "Bestill kjøretøy",
  cancelOrder = "Kanseller bestilling",
  delivery = "Leveranse",
  delivered = "Levert",
  noOrders = "Ingen ordre funnet",
  quantity = "Antall",
  totalCost = "Totale utgifter",
  totalSales = "Totale salg",
  noSales = "Ingen salg funnet",
  paid = "Betalt",
  owed = "Å betale",
  dealershipName = "Forhandlernavn",
  save = "Lagre endringer",
  cancel = "Avbryt",
  notEnoughMoney = "Ikke nok penger",
  placeOrder = "Legg inn bestilling",
  purchaseCost = "Kjøpskostnad",
  salePrice = "Salgspris",
  inStock = "På lager",
  outOfStock = "Utsolgt",
  placeVehiclePrompt = "Trykk %{value} for å plassere kjøretøy. Du kan fortsette å justere etterpå!",
  remaining = "Gjenstående",
  prePurchaseRepoWarning = "Hvis ikke du kan betale for finansieringen, vil kjøretøyet ditt bli tatt tilbake!.",
  repossessionWarning = "Din siste betalingen mislyktes - kjøretøyet blir tatt tilbake om du ikke gjennomfør en betaling til finansieringen nå! .",
  recurringPayment = "Gjentakende Avdrag",
  remainingBalance = "Gjenstående Saldo ",
  remainingPayments = "Gjenstående Avdrag",
  paymentTakenEvery = "Betaling tas hver",
  hours = "time(r)",
  seconds = "sekunder",
  nextPayment = "Den neste betalingen skjer om",
  makePayment = "Betal et avdrag",
  vehicleRepossessed = "Kjøretøyet vil bli tatt tilbake",
  payInFull = "Fullfør nedbetaling",
  earlyPaymentConfirmation = "Er du sikker på at du vil gjennomføre et avdrag?",
  financedVehicles = "Finansierte Kjøretøy",
  noFinancedVehicles = "Du har ingen kjøretøy med aktive nedbetalinger",
  financeBreakdown = "Finansplan",
  initialPayment = "Førstegangsbetaling",
  payments = "Betalinger",
  length = "Lengde",
  interest = "Renter",
  totalPayable = "Totalt å betale",
  leaveShowroom = "Forlat utstillingsrom",
  handling = "Kjøreegenskaper",
  topSpeed = "Topp Hastighet",
  power = "Effekt",
  torque = "Moment",
  brake = "Bremser",
  financing = "Finansiering",
  financingAvailable = "Finansiering tilgjengelig",
  paymentsOf = "betalinger av",
  clear = "Tøm",
  testDrive = "Prøvekjøring",
  allCategories = "Alle Kategorier",
  sortByName = "Sorter etter: Navn",
  sortByAvailability = "Sorter etter: Tilgjengelighet",
  sortByCheapest = "Sorter etter: Billigst",
  sortByMostExpensive = "Sorter etter: Dyrest",
  sortByNewest = "Sorter etter: Nyest",
  purchaseVehicle = "Kjøp Kjøretøy",
  purchaseFor = "Kjøp for",
  selectSociety = "Velg Firma",
  financeOverPayments = "Finansiering over %{value} betalinger",
  payToday = "Betal i dag",
  financeThen = "Da",
  seeFullBreakdown = "Se fullstendig oversikt",
  testDriveExit = "Du kan forlate kjøretøyet til en hver tid for å avslutte prøveturen.",

  -- NOTIFICATIONS
  purchaseSuccess = "Gratulerer med nytt kjøretøy!",
  depositSuccess = "Innskudd vellykket",
  withdrawSuccess = "Uttak vellykket",
  errorNotEnoughMoney = "Du har ikke nok penger",
  errorVehicleOutOfStock = "Dette kjøretøyet er ikke på lager",
  errorCannotAffordVehicle = "Du har ikke råd til dette kjøretøyet",
  vehicleFinancePaymentMade = "Nedbetaling gjennomført %{value}",
  vehicleFinancePaidOff = "Gratulerer, du har nå betalt ferdig kjøretøyet, og er nå fulleier %{value}",
  vehicleFinancePaymentFailed = "Nedbetaling for kjøretøyet feilet %{value}",
  vehicleFinanceRepossessedSoon = "Du må gjennomføre et innskudd for kjøretøyet ditt %{value} ellers vil kjøretøyet bli tatt tilbake",
  vehicleFinanceRepossessed = "På grunn av manglende betaling, har kjøretøyet ditt blitt tatt tilbake til forhandler. Gjelder kjøretøy med skiltnummer %{value}",
  dealershipNotEnoughFunds = "Forhandleren har ikke nok penger",
  dealershipVehiclesOrdered = "Bestilling av kjøretøy gjennomført",
  dealershipOrderCancelled = "Bestillingen ble kansellert",
  errorVehicleWithSpawnCodeExists = "Et kjøretøy med denne spawn koden finnes allerede",
  errorExitVehicle = "Du må forlate kjøretøyet først",

  -- NEW v1.1
  purchaseRequest = "Kjøpsforespørsel",
  sendRequest = "Send forespørsel",
  dealer = "Forhandler",
  financed = "Finansiert",
  signHere = "Signer her",
  signFirstError = "Vennligst signer først",
  denyRequest = "Nekte forespørsel",
  playerTooManyFinancedVehicles = "Spilleren har for mange finansierte kjøretøyer",
  employeePermissionsError = "Du har ikke nødvendige ansattes tillatelser",
  managerRole = "Sjef",
  supervisorRole = "Veileder",
  salesRole = "Salg",
  ownerRole = "Eieren",
  employmentRequest = "Ansettelsesforespørsel",
  accept = "Aksepterer",
  jobOfferDescription = "Du har blitt tilbudt en jobb på \"%{value}\" forhandler.Vil du godta?",
  pending = "Pending",
  employeeHiredMsg = "Kjøretlyforhandler tilbud ble akseptert!",
  employeeRejectedMsg = "Kjøretlyforhandler tilbud ble avvist",
  sellVehicle = "Selg kjøretøy",
  vehicleTerms = "Kjøretøyer",
  financePayments = "Finansbetalinger",
  commission = "Kommisjon",
  role = "Rolle",
  firedNotification = "Du har fått sparken fra \"%{value}\" forhandler",
  dealershipTooFarAway = "Du er ikke i nærheten av noen forhandlere",
  restoreDisplayVehicles = "Gjenopprett showroom",
  customer = "Kunde",
  lessThanAMin = "Mindre enn ett minutt",
  mins = "min(s)",
  notInVehicle = "Du sitter ikke i et kjøretøy",
  notYourVehicleError = "Dette kjøretøyet tilhører ikke deg",
  vehicleFinancedError = "Du kan ikke selge dette kjøretøyet fordi det har finansbetalinger utestående",
  dealershipDoesntSellVehicle = "Dette forhandleren kan ikke kjøpe dette kjøretøyet",
  dealershipWantsYourVehicle = "Gratulerer! Denne forhandleren vil gjerne kjøpe kjøretøyet ditt.",
  purchasePrice = "Tilbudt pris: ",

  spawnCodeInvalid = "Ugyldig spawn-kode",
  salesRep = "Salgsrepresentant",
  directSaleAccepted = "Direktesalgsforespørsel akseptert! Din provisjon er betalt.",
  directSaleRejected = "Direktesalgsforespørsel avvist",

  displayVehicleOutsideZone = "Utstillingskjøretøy må plasseres innenfor forhandlersonen",
  serverAdmin = "Serveradmin",
  selfService = "Selvbetjening",
  owned = "Eid",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Ugyldig betalingsmetode",
  paymentMethodNoFinance = "Denne betalingsmetoden støtter ikke finansiering",
  couldNotGeneratePlate = "Kunne ikke generere bilskilt",
  invalidCoupon = "Ugyldig kupong: %{value}",
  tooManyFinancedVehicles = "Du har for mange finansierte kjøretøy",
  couldNotSpawnVehicle = "Kunne ikke opprette kjøretøy",

  -- v2: Permissions
  insufficientPermissions = "Utilstrekkelige tillatelser",

  -- v2: Coupons
  couponCodeAlreadyExists = "Denne kupongkoden finnes allerede",
  failedToCreateCoupon = "Kunne ikke opprette kupong",
  couponCreatedSuccessfully = "Kupong opprettet",
  couponNotFound = "Kupong ikke funnet",
  couponUpdatedSuccessfully = "Kupong oppdatert",
  failedToDeleteCoupon = "Kunne ikke slette kupong",
  couponDeletedSuccessfully = "Kupong slettet",
  editCoupon = "Rediger kupong",
  addCoupon = "Legg til kupong",
  couponCode = "Kupongkode",
  generating = "Genererer...",
  generate = "Generer",
  discountType = "Rabattype",
  percentageOff = "Prosentrabatt",
  amountOff = "Beløpsrabatt",
  discountValue = "Rabattverdi",
  unlimitedTotalUses = "Ubegrenset total bruk",
  unlimitedUsesPerPlayer = "Ubegrenset bruk per spiller",
  setExpiryDate = "Angi utløpsdato",
  restrictToSpecificVehicles = "Begrens til spesifikke kjøretøy",
  restrictToSpecificCategories = "Begrens til spesifikke kategorier",
  allowUseWithFinance = "Tillat bruk med finansiering",
  deleteCoupon = "Slett kupong",
  inactive = "Inaktiv",
  expired = "Utløpt",
  maxUses = "Maks bruk",
  coupons = "Kuponger",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Bare serveradmins kan ansette seg selv",
  playerNotFound = "Spiller ikke funnet",
  failedToHireEmployee = "Kunne ikke ansette medarbeider",
  failedToFireEmployee = "Kunne ikke sparke medarbeider",
  failedToUpdateEmployeeRole = "Kunne ikke oppdatere medarbeiders rolle",
  hireEmployee = "Ansett medarbeider",
  fireEmployee = "Spark medarbeider",
  editRole = "Rediger rolle",
  fire = "Spark",
  changeRole = "Endre rolle",
  updateRole = "Oppdater rolle",

  -- v2: Test drives
  maxTestDrivesReached = "Denne forhandleren har nådd maksimalt antall aktive prøvekjøringer",
  testDriveNotEnabled = "Prøvekjøringer er ikke aktivert hos denne forhandleren",
  noTestDriveSpawnCoords = "Ingen prøvekjøring spawn-koordinater konfigurert for denne forhandleren",
  couldNotSpawnTestDriveVehicle = "Kunne ikke opprette prøvekjøringskjøretøy",
  couldNotGetPlateFromServer = "Kunne ikke hente bilskilt fra server",
  couldNotRegisterTestDriveVehicle = "Kunne ikke registrere prøvekjøringskjøretøy",
  testDriveEndedByEmployee = "Prøvekjøringen ble avsluttet av en annen medarbeider",
  trackingVehicleLocation = "Sporer kjøretøyposisjon...",
  directSaleCancelled = "Salgsforespørselen ble kansellert av selgeren",
  testDriveKeysReceived = "Du har mottatt nøklene til prøvekjøringskjøretøyet",
  testDriveEndedCustomer = "Prøvekjøringen er avsluttet",
  starting = "Starter...",
  startTestDrive = "Start prøvekjøring",
  spawningTestDriveVehicle = "Oppretter prøvekjøringskjøretøy...",
  testDriveReady = "Prøvekjøring klar",
  testDriveWalkToVehicle = "Prøvekjøringskjøretøyet er opprettet på den merkede posisjonen på kartet ditt. Følg kunden til kjøretøyet. Etter at du har gitt nøklene til kunden, må du manuelt avslutte prøvekjøringen når de kommer tilbake.",
  givingKeys = "Gir nøkler...",
  continueAndGiveKeys = "Fortsett og gi nøkler",
  endTestDrive = "Avslutt prøvekjøring",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Ingen lagerbeholdning tilgjengelig for dette kjøretøyet",
  globalStockLimitExceeded = "Bare %{value} enheter tilgjengelig",
  orderNotFoundOrFulfilled = "Bestilling ikke funnet eller allerede fullført",
  priceBelowMinimum = "Prisen kan ikke være lavere enn %{value}",
  priceAboveMaximum = "Prisen kan ikke være høyere enn %{value}",
  stockUpdated = "Lager oppdatert",
  changesSaved = "Endringer lagret",
  noStockAvailable = "Ingen lagerbeholdning tilgjengelig",
  orderPlaced = "Bestilling lagt inn",
  remainingInStock = "gjenstår i globalt lager",
  exceedsStockLimit = "Overskrider lagergrense",
  setStockQty = "Angi lagerantall",
  invalidStockValue = "Vennligst oppgi en gyldig lagerverdi",
  errorSettingStock = "Feil ved innstilling av lager",
  stockQuantity = "Lagerantall",
  currentStock = "Nåværende lager",
  priceLimitsEnabled = "Aktiver prisgrenser",
  priceLimitsDescription = "Når aktivert kan forhandlersjefer bare sette priser innenfor det angitte området.",
  minPrice = "Minimumspris",
  maxPrice = "Maksimumspris",
  optional = "Valgfritt",
  unlimitedStock = "Ubegrenset lager",
  globalStockLimit = "Global lagergrense",
  globalStockLimitDescription = "Angi maksimalt antall enheter som kan bestilles hos alle forhandlere.",
  currentlyOrdered = "For øyeblikket bestilt",
  priceRange = "Prisområde",
  noMinimum = "Ingen minimum",
  noMaximum = "Ingen maksimum",
  vehicleStock = "Kjøretøylager",

  -- v2: Sales
  allSales = "Alle salg",
  paidInFull = "Betalt i sin helhet",
  salesVolume = "Salgsvolum",
  pastMonth = "Siste måned",
  pastYear = "Siste år",

  -- v2: Management misc
  exploitAttemptDetected = "Slutt å prøve å utnytte skriptet",
  dealershipNoJobConfigured = "Forhandleren har ingen jobb konfigurert",
  modelDoesNotMatchDb = "Kjøretøymodell samsvarer ikke med databasen",
  importFailed = "Import mislyktes: %{value}",
  notInDealershipZone = "Du må være innenfor en forhandler for å bruke denne kommandoen",
  notAnEmployee = "Du er ikke ansatt hos denne forhandleren.",
  failedToPrepareDelivery = "Kunne ikke forberede levering",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Kjøretøymodellen finnes ikke - kontakt en admin",
  vehiclePlateInvalid = "Bilskiltet til dette kjøretøyet er ugyldig (trykk F8 for mer detaljer)",
  currentlyInRagdollState = "Du er for øyeblikket i ragdoll-tilstand",
  vehicleDoesNotExistContactAdmin = "Kjøretøyet finnes ikke. Vennligst kontakt en admin!",
  vehicleSecurityBreachDetected = "Kjøretøy sikkerhetsbrudd oppdaget",

  -- v2: Admin vehicles
  allVehicles = "Alle kjøretøy",
  unassignedVehicles = "Ingen forhandler",
  searchDealerships = "Søk forhandlere...",

  -- v2: Trucking mission
  truckingGetInTruck = "Sett deg inn i lastebilen på den merkede posisjonen for å starte leveringen",
  truckingDriveToDelivery = "Kjør til leveringsstedet",
  truckingCompleteDelivery = "Fullfør levering",
  truckingDeliveryComplete = "Levering fullført: Du har fullført leveringen!",
  truckingDeliveryFailed = "Levering mislyktes: Noe gikk galt med leveringen",
  truckingDriveToPickup = "Kjør til hentepunktet for å hente tilhengeren",
  truckingMissionFailedSpawnCargo = "Oppdrag mislyktes: Kunne ikke opprette lasttilhenger",
  truckingMissionFailedFindCargo = "Oppdrag mislyktes: Kunne ikke finne opprettet last",
  truckingVehiclesLoaded = "%{count} kjøretøy lastet",
  truckingWrongTrailer = "Feil tilhenger! Du må koble til riktig oppdragstilhenger.",
  truckingTrailerAttached = "Tilhenger koblet til - klar til å fortsette",
  truckingDriveToPickupLocation = "Kjør til hentepunktet",
  truckingWaitingForVehicles = "Venter på lasting av kjøretøy...",
  truckingDriveUnderTrailer = "Kjør under tilhengeren for å koble til",
  truckingGetInTruckContinue = "Sett deg inn i lastebilen for å fortsette",
  truckingMissionStarted = "Transportoppdrag startet: Hentepunkt - %{location}",
  truckingMissionCancelled = "Oppdrag kansellert: Du kansellerte transportoppdraget",
  truckingNoActiveMission = "Ingen aktivt transportoppdrag å kansellere",
  deliveryNotPrepared = "Levering ikke forberedt - vennligst prøv igjen",
  deliveryConfigMismatch = "Leveringskonfigurasjon samsvarer ikke",
  deliveryPreparationExpired = "Leveringsforberedelse utløpt - vennligst prøv igjen",
  noTruckingVehicleCoordinates = "Transportkjøretøy-koordinater ikke satt",
  pickupLocationUnavailable = "Hentepunkt ikke lenger tilgjengelig - vennligst prøv igjen",
  failedToSpawnTruck = "Kunne ikke opprette lastebil",
  clientFailedToStartMission = "Klient kunne ikke starte oppdrag",

  -- v2: Trucking UI/Keys
  keyDismiss = "Lukk",
  keyDeliverCargo = "Lever last",
  keyContinueToDelivery = "Fortsett til levering",
  startDeliveryMission = "Start leveringsoppdrag",
  orderDetails = "Bestillingsdetaljer",
  pickupLocation = "Hentepunkt",
  deliveryStatus = "Leveringsstatus",
  selectOrders = "Velg bestillinger",
  carTrailer = "Biltransport",
  container = "Container",
  deliveryRoute = "Leveringsrute",
  startDelivery = "Start levering",

  -- v2: Direct sales UI
  waitingForCustomer = "Venter på kunde",
  cancelRequest = "Avbryt forespørsel",
  saleComplete = "Salg fullført!",
  done = "Ferdig",
  saleDeclined = "Salg avvist",
  close = "Lukk",

  -- v2: Display vehicle placement
  movement = "Bevegelse",
  rotate = "Roter",
  forward = "Fremover",
  backward = "Bakover",
  left = "Venstre",
  right = "Høyre",
  rotateLeft = "Roter venstre",
  rotateRight = "Roter høyre",

  -- v2: Showroom misc
  originalPrice = "Opprinnelig pris",
  discount = "Rabatt",
  createInteraction = "Opprett interaksjon",
  viewAll = "Vis alle",
  fetchingPlayers = "Henter spillere",
  refresh = "Oppdater",
  loadingPlayers = "Laster inn spillere...",
  failedToLoadPlayers = "Kunne ikke laste inn spillere",
  selectAPlayer = "Velg en spiller",
  failedToLoadPlayersRetry = "Kunne ikke laste inn spillere. Klikk 'Oppdater' for å prøve igjen.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Selvbetjening forhandler",
  categories = "Kategorier",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Lokasjoner",
  createNew = "Opprett ny",
  enable = "Aktiver",
  disable = "Deaktiver",
  loading = "Laster...",
  errors = "Feil",
  update = "Oppdater",
  create = "Opprett",

  -- v2: Dealership creation/editing
  createDealership = "Opprett forhandler",
  editDealership = "Rediger forhandler",
  essentials = "Grunnleggende",
  advanced = "Avansert",
  noDealershipLocations = "Ingen forhandlerlokasjoner",
  noDealershipLocationsDesc = "Du kan legge til en ny lokasjon, importere fra konfigurasjonen din (hvis du migrerer fra v1) eller automatisk legge til standardlokasjoner.",

  -- v2: Location sections
  dealershipZone = "Forhandlersone",
  showroomAndManagement = "Utstilling og ledelse",
  openShowroom = "Åpne utstilling",
  openManagement = "Åpne ledelse",
  enableSellVehicle = "Aktiver kjøretøysalg",
  percentageOfVehicleValue = "Prosent av kjøretøyverdi",
  enablePurchase = "Aktiver kjøp",
  purchasedVehicleSpawn = "Kjøpt kjøretøy spawn",
  enableTestDrive = "Aktiver prøvekjøring",
  testDriveVehicleSpawn = "Prøvekjøring kjøretøy spawn",
  truckDelivery = "Lastebillevering",
  truckDeliveryVehicleSpawn = "Leveringskjøretøy spawn",

  -- v2: Location advanced settings
  paymentMethods = "Betalingsmetoder",
  supportsFinancing = "(støtter finansiering)",
  enableFinance = "Aktiver finansiering",
  cameraPreset = "Kamera",
  preset = "Forhåndsinnstilling",
  custom = "Tilpasset",
  vehiclePosition = "Kjøretøyposisjon",
  zoomPositions = "Zoomposisjoner (kommaseparert)",
  zoomPositionsPlaceholder = "eksempel: 5,8,12,8",
  vehicleColour = "Kjøretøyfarge",
  selectionType = "Valgtype",
  noColourSelection = "Ingen fargevalg",
  rgbColourWheel = "RGB fargehjul",
  listOfRgbColours = "Liste over RGB farger",
  listOfColourIds = "Liste over farge-IDer",
  accessControl = "Tilgangskontroll",
  showroomJobWhitelist = "Utstilling jobb hviteliste",
  showroomGangWhitelist = "Utstilling gjeng hviteliste",
  societyPurchaseJobWhitelist = "Samfunnskjøp jobb hviteliste",
  societyPurchaseGangWhitelist = "Samfunnskjøp gjeng hviteliste",
  setInGame = "Sett i spillet",
  addNew = "Legg til ny",

  -- v2: Job/Gang whitelist editor
  job = "Jobb",
  gang = "Gjeng",
  jobWhitelist = "Jobb hviteliste",
  gangWhitelist = "Gjeng hviteliste",
  addJob = "Legg til jobb",
  addGang = "Legg til gjeng",
  editJob = "Rediger jobb",
  editGang = "Rediger gjeng",
  manageJobs = "Administrer jobber",
  manageGangs = "Administrer gjenger",
  jobName = "Jobbnavn",
  gangName = "Gjengnavn",
  selectGrades = "Velg grader",
  selectAll = "Velg alle",
  deselectAll = "Fjern alle valg",
  invalidJobName = "Ugyldig jobbnavn. Sjekk framework-konfigurasjonen.",
  invalidGangName = "Ugyldig gjengnavn. Sjekk framework-konfigurasjonen.",
  grades = "Grader",
  noJobsConfigured = "Ingen jobber konfigurert",
  noGangsConfigured = "Ingen gjenger konfigurert",
  click = "Klikk",
  toGetStarted = "for å komme i gang.",
  more = "flere",
  jobPlaceholder = "For eksempel: cardealer",
  jobOptionalDescription = "Valgfritt knytte forhandlerroller til en framework-jobb. Når ansatte ansettes/sparkes, vil framework-jobben deres også oppdateres.",
  jobRankPermissions = "Jobb rang tillatelser",
  roleToJobRankMapping = "Rolle til jobb rang kartlegging",
  addPerm = "Legg til tillatelse",

  -- v2: Colour selector
  searchColours = "Søk etter farger...",
  noColoursFound = "Ingen farger funnet",

  -- v2: Interactions creator
  noInteractions = "Ingen interaksjoner",
  highlightInteractions = "Fremhev interaksjoner",
  explorationMode = "Utforskningsmodus",
  pressEsc = "Trykk ESC",
  toWalkAround = "for å gå rundt",
  toReturnToUI = "for å gå tilbake til UI",
  points = "punkter",
  location = "lokasjon",
  manageLocations = "Administrer lokasjoner",

  -- v2: Interaction modal
  interactionType = "Type",
  nicknameOptional = "Kallenavn (Valgfritt)",
  invalidModel = "Ugyldig modell",
  failedToValidateModel = "Kunne ikke validere modell",
  pedScenario = "Ped scenario",
  coords = "Koordinater",
  size = "Størrelse",
  blip = "Blip",
  enableBlip = "Aktiver blip",
  blipIconId = "Blip ikon-ID",
  blipColourId = "Blip farge-ID",
  blipSize = "Blip størrelse",
  marker = "Markør",
  enableMarker = "Aktiver markør",
  markerStyleId = "Markør stil-ID",
  markerSize = "Markør størrelse",
  markerColor = "Markør farge",
  markerBobUpAndDown = "Sveve opp og ned",
  markerFaceCamera = "Se mot kamera",
  markerRotate = "Roter",
  markerDrawOnEnts = "Tegn på enheter",
  updatePosition = "Oppdater posisjon",
  setPosition = "Sett posisjon",

  -- v2: Interaction types
  interactionPoint = "Punkt",
  interactionPointDesc = "Et enkelt skalerbart punkt med valgfri markør",
  interactionPolyzone = "Polysone",
  interactionPolyzoneDesc = "Flerkoordinat sone for å lage et spesifikt interaksjonsområde",
  interactionVehicle = "Kjøretøy",
  interactionVehicleDesc = "Spawn en kjøretøymodell, ideelt for target eller 3D tekst UI interaksjonsmetoder",
  interactionObject = "Objekt",
  interactionObjectDesc = "Spawn en objektmodell, ideelt for target eller 3D tekst UI interaksjonsmetoder",
  interactionPed = "Ped",
  interactionPedDesc = "Spawn en ped-modell med valgfritt scenario, ideelt for target eller 3D tekst UI interaksjonsmetoder",

  -- v2: Import modal
  importLocationsTitle = "Importer lokasjoner",
  syncStockLabel = "Synkroniser lager",
  syncStockDescription = "Legg til kjøretøy i hver forhandlers lager basert på kategorier",
  importSourceSelectorDesc = "Du kan importere standard lokasjoner for et ferdig oppsett, eller importere eksisterende lokasjoner fra konfigurasjonen din hvis du migrerer fra Dealerships v1.",
  importSourceSelectorSkipDesc = "Lokasjoner som allerede finnes i databasen vil bli hoppet over; kun nye lokasjoner vil bli importert.",
  successfullyImported = "Vellykket importert",
  alreadyExist = "Finnes allerede",
  defaultLocations = "Standard lokasjoner",
  defaultLocationsDesc = "Importer forhåndskonfigurerte forhandlerlokasjoner (PDM, Luksus, Båter, Fly, Lastebil)",
  existingConfig = "Eksisterende konfigurasjon",
  existingConfigDesc = "Importer lokasjoner fra config.lua (for v1 migrering)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Vil du automatisk legge til kjøretøy i denne forhandlerens lager basert på valgte kategorier?",
  categorySyncEditDesc = "Du endret kategoriene for denne forhandleren. Vil du automatisk oppdatere kjøretøylageret?",
  addVehicles = "Legg til kjøretøy",
  removeVehicles = "Fjern kjøretøy",
  fromNewCategories = "fra nye kategorier",
  fromSelectedCategories = "fra valgte kategorier",
  fromRemovedCategories = "fra fjernede kategorier",
  categoriesAdded = "Kategorier lagt til:",
  categoriesRemoved = "Kategorier fjernet:",
  skip = "Hopp over",
  syncStock = "Synkroniser lager",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Sjekker kildetilgjengelighet...",
  vehiclesAvailableToImport = "kjøretøy tilgjengelig for import",
  includesDealershipIds = "inkluderer forhandler-IDer",
  sourceUnavailable = "Kilde utilgjengelig",
  noVehiclesAdminDescription = "Du kan legge til kjøretøy manuelt eller importere dem fra ditt framework.",
  appendBehaviour = "Tilføy",
  overwriteBehaviour = "Overskriv",
  appendDescription = "Legg kun til nye kjøretøy som ikke allerede finnes i databasen",
  overwriteDescription = "Slett alle eksisterende kjøretøydata og importer på nytt",
  stockAssignmentMethod = "Lagertildelingsmetode",
  useDealershipIdsFromSource = "Bruk forhandler-IDer fra kilde",
  matchByVehicleCategory = "Match etter kjøretøykategori",
  byShopDescription = "Kjøretøy vil bli tildelt forhandlere basert på 'shop'-feltet i kildedataene",
  byCategoryDescription = "Kjøretøy vil bli tildelt forhandlere med matchende kategorier",
  overwriteWarning = "Advarsel: Overskriving vil slette alle eksisterende kjøretøy, bestillinger, utstillingskjøretøy og salgsdata.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX kjøretøytabell",
  selectCategory = "Velg kategori",

  -- v2: Management menu items
  vehiclesMenu = "Kjøretøy",
  displayVehiclesMenu = "Utstillingskjøretøy",
  ordersMenu = "Bestillinger",
  salesMenu = "Salg",
  bankAccountMenu = "Bankkonto",
  employeesMenu = "Ansatte",
  couponsMenu = "Kuponger",
  settingsMenu = "Innstillinger",
  noPermissionAccessManagement = "Du har ikke tilgang til administrasjonsfunksjoner.",
  backToAdmin = "Tilbake til admin",
  viewingAsAdmin = "VISER SOM ADMIN",

  -- v2: Coupons table
  code = "Kode",
  uses = "Bruk",
  perPlayer = "Per spiller",
  never = "Aldri",
  noCoupons = "Ingen kuponger",
  noCouponsDescription = "Kunder kan taste inn en kupong ved kjøretøykjøp og spare penger.",

  -- v2: Coupon modal
  couponCodeLabel = "Kupongkode",
  couponCodePlaceholder = "f.eks. SOMMER2024 eller SPAR10",
  couponCodeHelp = "Skriv inn en tilpasset kode (maks 25 tegn, kun bokstaver, tall og bindestreker) eller klikk 'Generer'.",
  maxNumberOfUsesPlaceholder = "Maksimalt antall bruk",
  maxUsesPerPlayerPlaceholder = "Maks bruk per spiller",
  vehicleRestrictionsPlaceholder = "Skriv inn spawn-koder separert med komma (f.eks. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Tillat på finansierte kjøp",
  createCoupon = "Opprett kupong",
  updateCoupon = "Oppdater kupong",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kupongkode er påkrevd",
  couponCodeMaxLength = "Koden må være 25 tegn eller mindre",
  couponCodeInvalidChars = "Koden kan bare inneholde store bokstaver, tall og bindestreker",
  discountTypeRequired = "Rabattype er påkrevd",
  discountValueRequired = "Rabattverdi er påkrevd",
  discountValueMin = "Rabattverdi må være større enn 0",
  discountValueMaxPercent = "Prosent kan ikke overstige 100",
  maxUsesRequired = "Maksimalt antall bruk er påkrevd",
  maxUsesMin = "Må være minst 1",
  perPlayerLimitRequired = "Per spiller grense er påkrevd",
  expiryDateRequired = "Utløpsdato er påkrevd",
  vehicleRestrictionsRequired = "Kjøretøybegrensninger er påkrevd",
  categoryRestrictionsRequired = "Kategoribegrensninger er påkrevd",
  selectAtLeastOneCategory = "Velg minst én kategori",

  -- v2: Dashboard
  today = "I dag",
  thisMonth = "Denne måneden",
  allTime = "Totalt",
  recentSales = "Nylige salg",
  noSalesYet = "Ingen salg ennå!",
  noSalesDescription = "Kjøretøysalg vil vises her etter første salg.",
  past7Days = "Siste 7 dager",
  past6Months = "Siste 6 måneder",
  numberOfSales = "Antall salg",
  noDataAvailableForPeriod = "Ingen data tilgjengelig for denne perioden",

  -- v2: Display vehicles
  displayVehiclesDescription = "Utstillingskjøretøy er faste utstillingsmodeller som brukes til å vise lageret ditt og oppmuntre kunder til å kjøpe.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework-jobber aktivert",
  frameworkJobsDescription = "Ansattadministrasjon håndteres gjennom framework jobbsystem. Spillere med forhandlerjobben vil automatisk ha tilgang basert på rang. Konfigurer jobbtillatelser i admin-panelets lokasjonsinnstillinger.",
  joinedColumn = "Ble med",
  youBadge = "Deg",

  -- v2: Orders
  noOrdersTitle = "Ingen bestillinger",
  noOrdersDescription = "For å legge inn en bestilling, åpne 'Kjøretøy'-fanen og klikk 'Bestill' på kjøretøyet du vil fylle på.",
  inProgress = "Pågår",
  awaitingDelivery = "Venter på levering",
  orderedBy = "Bestilt av",
  viewDeliveryInfo = "Vis leveringsinformasjon",

  -- v2: Delivery
  startDeliveryMissionTitle = "Start leveringsoppdrag",
  startDeliveryDescription = "Du skal starte et leveringsoppdrag for denne kjøretøybestillingen. Du må kjøre til hentepunktet, hente lastetraileren og levere den tilbake til forhandleren.",
  totalDistanceAndDriveTime = "Total distanse og kjøretid",
  roundTrip = "tur-retur",
  deliveryCompleteTitle = "Levering fullført",
  deliveryInProgressTitle = "Levering pågår",
  deliveredAt = "Levert:",
  startedAt = "Startet:",
  deliveredBy = "Levert av:",
  beingDeliveredBy = "Blir levert av:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Ingen bestillinger tilgjengelig for levering. Bestillinger må være klare og ikke under aktiv levering.",
  confirmDeliveryTitle = "Bekreft levering",
  configureDeliveryTitle = "Konfigurer levering",
  trailerCapacityExceeded = "Trailer-kapasitet overskredet! Du valgte %{usedSlots} plasser, men maksimum er %{maxSlots} plasser.",
  smallVehiclesSlotInfo = "Merk: Små kjøretøy tar 1 plass, mellomstore tar 1,5 plass.",
  fetchingRoute = "Henter...",
  getRouteButton = "Hent rute",
  selectTrailerType = "Velg trailertype",
  carTrailerLabel = "Biltransport",
  smallMedium = "(Liten/Mellomstor)",
  containerLabel = "Container",
  large = "(Stor)",
  carTrailerDescription = "Biltransporten har 2 rader. Hver rad tar 3 små (1 plass hver) eller 2 mellomstore (1,5 plass hver). Maks 6 plasser totalt.",
  containerDescription = "Container-traileren transporterer 1 stort kjøretøy",
  selectOrdersTitle = "Velg bestillinger",
  slots = "plasser",
  noOrdersForTrailerType = "Ingen bestillinger tilgjengelig for denne trailertypen.",
  qty = "Antall:",
  inTransit = "under transport",
  totalVehicles = "Totalt kjøretøy:",
  estimatedTime = "Estimert tid:",
  unknown = "Ukjent",

  -- v2: Sales
  salesEmptyDescription = "Kjøretøysalg vil vises her etter første salg.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Bestilling lagt inn!",
  orderPlacedTruckingDescription = "Bestillingen din er klar for henting. Gå til bestillingssiden for å fullføre.",
  orderPlacedTimedDescription = "Bestillingen din vil ankomme om %{value} minutter.",
  goToOrders = "Gå til bestillinger",
  noStockAvailableDescription = "Ikke noe lager tilgjengelig for dette kjøretøyet. Global lagergrense nådd.",
  stockUpdatedDescription = "Lagerantall ble oppdatert.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktive prøvekjøringer",
  tracking = "Sporing",
  track = "Spor",
  endButton = "Avslutt",
  endTestDriveTitle = "Avslutt prøvekjøring",
  endTestDriveConfirmation = "Er du sikker på at du vil avslutte denne prøvekjøringen? Kjøretøyet vil bli slettet og passasjerer vil ikke bli teleportert tilbake til forhandleren.",
  vehicleLocationOnMap = "Kjøretøyets plassering er markert på kartet ditt.",
  sell = "Selg",
  couponCodeOptional = "Kupongkode (Valgfritt)",
  pleaseEnterCouponCode = "Vennligst skriv inn kupongkode",
  invalidCouponCode = "Ugyldig kupongkode",
  failedToValidateCoupon = "Kunne ikke validere kupong",
  apply = "Bruk",
  applying = "Bruker...",
  allStock = "Alt lager",
  inStockFilter = "På lager",
  outOfStockFilter = "Utsolgt",
  noResultsFound = "Ingen resultater funnet",
  noResults = "Ingen resultater",
  noVehiclesMatchSearch = "Ingen kjøretøy matcher søket ditt",
  noVehiclesMatchFilters = "Ingen kjøretøy matcher gjeldende filtre",
  noItemsMatchSearch = "Ingen elementer matcher søket ditt",
  noItemsMatchFilters = "Ingen elementer matcher gjeldende filtre",
  selectColour = "Velg farge",
  refreshNearbyPlayers = "Oppdater nærliggende spillere",
  you = "Deg",
  items = "elementer",
  waitingForCustomerToRespond = "Venter på kundens svar...",
  vehicleSpawnedMessage = "Kjøretøyet har spawnet på punktet markert på kartet ditt - ta kunden dit.",
  customerDeclinedMessage = "Kunden avviste kjøpsforespørselen.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "SIGNER HER",
  acceptAndPurchase = "Godta og kjøp",
  couponApplied = "Kupong %{code} brukt! Du sparer %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Trenger minst 3 punkter for å fullføre sonen! (Nå har du %{value})",
  addPoint = "Legg til punkt",
  removeLast = "Fjern siste",
  completeZone = "Fullfør sone",
  spawnPreview = "Spawn forhåndsvisning",
  up = "Opp",
  down = "Ned",
  confirm = "Bekreft",
  placePoint = "Plasser punkt",
  radius = "Radius",

  -- v2: Blip labels
  soldVehicleLocation = "Solgt kjøretøy plassering",
  testDriveVehicleBlip = "Prøvekjøringskjøretøy",

  -- v2: Stock sync
  stockSyncResult = "Lagersynkronisering: %{added} lagt til, %{removed} fjernet",
  stockSyncAdded = "Lagersynkronisering: %{value} kjøretøy lagt til",
  importSuccessful = "Import vellykket! %{imported} kjøretøy importert (totalt %{total})",

  -- v2: Tooltip actions
  findOnMap = "Finn på kartet",
  adminPanel = "Admin-panel",

  -- v2: Common dropdown
  selectOne = "Velg én",
}
