Locales = Locales or {}

Locales['pl'] = {
  -- UI
  vehicle = "Pojazd",
  vehicles = "Pojazdy",
  dealership = "Dealer samochodowy",
  dealerships = "Dealerzy samochodowi",
  vehiclesCount = "Liczba pojazdów",
  dealersCount = "Liczba dealerów",
  accountBalance = "Saldo konta",
  bank = "Bank",
  cash = "Gotówka",
  amount = "Kwota",
  societyFund = "Fundusz społeczny",
  paymentSource = "Źródło płatności",
  purchase = "Zakup",
  personalPurchase = "Osobisty zakup",
  societyPurchase = "Zakup społeczny",
  purchaseType = "Typ zakupu",
  deposit = "Depozyt",
  withdraw = "Wypłata",
  all = "Wszystko",
  yes = "Tak",
  no = "Nie",
  add = "Dodaj",
  edit = "Edytuj",
  id = "ID",
  created = "Utworzono",
  type = "Typ",
  name = "Nazwa",
  owner = "Właściciel",
  bankBalance = "Saldo bankowe",
  status = "Status",
  back = "Powrót",
  previous = "Poprzedni",
  next = "Następny",
  admin = "Administrator",
  vehiclesAdmin = "Administrator pojazdów",
  dealershipsAdmin = "Administrator dealerów",
  search = "Szukaj",
  noDealershipsFound = "Nie znaleziono dealerów samochodowych",
  noVehicles = "Brak pojazdów",
  page = "Strona",
  of = "z",
  every = "każdy",
  show = "Pokaż",
  active = "Aktywny",
  activeFinance = "Aktywna finansowanie",
  failed = "Niepowodzenie",
  removed = "Usunięty",
  setOwner = "Ustaw właściciela",
  manage = "Zarządzaj",
  deleteData = "Usuń dane",
  deleteVehicle = "Usuń pojazd",
  delete = "Usuń",
  deleteConfirmation = "Na pewno?",
  deleteConfirmationDanger = "Czy na pewno? Tej operacji nie można cofnąć.",
  setDealershipOwner = "Ustaw właściciela dealerowi",
  overwriteDealerPrices = "Nadpisz ceny dealerów",
  nearbyPlayers = "Gracze w pobliżu",
  noPlayersNearby = "Brak graczy w pobliżu",
  selectPlayer = "Wybierz gracza",
  required = "Wymagane",
  forExample = "Na przykład",
  spawnCode = "Kod spawnu",
  brand = "Marka",
  model = "Model",
  category = "Kategoria",
  price = "Cena",
  import = "Importuj",
  importing = "Importowanie",
  importBehaviour = "Zachowanie importu",
  importVehicles = "Importuj pojazdy",
  importFrom = "Importuj z",
  dashboard = "Deska rozdzielcza",
  displayVehicle = "Wyświetl pojazd",
  displayVehicles = "Wyświetl pojazdy",
  orders = "Zamówienia",
  sales = "Sprzedaż",
  vehiclesOnDisplay = "Pojazdy na wystawie",
  employees = "Pracownicy",
  settings = "Ustawienia",
  switchVehicle = "Zmień pojazd",
  remove = "Usuń",
  noDisplayVehicles = "Brak pojazdów na wystawie",
  selectVehicle = "Wybierz pojazd",
  colour = "Kolor",
  placeVehicle = "Umieść pojazd",
  orderVehicle = "Zamów pojazd",
  cancelOrder = "Anuluj zamówienie",
  delivery = "Dostawa",
  delivered = "Dostarczono",
  noOrders = "Brak zamówień",
  quantity = "Ilość",
  totalCost = "Całkowity koszt",
  totalSales = "Całkowita sprzedaż",
  noSales = "Brak sprzedaży",
  paid = "Zapłacono",
  owed = "Dłużne",
  dealershipName = "Nazwa dealera samochodowego",
  save = "Zapisz zmiany",
  cancel = "Anuluj",
  notEnoughMoney = "Za mało środków",
  placeOrder = "Złóż zamówienie",
  purchaseCost = "Koszt zakupu",
  salePrice = "Cena sprzedaży",
  inStock = "Na stanie",
  outOfStock = "Brak w magazynie",
  placeVehiclePrompt = "Naciśnij %{value}, aby umieścić pojazd. Następnie możesz wprowadzić dalsze zmiany!",
  remaining = "Pozostało",
  prePurchaseRepoWarning = "Jeśli nie spłacisz rat kredytu, twój pojazd zostanie zarekwirowany.",
  repossessionWarning = "Twoja ostatnia płatność nie powiodła się - jeśli teraz nie zapłacisz, twój pojazd zostanie niedługo zarekwirowany.",
  recurringPayment = "Płatność cykliczna",
  remainingBalance = "Pozostałe saldo",
  remainingPayments = "Pozostałe płatności",
  paymentTakenEvery = "Płatność pobierana co",
  hours = "Godzin",
  seconds = "Sekundy",
  nextPayment = "Następna płatność",
  makePayment = "Dokonaj płatności",
  vehicleRepossessed = "Twój pojazd zostanie zarekwirowany",
  payInFull = "Zapłać całość",
  earlyPaymentConfirmation = "Czy na pewno chcesz zapłacić wcześniej?",
  financedVehicles = "Pojazdy objęte finansowaniem",
  noFinancedVehicles = "Nie masz żadnych aktywnych pojazdów objętych finansowaniem",
  financeBreakdown = "Podział finansów",
  initialPayment = "Pierwsza płatność",
  payments = "Płatności",
  length = "Długość",
  interest = "Oprocentowanie",
  totalPayable = "Całkowita kwota do zapłaty",
  leaveShowroom = "Opuść salon",
  handling = "Zarządzanie",
  topSpeed = "Maksymalna prędkość",
  power = "Moc",
  torque = "Moment obrotowy",
  brake = "Hamulec",
  financing = "Finansowanie",
  financingAvailable = "Dostępne finansowanie",
  paymentsOf = "płatności po",
  clear = "Wyczyść",
  testDrive = "Jazda próbna",
  allCategories = "Wszystkie kategorie",
  sortByName = "Sortuj według nazwy",
  sortByAvailability = "Sortuj według dostępności",
  sortByCheapest = "Sortuj według najniższej ceny",
  sortByMostExpensive = "Sortuj według najwyższej ceny",
  sortByNewest = "Sortuj według najnowszych",
  purchaseVehicle = "Kup pojazd",
  purchaseFor = "Kup dla",
  selectSociety = "Wybierz społeczność",
  financeOverPayments = "%{value} płatności ponad finansowanie",
  payToday = "Zapłać dzisiaj",
  financeThen = "Następnie",
  seeFullBreakdown = "Zobacz pełny podział",
  testDriveExit = "Możesz w każdej chwili opuścić pojazd, aby zakończyć jazdę próbną.",

  -- NOTIFICATIONS
  purchaseSuccess = "Dziękujemy za zakup!",
  depositSuccess = "Udany depozyt",
  withdrawSuccess = "Udany przelew",
  errorNotEnoughMoney = "Za mało środków",
  errorVehicleOutOfStock = "Ten pojazd nie jest dostępny",
  errorCannotAffordVehicle = "Nie stać cię na ten pojazd",
  vehicleFinancePaymentMade = "Płatność %{value} za twój pojazd zakończona powodzeniem",
  vehicleFinancePaidOff = "Gratulacje, spłaciłeś swojego pojazda! Pozostało %{value}",
  vehicleFinancePaymentFailed = "Płatność %{value} za twój pojazd nie powiodła się",
  vehicleFinanceRepossessedSoon = "Musisz zapłacić %{value} za twój pojazd, w przeciwnym razie wkrótce zostanie zarekwirowany",
  vehicleFinanceRepossessed = "Z powodu niezapłacenia, twój pojazd o numerze rejestracyjnym %{value} został zarekwirowany.",
  dealershipNotEnoughFunds = "Dealer samochodowy nie ma wystarczających funduszy",
  dealershipVehiclesOrdered = "Pojazdy zostały pomyślnie zamówione u dealera samochodowego",
  dealershipOrderCancelled = "Zamówienie u dealera samochodowego zostało pomyślnie anulowane",
  errorVehicleWithSpawnCodeExists = "Pojazd o tym kodzie spawnu już istnieje",
  errorExitVehicle = "Najpierw musisz opuścić pojazd",

  -- NEW v1.1
  purchaseRequest = "Prośba o zakup",
  sendRequest = "Wyślij prośbę",
  dealer = "Dealer",
  financed = "Finansowane",
  signHere = "Podpisz tutaj",
  signFirstError = "Najpierw podpisz, proszę",
  denyRequest = "Odrzuć prośbę",
  playerTooManyFinancedVehicles = "Ten gracz ma zbyt wiele finansowanych pojazdów",
  employeePermissionsError = "Nie masz wymaganych uprawnień jako pracownik",
  managerRole = "Manager",
  supervisorRole = "Przełożony",
  salesRole = "Sprzedaż",
  ownerRole = "Właściciel",
  employmentRequest = "Prośba o zatrudnienie",
  accept = "Akceptuj",
  jobOfferDescription = "Otrzymałeś ofertę pracy od \"%{value}\" dealera samochodowego. Czy chcesz ją zaakceptować?",
  pending = "Oczekuje",
  employeeHiredMsg = "Zostałeś zatrudniony u dealera samochodowego!",
  employeeRejectedMsg = "Twoja prośba o zatrudnienie u dealera samochodowego została odrzucona",
  sellVehicle = "Sprzedaj pojazd",
  vehicleTerms = "Warunki pojazdu",
  financePayments = "Płatności finansowe",
  commission = "Prowizja",
  role = "Rola",
  firedNotification = "Zostałeś zwolniony u dealera samochodowego \"%{value}\"",
  dealershipTooFarAway = "Jesteś zbyt daleko od dealera samochodowego",
  restoreDisplayVehicles = "Przywróć pojazdy",
  customer = "Klient",
  lessThanAMin = "Mniej niż minutę",
  mins = "minut(y)",
  notInVehicle = "Nie jesteś w pojeździe",
  notYourVehicleError = "Ten pojazd nie należy do ciebie",
  vehicleFinancedError = "Nie możesz sprzedać tego pojazdu, ponieważ pozostały jeszcze płatności finansowe",
  dealershipDoesntSellVehicle = "Ten dealer samochodowy nie sprzedaje tego pojazdu",
  dealershipWantsYourVehicle = "Gratulacje! Ten dealer samochodowy chce kupić twój pojazd.",
  purchasePrice = "Zaproponowana cena: ",

  spawnCodeInvalid = "Nieprawidłowy kod spawn",
  salesRep = "Przedstawiciel handlowy",
  directSaleAccepted = "Prośba o sprzedaż bezpośrednią zaakceptowana! Twoja prowizja została wypłacona.",
  directSaleRejected = "Prośba o sprzedaż bezpośrednią odrzucona",

  displayVehicleOutsideZone = "Pojazdy wystawowe muszą być umieszczone w strefie dealera",
  serverAdmin = "Admin serwera",
  selfService = "Samoobsługa",
  owned = "Posiadane",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Nieprawidłowa metoda płatności",
  paymentMethodNoFinance = "Ta metoda płatności nie obsługuje finansowania",
  couldNotGeneratePlate = "Nie można wygenerować tablicy rejestracyjnej",
  invalidCoupon = "Nieprawidłowy kupon: %{value}",
  tooManyFinancedVehicles = "Masz zbyt wiele finansowanych pojazdów",
  couldNotSpawnVehicle = "Nie można wygenerować pojazdu",

  -- v2: Permissions
  insufficientPermissions = "Niewystarczające uprawnienia",

  -- v2: Coupons
  couponCodeAlreadyExists = "Ten kod kuponu już istnieje",
  failedToCreateCoupon = "Nie udało się utworzyć kuponu",
  couponCreatedSuccessfully = "Kupon utworzony pomyślnie",
  couponNotFound = "Kupon nie znaleziony",
  couponUpdatedSuccessfully = "Kupon zaktualizowany pomyślnie",
  failedToDeleteCoupon = "Nie udało się usunąć kuponu",
  couponDeletedSuccessfully = "Kupon usunięty pomyślnie",
  editCoupon = "Edytuj kupon",
  addCoupon = "Dodaj kupon",
  couponCode = "Kod kuponu",
  generating = "Generowanie...",
  generate = "Generuj",
  discountType = "Typ rabatu",
  percentageOff = "Procent zniżki",
  amountOff = "Kwota zniżki",
  discountValue = "Wartość rabatu",
  unlimitedTotalUses = "Nieograniczona liczba użyć",
  unlimitedUsesPerPlayer = "Nieograniczone użycia na gracza",
  setExpiryDate = "Ustaw datę wygaśnięcia",
  restrictToSpecificVehicles = "Ogranicz do określonych pojazdów",
  restrictToSpecificCategories = "Ogranicz do określonych kategorii",
  allowUseWithFinance = "Zezwól na użycie z finansowaniem",
  deleteCoupon = "Usuń kupon",
  inactive = "Nieaktywny",
  expired = "Wygasły",
  maxUses = "Maksymalna liczba użyć",
  coupons = "Kupony",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Tylko administratorzy serwera mogą się samozatrudnić",
  playerNotFound = "Gracz nie znaleziony",
  failedToHireEmployee = "Nie udało się zatrudnić pracownika",
  failedToFireEmployee = "Nie udało się zwolnić pracownika",
  failedToUpdateEmployeeRole = "Nie udało się zaktualizować roli pracownika",
  hireEmployee = "Zatrudnij pracownika",
  fireEmployee = "Zwolnij pracownika",
  editRole = "Edytuj rolę",
  fire = "Zwolnij",
  changeRole = "Zmień rolę",
  updateRole = "Aktualizuj rolę",

  -- v2: Test drives
  maxTestDrivesReached = "Ten dealer osiągnął maksymalną liczbę aktywnych jazd próbnych",
  testDriveNotEnabled = "Jazdy próbne nie są włączone u tego dealera",
  noTestDriveSpawnCoords = "Brak skonfigurowanych współrzędnych spawn dla jazd próbnych u tego dealera",
  couldNotSpawnTestDriveVehicle = "Nie można wygenerować pojazdu do jazdy próbnej",
  couldNotGetPlateFromServer = "Nie można pobrać tablicy rejestracyjnej z serwera",
  couldNotRegisterTestDriveVehicle = "Nie można zarejestrować pojazdu do jazdy próbnej",
  testDriveEndedByEmployee = "Jazda próbna została zakończona przez innego pracownika",
  trackingVehicleLocation = "Śledzenie lokalizacji pojazdu...",
  directSaleCancelled = "Prośba o sprzedaż została anulowana przez sprzedawcę",
  testDriveKeysReceived = "Otrzymałeś klucze do pojazdu na jazdę próbną",
  testDriveEndedCustomer = "Jazda próbna zakończona",
  starting = "Uruchamianie...",
  startTestDrive = "Rozpocznij jazdę próbną",
  spawningTestDriveVehicle = "Generowanie pojazdu do jazdy próbnej...",
  testDriveReady = "Jazda próbna gotowa",
  testDriveWalkToVehicle = "Pojazd do jazdy próbnej pojawił się w oznaczonym miejscu na twojej mapie. Odprowadź klienta do pojazdu. Po przekazaniu kluczy klientowi, musisz ręcznie zakończyć jazdę próbną, gdy wróci.",
  givingKeys = "Przekazywanie kluczy...",
  continueAndGiveKeys = "Kontynuuj i przekaż klucze",
  endTestDrive = "Zakończ jazdę próbną",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Brak dostępnych sztuk tego pojazdu",
  globalStockLimitExceeded = "Dostępne tylko %{value} sztuk",
  orderNotFoundOrFulfilled = "Zamówienie nie znalezione lub już zrealizowane",
  priceBelowMinimum = "Cena nie może być niższa niż %{value}",
  priceAboveMaximum = "Cena nie może być wyższa niż %{value}",
  stockUpdated = "Stan magazynowy zaktualizowany",
  changesSaved = "Zmiany zapisane",
  noStockAvailable = "Brak dostępnych sztuk",
  orderPlaced = "Zamówienie złożone",
  remainingInStock = "pozostało w globalnym magazynie",
  exceedsStockLimit = "Przekracza limit magazynowy",
  setStockQty = "Ustaw ilość magazynową",
  invalidStockValue = "Wprowadź prawidłową wartość magazynową",
  errorSettingStock = "Błąd podczas ustawiania stanu magazynowego",
  stockQuantity = "Ilość magazynowa",
  currentStock = "Aktualny stan",
  priceLimitsEnabled = "Włącz limity cenowe",
  priceLimitsDescription = "Po włączeniu menedżerowie dealerów mogą ustawiać ceny tylko w określonym zakresie.",
  minPrice = "Cena minimalna",
  maxPrice = "Cena maksymalna",
  optional = "Opcjonalne",
  unlimitedStock = "Nieograniczony magazyn",
  globalStockLimit = "Globalny limit magazynowy",
  globalStockLimitDescription = "Ustaw maksymalną liczbę sztuk, które mogą być zamówione u wszystkich dealerów.",
  currentlyOrdered = "Aktualnie zamówione",
  priceRange = "Zakres cenowy",
  noMinimum = "Brak minimum",
  noMaximum = "Brak maksimum",
  vehicleStock = "Stan pojazdów",

  -- v2: Sales
  allSales = "Wszystkie sprzedaże",
  paidInFull = "Zapłacone w całości",
  salesVolume = "Wolumen sprzedaży",
  pastMonth = "Ostatni miesiąc",
  pastYear = "Ostatni rok",

  -- v2: Management misc
  exploitAttemptDetected = "Przestań próbować wykorzystywać skrypt",
  dealershipNoJobConfigured = "Dealer nie ma skonfigurowanej pracy",
  modelDoesNotMatchDb = "Model pojazdu nie odpowiada bazie danych",
  importFailed = "Import nieudany: %{value}",
  notInDealershipZone = "Musisz być w strefie dealera, aby użyć tego polecenia",
  notAnEmployee = "Nie jesteś pracownikiem tego dealera.",
  failedToPrepareDelivery = "Nie udało się przygotować dostawy",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Model pojazdu nie istnieje - skontaktuj się z adminem",
  vehiclePlateInvalid = "Tablica rejestracyjna tego pojazdu jest nieprawidłowa (naciśnij F8, aby uzyskać więcej szczegółów)",
  currentlyInRagdollState = "Jesteś obecnie w stanie ragdoll",
  vehicleDoesNotExistContactAdmin = "Pojazd nie istnieje. Skontaktuj się z adminem!",
  vehicleSecurityBreachDetected = "Wykryto naruszenie bezpieczeństwa pojazdu",

  -- v2: Admin vehicles
  allVehicles = "Wszystkie pojazdy",
  unassignedVehicles = "Brak dealera",
  searchDealerships = "Szukaj dealerów...",

  -- v2: Trucking mission
  truckingGetInTruck = "Wsiądź do ciężarówki w oznaczonym miejscu, aby rozpocząć dostawę",
  truckingDriveToDelivery = "Jedź do miejsca dostawy",
  truckingCompleteDelivery = "Zakończ dostawę",
  truckingDeliveryComplete = "Dostawa zakończona: Pomyślnie ukończyłeś dostawę!",
  truckingDeliveryFailed = "Dostawa nieudana: Coś poszło nie tak z dostawą",
  truckingDriveToPickup = "Jedź do punktu odbioru, aby odebrać przyczepę",
  truckingMissionFailedSpawnCargo = "Misja nieudana: Nie można wygenerować przyczepy towarowej",
  truckingMissionFailedFindCargo = "Misja nieudana: Nie można znaleźć wygenerowanego ładunku",
  truckingVehiclesLoaded = "%{count} pojazd(ów) załadowanych",
  truckingWrongTrailer = "Zła przyczepa! Musisz podłączyć właściwą przyczepę misji.",
  truckingTrailerAttached = "Przyczepa podłączona - gotowy do kontynuowania",
  truckingDriveToPickupLocation = "Jedź do punktu odbioru",
  truckingWaitingForVehicles = "Oczekiwanie na załadunek pojazdów...",
  truckingDriveUnderTrailer = "Podjedź pod przyczepę, aby ją podłączyć",
  truckingGetInTruckContinue = "Wsiądź do ciężarówki, aby kontynuować",
  truckingMissionStarted = "Misja transportowa rozpoczęta: Punkt odbioru - %{location}",
  truckingMissionCancelled = "Misja anulowana: Anulowałeś misję transportową",
  truckingNoActiveMission = "Brak aktywnej misji transportowej do anulowania",
  deliveryNotPrepared = "Dostawa nieprzygotowana - spróbuj ponownie",
  deliveryConfigMismatch = "Niezgodność konfiguracji dostawy",
  deliveryPreparationExpired = "Przygotowanie dostawy wygasło - spróbuj ponownie",
  noTruckingVehicleCoordinates = "Nie ustawiono współrzędnych pojazdu transportowego",
  pickupLocationUnavailable = "Punkt odbioru już niedostępny - spróbuj ponownie",
  failedToSpawnTruck = "Nie udało się wygenerować ciężarówki",
  clientFailedToStartMission = "Klient nie mógł rozpocząć misji",

  -- v2: Trucking UI/Keys
  keyDismiss = "Zamknij",
  keyDeliverCargo = "Dostarcz ładunek",
  keyContinueToDelivery = "Kontynuuj do dostawy",
  startDeliveryMission = "Rozpocznij misję dostawy",
  orderDetails = "Szczegóły zamówienia",
  pickupLocation = "Punkt odbioru",
  deliveryStatus = "Status dostawy",
  selectOrders = "Wybierz zamówienia",
  carTrailer = "Laweta",
  container = "Kontener",
  deliveryRoute = "Trasa dostawy",
  startDelivery = "Rozpocznij dostawę",

  -- v2: Direct sales UI
  waitingForCustomer = "Oczekiwanie na klienta",
  cancelRequest = "Anuluj prośbę",
  saleComplete = "Sprzedaż zakończona!",
  done = "Gotowe",
  saleDeclined = "Sprzedaż odrzucona",
  close = "Zamknij",

  -- v2: Display vehicle placement
  movement = "Ruch",
  rotate = "Obróć",
  forward = "Do przodu",
  backward = "Do tyłu",
  left = "W lewo",
  right = "W prawo",
  rotateLeft = "Obróć w lewo",
  rotateRight = "Obróć w prawo",

  -- v2: Showroom misc
  originalPrice = "Cena oryginalna",
  discount = "Rabat",
  createInteraction = "Utwórz interakcję",
  viewAll = "Pokaż wszystko",
  fetchingPlayers = "Pobieranie graczy",
  refresh = "Odśwież",
  loadingPlayers = "Ładowanie graczy...",
  failedToLoadPlayers = "Nie udało się załadować graczy",
  selectAPlayer = "Wybierz gracza",
  failedToLoadPlayersRetry = "Nie udało się załadować graczy. Kliknij 'Odśwież', aby spróbować ponownie.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Salon samoobsługowy",
  categories = "Kategorie",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Lokalizacje",
  createNew = "Utwórz nowy",
  enable = "Włącz",
  disable = "Wyłącz",
  loading = "Ładowanie...",
  errors = "Błędy",
  update = "Aktualizuj",
  create = "Utwórz",

  -- v2: Dealership creation/editing
  createDealership = "Utwórz salon",
  editDealership = "Edytuj salon",
  essentials = "Podstawowe",
  advanced = "Zaawansowane",
  noDealershipLocations = "Brak lokalizacji salonu",
  noDealershipLocationsDesc = "Możesz dodać nową lokalizację, zaimportować z konfiguracji (jeśli migrujesz z v1) lub automatycznie dodać domyślne lokalizacje.",

  -- v2: Location sections
  dealershipZone = "Strefa salonu",
  showroomAndManagement = "Showroom i zarządzanie",
  openShowroom = "Otwórz showroom",
  openManagement = "Otwórz zarządzanie",
  enableSellVehicle = "Włącz sprzedaż pojazdów",
  percentageOfVehicleValue = "Procent % wartości pojazdu",
  enablePurchase = "Włącz zakup",
  purchasedVehicleSpawn = "Spawn zakupionego pojazdu",
  enableTestDrive = "Włącz jazdę próbną",
  testDriveVehicleSpawn = "Spawn pojazdu do jazdy próbnej",
  truckDelivery = "Dostawa ciężarówką",
  truckDeliveryVehicleSpawn = "Spawn pojazdu dostawczego",

  -- v2: Location advanced settings
  paymentMethods = "Metody płatności",
  supportsFinancing = "(obsługuje finansowanie)",
  enableFinance = "Włącz finansowanie",
  cameraPreset = "Kamera",
  preset = "Preset",
  custom = "Niestandardowy",
  vehiclePosition = "Pozycja pojazdu",
  zoomPositions = "Pozycje zoomu (oddzielone przecinkami)",
  zoomPositionsPlaceholder = "przykład: 5,8,12,8",
  vehicleColour = "Kolor pojazdu",
  selectionType = "Typ wyboru",
  noColourSelection = "Brak wyboru koloru",
  rgbColourWheel = "Koło kolorów RGB",
  listOfRgbColours = "Lista kolorów RGB",
  listOfColourIds = "Lista ID kolorów",
  accessControl = "Kontrola dostępu",
  showroomJobWhitelist = "Biała lista prac showroomu",
  showroomGangWhitelist = "Biała lista gangów showroomu",
  societyPurchaseJobWhitelist = "Biała lista prac zakupu firmy",
  societyPurchaseGangWhitelist = "Biała lista gangów zakupu firmy",
  setInGame = "Ustaw w grze",
  addNew = "Dodaj nowy",

  -- v2: Job/Gang whitelist editor
  job = "Praca",
  gang = "Gang",
  jobWhitelist = "Biała lista prac",
  gangWhitelist = "Biała lista gangów",
  addJob = "Dodaj pracę",
  addGang = "Dodaj gang",
  editJob = "Edytuj pracę",
  editGang = "Edytuj gang",
  manageJobs = "Zarządzaj pracami",
  manageGangs = "Zarządzaj gangami",
  jobName = "Nazwa pracy",
  gangName = "Nazwa gangu",
  selectGrades = "Wybierz rangi",
  selectAll = "Zaznacz wszystko",
  deselectAll = "Odznacz wszystko",
  invalidJobName = "Nieprawidłowa nazwa pracy. Sprawdź konfigurację swojego frameworka.",
  invalidGangName = "Nieprawidłowa nazwa gangu. Sprawdź konfigurację swojego frameworka.",
  grades = "Rangi",
  noJobsConfigured = "Brak skonfigurowanych prac",
  noGangsConfigured = "Brak skonfigurowanych gangów",
  click = "Kliknij",
  toGetStarted = "aby rozpocząć.",
  more = "więcej",
  jobPlaceholder = "Na przykład: cardealer",
  jobOptionalDescription = "Opcjonalnie powiąż role salonu z pracą frameworka. Gdy pracownicy są zatrudniani/zwalniani, ich praca frameworka również zostanie zaktualizowana.",
  jobRankPermissions = "Uprawnienia rangi pracy",
  roleToJobRankMapping = "Mapowanie roli do rangi pracy",
  addPerm = "Dodaj uprawnienie",

  -- v2: Colour selector
  searchColours = "Szukaj kolorów...",
  noColoursFound = "Nie znaleziono kolorów",

  -- v2: Interactions creator
  noInteractions = "Brak interakcji",
  highlightInteractions = "Podświetl interakcje",
  explorationMode = "Tryb eksploracji",
  pressEsc = "Naciśnij ESC",
  toWalkAround = "aby się rozejrzeć",
  toReturnToUI = "aby wrócić do UI",
  points = "punkty",
  location = "lokalizacja",
  manageLocations = "Zarządzaj lokalizacjami",

  -- v2: Interaction modal
  interactionType = "Typ",
  nicknameOptional = "Pseudonim (Opcjonalny)",
  invalidModel = "Nieprawidłowy model",
  failedToValidateModel = "Nie udało się zweryfikować modelu",
  pedScenario = "Scenariusz peda",
  coords = "Współrzędne",
  size = "Rozmiar",
  blip = "Blip",
  enableBlip = "Włącz blip",
  blipIconId = "ID ikony blipa",
  blipColourId = "ID koloru blipa",
  blipSize = "Rozmiar blipa",
  marker = "Marker",
  enableMarker = "Włącz marker",
  markerStyleId = "ID stylu markera",
  markerSize = "Rozmiar markera",
  markerColor = "Kolor markera",
  markerBobUpAndDown = "Pulsuj w górę i w dół",
  markerFaceCamera = "Skierowany do kamery",
  markerRotate = "Obracaj",
  markerDrawOnEnts = "Rysuj na jednostkach",
  updatePosition = "Aktualizuj pozycję",
  setPosition = "Ustaw pozycję",

  -- v2: Interaction types
  interactionPoint = "Punkt",
  interactionPointDesc = "Pojedynczy skalowany punkt, z opcjonalnym markerem",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Strefa wielowspółrzędnościowa do tworzenia określonego obszaru interakcji",
  interactionVehicle = "Pojazd",
  interactionVehicleDesc = "Wygeneruj model pojazdu, idealny dla metod interakcji target lub 3D text UI",
  interactionObject = "Obiekt",
  interactionObjectDesc = "Wygeneruj model obiektu, idealny dla metod interakcji target lub 3D text UI",
  interactionPed = "Ped",
  interactionPedDesc = "Wygeneruj model peda z opcjonalnym scenariuszem, idealny dla metod interakcji target lub 3D text UI",

  -- v2: Import modal
  importLocationsTitle = "Importuj lokalizacje",
  syncStockLabel = "Synchronizuj zapasy",
  syncStockDescription = "Dodaj pojazdy do zapasów każdego salonu na podstawie jego kategorii",
  importSourceSelectorDesc = "Możesz zaimportować zestaw domyślnych lokalizacji dla gotowej konfiguracji lub zaimportować istniejące lokalizacje z konfiguracji, jeśli migrujesz z Dealerships v1.",
  importSourceSelectorSkipDesc = "Lokalizacje już istniejące w bazie danych zostaną pominięte; zaimportowane zostaną tylko nowe lokalizacje.",
  successfullyImported = "Pomyślnie zaimportowano",
  alreadyExist = "Już istnieje",
  defaultLocations = "Domyślne lokalizacje",
  defaultLocationsDesc = "Importuj wstępnie skonfigurowane lokalizacje salonu (PDM, Luksus, Łodzie, Lotnicze, Ciężarówki)",
  existingConfig = "Istniejąca konfiguracja",
  existingConfigDesc = "Importuj lokalizacje z config.lua (dla migracji v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Czy chcesz automatycznie dodać pojazdy do zapasów tego salonu na podstawie wybranych kategorii?",
  categorySyncEditDesc = "Zmieniłeś kategorie dla tego salonu. Czy chcesz automatycznie zaktualizować zapasy pojazdów?",
  addVehicles = "Dodaj pojazdy",
  removeVehicles = "Usuń pojazdy",
  fromNewCategories = "z nowych kategorii",
  fromSelectedCategories = "z wybranych kategorii",
  fromRemovedCategories = "z usuniętych kategorii",
  categoriesAdded = "Dodane kategorie:",
  categoriesRemoved = "Usunięte kategorie:",
  skip = "Pomiń",
  syncStock = "Synchronizuj zapasy",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Sprawdzanie dostępności źródła...",
  vehiclesAvailableToImport = "pojazdy dostępne do importu",
  includesDealershipIds = "zawiera ID salonów",
  sourceUnavailable = "Źródło niedostępne",
  noVehiclesAdminDescription = "Możesz dodać pojazdy ręcznie lub zaimportować je z frameworka.",
  appendBehaviour = "Dołącz",
  overwriteBehaviour = "Nadpisz",
  appendDescription = "Dodaj tylko nowe pojazdy, które nie istnieją jeszcze w bazie danych",
  overwriteDescription = "Usuń wszystkie istniejące dane pojazdów i zaimportuj od nowa",
  stockAssignmentMethod = "Metoda przypisania zapasów",
  useDealershipIdsFromSource = "Użyj ID salonów ze źródła",
  matchByVehicleCategory = "Dopasuj według kategorii pojazdu",
  byShopDescription = "Pojazdy zostaną przypisane do salonów na podstawie pola 'shop' w danych źródłowych",
  byCategoryDescription = "Pojazdy zostaną przypisane do salonów z pasującymi kategoriami",
  overwriteWarning = "Ostrzeżenie: Nadpisanie usunie wszystkie istniejące pojazdy, zamówienia, pojazdy wystawowe i dane sprzedaży.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "Tabela pojazdów ESX",
  selectCategory = "Wybierz kategorię",

  -- v2: Management menu items
  vehiclesMenu = "Pojazdy",
  displayVehiclesMenu = "Pojazdy wystawowe",
  ordersMenu = "Zamówienia",
  salesMenu = "Sprzedaże",
  bankAccountMenu = "Konto bankowe",
  employeesMenu = "Pracownicy",
  couponsMenu = "Kupony",
  settingsMenu = "Ustawienia",
  noPermissionAccessManagement = "Nie masz uprawnień do funkcji zarządzania.",
  backToAdmin = "Powrót do admina",
  viewingAsAdmin = "PODGLĄD JAKO ADMIN",

  -- v2: Coupons table
  code = "Kod",
  uses = "Użycia",
  perPlayer = "Na gracza",
  never = "Nigdy",
  noCoupons = "Brak kuponów",
  noCouponsDescription = "Klienci mogą wprowadzić kupon na etapie zakupu pojazdu i zaoszczędzić pieniądze.",

  -- v2: Coupon modal
  couponCodeLabel = "Kod kuponu",
  couponCodePlaceholder = "np. LATO2024 lub OSZCZEDZ10",
  couponCodeHelp = "Wprowadź własny kod (do 25 znaków, tylko litery, cyfry i myślniki) lub kliknij 'Generuj'.",
  maxNumberOfUsesPlaceholder = "Maksymalna liczba użyć",
  maxUsesPerPlayerPlaceholder = "Maksymalne użycia na gracza",
  vehicleRestrictionsPlaceholder = "Wprowadź kody spawn oddzielone przecinkami (np. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Zezwól na zakupy finansowane",
  createCoupon = "Utwórz kupon",
  updateCoupon = "Aktualizuj kupon",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kod kuponu jest wymagany",
  couponCodeMaxLength = "Kod może mieć maksymalnie 25 znaków",
  couponCodeInvalidChars = "Kod może zawierać tylko wielkie litery, cyfry i myślniki",
  discountTypeRequired = "Typ rabatu jest wymagany",
  discountValueRequired = "Wartość rabatu jest wymagana",
  discountValueMin = "Wartość rabatu musi być większa niż 0",
  discountValueMaxPercent = "Procent nie może przekraczać 100",
  maxUsesRequired = "Maksymalne użycia są wymagane",
  maxUsesMin = "Musi być co najmniej 1",
  perPlayerLimitRequired = "Limit na gracza jest wymagany",
  expiryDateRequired = "Data wygaśnięcia jest wymagana",
  vehicleRestrictionsRequired = "Ograniczenia pojazdów są wymagane",
  categoryRestrictionsRequired = "Ograniczenia kategorii są wymagane",
  selectAtLeastOneCategory = "Wybierz co najmniej jedną kategorię",

  -- v2: Dashboard
  today = "Dzisiaj",
  thisMonth = "Ten miesiąc",
  allTime = "Cały czas",
  recentSales = "Ostatnie sprzedaże",
  noSalesYet = "Jeszcze brak sprzedaży!",
  noSalesDescription = "Sprzedaże pojazdów pojawią się tutaj po dokonaniu pierwszej.",
  past7Days = "Ostatnie 7 dni",
  past6Months = "Ostatnie 6 miesięcy",
  numberOfSales = "Liczba sprzedaży",
  noDataAvailableForPeriod = "Brak danych dostępnych dla tego okresu",

  -- v2: Display vehicles
  displayVehiclesDescription = "Pojazdy wystawowe to stałe modele showroomowe używane do prezentacji inwentarza i zachęcania klientów do zakupu.",

  -- v2: Employees
  frameworkJobsEnabled = "Prace frameworka włączone",
  frameworkJobsDescription = "Zarządzanie pracownikami jest obsługiwane przez system prac frameworka. Gracze z pracą salonu będą mieli automatyczny dostęp na podstawie rangi. Skonfiguruj uprawnienia pracy w ustawieniach lokalizacji panelu admina.",
  joinedColumn = "Dołączył",
  youBadge = "Ty",

  -- v2: Orders
  noOrdersTitle = "Brak zamówień",
  noOrdersDescription = "Aby złożyć zamówienie, otwórz zakładkę 'Pojazdy' i kliknij 'Zamów' przy pojeździe, który chcesz uzupełnić.",
  inProgress = "W trakcie",
  awaitingDelivery = "Oczekuje na dostawę",
  orderedBy = "Zamówione przez",
  viewDeliveryInfo = "Zobacz info o dostawie",

  -- v2: Delivery
  startDeliveryMissionTitle = "Rozpocznij misję dostawy",
  startDeliveryDescription = "Zaraz rozpoczniesz misję dostawy dla tego zamówienia pojazdu. Musisz dojechać do punktu odbioru, odebrać przyczepę z ładunkiem i dostarczyć ją do salonu.",
  totalDistanceAndDriveTime = "Całkowita odległość i czas jazdy",
  roundTrip = "w obie strony",
  deliveryCompleteTitle = "Dostawa zakończona",
  deliveryInProgressTitle = "Dostawa w trakcie",
  deliveredAt = "Dostarczone o:",
  startedAt = "Rozpoczęte o:",
  deliveredBy = "Dostarczone przez:",
  beingDeliveredBy = "Dostarczane przez:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Brak zamówień dostępnych do dostawy. Zamówienia muszą być gotowe i nie być w aktywnej dostawie.",
  confirmDeliveryTitle = "Potwierdź dostawę",
  configureDeliveryTitle = "Skonfiguruj dostawę",
  trailerCapacityExceeded = "Przekroczono pojemność przyczepy! Wybrałeś %{usedSlots} slotów, ale maksimum to %{maxSlots} slotów.",
  smallVehiclesSlotInfo = "Pamiętaj: małe pojazdy zajmują 1 slot, średnie pojazdy zajmują 1.5 slota.",
  fetchingRoute = "Pobieranie...",
  getRouteButton = "Pobierz trasę",
  selectTrailerType = "Wybierz typ przyczepy",
  carTrailerLabel = "Laweta",
  smallMedium = "(Mały/Średni)",
  containerLabel = "Kontener",
  large = "(Duży)",
  carTrailerDescription = "Laweta ma 2 rzędy. Każdy rząd mieści 3 małe (1 slot każdy) lub 2 średnie (1.5 slota każdy). Maksymalnie 6 slotów.",
  containerDescription = "Przyczepa kontenerowa przewozi 1 duży pojazd",
  selectOrdersTitle = "Wybierz zamówienia",
  slots = "sloty",
  noOrdersForTrailerType = "Brak zamówień dostępnych dla tego typu przyczepy.",
  qty = "Ilość:",
  inTransit = "w tranzycie",
  totalVehicles = "Łącznie pojazdów:",
  estimatedTime = "Szacowany czas:",
  unknown = "Nieznany",

  -- v2: Sales
  salesEmptyDescription = "Sprzedaże pojazdów pojawią się tutaj po dokonaniu pierwszej.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Zamówienie złożone!",
  orderPlacedTruckingDescription = "Twoje zamówienie jest gotowe do odbioru. Przejdź do strony zamówień, aby je zrealizować.",
  orderPlacedTimedDescription = "Twoje zamówienie zostanie dostarczone za %{value} minut.",
  goToOrders = "Przejdź do zamówień",
  noStockAvailableDescription = "Brak zapasów dla tego pojazdu. Osiągnięto globalny limit zapasów.",
  stockUpdatedDescription = "Ilość zapasów została pomyślnie zaktualizowana.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktywne jazdy próbne",
  tracking = "Śledzenie",
  track = "Śledź",
  endButton = "Zakończ",
  endTestDriveTitle = "Zakończ jazdę próbną",
  endTestDriveConfirmation = "Czy na pewno chcesz zakończyć tę jazdę próbną? Pojazd zostanie usunięty, a pasażerowie nie zostaną przeteleportowani do salonu.",
  vehicleLocationOnMap = "Lokalizacja pojazdu została oznaczona na mapie.",
  sell = "Sprzedaj",
  couponCodeOptional = "Kod kuponu (Opcjonalny)",
  pleaseEnterCouponCode = "Wprowadź kod kuponu",
  invalidCouponCode = "Nieprawidłowy kod kuponu",
  failedToValidateCoupon = "Nie udało się zweryfikować kuponu",
  apply = "Zastosuj",
  applying = "Stosowanie...",
  allStock = "Wszystkie zapasy",
  inStockFilter = "Na stanie",
  outOfStockFilter = "Brak na stanie",
  noResultsFound = "Nie znaleziono wyników",
  noResults = "Brak wyników",
  noVehiclesMatchSearch = "Żadne pojazdy nie pasują do wyszukiwania",
  noVehiclesMatchFilters = "Żadne pojazdy nie pasują do aktualnych filtrów",
  noItemsMatchSearch = "Żadne przedmioty nie pasują do wyszukiwania",
  noItemsMatchFilters = "Żadne przedmioty nie pasują do aktualnych filtrów",
  selectColour = "Wybierz kolor",
  refreshNearbyPlayers = "Odśwież pobliskich graczy",
  you = "Ty",
  items = "przedmioty",
  waitingForCustomerToRespond = "Oczekiwanie na odpowiedź klienta...",
  vehicleSpawnedMessage = "Pojazd pojawił się w punkcie na mapie - zaprowadź tam klienta.",
  customerDeclinedMessage = "Klient odrzucił prośbę o zakup.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "PODPISZ TUTAJ",
  acceptAndPurchase = "Zaakceptuj i kup",
  couponApplied = "Kupon %{code} zastosowany! Oszczędzasz %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Potrzebujesz co najmniej 3 punktów, aby ukończyć strefę! (Aktualnie %{value})",
  addPoint = "Dodaj punkt",
  removeLast = "Usuń ostatni",
  completeZone = "Ukończ strefę",
  spawnPreview = "Podgląd spawnu",
  up = "Góra",
  down = "Dół",
  confirm = "Potwierdź",
  placePoint = "Umieść punkt",
  radius = "Promień",

  -- v2: Blip labels
  soldVehicleLocation = "Lokalizacja sprzedanego pojazdu",
  testDriveVehicleBlip = "Pojazd do jazdy próbnej",

  -- v2: Stock sync
  stockSyncResult = "Synchronizacja zapasów: %{added} dodanych, %{removed} usuniętych",
  stockSyncAdded = "Synchronizacja zapasów: %{value} pojazdów dodanych",
  importSuccessful = "Import zakończony! %{imported} pojazdów zaimportowanych (łącznie %{total})",

  -- v2: Tooltip actions
  findOnMap = "Znajdź na mapie",
  adminPanel = "Panel admina",

  -- v2: Common dropdown
  selectOne = "Wybierz jeden",
}
