Locales = Locales or {}

Locales['pt'] = {
  -- UI
  vehicle = "Veículo",
  vehicles = "Veículos",
  dealership = "Concessionária",
  dealerships = "Concessionárias",
  vehiclesCount = "veículo(s)",
  dealersCount = "concessionária(s)",
  accountBalance = "Saldo da Conta",
  bank = "Conta Bancária",
  cash = "Dinheiro",
  amount = "Valor",
  societyFund = "Fundo da Sociedade",
  paymentSource = "Origem do Pagamento",
  purchase = "Compra",
  personalPurchase = "Compra Pessoal",
  societyPurchase = "Compra da Sociedade",
  purchaseType = "Tipo de Compra",
  deposit = "Depósito",
  withdraw = "Retirar",
  all = "Todos",
  yes = "Sim",
  no = "Não",
  add = "Adicionar",
  edit = "Editar",
  id = "ID",
  created = "Criado",
  type = "Tipo",
  name = "Nome",
  owner = "Proprietário",
  bankBalance = "Saldo Bancário",
  status = "Status",
  back = "Voltar",
  previous = "Anterior",
  next = "Próximo",
  admin = "Admin",
  vehiclesAdmin = "Administração de Veículos",
  dealershipsAdmin = "Administração de Concessionárias",
  search = "Buscar",
  noDealershipsFound = "Nenhuma concessionária encontrada",
  noVehicles = "Nenhum veículo encontrado",
  page = "Página",
  of = "de",
  every = "todos",
  show = "Mostrar",
  active = "Ativo",
  activeFinance = "Financiamento Ativo",
  failed = "Pagamento Falhou",
  removed = "Removido",
  setOwner = "Definir Proprietário",
  manage = "Gerenciar",
  deleteData = "Excluir Dados",
  deleteVehicle = "Excluir Veículo",
  delete = "Excluir",
  deleteConfirmation = "Você tem certeza?",
  deleteConfirmationDanger = "Você tem certeza? Essa ação é irreversível.",
  setDealershipOwner = "Definir Proprietário da Concessionária",
  overwriteDealerPrices = "Sobrescrever preços da concessionária",
  nearbyPlayers = "Jogadores Próximos",
  noPlayersNearby = "Nenhum jogador próximo",
  selectPlayer = "Selecionar jogador",
  required = "Obrigatório",
  forExample = "Por exemplo",
  spawnCode = "Código de Spawn",
  brand = "Marca",
  model = "Modelo",
  category = "Categoria",
  price = "Preço",
  import = "Importar",
  importing = "Importando",
  importBehaviour = "Comportamento de Importação",
  importVehicles = "Importar veículos",
  importFrom = "Importar de",
  dashboard = "Painel de Controle",
  displayVehicle = "Exibir Veículo",
  displayVehicles = "Exibir Veículos",
  orders = "Pedidos",
  sales = "Vendas",
  vehiclesOnDisplay = "Veículos em Exibição",
  employees = "Funcionários",
  settings = "Configurações",
  switchVehicle = "Trocar Veículo",
  remove = "Remover",
  noDisplayVehicles = "Nenhum veículo em exibição",
  selectVehicle = "Selecionar veículo",
  colour = "Cor",
  placeVehicle = "Colocar Veículo",
  orderVehicle = "Pedir Veículo",
  cancelOrder = "Cancelar Pedido",
  delivery = "Entrega",
  delivered = "Entregue",
  noOrders = "Nenhum pedido encontrado",
  quantity = "Quantidade",
  totalCost = "Custo Total",
  totalSales = "Total de Vendas",
  noSales = "Nenhuma venda encontrada",
  paid = "Pago",
  owed = "Devido",
  dealershipName = "Nome da Concessionária",
  save = "Salvar Alterações",
  cancel = "Cancelar",
  notEnoughMoney = "Dinheiro insuficiente",
  placeOrder = "Fazer Pedido",
  purchaseCost = "Custo de Compra",
  salePrice = "Preço de Venda",
  inStock = "Em estoque",
  outOfStock = "Sem estoque",
  placeVehiclePrompt = "Pressione %{value} para colocar o veículo. Podes fazer ajustes finos posteriormente!",
  remaining = "Restante",
  prePurchaseRepoWarning = "Se não conseguires pagar as suas parcelas, o teu  veículo será retomado.",
  repossessionWarning = "O teu último pagamento falhou - o teu veículo será retomado, a menos que faças um pagamento agora.",
  recurringPayment = "Pagamento Recorrente",
  remainingBalance = "Saldo Restante",
  remainingPayments = "Parcelas Restantes",
  paymentTakenEvery = "Pagamento realizado a cada",
  hours = "horas",
  seconds = "segundos",
  nextPayment = "Próximo pagamento",
  makePayment = "Realizar pagamento",
  vehicleRepossessed = "Veículo será retomado",
  payInFull = "Pagar integralmente",
  earlyPaymentConfirmation = "Tem certeza de que deseja fazer um pagamento antecipado de",
  financedVehicles = "Veículos Financiados",
  noFinancedVehicles = "Não possui veículos com financiamento ativo",
  financeBreakdown = "Detalhes do Financiamento",
  initialPayment = "Pagamento Inicial",
  payments = "Parcelas",
  length = "Duração",
  interest = "Juros",
  totalPayable = "Total a Pagar",
  leaveShowroom = "Sair da Exibição",
  handling = "Manuseio",
  topSpeed = "Velocidade Máxima",
  power = "Potência",
  torque = "Torque",
  brake = "Freio",
  financing = "Financiamento",
  financingAvailable = "Financiamento disponível",
  paymentsOf = "parcelas de",
  clear = "Limpar",
  testDrive = "Test Drive",
  allCategories = "Todas as Categorias",
  sortByName = "Ordenar por: Nome",
  sortByAvailability = "Ordenar por: Disponibilidade",
  sortByCheapest = "Ordenar por: Mais Barato",
  sortByMostExpensive = "Ordenar por: Mais Caro",
  sortByNewest = "Ordenar por: Mais Recente",
  purchaseVehicle = "Comprar Veículo",
  purchaseFor = "Comprar para",
  selectSociety = "Selecionar uma sociedade",
  financeOverPayments = "Financiar em %{value} parcelas",
  payToday = "Pagar hoje",
  financeThen = "Depois",
  seeFullBreakdown = "Ver detalhes completos",
  testDriveExit = "Pode sair do veículo a qualquer momento para encerrar o teste drive.",

  -- NOTIFICATIONS
  purchaseSuccess = "Parabéns pela sua compra!",
  depositSuccess = "Depósito realizado com sucesso",
  withdrawSuccess = "Retirada realizada com sucesso",
  errorNotEnoughMoney = "Você não tem dinheiro suficiente",
  errorVehicleOutOfStock = "Este veículo está sem estoque",
  errorCannotAffordVehicle = "Você não pode pagar por este veículo",
  vehicleFinancePaymentMade = "Pagamento do financiamento realizado para o seu veículo %{value}",
  vehicleFinancePaidOff = "Parabéns, você quitou e agora é dono do seu veículo %{value}",
  vehicleFinancePaymentFailed = "Falha no pagamento do financiamento para o seu veículo %{value}",
  vehicleFinanceRepossessedSoon = "Precisa fazer um pagamento para o teu veículo %{value} ou ele será retomado em breve",
  vehicleFinanceRepossessed = "Devido à falta de pagamento, o teu veículo foi retomado com a placa %{value}",
  dealershipNotEnoughFunds = "A concessionária não tem fundos suficientes",
  dealershipVehiclesOrdered = "Veículo(s) foram pedidos com sucesso",
  dealershipOrderCancelled = "Pedido cancelado com sucesso",
  errorVehicleWithSpawnCodeExists = "Já existe um veículo com este código de spawn",
  errorExitVehicle = "Precisa sair do veículo primeiro",
  
  -- NEW v1.1
  purchaseRequest = "Pedido de compra",
  sendRequest = "Enviar pedido",
  dealer = "Comerciante",
  financed = "Financiado",
  signHere = "Assinar aqui",
  signFirstError = "Por favor, assine primeiro",
  denyRequest = "Recusar pedido",
  playerTooManyFinancedVehicles = "O jogador tem demasiados veículos financiados",
  employeePermissionsError = "Não tem as permissões necessárias para os empregados",
  managerRole = "Diretor",
  supervisorRole = "Supervisor",
  salesRole = "Vendas",
  ownerRole = "Proprietário",
  employmentRequest = "Pedido de emprego",
  accept = "Aceitar",
  jobOfferDescription = "Ofereceram-lhe um emprego no concessionário \"%{value}\". Gostarias de aceitar?",
  pending = "Pendente",
  employeeHiredMsg = "O pedido de aluguer do concessionário foi aceite!",
  employeeRejectedMsg = "O pedido de aluguer do concessionário foi rejeitado",
  sellVehicle = "Vender veículo",
  vehicleTerms = "Condições do veículo",
  financePayments = "Pagamentos financeiros",
  commission = "Comissão",
  role = "Papel",
  firedNotification = "Foi despedido do concessionário \"%{value}\"",
  dealershipTooFarAway = "Não está perto de nenhum concessionário",
  restoreDisplayVehicles = "Salão de exposição Restore",
  customer = "Cliente",
  lessThanAMin = "Menos de um minuto",
  mins = "mínimo(s)",
  notInVehicle = "Não está sentado num veículo",
  notYourVehicleError = "Este veículo não lhe pertence",
  vehicleFinancedError = "Não pode vender este veículo porque ainda tem prestações de financiamento",
  dealershipDoesntSellVehicle = "Este concessionário não pode comprar este veículo",
  dealershipWantsYourVehicle = "Parabéns! Este concessionário gostaria de comprar o seu veículo.",
  purchasePrice = "Preço de oferta: ",

  spawnCodeInvalid = "Código de spawn inválido",
  salesRep = "Representante de Vendas",
  directSaleAccepted = "Pedido de venda direta aceite! A sua comissão foi paga.",
  directSaleRejected = "Pedido de venda direta rejeitado",

  displayVehicleOutsideZone = "Os veículos de exposição devem ser colocados dentro da zona do concessionário",
  serverAdmin = "Admin do Servidor",
  selfService = "Autoatendimento",
  owned = "Próprio",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Método de pagamento inválido",
  paymentMethodNoFinance = "Este método de pagamento não suporta financiamento",
  couldNotGeneratePlate = "Não foi possível gerar a matrícula",
  invalidCoupon = "Cupão inválido: %{value}",
  tooManyFinancedVehicles = "Tem demasiados veículos financiados",
  couldNotSpawnVehicle = "Não foi possível gerar o veículo",

  -- v2: Permissions
  insufficientPermissions = "Permissões insuficientes",

  -- v2: Coupons
  couponCodeAlreadyExists = "O código de cupão já existe",
  failedToCreateCoupon = "Falha ao criar cupão",
  couponCreatedSuccessfully = "Cupão criado com sucesso",
  couponNotFound = "Cupão não encontrado",
  couponUpdatedSuccessfully = "Cupão atualizado com sucesso",
  failedToDeleteCoupon = "Falha ao eliminar cupão",
  couponDeletedSuccessfully = "Cupão eliminado com sucesso",
  editCoupon = "Editar cupão",
  addCoupon = "Adicionar cupão",
  couponCode = "Código do cupão",
  generating = "A gerar...",
  generate = "Gerar",
  discountType = "Tipo de desconto",
  percentageOff = "Percentagem de desconto",
  amountOff = "Valor de desconto",
  discountValue = "Valor do desconto",
  unlimitedTotalUses = "Utilizações totais ilimitadas",
  unlimitedUsesPerPlayer = "Utilizações ilimitadas por jogador",
  setExpiryDate = "Definir data de validade",
  restrictToSpecificVehicles = "Restringir a veículos específicos",
  restrictToSpecificCategories = "Restringir a categorias específicas",
  allowUseWithFinance = "Permitir utilização com financiamento",
  deleteCoupon = "Eliminar cupão",
  inactive = "Inativo",
  expired = "Expirado",
  maxUses = "Utilizações máximas",
  coupons = "Cupões",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Apenas administradores do servidor podem autocontratar-se",
  playerNotFound = "Jogador não encontrado",
  failedToHireEmployee = "Falha ao contratar funcionário",
  failedToFireEmployee = "Falha ao despedir funcionário",
  failedToUpdateEmployeeRole = "Falha ao atualizar cargo do funcionário",
  hireEmployee = "Contratar funcionário",
  fireEmployee = "Despedir funcionário",
  editRole = "Editar cargo",
  fire = "Despedir",
  changeRole = "Alterar cargo",
  updateRole = "Atualizar cargo",

  -- v2: Test drives
  maxTestDrivesReached = "Este concessionário atingiu o número máximo de test drives ativos",
  testDriveNotEnabled = "Test drives não estão ativados neste concessionário",
  noTestDriveSpawnCoords = "Não há coordenadas de spawn de test drive configuradas para este concessionário",
  couldNotSpawnTestDriveVehicle = "Não foi possível gerar o veículo de test drive",
  couldNotGetPlateFromServer = "Não foi possível obter a matrícula do servidor",
  couldNotRegisterTestDriveVehicle = "Não foi possível registar o veículo de test drive",
  testDriveEndedByEmployee = "O test drive foi terminado por outro funcionário",
  trackingVehicleLocation = "A rastrear localização do veículo...",
  directSaleCancelled = "O pedido de venda foi cancelado pelo vendedor",
  testDriveKeysReceived = "Recebeu as chaves do veículo de test drive",
  testDriveEndedCustomer = "O test drive terminou",
  starting = "A iniciar...",
  startTestDrive = "Iniciar test drive",
  spawningTestDriveVehicle = "A gerar veículo de test drive...",
  testDriveReady = "Test drive pronto",
  testDriveWalkToVehicle = "O veículo de test drive apareceu no ponto marcado no seu mapa. Acompanhe o cliente até ao veículo. Depois de dar as chaves ao cliente, terá de terminar manualmente o test drive quando ele regressar.",
  givingKeys = "A entregar chaves...",
  continueAndGiveKeys = "Continuar e dar chaves",
  endTestDrive = "Terminar test drive",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Sem stock disponível para este veículo",
  globalStockLimitExceeded = "Apenas %{value} unidades disponíveis",
  orderNotFoundOrFulfilled = "Encomenda não encontrada ou já processada",
  priceBelowMinimum = "O preço não pode ser inferior a %{value}",
  priceAboveMaximum = "O preço não pode ser superior a %{value}",
  stockUpdated = "Stock atualizado",
  changesSaved = "Alterações guardadas",
  noStockAvailable = "Sem stock disponível",
  orderPlaced = "Encomenda realizada",
  remainingInStock = "restante em stock global",
  exceedsStockLimit = "Excede limite de stock",
  setStockQty = "Definir quantidade de stock",
  invalidStockValue = "Por favor, introduza um valor de stock válido",
  errorSettingStock = "Erro ao definir stock",
  stockQuantity = "Quantidade de stock",
  currentStock = "Stock atual",
  priceLimitsEnabled = "Ativar limites de preço",
  priceLimitsDescription = "Quando ativado, os gestores do concessionário só podem definir preços dentro do intervalo especificado.",
  minPrice = "Preço mínimo",
  maxPrice = "Preço máximo",
  optional = "Opcional",
  unlimitedStock = "Stock ilimitado",
  globalStockLimit = "Limite de stock global",
  globalStockLimitDescription = "Defina um número máximo de unidades que podem ser encomendadas em todos os concessionários.",
  currentlyOrdered = "Atualmente encomendado",
  priceRange = "Intervalo de preços",
  noMinimum = "Sem mínimo",
  noMaximum = "Sem máximo",
  vehicleStock = "Stock de veículos",

  -- v2: Sales
  allSales = "Todas as vendas",
  paidInFull = "Pago na totalidade",
  salesVolume = "Volume de vendas",
  pastMonth = "Mês passado",
  pastYear = "Ano passado",

  -- v2: Management misc
  exploitAttemptDetected = "Pare de tentar explorar o script",
  dealershipNoJobConfigured = "O concessionário não tem emprego configurado",
  modelDoesNotMatchDb = "O modelo do veículo não corresponde à base de dados",
  importFailed = "Importação falhou: %{value}",
  notInDealershipZone = "Deve estar dentro de um concessionário para usar este comando",
  notAnEmployee = "Não é funcionário deste concessionário.",
  failedToPrepareDelivery = "Falha ao preparar entrega",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "O modelo do veículo não existe - contacte um admin",
  vehiclePlateInvalid = "A matrícula deste veículo é inválida (pressione F8 para mais detalhes)",
  currentlyInRagdollState = "Está atualmente em estado ragdoll",
  vehicleDoesNotExistContactAdmin = "O veículo não existe. Por favor, contacte um admin!",
  vehicleSecurityBreachDetected = "Violação de segurança do veículo detetada",

  -- v2: Admin vehicles
  allVehicles = "Todos os veículos",
  unassignedVehicles = "Sem concessionário",
  searchDealerships = "Pesquisar concessionários...",

  -- v2: Trucking mission
  truckingGetInTruck = "Entre no camião na localização marcada para iniciar a sua entrega",
  truckingDriveToDelivery = "Conduza até ao local de entrega",
  truckingCompleteDelivery = "Completar a entrega",
  truckingDeliveryComplete = "Entrega concluída: Concluiu a entrega com sucesso!",
  truckingDeliveryFailed = "Entrega falhou: Algo correu mal com a entrega",
  truckingDriveToPickup = "Conduza até ao ponto de recolha para recolher o reboque",
  truckingMissionFailedSpawnCargo = "Missão falhou: Não foi possível gerar o reboque de carga",
  truckingMissionFailedFindCargo = "Missão falhou: Não foi possível encontrar a carga gerada",
  truckingVehiclesLoaded = "%{count} veículo%{s} carregado",
  truckingWrongTrailer = "Reboque errado! Deve anexar o reboque de missão correto.",
  truckingTrailerAttached = "Reboque anexado - pronto para continuar",
  truckingDriveToPickupLocation = "Conduza até ao ponto de recolha",
  truckingWaitingForVehicles = "A aguardar carregamento de veículos...",
  truckingDriveUnderTrailer = "Passe por baixo do reboque para o anexar",
  truckingGetInTruckContinue = "Entre no camião para continuar",
  truckingMissionStarted = "Missão de transporte iniciada: Ponto de recolha - %{location}",
  truckingMissionCancelled = "Missão cancelada: Cancelou a missão de transporte",
  truckingNoActiveMission = "Sem missão de transporte ativa para cancelar",
  deliveryNotPrepared = "Entrega não preparada - por favor, tente novamente",
  deliveryConfigMismatch = "Configuração de entrega não coincidente",
  deliveryPreparationExpired = "Preparação de entrega expirada - por favor, tente novamente",
  noTruckingVehicleCoordinates = "Coordenadas de veículo de transporte não definidas",
  pickupLocationUnavailable = "Ponto de recolha já não disponível - por favor, tente novamente",
  failedToSpawnTruck = "Falha ao gerar camião",
  clientFailedToStartMission = "O cliente falhou ao iniciar a missão",

  -- v2: Trucking UI/Keys
  keyDismiss = "Fechar",
  keyDeliverCargo = "Entregar carga",
  keyContinueToDelivery = "Continuar para entrega",
  startDeliveryMission = "Iniciar missão de entrega",
  orderDetails = "Detalhes da encomenda",
  pickupLocation = "Ponto de recolha",
  deliveryStatus = "Estado da entrega",
  selectOrders = "Selecionar encomendas",
  carTrailer = "Porta-carros",
  container = "Contentor",
  deliveryRoute = "Rota de entrega",
  startDelivery = "Iniciar entrega",

  -- v2: Direct sales UI
  waitingForCustomer = "A aguardar cliente",
  cancelRequest = "Cancelar pedido",
  saleComplete = "Venda concluída!",
  done = "Concluído",
  saleDeclined = "Venda recusada",
  close = "Fechar",

  -- v2: Display vehicle placement
  movement = "Movimento",
  rotate = "Rodar",
  forward = "Frente",
  backward = "Trás",
  left = "Esquerda",
  right = "Direita",
  rotateLeft = "Rodar esquerda",
  rotateRight = "Rodar direita",

  -- v2: Showroom misc
  originalPrice = "Preço original",
  discount = "Desconto",
  createInteraction = "Criar interação",
  viewAll = "Ver tudo",
  fetchingPlayers = "A obter jogadores",
  refresh = "Atualizar",
  loadingPlayers = "A carregar jogadores...",
  failedToLoadPlayers = "Falha ao carregar jogadores",
  selectAPlayer = "Selecionar um jogador",
  failedToLoadPlayersRetry = "Falha ao carregar jogadores. Clique em 'Atualizar' para tentar novamente.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Concessionário self-service",
  categories = "Categorias",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Localizações",
  createNew = "Criar novo",
  enable = "Ativar",
  disable = "Desativar",
  loading = "A carregar...",
  errors = "Erros",
  update = "Atualizar",
  create = "Criar",

  -- v2: Dealership creation/editing
  createDealership = "Criar concessionário",
  editDealership = "Editar concessionário",
  essentials = "Essenciais",
  advanced = "Avançado",
  noDealershipLocations = "Sem localizações de concessionário",
  noDealershipLocationsDesc = "Pode adicionar uma nova localização, importar da sua configuração (se estiver a migrar da v1) ou adicionar localizações predefinidas automaticamente.",

  -- v2: Location sections
  dealershipZone = "Zona do concessionário",
  showroomAndManagement = "Showroom e gestão",
  openShowroom = "Abrir showroom",
  openManagement = "Abrir gestão",
  enableSellVehicle = "Ativar venda de veículos",
  percentageOfVehicleValue = "Percentagem % do valor do veículo",
  enablePurchase = "Ativar compra",
  purchasedVehicleSpawn = "Spawn de veículo comprado",
  enableTestDrive = "Ativar test drive",
  testDriveVehicleSpawn = "Spawn de veículo de test drive",
  truckDelivery = "Entrega por camião",
  truckDeliveryVehicleSpawn = "Spawn de veículo de entrega",

  -- v2: Location advanced settings
  paymentMethods = "Métodos de pagamento",
  supportsFinancing = "(suporta financiamento)",
  enableFinance = "Ativar financiamento",
  cameraPreset = "Câmara",
  preset = "Predefinido",
  custom = "Personalizado",
  vehiclePosition = "Posição do veículo",
  zoomPositions = "Posições de zoom (separadas por vírgula)",
  zoomPositionsPlaceholder = "exemplo: 5,8,12,8",
  vehicleColour = "Cor do veículo",
  selectionType = "Tipo de seleção",
  noColourSelection = "Sem seleção de cor",
  rgbColourWheel = "Roda de cores RGB",
  listOfRgbColours = "Lista de cores RGB",
  listOfColourIds = "Lista de IDs de cor",
  accessControl = "Controlo de acesso",
  showroomJobWhitelist = "Lista branca de trabalhos do showroom",
  showroomGangWhitelist = "Lista branca de gangs do showroom",
  societyPurchaseJobWhitelist = "Lista branca de trabalhos para compra de sociedade",
  societyPurchaseGangWhitelist = "Lista branca de gangs para compra de sociedade",
  setInGame = "Definir no jogo",
  addNew = "Adicionar novo",

  -- v2: Job/Gang whitelist editor
  job = "Trabalho",
  gang = "Gang",
  jobWhitelist = "Lista branca de trabalhos",
  gangWhitelist = "Lista branca de gangs",
  addJob = "Adicionar trabalho",
  addGang = "Adicionar gang",
  editJob = "Editar trabalho",
  editGang = "Editar gang",
  manageJobs = "Gerir trabalhos",
  manageGangs = "Gerir gangs",
  jobName = "Nome do trabalho",
  gangName = "Nome da gang",
  selectGrades = "Selecionar graus",
  selectAll = "Selecionar tudo",
  deselectAll = "Desselecionar tudo",
  invalidJobName = "Nome de trabalho inválido. Por favor verifique a configuração do seu framework.",
  invalidGangName = "Nome de gang inválido. Por favor verifique a configuração do seu framework.",
  grades = "Graus",
  noJobsConfigured = "Nenhum trabalho configurado",
  noGangsConfigured = "Nenhuma gang configurada",
  click = "Clique",
  toGetStarted = "para começar.",
  more = "mais",
  jobPlaceholder = "Por exemplo: cardealer",
  jobOptionalDescription = "Opcionalmente associe funções do concessionário a um trabalho do framework. Quando funcionários são contratados/despedidos, o seu trabalho do framework também será atualizado.",
  jobRankPermissions = "Permissões de nível de trabalho",
  roleToJobRankMapping = "Mapeamento de função para nível de trabalho",
  addPerm = "Adicionar permissão",

  -- v2: Colour selector
  searchColours = "Pesquisar cores...",
  noColoursFound = "Nenhuma cor encontrada",

  -- v2: Interactions creator
  noInteractions = "Sem interações",
  highlightInteractions = "Destacar interações",
  explorationMode = "Modo exploração",
  pressEsc = "Prima ESC",
  toWalkAround = "para andar",
  toReturnToUI = "para voltar à interface",
  points = "pontos",
  location = "localização",
  manageLocations = "Gerir localizações",

  -- v2: Interaction modal
  interactionType = "Tipo",
  nicknameOptional = "Alcunha (Opcional)",
  invalidModel = "Modelo inválido",
  failedToValidateModel = "Falha ao validar modelo",
  pedScenario = "Cenário de ped",
  coords = "Coordenadas",
  size = "Tamanho",
  blip = "Blip",
  enableBlip = "Ativar blip",
  blipIconId = "ID do ícone do blip",
  blipColourId = "ID da cor do blip",
  blipSize = "Tamanho do blip",
  marker = "Marcador",
  enableMarker = "Ativar marcador",
  markerStyleId = "ID do estilo do marcador",
  markerSize = "Tamanho do marcador",
  markerColor = "Cor do marcador",
  markerBobUpAndDown = "Flutuar para cima e baixo",
  markerFaceCamera = "Virado para a câmara",
  markerRotate = "Rodar",
  markerDrawOnEnts = "Desenhar em entidades",
  updatePosition = "Atualizar posição",
  setPosition = "Definir posição",

  -- v2: Interaction types
  interactionPoint = "Ponto",
  interactionPointDesc = "Ponto único redimensionável, com marcador opcional",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Zona de múltiplas coordenadas para criar uma área de interação específica",
  interactionVehicle = "Veículo",
  interactionVehicleDesc = "Gerar um modelo de veículo, ideal para métodos de interação target ou texto 3D",
  interactionObject = "Objeto",
  interactionObjectDesc = "Gerar um modelo de objeto, ideal para métodos de interação target ou texto 3D",
  interactionPed = "Ped",
  interactionPedDesc = "Gerar um modelo de ped com cenário opcional, ideal para métodos de interação target ou texto 3D",

  -- v2: Import modal
  importLocationsTitle = "Importar localizações",
  syncStockLabel = "Sincronizar stock",
  syncStockDescription = "Adicionar veículos ao stock de cada concessionário com base nas suas categorias",
  importSourceSelectorDesc = "Pode importar um conjunto de localizações predefinidas para uma configuração pronta, ou importar as suas localizações existentes da configuração se estiver a migrar da Dealerships v1.",
  importSourceSelectorSkipDesc = "Localizações que já existam na base de dados serão ignoradas; apenas novas localizações serão importadas.",
  successfullyImported = "Importado com sucesso",
  alreadyExist = "Já existe",
  defaultLocations = "Localizações predefinidas",
  defaultLocationsDesc = "Importar localizações de concessionários pré-configuradas (PDM, Luxo, Barcos, Aéreo, Camiões)",
  existingConfig = "Configuração existente",
  existingConfigDesc = "Importar localizações do seu config.lua (para migração v1)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Deseja adicionar automaticamente veículos ao stock deste concessionário com base nas categorias selecionadas?",
  categorySyncEditDesc = "Alterou as categorias deste concessionário. Deseja atualizar automaticamente o stock de veículos?",
  addVehicles = "Adicionar veículos",
  removeVehicles = "Remover veículos",
  fromNewCategories = "das novas categorias",
  fromSelectedCategories = "das categorias selecionadas",
  fromRemovedCategories = "das categorias removidas",
  categoriesAdded = "Categorias adicionadas:",
  categoriesRemoved = "Categorias removidas:",
  skip = "Ignorar",
  syncStock = "Sincronizar stock",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "A verificar disponibilidade da fonte...",
  vehiclesAvailableToImport = "veículos disponíveis para importar",
  includesDealershipIds = "inclui IDs de concessionário",
  sourceUnavailable = "Fonte não disponível",
  noVehiclesAdminDescription = "Pode adicionar veículos manualmente ou importá-los do seu framework.",
  appendBehaviour = "Adicionar",
  overwriteBehaviour = "Substituir",
  appendDescription = "Apenas adicionar novos veículos que não existam na base de dados",
  overwriteDescription = "Eliminar todos os dados de veículos existentes e importar novamente",
  stockAssignmentMethod = "Método de atribuição de stock",
  useDealershipIdsFromSource = "Usar IDs de concessionário da fonte",
  matchByVehicleCategory = "Corresponder por categoria de veículo",
  byShopDescription = "Os veículos serão atribuídos a concessionários com base no campo 'shop' nos dados de origem",
  byCategoryDescription = "Os veículos serão atribuídos a concessionários com categorias correspondentes",
  overwriteWarning = "Aviso: Substituir eliminará todos os veículos existentes, encomendas, veículos em exposição e dados de vendas.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "Tabela de veículos ESX",
  selectCategory = "Selecionar uma categoria",

  -- v2: Management menu items
  vehiclesMenu = "Veículos",
  displayVehiclesMenu = "Veículos em exposição",
  ordersMenu = "Encomendas",
  salesMenu = "Vendas",
  bankAccountMenu = "Conta bancária",
  employeesMenu = "Funcionários",
  couponsMenu = "Cupões",
  settingsMenu = "Definições",
  noPermissionAccessManagement = "Não tem permissão para aceder às funcionalidades de gestão.",
  backToAdmin = "Voltar à administração",
  viewingAsAdmin = "A VER COMO ADMIN",

  -- v2: Coupons table
  code = "Código",
  uses = "Utilizações",
  perPlayer = "Por jogador",
  never = "Nunca",
  noCoupons = "Sem cupões",
  noCouponsDescription = "Os clientes podem inserir um cupão na fase de compra do veículo e poupar dinheiro.",

  -- v2: Coupon modal
  couponCodeLabel = "Código do cupão",
  couponCodePlaceholder = "ex., VERAO2024 ou POUPA10",
  couponCodeHelp = "Insira um código personalizado (até 25 caracteres, apenas letras, números e hífens) ou clique em 'Gerar'.",
  maxNumberOfUsesPlaceholder = "Número máximo de utilizações",
  maxUsesPerPlayerPlaceholder = "Utilizações máximas por jogador",
  vehicleRestrictionsPlaceholder = "Insira códigos de spawn separados por vírgulas (ex., adder, t20, zentorno)",
  allowOnFinancedPurchases = "Permitir em compras financiadas",
  createCoupon = "Criar cupão",
  updateCoupon = "Atualizar cupão",

  -- v2: Coupon validation messages
  couponCodeRequired = "O código do cupão é obrigatório",
  couponCodeMaxLength = "O código deve ter 25 caracteres ou menos",
  couponCodeInvalidChars = "O código só pode conter letras maiúsculas, números e hífens",
  discountTypeRequired = "O tipo de desconto é obrigatório",
  discountValueRequired = "O valor do desconto é obrigatório",
  discountValueMin = "O valor do desconto deve ser superior a 0",
  discountValueMaxPercent = "A percentagem não pode exceder 100",
  maxUsesRequired = "Utilizações máximas obrigatórias",
  maxUsesMin = "Deve ser pelo menos 1",
  perPlayerLimitRequired = "Limite por jogador obrigatório",
  expiryDateRequired = "Data de expiração obrigatória",
  vehicleRestrictionsRequired = "Restrições de veículos obrigatórias",
  categoryRestrictionsRequired = "Restrições de categorias obrigatórias",
  selectAtLeastOneCategory = "Selecione pelo menos uma categoria",

  -- v2: Dashboard
  today = "Hoje",
  thisMonth = "Este mês",
  allTime = "Todo o tempo",
  recentSales = "Vendas recentes",
  noSalesYet = "Ainda sem vendas!",
  noSalesDescription = "As vendas de veículos aparecerão aqui após ser feita uma.",
  past7Days = "Últimos 7 dias",
  past6Months = "Últimos 6 meses",
  numberOfSales = "Número de vendas",
  noDataAvailableForPeriod = "Sem dados disponíveis para este período",

  -- v2: Display vehicles
  displayVehiclesDescription = "Os veículos em exposição são modelos fixos do showroom usados para mostrar o seu inventário e atrair clientes a fazer uma compra.",

  -- v2: Employees
  frameworkJobsEnabled = "Trabalhos do framework ativados",
  frameworkJobsDescription = "A gestão de funcionários é tratada através do sistema de trabalhos do framework. Os jogadores com o trabalho do concessionário terão acesso automaticamente com base no seu grau. Configure as permissões de trabalho nas definições de localização do painel de admin.",
  joinedColumn = "Entrou",
  youBadge = "Tu",

  -- v2: Orders
  noOrdersTitle = "Sem encomendas",
  noOrdersDescription = "Para fazer uma encomenda, abra o separador 'Veículos' e clique em 'Encomendar' no veículo que deseja reabastecer.",
  inProgress = "Em progresso",
  awaitingDelivery = "A aguardar entrega",
  orderedBy = "Encomendado por",
  viewDeliveryInfo = "Ver info de entrega",

  -- v2: Delivery
  startDeliveryMissionTitle = "Iniciar missão de entrega",
  startDeliveryDescription = "Está prestes a iniciar uma missão de entrega para esta encomenda de veículo. Terá de conduzir até ao ponto de recolha, recolher o reboque de carga e entregá-lo de volta ao concessionário.",
  totalDistanceAndDriveTime = "Distância total e tempo de condução",
  roundTrip = "ida e volta",
  deliveryCompleteTitle = "Entrega concluída",
  deliveryInProgressTitle = "Entrega em progresso",
  deliveredAt = "Entregue às:",
  startedAt = "Iniciado às:",
  deliveredBy = "Entregue por:",
  beingDeliveredBy = "A ser entregue por:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Sem encomendas disponíveis para entrega. As encomendas devem estar prontas e não já numa entrega ativa.",
  confirmDeliveryTitle = "Confirmar entrega",
  configureDeliveryTitle = "Configurar entrega",
  trailerCapacityExceeded = "Capacidade do reboque excedida! Selecionou %{usedSlots} slots mas o máximo é %{maxSlots} slots.",
  smallVehiclesSlotInfo = "Lembre-se: veículos pequenos usam 1 slot, veículos médios usam 1.5 slots.",
  fetchingRoute = "A obter...",
  getRouteButton = "Obter rota",
  selectTrailerType = "Selecionar tipo de reboque",
  carTrailerLabel = "Porta-carros",
  smallMedium = "(Pequeno/Médio)",
  containerLabel = "Contentor",
  large = "(Grande)",
  carTrailerDescription = "O porta-carros tem 2 filas. Cada fila cabe 3 pequenos (1 slot cada) ou 2 médios (1.5 slots cada). Máximo 6 slots no total.",
  containerDescription = "O reboque contentor transporta 1 veículo grande",
  selectOrdersTitle = "Selecionar encomendas",
  slots = "slots",
  noOrdersForTrailerType = "Sem encomendas disponíveis para este tipo de reboque.",
  qty = "Qtd:",
  inTransit = "em trânsito",
  totalVehicles = "Total de veículos:",
  estimatedTime = "Tempo estimado:",
  unknown = "Desconhecido",

  -- v2: Sales
  salesEmptyDescription = "As vendas de veículos aparecerão aqui após ser feita uma.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Encomenda feita!",
  orderPlacedTruckingDescription = "A sua encomenda está pronta para recolha. Vá à página de encomendas para a completar.",
  orderPlacedTimedDescription = "A sua encomenda será entregue em %{value} minutos.",
  goToOrders = "Ir para encomendas",
  noStockAvailableDescription = "Não há stock disponível para este veículo. O limite de stock global foi atingido.",
  stockUpdatedDescription = "A quantidade de stock foi atualizada com sucesso.",

  -- v2: Direct sales tablet
  activeTestDrives = "Test drives ativos",
  tracking = "Rastreamento",
  track = "Rastrear",
  endButton = "Terminar",
  endTestDriveTitle = "Terminar test drive",
  endTestDriveConfirmation = "Tem a certeza de que quer terminar este test drive? O veículo será eliminado e os ocupantes do veículo não serão teletransportados de volta ao concessionário.",
  vehicleLocationOnMap = "A localização do veículo foi colocada no seu mapa.",
  sell = "Vender",
  couponCodeOptional = "Código do cupão (Opcional)",
  pleaseEnterCouponCode = "Por favor insira um código de cupão",
  invalidCouponCode = "Código de cupão inválido",
  failedToValidateCoupon = "Falha ao validar cupão",
  apply = "Aplicar",
  applying = "A aplicar...",
  allStock = "Todo o stock",
  inStockFilter = "Em stock",
  outOfStockFilter = "Esgotado",
  noResultsFound = "Sem resultados encontrados",
  noResults = "Sem resultados",
  noVehiclesMatchSearch = "Nenhum veículo corresponde à sua pesquisa",
  noVehiclesMatchFilters = "Nenhum veículo corresponde aos seus filtros atuais",
  noItemsMatchSearch = "Nenhum item corresponde à sua pesquisa",
  noItemsMatchFilters = "Nenhum item corresponde aos seus filtros atuais",
  selectColour = "Selecionar cor",
  refreshNearbyPlayers = "Atualizar jogadores próximos",
  you = "Tu",
  items = "itens",
  waitingForCustomerToRespond = "A aguardar resposta do cliente...",
  vehicleSpawnedMessage = "O veículo apareceu no ponto no seu mapa - leve o cliente até ele.",
  customerDeclinedMessage = "O cliente recusou o pedido de compra.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "ASSINE AQUI",
  acceptAndPurchase = "Aceitar e comprar",
  couponApplied = "Cupão %{code} aplicado! A poupar %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Precisa de pelo menos 3 pontos para completar a zona! (Atualmente tem %{value})",
  addPoint = "Adicionar ponto",
  removeLast = "Remover último",
  completeZone = "Completar zona",
  spawnPreview = "Pré-visualização de spawn",
  up = "Cima",
  down = "Baixo",
  confirm = "Confirmar",
  placePoint = "Colocar ponto",
  radius = "Raio",

  -- v2: Blip labels
  soldVehicleLocation = "Localização de veículo vendido",
  testDriveVehicleBlip = "Veículo de test drive",

  -- v2: Stock sync
  stockSyncResult = "Sincronização de stock: %{added} adicionados, %{removed} removidos",
  stockSyncAdded = "Sincronização de stock: %{value} veículos adicionados",
  importSuccessful = "Importação bem-sucedida! %{imported} veículos importados (%{total} no total)",

  -- v2: Tooltip actions
  findOnMap = "Encontrar no mapa",
  adminPanel = "Painel de administração",

  -- v2: Common dropdown
  selectOne = "Selecionar um",
}
