Locales = Locales or {}

Locales['sv'] = {
  -- UI
  vehicle = "Fordon",
  vehicles = "Fordon",
  dealership = "Bilfirma",
  dealerships = "Bilfirmor",
  vehiclesCount = "Fordon",
  dealersCount = "Bilfirmor",
  accountBalance = "Konto Saldo",
  bank = "Bankkonto",
  cash = "Kontant",
  amount = "Summa",
  societyFund = "Företagskonto",
  paymentSource = "Betalningsmetod",
  purchase = "Köp",
  personalPurchase = "Personligtköp",
  societyPurchase = "Företagsköp",
  purchaseType = "Köp typ",
  deposit = "Sätt in",
  withdraw = "Ta ut",
  all = "Alla",
  yes = "Ja",
  no = "Nej",
  add = "Lägg till",
  edit = "Ändra",
  id = "ID",
  created = "Skapad",
  type = "Typ",
  name = "Namn",
  owner = "Ägare",
  bankBalance = "Banksaldo",
  status = "Status",
  back = "Tillbaka",
  previous = "Förgående",
  next = "Nästa",
  admin = "Admin",
  vehiclesAdmin = "Fordons Admin",
  dealershipsAdmin = "Firma Admin",
  search = "Sök",
  noDealershipsFound = "Inga firmor hittades",
  noVehicles = "Inga fordon hittades",
  page = "Sida",
  of = "av",
  every = "varje",
  show = "Visa",
  active = "Aktiv",
  activeFinance = "Aktiv Delbetalning",
  failed = "Betalnings misslyckades",
  removed = "Borttagen",
  setOwner = "Sätt ägare",
  manage = "Ändra",
  deleteData = "Tabort Data",
  deleteVehicle = "Tabort Fordon",
  delete = "Tabort",
  deleteConfirmation = "Är du säker?",
  deleteConfirmationDanger = "Är du säker? Denna är oreversebalt.",
  setDealershipOwner = "Sätt firma ägare",
  overwriteDealerPrices = "Överskriv firma priser",
  nearbyPlayers = "Närliggande spelare",
  noPlayersNearby = "Inga spelare i närheten",
  selectPlayer = "Välj spelare",
  required = "Obligatorisk",
  forExample = "För exempel",
  spawnCode = "Spawnnamn",
  brand = "Märke",
  model = "Modell",
  category = "Kategori",
  price = "Pris",
  import = "Import",
  importing = "Importerar",
  importBehaviour = "Importera behaviour",
  importVehicles = "Importera Fordon",
  importFrom = "Importera från",
  dashboard = "Översikt",
  displayVehicle = "Uppvisa Fordon",
  displayVehicles = "Uppvisade Fordon",
  orders = "Beställningar",
  sales = "Försäljningar",
  vehiclesOnDisplay = "Uppvisade Fordon",
  employees = "Anställda",
  settings = "Inställningar",
  switchVehicle = "Byt Fordon",
  remove = "Ta bort",
  noDisplayVehicles = "Inga uppvisade fordon",
  selectVehicle = "Välj fordon",
  colour = "Färg",
  placeVehicle = "Placera Fordon",
  orderVehicle = "Beställ Fordon",
  cancelOrder = "Avbryt Order",
  delivery = "Leverans",
  delivered = "Levererad",
  noOrders = "Inga beställningar hittades",
  quantity = "Mängd",
  totalCost = "Totala kostnad",
  totalSales = "Totala försäljningar",
  noSales = "Inga försäljningar hittades",
  paid = "Betalad",
  owed = "Delbetalad",
  dealershipName = "Bilfirma Namn",
  save = "Spara Ändringar",
  cancel = "Avbryt",
  notEnoughMoney = "Du har inte råd",
  placeOrder = "Placera Beställning",
  purchaseCost = "Kostnad",
  salePrice = "Försäljnings Pris",
  inStock = "I lager",
  outOfStock = "Slut i lager",
  placeVehiclePrompt = "Tryck %{value} för att placera fordon. Du kan finjustera efteråt!",
  remaining = "Kvartstående",
  prePurchaseRepoWarning = "Om du inte hinner betala fordonet i tid så kommer det att återtas.",
  repossessionWarning = "Din senaste betalning misslyckades - Ditt fordon kommer att återhämtas om du inte gör en betalning nu.",
  recurringPayment = "Återkommande Betalning",
  remainingBalance = "Kvarstående Balans",
  remainingPayments = "Kvartsående Betalningar",
  paymentTakenEvery = "Betalning hämtas varje",
  hours = "timmar",
  seconds = "sekunder",
  nextPayment = "Nästa betalning",
  makePayment = "Utför betalning",
  vehicleRepossessed = "Ditt fordon kommer återtas",
  payInFull = "Betala av helt",
  earlyPaymentConfirmation = "Är du säker på att du vill göra en förbetalning på",
  financedVehicles = "Delbetalade Fordon",
  noFinancedVehicles = "Du har inga delbetalde fordon",
  financeBreakdown = "Finans Översikt",
  initialPayment = "Första betalning",
  payments = "Betalningar",
  length = "Längd",
  interest = "Ränta",
  totalPayable = "Totals Betalbart",
  leaveShowroom = "Lämna bilkatalog",
  handling = "Handling",
  topSpeed = "Topp Hastighet",
  power = "Kraft",
  torque = "Vridmoment",
  brake = "Broms",
  financing = "Delbetalning",
  financingAvailable = "Delbetalning Tillgängligt",
  paymentsOf = "betalningar på",
  clear = "Rensa",
  testDrive = "Testkör",
  allCategories = "Alla Kategorier",
  sortByName = "Sortera: Namn",
  sortByAvailability = "Sortera: Lager",
  sortByCheapest = "Sortera: Billigast",
  sortByMostExpensive = "Sortera: Dyrast",
  sortByNewest = "Sortera: Nyast",
  purchaseVehicle = "Köp Fordon",
  purchaseFor = "Köp för",
  selectSociety = "Välj företag",
  financeOverPayments = "Delbetala över %{value} betalningar",
  payToday = "Betala idag",
  financeThen = "Sedan",
  seeFullBreakdown = "Se hela översikten",
  testDriveExit = "Du kan kliva ut ur fordonet när som för att avbryta testkörningen",

  -- NOTIFICATIONS
  purchaseSuccess = "Grattis på ditt fordon!",
  depositSuccess = "Instättning lyckades",
  withdrawSuccess = "Uttag lyckades",
  errorNotEnoughMoney = "Du har inte råd",
  errorVehicleOutOfStock = "Detta fordon är slut i lager",
  errorCannotAffordVehicle = "Du har inte råd med detta fordon",
  vehicleFinancePaymentMade = "Betalning gjordes för ditt fordon %{value}",
  vehicleFinancePaidOff = "Grattis, du har betalat av och äger nu %{value}",
  vehicleFinancePaymentFailed = "Delbetalning misslyckades för %{value}",
  vehicleFinanceRepossessedSoon = "Du måste göra en betalning för %{value} annars kommer ditt fordon återtas inom kort",
  vehicleFinanceRepossessed = "Pågrund av en misslyckad betalning, så har ditt fordon med regplåt %{value} återhämtats.",
  dealershipNotEnoughFunds = "Firman har inte råd",
  dealershipVehiclesOrdered = "Fordon(en) har beställts",
  dealershipOrderCancelled = "Beställning avbröts",
  errorVehicleWithSpawnCodeExists = "Ett fordon med detta spawnnamn finns redan",
  errorExitVehicle = "Du måste lämna ditt fordon först",

  -- NEW v1.1
  purchaseRequest = "Betalnings förfrågan",
  sendRequest = "Skicka förfrågan",
  dealer = "Bilfirma",
  financed = "Delbetalad",
  signHere = "Singnera här",
  signFirstError = "Vänligen signera först",
  denyRequest = "Neka Förfrågan",
  playerTooManyFinancedVehicles = "Spelaren har för många delbetalade fordon",
  employeePermissionsError = "Du har inte rätt behörigheter för att utföra detta",
  managerRole = "Chef",
  supervisorRole = "Handledare",
  salesRole = "Försäljare",
  ownerRole = "Ägare",
  employmentRequest = "Anställnings Förfrågan",
  accept = "Acceptera",
  jobOfferDescription = "Du har blivit erbjuden ett jobb på \"%{value}\". Vill du godkänna detta jobb?",
  pending = "Väntar",
  employeeHiredMsg = "Anställnings förfrågan accepterades!",
  employeeRejectedMsg = "Anställnings förfrågan nekades",
  sellVehicle = "Sälj Fordon",
  vehicleTerms = "Fordons vilkor",
  financePayments = "Mängd Delbetalningar",
  commission = "Provision",
  role = "Roll",
  firedNotification = "Du har blivit avskedad från \"%{value}\"",
  dealershipTooFarAway = "Du är inte i närheten av en bilfirma",
  restoreDisplayVehicles = "Återställ Uppvisade Fordon",
  customer = "Kund",
  lessThanAMin = "Mindre än en minut",
  mins = "minut(er)",
  notInVehicle = "Du sitter inte i ett fordon",
  notYourVehicleError = "Detta fordon tillhör inte dig",
  vehicleFinancedError = "Du kan inte sälja detta fordon för det är inte avbetalat än",
  dealershipDoesntSellVehicle = "Bilfirman kan inte köpa detta fordon",
  dealershipWantsYourVehicle = "Grattis! Bilfirman hade velat köpa ditt fordon!.",
  purchasePrice = "Erbjudet pris: ",
  
  spawnCodeInvalid = "Spawnnamn Ogiltigt",
  salesRep = "Försäljare",
  directSaleAccepted = "Försäljningen accepterades, du har fått din provision!",
  directSaleRejected = "Försäljningen misslyckades",

  displayVehicleOutsideZone = "Utställningsfordon måste placeras inom bilfirmans zon",
  serverAdmin = "Serveradmin",
  selfService = "Självbetjäning",
  owned = "Ägd",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Ogiltig betalningsmetod",
  paymentMethodNoFinance = "Denna betalningsmetod stödjer inte finansiering",
  couldNotGeneratePlate = "Kunde inte generera registreringsskylt",
  invalidCoupon = "Ogiltig kupong: %{value}",
  tooManyFinancedVehicles = "Du har för många finansierade fordon",
  couldNotSpawnVehicle = "Kunde inte skapa fordon",

  -- v2: Permissions
  insufficientPermissions = "Otillräckliga behörigheter",

  -- v2: Coupons
  couponCodeAlreadyExists = "Denna kupongkod finns redan",
  failedToCreateCoupon = "Misslyckades att skapa kupong",
  couponCreatedSuccessfully = "Kupong skapad framgångsrikt",
  couponNotFound = "Kupong hittades inte",
  couponUpdatedSuccessfully = "Kupong uppdaterad framgångsrikt",
  failedToDeleteCoupon = "Misslyckades att ta bort kupong",
  couponDeletedSuccessfully = "Kupong raderad framgångsrikt",
  editCoupon = "Redigera kupong",
  addCoupon = "Lägg till kupong",
  couponCode = "Kupongkod",
  generating = "Genererar...",
  generate = "Generera",
  discountType = "Rabattyp",
  percentageOff = "Procentrabatt",
  amountOff = "Beloppsrabatt",
  discountValue = "Rabattvärde",
  unlimitedTotalUses = "Obegränsad total användning",
  unlimitedUsesPerPlayer = "Obegränsad användning per spelare",
  setExpiryDate = "Ange utgångsdatum",
  restrictToSpecificVehicles = "Begränsa till specifika fordon",
  restrictToSpecificCategories = "Begränsa till specifika kategorier",
  allowUseWithFinance = "Tillåt användning med finansiering",
  deleteCoupon = "Ta bort kupong",
  inactive = "Inaktiv",
  expired = "Utgången",
  maxUses = "Max användning",
  coupons = "Kuponger",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Endast serveradmins kan anställa sig själva",
  playerNotFound = "Spelare hittades inte",
  failedToHireEmployee = "Misslyckades att anställa medarbetare",
  failedToFireEmployee = "Misslyckades att avskeda medarbetare",
  failedToUpdateEmployeeRole = "Misslyckades att uppdatera medarbetarens roll",
  hireEmployee = "Anställ medarbetare",
  fireEmployee = "Avskeda medarbetare",
  editRole = "Redigera roll",
  fire = "Avskeda",
  changeRole = "Ändra roll",
  updateRole = "Uppdatera roll",

  -- v2: Test drives
  maxTestDrivesReached = "Denna bilfirma har nått maximalt antal aktiva provkörningar",
  testDriveNotEnabled = "Provkörningar är inte aktiverade på denna bilfirma",
  noTestDriveSpawnCoords = "Inga provkörnings-spawnkoordinater konfigurerade för denna bilfirma",
  couldNotSpawnTestDriveVehicle = "Kunde inte skapa provkörningsfordon",
  couldNotGetPlateFromServer = "Kunde inte hämta registreringsskylt från server",
  couldNotRegisterTestDriveVehicle = "Kunde inte registrera provkörningsfordon",
  testDriveEndedByEmployee = "Provkörningen avslutades av en annan medarbetare",
  trackingVehicleLocation = "Spårar fordonsposition...",
  directSaleCancelled = "Försäljningsförfrågan avbröts av säljaren",
  testDriveKeysReceived = "Du har fått nycklarna till provkörningsfordonet",
  testDriveEndedCustomer = "Provkörningen har avslutats",
  starting = "Startar...",
  startTestDrive = "Starta provkörning",
  spawningTestDriveVehicle = "Skapar provkörningsfordon...",
  testDriveReady = "Provkörning klar",
  testDriveWalkToVehicle = "Provkörningsfordonet har skapats på den markerade platsen på din karta. Följ med kunden till fordonet. Efter att du gett nycklarna till kunden måste du manuellt avsluta provkörningen när de återvänder.",
  givingKeys = "Ger nycklar...",
  continueAndGiveKeys = "Fortsätt och ge nycklar",
  endTestDrive = "Avsluta provkörning",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Inget lager tillgängligt för detta fordon",
  globalStockLimitExceeded = "Endast %{value} enheter tillgängliga",
  orderNotFoundOrFulfilled = "Beställning hittades inte eller redan fullföljd",
  priceBelowMinimum = "Priset kan inte vara lägre än %{value}",
  priceAboveMaximum = "Priset kan inte vara högre än %{value}",
  stockUpdated = "Lager uppdaterat",
  changesSaved = "Ändringar sparade",
  noStockAvailable = "Inget lager tillgängligt",
  orderPlaced = "Beställning lagd",
  remainingInStock = "kvar i globalt lager",
  exceedsStockLimit = "Överskrider lagergräns",
  setStockQty = "Ange lagerantal",
  invalidStockValue = "Ange ett giltigt lagervärde",
  errorSettingStock = "Fel vid inställning av lager",
  stockQuantity = "Lagerantal",
  currentStock = "Nuvarande lager",
  priceLimitsEnabled = "Aktivera prisgränser",
  priceLimitsDescription = "När aktiverat kan bilfirmans chefer endast sätta priser inom det angivna intervallet.",
  minPrice = "Minimipris",
  maxPrice = "Maximipris",
  optional = "Valfritt",
  unlimitedStock = "Obegränsat lager",
  globalStockLimit = "Global lagergräns",
  globalStockLimitDescription = "Ange maximalt antal enheter som kan beställas hos alla bilfirmor.",
  currentlyOrdered = "För närvarande beställt",
  priceRange = "Prisintervall",
  noMinimum = "Inget minimum",
  noMaximum = "Inget maximum",
  vehicleStock = "Fordonslager",

  -- v2: Sales
  allSales = "Alla försäljningar",
  paidInFull = "Betald i sin helhet",
  salesVolume = "Försäljningsvolym",
  pastMonth = "Senaste månaden",
  pastYear = "Senaste året",

  -- v2: Management misc
  exploitAttemptDetected = "Sluta försöka utnyttja skriptet",
  dealershipNoJobConfigured = "Bilfirman har inget jobb konfigurerat",
  modelDoesNotMatchDb = "Fordonsmodell matchar inte databasen",
  importFailed = "Import misslyckades: %{value}",
  notInDealershipZone = "Du måste vara inom en bilfirma för att använda detta kommando",
  notAnEmployee = "Du är inte anställd på denna bilfirma.",
  failedToPrepareDelivery = "Misslyckades att förbereda leverans",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Fordonsmodellen finns inte - kontakta en admin",
  vehiclePlateInvalid = "Detta fordons registreringsskylt är ogiltig (tryck F8 för mer detaljer)",
  currentlyInRagdollState = "Du är för närvarande i ragdoll-tillstånd",
  vehicleDoesNotExistContactAdmin = "Fordonet finns inte. Kontakta en admin!",
  vehicleSecurityBreachDetected = "Fordons säkerhetsbrott upptäckt",

  -- v2: Admin vehicles
  allVehicles = "Alla fordon",
  unassignedVehicles = "Ingen bilfirma",
  searchDealerships = "Sök bilfirmor...",

  -- v2: Trucking mission
  truckingGetInTruck = "Stig in i lastbilen på den markerade platsen för att starta din leverans",
  truckingDriveToDelivery = "Kör till leveransplatsen",
  truckingCompleteDelivery = "Slutför leverans",
  truckingDeliveryComplete = "Leverans slutförd: Du har framgångsrikt slutfört leveransen!",
  truckingDeliveryFailed = "Leverans misslyckades: Något gick fel med leveransen",
  truckingDriveToPickup = "Kör till upphämtningspunkten för att hämta släpet",
  truckingMissionFailedSpawnCargo = "Uppdrag misslyckades: Kunde inte skapa lastsläp",
  truckingMissionFailedFindCargo = "Uppdrag misslyckades: Kunde inte hitta skapad last",
  truckingVehiclesLoaded = "%{count} fordon lastat",
  truckingWrongTrailer = "Fel släp! Du måste koppla rätt uppdragssläp.",
  truckingTrailerAttached = "Släp kopplat - redo att fortsätta",
  truckingDriveToPickupLocation = "Kör till upphämtningspunkten",
  truckingWaitingForVehicles = "Väntar på att fordon lastas...",
  truckingDriveUnderTrailer = "Kör under släpet för att koppla",
  truckingGetInTruckContinue = "Stig in i lastbilen för att fortsätta",
  truckingMissionStarted = "Transportuppdrag startat: Upphämtningspunkt - %{location}",
  truckingMissionCancelled = "Uppdrag avbrutet: Du avbröt transportuppdraget",
  truckingNoActiveMission = "Inget aktivt transportuppdrag att avbryta",
  deliveryNotPrepared = "Leverans inte förberedd - försök igen",
  deliveryConfigMismatch = "Leveranskonfiguration matchar inte",
  deliveryPreparationExpired = "Leveransförberedelse har gått ut - försök igen",
  noTruckingVehicleCoordinates = "Transportfordonskoordinater inte inställda",
  pickupLocationUnavailable = "Upphämtningspunkt inte längre tillgänglig - försök igen",
  failedToSpawnTruck = "Misslyckades att skapa lastbil",
  clientFailedToStartMission = "Klient misslyckades att starta uppdrag",

  -- v2: Trucking UI/Keys
  keyDismiss = "Stäng",
  keyDeliverCargo = "Leverera last",
  keyContinueToDelivery = "Fortsätt till leverans",
  startDeliveryMission = "Starta leveransuppdrag",
  orderDetails = "Beställningsdetaljer",
  pickupLocation = "Upphämtningspunkt",
  deliveryStatus = "Leveransstatus",
  selectOrders = "Välj beställningar",
  carTrailer = "Biltransport",
  container = "Container",
  deliveryRoute = "Leveransrutt",
  startDelivery = "Starta leverans",

  -- v2: Direct sales UI
  waitingForCustomer = "Väntar på kund",
  cancelRequest = "Avbryt förfrågan",
  saleComplete = "Försäljning slutförd!",
  done = "Klar",
  saleDeclined = "Försäljning avvisad",
  close = "Stäng",

  -- v2: Display vehicle placement
  movement = "Rörelse",
  rotate = "Rotera",
  forward = "Framåt",
  backward = "Bakåt",
  left = "Vänster",
  right = "Höger",
  rotateLeft = "Rotera vänster",
  rotateRight = "Rotera höger",

  -- v2: Showroom misc
  originalPrice = "Originalpris",
  discount = "Rabatt",
  createInteraction = "Skapa interaktion",
  viewAll = "Visa alla",
  fetchingPlayers = "Hämtar spelare",
  refresh = "Uppdatera",
  loadingPlayers = "Laddar spelare...",
  failedToLoadPlayers = "Kunde inte ladda spelare",
  selectAPlayer = "Välj en spelare",
  failedToLoadPlayersRetry = "Kunde inte ladda spelare. Klicka på 'Uppdatera' för att försöka igen.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Självbetjäning återförsäljare",
  categories = "Kategorier",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Platser",
  createNew = "Skapa ny",
  enable = "Aktivera",
  disable = "Inaktivera",
  loading = "Laddar...",
  errors = "Fel",
  update = "Uppdatera",
  create = "Skapa",

  -- v2: Dealership creation/editing
  createDealership = "Skapa återförsäljare",
  editDealership = "Redigera återförsäljare",
  essentials = "Grundläggande",
  advanced = "Avancerat",
  noDealershipLocations = "Inga återförsäljarplatser",
  noDealershipLocationsDesc = "Du kan lägga till en ny plats, importera från din konfiguration (om du migrerar från v1) eller automatiskt lägga till standardplatser.",

  -- v2: Location sections
  dealershipZone = "Återförsäljarzon",
  showroomAndManagement = "Utställning och hantering",
  openShowroom = "Öppna utställning",
  openManagement = "Öppna hantering",
  enableSellVehicle = "Aktivera fordonsförsäljning",
  percentageOfVehicleValue = "Procent av fordonsvärde",
  enablePurchase = "Aktivera köp",
  purchasedVehicleSpawn = "Köpt fordon spawn",
  enableTestDrive = "Aktivera provkörning",
  testDriveVehicleSpawn = "Provkörning fordon spawn",
  truckDelivery = "Lastbilsleverans",
  truckDeliveryVehicleSpawn = "Leveransfordon spawn",

  -- v2: Location advanced settings
  paymentMethods = "Betalningsmetoder",
  supportsFinancing = "(stödjer finansiering)",
  enableFinance = "Aktivera finansiering",
  cameraPreset = "Kamera",
  preset = "Förinställning",
  custom = "Anpassad",
  vehiclePosition = "Fordonsposition",
  zoomPositions = "Zoompositioner (kommaseparerade)",
  zoomPositionsPlaceholder = "exempel: 5,8,12,8",
  vehicleColour = "Fordonsfärg",
  selectionType = "Urvaltyp",
  noColourSelection = "Ingen färgval",
  rgbColourWheel = "RGB färghjul",
  listOfRgbColours = "Lista över RGB färger",
  listOfColourIds = "Lista över färg-IDn",
  accessControl = "Åtkomstkontroll",
  showroomJobWhitelist = "Utställning jobb vitlista",
  showroomGangWhitelist = "Utställning gäng vitlista",
  societyPurchaseJobWhitelist = "Organisationsköp jobb vitlista",
  societyPurchaseGangWhitelist = "Organisationsköp gäng vitlista",
  setInGame = "Ställ in i spelet",
  addNew = "Lägg till ny",

  -- v2: Job/Gang whitelist editor
  job = "Jobb",
  gang = "Gäng",
  jobWhitelist = "Jobb vitlista",
  gangWhitelist = "Gäng vitlista",
  addJob = "Lägg till jobb",
  addGang = "Lägg till gäng",
  editJob = "Redigera jobb",
  editGang = "Redigera gäng",
  manageJobs = "Hantera jobb",
  manageGangs = "Hantera gäng",
  jobName = "Jobbnamn",
  gangName = "Gängnamn",
  selectGrades = "Välj grader",
  selectAll = "Välj alla",
  deselectAll = "Avmarkera alla",
  invalidJobName = "Ogiltigt jobbnamn. Kontrollera din framework-konfiguration.",
  invalidGangName = "Ogiltigt gängnamn. Kontrollera din framework-konfiguration.",
  grades = "Grader",
  noJobsConfigured = "Inga jobb konfigurerade",
  noGangsConfigured = "Inga gäng konfigurerade",
  click = "Klicka",
  toGetStarted = "för att komma igång.",
  more = "fler",
  jobPlaceholder = "Till exempel: cardealer",
  jobOptionalDescription = "Koppla valfritt återförsäljarroller till ett framework-jobb. När anställda anställs/avskedas kommer deras framework-jobb också att uppdateras.",
  jobRankPermissions = "Jobb rang behörigheter",
  roleToJobRankMapping = "Roll till jobb rang mappning",
  addPerm = "Lägg till behörighet",

  -- v2: Colour selector
  searchColours = "Sök färger...",
  noColoursFound = "Inga färger hittades",

  -- v2: Interactions creator
  noInteractions = "Inga interaktioner",
  highlightInteractions = "Markera interaktioner",
  explorationMode = "Utforskningsläge",
  pressEsc = "Tryck ESC",
  toWalkAround = "för att gå runt",
  toReturnToUI = "för att återgå till UI",
  points = "punkter",
  location = "plats",
  manageLocations = "Hantera platser",

  -- v2: Interaction modal
  interactionType = "Typ",
  nicknameOptional = "Smeknamn (Valfritt)",
  invalidModel = "Ogiltig modell",
  failedToValidateModel = "Kunde inte validera modell",
  pedScenario = "Ped scenario",
  coords = "Koordinater",
  size = "Storlek",
  blip = "Blip",
  enableBlip = "Aktivera blip",
  blipIconId = "Blip ikon-ID",
  blipColourId = "Blip färg-ID",
  blipSize = "Blip storlek",
  marker = "Markör",
  enableMarker = "Aktivera markör",
  markerStyleId = "Markör stil-ID",
  markerSize = "Markör storlek",
  markerColor = "Markör färg",
  markerBobUpAndDown = "Sväva upp och ner",
  markerFaceCamera = "Vänd mot kamera",
  markerRotate = "Rotera",
  markerDrawOnEnts = "Rita på enheter",
  updatePosition = "Uppdatera position",
  setPosition = "Ställ in position",

  -- v2: Interaction types
  interactionPoint = "Punkt",
  interactionPointDesc = "En enda skalbar punkt med valfri markör",
  interactionPolyzone = "Polyzon",
  interactionPolyzoneDesc = "Flerkoordinat zon för att skapa ett specifikt interaktionsområde",
  interactionVehicle = "Fordon",
  interactionVehicleDesc = "Spawna en fordonsmodell, idealisk för target eller 3D text UI interaktionsmetoder",
  interactionObject = "Objekt",
  interactionObjectDesc = "Spawna en objektmodell, idealisk för target eller 3D text UI interaktionsmetoder",
  interactionPed = "Ped",
  interactionPedDesc = "Spawna en ped-modell med valfritt scenario, idealisk för target eller 3D text UI interaktionsmetoder",

  -- v2: Import modal
  importLocationsTitle = "Importera platser",
  syncStockLabel = "Synkronisera lager",
  syncStockDescription = "Lägg till fordon till varje återförsäljares lager baserat på kategorier",
  importSourceSelectorDesc = "Du kan importera standardplatser för en färdig installation, eller importera befintliga platser från din konfiguration om du migrerar från Dealerships v1.",
  importSourceSelectorSkipDesc = "Platser som redan finns i databasen kommer att hoppas över; endast nya platser kommer att importeras.",
  successfullyImported = "Framgångsrikt importerat",
  alreadyExist = "Finns redan",
  defaultLocations = "Standardplatser",
  defaultLocationsDesc = "Importera förkonfigurerade återförsäljarplatser (PDM, Lyx, Båtar, Flyg, Lastbil)",
  existingConfig = "Befintlig konfiguration",
  existingConfigDesc = "Importera platser från config.lua (för v1 migrering)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Vill du automatiskt lägga till fordon till denna återförsäljares lager baserat på valda kategorier?",
  categorySyncEditDesc = "Du ändrade kategorierna för denna återförsäljare. Vill du automatiskt uppdatera fordonslagret?",
  addVehicles = "Lägg till fordon",
  removeVehicles = "Ta bort fordon",
  fromNewCategories = "från nya kategorier",
  fromSelectedCategories = "från valda kategorier",
  fromRemovedCategories = "från borttagna kategorier",
  categoriesAdded = "Kategorier tillagda:",
  categoriesRemoved = "Kategorier borttagna:",
  skip = "Hoppa över",
  syncStock = "Synkronisera lager",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Kontrollerar källtillgänglighet...",
  vehiclesAvailableToImport = "fordon tillgängliga för import",
  includesDealershipIds = "inkluderar återförsäljar-IDn",
  sourceUnavailable = "Källa otillgänglig",
  noVehiclesAdminDescription = "Du kan lägga till fordon manuellt eller importera dem från ditt framework.",
  appendBehaviour = "Lägg till",
  overwriteBehaviour = "Skriv över",
  appendDescription = "Lägg endast till nya fordon som inte redan finns i databasen",
  overwriteDescription = "Ta bort all befintlig fordonsdata och importera på nytt",
  stockAssignmentMethod = "Lagertilldelningsmetod",
  useDealershipIdsFromSource = "Använd återförsäljar-IDn från källa",
  matchByVehicleCategory = "Matcha efter fordonskategori",
  byShopDescription = "Fordon kommer att tilldelas återförsäljare baserat på 'shop'-fältet i källdatan",
  byCategoryDescription = "Fordon kommer att tilldelas återförsäljare med matchande kategorier",
  overwriteWarning = "Varning: Överskrivning tar bort alla befintliga fordon, beställningar, utställningsfordon och försäljningsdata.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX fordonstabell",
  selectCategory = "Välj kategori",

  -- v2: Management menu items
  vehiclesMenu = "Fordon",
  displayVehiclesMenu = "Utställningsfordon",
  ordersMenu = "Beställningar",
  salesMenu = "Försäljning",
  bankAccountMenu = "Bankkonto",
  employeesMenu = "Anställda",
  couponsMenu = "Kuponger",
  settingsMenu = "Inställningar",
  noPermissionAccessManagement = "Du har inte behörighet att komma åt hanteringsfunktioner.",
  backToAdmin = "Tillbaka till admin",
  viewingAsAdmin = "VISAR SOM ADMIN",

  -- v2: Coupons table
  code = "Kod",
  uses = "Användningar",
  perPlayer = "Per spelare",
  never = "Aldrig",
  noCoupons = "Inga kuponger",
  noCouponsDescription = "Kunder kan ange en kupong vid fordonsköp och spara pengar.",

  -- v2: Coupon modal
  couponCodeLabel = "Kupongkod",
  couponCodePlaceholder = "t.ex. SOMMAR2024 eller SPARA10",
  couponCodeHelp = "Ange en anpassad kod (max 25 tecken, endast bokstäver, siffror och bindestreck) eller klicka 'Generera'.",
  maxNumberOfUsesPlaceholder = "Maximalt antal användningar",
  maxUsesPerPlayerPlaceholder = "Max användningar per spelare",
  vehicleRestrictionsPlaceholder = "Ange spawn-koder separerade med komma (t.ex. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Tillåt vid finansierade köp",
  createCoupon = "Skapa kupong",
  updateCoupon = "Uppdatera kupong",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kupongkod är obligatorisk",
  couponCodeMaxLength = "Koden måste vara 25 tecken eller mindre",
  couponCodeInvalidChars = "Koden kan endast innehålla stora bokstäver, siffror och bindestreck",
  discountTypeRequired = "Rabattyp är obligatorisk",
  discountValueRequired = "Rabattvärde är obligatoriskt",
  discountValueMin = "Rabattvärde måste vara större än 0",
  discountValueMaxPercent = "Procent kan inte överstiga 100",
  maxUsesRequired = "Maximalt antal användningar är obligatoriskt",
  maxUsesMin = "Måste vara minst 1",
  perPlayerLimitRequired = "Per spelare gräns är obligatorisk",
  expiryDateRequired = "Utgångsdatum är obligatoriskt",
  vehicleRestrictionsRequired = "Fordonsbegränsningar är obligatoriska",
  categoryRestrictionsRequired = "Kategoribegränsningar är obligatoriska",
  selectAtLeastOneCategory = "Välj minst en kategori",

  -- v2: Dashboard
  today = "Idag",
  thisMonth = "Denna månad",
  allTime = "Totalt",
  recentSales = "Senaste försäljningar",
  noSalesYet = "Inga försäljningar än!",
  noSalesDescription = "Fordonsförsäljningar kommer att visas här efter första försäljningen.",
  past7Days = "Senaste 7 dagarna",
  past6Months = "Senaste 6 månaderna",
  numberOfSales = "Antal försäljningar",
  noDataAvailableForPeriod = "Ingen data tillgänglig för denna period",

  -- v2: Display vehicles
  displayVehiclesDescription = "Utställningsfordon är fasta utställningsmodeller som används för att visa ditt lager och uppmuntra kunder att köpa.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework-jobb aktiverade",
  frameworkJobsDescription = "Anställningshantering hanteras genom framework jobbsystem. Spelare med återförsäljarjobbet kommer automatiskt ha åtkomst baserat på rang. Konfigurera jobbbehörigheter i admin-panelens platsinställningar.",
  joinedColumn = "Gick med",
  youBadge = "Du",

  -- v2: Orders
  noOrdersTitle = "Inga beställningar",
  noOrdersDescription = "För att lägga en beställning, öppna 'Fordon'-fliken och klicka 'Beställ' på fordonet du vill fylla på.",
  inProgress = "Pågår",
  awaitingDelivery = "Väntar på leverans",
  orderedBy = "Beställd av",
  viewDeliveryInfo = "Visa leveransinformation",

  -- v2: Delivery
  startDeliveryMissionTitle = "Starta leveransuppdrag",
  startDeliveryDescription = "Du ska starta ett leveransuppdrag för denna fordonsbeställning. Du måste köra till upphämtningspunkten, hämta lasttrailern och leverera den tillbaka till återförsäljaren.",
  totalDistanceAndDriveTime = "Total distans och körtid",
  roundTrip = "tur och retur",
  deliveryCompleteTitle = "Leverans slutförd",
  deliveryInProgressTitle = "Leverans pågår",
  deliveredAt = "Levererad:",
  startedAt = "Startad:",
  deliveredBy = "Levererad av:",
  beingDeliveredBy = "Levereras av:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Inga beställningar tillgängliga för leverans. Beställningar måste vara klara och inte under aktiv leverans.",
  confirmDeliveryTitle = "Bekräfta leverans",
  configureDeliveryTitle = "Konfigurera leverans",
  trailerCapacityExceeded = "Trailer-kapacitet överskriden! Du valde %{usedSlots} platser, men max är %{maxSlots} platser.",
  smallVehiclesSlotInfo = "Notera: Små fordon tar 1 plats, medelstora tar 1,5 platser.",
  fetchingRoute = "Hämtar...",
  getRouteButton = "Hämta rutt",
  selectTrailerType = "Välj trailertyp",
  carTrailerLabel = "Biltransport",
  smallMedium = "(Liten/Medel)",
  containerLabel = "Container",
  large = "(Stor)",
  carTrailerDescription = "Biltransporten har 2 rader. Varje rad tar 3 små (1 plats var) eller 2 medelstora (1,5 platser var). Max 6 platser totalt.",
  containerDescription = "Container-trailern transporterar 1 stort fordon",
  selectOrdersTitle = "Välj beställningar",
  slots = "platser",
  noOrdersForTrailerType = "Inga beställningar tillgängliga för denna trailertyp.",
  qty = "Antal:",
  inTransit = "under transport",
  totalVehicles = "Totalt fordon:",
  estimatedTime = "Beräknad tid:",
  unknown = "Okänd",

  -- v2: Sales
  salesEmptyDescription = "Fordonsförsäljningar kommer att visas här efter första försäljningen.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Beställning lagd!",
  orderPlacedTruckingDescription = "Din beställning är redo för upphämtning. Gå till beställningssidan för att slutföra.",
  orderPlacedTimedDescription = "Din beställning kommer om %{value} minuter.",
  goToOrders = "Gå till beställningar",
  noStockAvailableDescription = "Inget lager tillgängligt för detta fordon. Global lagergräns nådd.",
  stockUpdatedDescription = "Lagerantal har uppdaterats.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktiva provkörningar",
  tracking = "Spårning",
  track = "Spåra",
  endButton = "Avsluta",
  endTestDriveTitle = "Avsluta provkörning",
  endTestDriveConfirmation = "Är du säker på att du vill avsluta denna provkörning? Fordonet kommer att raderas och passagerare kommer inte att teleporteras tillbaka till återförsäljaren.",
  vehicleLocationOnMap = "Fordonets plats är markerad på din karta.",
  sell = "Sälj",
  couponCodeOptional = "Kupongkod (Valfritt)",
  pleaseEnterCouponCode = "Vänligen ange kupongkod",
  invalidCouponCode = "Ogiltig kupongkod",
  failedToValidateCoupon = "Kunde inte validera kupong",
  apply = "Tillämpa",
  applying = "Tillämpar...",
  allStock = "Allt lager",
  inStockFilter = "I lager",
  outOfStockFilter = "Slut i lager",
  noResultsFound = "Inga resultat hittades",
  noResults = "Inga resultat",
  noVehiclesMatchSearch = "Inga fordon matchar din sökning",
  noVehiclesMatchFilters = "Inga fordon matchar nuvarande filter",
  noItemsMatchSearch = "Inga objekt matchar din sökning",
  noItemsMatchFilters = "Inga objekt matchar nuvarande filter",
  selectColour = "Välj färg",
  refreshNearbyPlayers = "Uppdatera närliggande spelare",
  you = "Du",
  items = "objekt",
  waitingForCustomerToRespond = "Väntar på kundens svar...",
  vehicleSpawnedMessage = "Fordonet har spawnats vid punkten markerad på din karta - ta kunden dit.",
  customerDeclinedMessage = "Kunden avböjde köpförfrågan.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "SIGNERA HÄR",
  acceptAndPurchase = "Acceptera och köp",
  couponApplied = "Kupong %{code} tillämpad! Du sparar %{discount}",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Behöver minst 3 punkter för att slutföra zonen! (Du har för närvarande %{value})",
  addPoint = "Lägg till punkt",
  removeLast = "Ta bort sista",
  completeZone = "Slutför zon",
  spawnPreview = "Spawn förhandsgranskning",
  up = "Upp",
  down = "Ner",
  confirm = "Bekräfta",
  placePoint = "Placera punkt",
  radius = "Radie",

  -- v2: Blip labels
  soldVehicleLocation = "Sålt fordon plats",
  testDriveVehicleBlip = "Provkörningsfordon",

  -- v2: Stock sync
  stockSyncResult = "Lagersynkronisering: %{added} tillagda, %{removed} borttagna",
  stockSyncAdded = "Lagersynkronisering: %{value} fordon tillagda",
  importSuccessful = "Import lyckades! %{imported} fordon importerade (totalt %{total})",

  -- v2: Tooltip actions
  findOnMap = "Hitta på kartan",
  adminPanel = "Admin-panel",

  -- v2: Common dropdown
  selectOne = "Välj en",
}
