Locales = Locales or {}

Locales['tr'] = {
  -- UI
  vehicle = "Araç",
  vehicles = "Araçlar",
  dealership = "Galeri",
  dealerships = "Galeriler",
  vehiclesCount = "Araçlar",
  dealersCount = "Galeriler",
  accountBalance = "Hesap Bakiyesi",
  bank = "Banka",
  cash = "Nakit",
  amount = "Miktar",
  societyFund = "Toplum Fonu",
  paymentSource = "Ödeme Türü",
  purchase = "Satın al",
  personalPurchase = "Kişisel satın al",
  societyPurchase = "Toplum satın al",
  purchaseType = "Satın Alma Türü",
  deposit = "Depozito",
  withdraw = "Geri çek",
  all = "Hepsi",
  yes = "Evet",
  no = "Hayır",
  add = "Ekle",
  edit = "Düzenle",
  id = "ID",
  created = "Oluşturuldu",
  type = "Tip",
  name = "İsim",
  owner = "Mal sahibi",
  bankBalance = "Banka hesap bakiyesi",
  status = "Durum",
  back = "Geri",
  previous = "Önceki",
  next = "Sonraki",
  admin = "Yönetici",
  vehiclesAdmin = "Araç Yöneticisi",
  dealershipsAdmin = "Galeri Yöneticisi",
  search = "Ara",
  noDealershipsFound = "Galeri bulunamadı",
  noVehicles = "Araç bulunamadı",
  page = "Sayfa",
  of = "ile ilgili",
  every = "her bir",
  show = "Göster",
  active = "Aktif",
  activeFinance = "Kredi Aktif",
  failed = "Ödeme başarısız",
  removed = "Kaldırıldı",
  setOwner = "Sahibini Ayarla",
  manage = "Ayarlar",
  deleteData = "Verileri Sil",
  deleteVehicle = "Aracı Sil",
  delete = "Sil",
  deleteConfirmation = "Emin misin?",
  deleteConfirmationDanger = "Emin misin? Bu işlem geri alınamaz.",
  setDealershipOwner = "Galeri Sahibini Ayarla",
  overwriteDealerPrices = "Galeri fiyatlarının üzerine yaz",
  nearbyPlayers = "Yakındaki oyuncular",
  noPlayersNearby = "Yakınlarda oyuncu yok",
  selectPlayer = "Kişi seç",
  required = "Gerekli",
  forExample = "Örneğin",
  spawnCode = "Işınlama Kodu",
  brand = "Marka",
  model = "Model",
  category = "Katagori",
  price = "Fiyat",
  import = "İçe aktar",
  importing = "İthalat",
  importBehaviour = "Davranışı İçe Aktar",
  importVehicles = "Araçları içe aktarın",
  importFrom = "için aktar",
  dashboard = "Gösterge Paneli",
  displayVehicle = "Araç Görüntüle",
  displayVehicles = "Araç Görüntüle",
  orders = "Emirler",
  sales = "Satış",
  vehiclesOnDisplay = "Sergilenen araçlar",
  employees = "Çalışanlar",
  settings = "Ayarlar",
  switchVehicle = "Araç Değiştir",
  remove = "Kaldır",
  noDisplayVehicles = "Gösterilen araç yok",
  selectVehicle = "Araç seçin",
  colour = "Renk",
  placeVehicle = "Araç Yerleştir",
  orderVehicle = "Araç Siparişi",
  cancelOrder = "Siparişi iptal et",
  delivery = "Teslimat",
  delivered = "Teslim edilenler",
  noOrders = "Sipariş Bulunamadı",
  quantity = "Miktar",
  totalCost = "Toplam tutar",
  totalSales = "Total sales",
  noSales = "Satış bulunamadı",
  paid = "Nakit Ödeme",
  owed = "Kredi Çek",
  dealershipName = "Galeri Adı",
  save = "Değişiklikleri Kaydet",
  cancel = "Vazgeç",
  notEnoughMoney = "Yetersiz para",
  placeOrder = "Sipariş Ver",
  purchaseCost = "Satın alma maliyeti",
  salePrice = "Satış ücreti",
  inStock = "Stokta var",
  outOfStock = "Stoklar tükendi",
  placeVehiclePrompt = "Aracı yerleştirmek için %{value} tuşuna basın. Sonrasında daha ince ayarlamalar yapabilirsiniz!",
  remaining = "Geriye kalan",
  prePurchaseRepoWarning = "Kredi ödemelerinizi takip edemezseniz, aracınıza el konulacaktır..",
  repossessionWarning = "Son ödemeniz başarısız oldu - şimdi ödeme yapmazsanız aracınıza el konulacak.",
  recurringPayment = "Yinelenen ödeme",
  remainingBalance = "Kalan bakiye",
  remainingPayments = "Kalan ödemeler",
  paymentTakenEvery = "Ödeme alındı",
  hours = "Saat",
  seconds = "Saniye",
  nextPayment = "Sonraki ödeme",
  makePayment = "Ödeme yap",
  vehicleRepossessed = "Araç geri alınacaktır",
  payInFull = "Hepsini öde",
  earlyPaymentConfirmation = "Erken ödeme yapmak istediğinizden emin misiniz?",
  financedVehicles = "Kredili Araçlar",
  noFinancedVehicles = "Aktif Krediye sahip aracınız yok",
  financeBreakdown = "Kredi Dağılımı",
  initialPayment = "İlk ödeme",
  payments = "Ödemeler",
  length = "Uzunluk",
  interest = "Faiz",
  totalPayable = "Toplam Ödenecek Tutar",
  leaveShowroom = "Showroom'dan Ayrıl",
  handling = "kullanım",
  topSpeed = "En yüksek hız",
  power = "Güç",
  torque = "Tork",
  brake = "Fren",
  financing = "Finansman",
  financingAvailable = "Finansman Mevcut",
  paymentsOf = "ödemeleri",
  clear = "Temizle",
  testDrive = "Test Sürüşü",
  allCategories = "Tüm Kategoriler",
  sortByName = "İsme göre sırala",
  sortByAvailability = "satışa göre sırala",
  sortByCheapest = "En ucuza göre sırala",
  sortByMostExpensive = "En pahalıya göre sırala",
  sortByNewest = "Yeniye göre sırala",
  purchaseVehicle = "Araç Satın Al",
  purchaseFor = "için satın al",
  selectSociety = "Bir topluluk seçin",
  financeOverPayments = "%{value} ödeme üzerinden finansman",
  payToday = "Bugün öde",
  financeThen = "Daha sonra",
  seeFullBreakdown = "Tam dökümü görün",
  testDriveExit = "Test sürüşünü erken sonlandırmak için istediğiniz zaman aracınızdan çıkabilirsiniz..",

  -- NOTIFICATIONS
  purchaseSuccess = "Satın aldığınız için teşekkürler!",
  depositSuccess = "Para yatırma işlemi başarılı",
  withdrawSuccess = "Para çekme başarılı",
  errorNotEnoughMoney = "Yeterli paran yok",
  errorVehicleOutOfStock = "Bu araç stokta yok",
  errorCannotAffordVehicle = "Bu araca paranız yetmez",
  vehicleFinancePaymentMade = "Aracınız için yapılan kredi ödemesi %{value}",
  vehicleFinancePaidOff = "Tebrikler, parasını ödediniz ve şimdi aracınızın sahibi oldunuz %{value}",
  vehicleFinancePaymentFailed = "%{value} aracınız için kredi ödemesi başarısız oldu",
  vehicleFinanceRepossessedSoon = "%{value} aracınız için kredi ödemesi yapmanız gerekiyor, aksi takdirde aracınıza yakında el konulacak",
  vehicleFinanceRepossessed = "Ödeme yapılmaması nedeniyle, %{value} plakalı aracınıza el konuldu.",
  dealershipNotEnoughFunds = "Bayinin yeterli fonu yok",
  dealershipVehiclesOrdered = "Araçlar başarıyla sipariş edildi",
  dealershipOrderCancelled = "Sipariş başarıyla iptal edildi",
  errorVehicleWithSpawnCodeExists = "Bu ışınlanma koduna sahip bir araç zaten var",
  errorExitVehicle = "Önce aracınızdan çıkmanız gerekiyor",

  -- NEW v1.1
  purchaseRequest = "Satın Alma Talebi",
  sendRequest = "İstek Gönder",
  dealer = "Bayi",
  financed = "Finanse Edildi",
  signHere = "Burayı imzalayın",
  signFirstError = "Lütfen önce imzalayın",
  denyRequest = "Talebi Reddet",
  playerTooManyFinancedVehicles = "Oyuncunun çok fazla finanse edilmiş aracı var",
  employeePermissionsError = "Gerekli çalışan izinlerine sahip değilsiniz",
  managerRole = "Müdür",
  supervisorRole = "Süpervizör",
  salesRole = "Satış",
  ownerRole = "Sahibi",
  employmentRequest = "İstihdam Talebi",
  accept = "Kabul et",
  jobOfferDescription = "Size \"%{değer}\" bayisinden bir iş teklifi geldi. Kabul etmek ister misiniz?",
  pending = "Beklemede",
  employeeHiredMsg = "Bayilik kiralama talebi kabul edildi!",
  employeeRejectedMsg = "Bayilik kiralama talebi reddedildi",
  sellVehicle = "Araç Satışı",
  vehicleTerms = "Araç şartları",
  financePayments = "Finans Ödemeleri",
  commission = "Komisyon",
  role = "Rol",
  firedNotification = "\"%{değer}\" bayiliğinden kovuldunuz",
  dealershipTooFarAway = "Hiçbir bayiye yakın değilsiniz",
  restoreDisplayVehicles = "Gösteri Merkezi",
  customer = "Müşteri",
  lessThanAMin = "Bir dakikadan az",
  mins = "dakika(lar)",
  notInVehicle = "Bir aracın içinde oturmuyorsunuz",
  notYourVehicleError = "Bu araç size ait değil",
  vehicleFinancedError = "Bu aracı satamazsınız çünkü kalan finansman ödemeleri var",
  dealershipDoesntSellVehicle = "Bu bayi bu aracı satın alamaz",
  dealershipWantsYourVehicle = "Tebrikler! Bu bayi aracınızı satın almak istiyor.",
  purchasePrice = "Teklif edilen fiyat: ",

  spawnCodeInvalid = "Geçersiz spawn kodu",
  salesRep = "Satış Temsilcisi",
  directSaleAccepted = "Doğrudan satış talebi kabul edildi! Komisyonunuz ödendi.",
  directSaleRejected = "Doğrudan satış talebi reddedildi",

  displayVehicleOutsideZone = "Teşhir araçları bayi bölgesi içinde yerleştirilmelidir",
  serverAdmin = "Sunucu Yöneticisi",
  selfService = "Self Servis",
  owned = "Sahip olunan",

  -- v2: Purchase/Payment errors
  invalidPaymentMethod = "Geçersiz ödeme yöntemi",
  paymentMethodNoFinance = "Bu ödeme yöntemi finansman desteklemiyor",
  couldNotGeneratePlate = "Plaka oluşturulamadı",
  invalidCoupon = "Geçersiz kupon: %{value}",
  tooManyFinancedVehicles = "Çok fazla finanse edilmiş aracınız var",
  couldNotSpawnVehicle = "Araç oluşturulamadı",

  -- v2: Permissions
  insufficientPermissions = "Yetersiz yetkiler",

  -- v2: Coupons
  couponCodeAlreadyExists = "Bu kupon kodu zaten mevcut",
  failedToCreateCoupon = "Kupon oluşturulamadı",
  couponCreatedSuccessfully = "Kupon başarıyla oluşturuldu",
  couponNotFound = "Kupon bulunamadı",
  couponUpdatedSuccessfully = "Kupon başarıyla güncellendi",
  failedToDeleteCoupon = "Kupon silinemedi",
  couponDeletedSuccessfully = "Kupon başarıyla silindi",
  editCoupon = "Kuponu düzenle",
  addCoupon = "Kupon ekle",
  couponCode = "Kupon kodu",
  generating = "Oluşturuluyor...",
  generate = "Oluştur",
  discountType = "İndirim türü",
  percentageOff = "Yüzde indirim",
  amountOff = "Tutar indirimi",
  discountValue = "İndirim değeri",
  unlimitedTotalUses = "Sınırsız toplam kullanım",
  unlimitedUsesPerPlayer = "Oyuncu başına sınırsız kullanım",
  setExpiryDate = "Son kullanma tarihi belirle",
  restrictToSpecificVehicles = "Belirli araçlarla sınırla",
  restrictToSpecificCategories = "Belirli kategorilerle sınırla",
  allowUseWithFinance = "Finansmanla kullanıma izin ver",
  deleteCoupon = "Kuponu sil",
  inactive = "Etkin değil",
  expired = "Süresi dolmuş",
  maxUses = "Maksimum kullanım",
  coupons = "Kuponlar",

  -- v2: Employees
  onlyServerAdminsCanSelfHire = "Sadece sunucu yöneticileri kendilerini işe alabilir",
  playerNotFound = "Oyuncu bulunamadı",
  failedToHireEmployee = "Çalışan işe alınamadı",
  failedToFireEmployee = "Çalışan kovulamadı",
  failedToUpdateEmployeeRole = "Çalışan rolü güncellenemedi",
  hireEmployee = "Çalışan işe al",
  fireEmployee = "Çalışanı kov",
  editRole = "Rolü düzenle",
  fire = "Kov",
  changeRole = "Rol değiştir",
  updateRole = "Rolü güncelle",

  -- v2: Test drives
  maxTestDrivesReached = "Bu bayi maksimum aktif test sürüşü sayısına ulaştı",
  testDriveNotEnabled = "Test sürüşleri bu bayide etkin değil",
  noTestDriveSpawnCoords = "Bu bayi için test sürüşü spawn koordinatları yapılandırılmamış",
  couldNotSpawnTestDriveVehicle = "Test sürüşü aracı oluşturulamadı",
  couldNotGetPlateFromServer = "Sunucudan plaka alınamadı",
  couldNotRegisterTestDriveVehicle = "Test sürüşü aracı kaydedilemedi",
  testDriveEndedByEmployee = "Test sürüşü başka bir çalışan tarafından sonlandırıldı",
  trackingVehicleLocation = "Araç konumu izleniyor...",
  directSaleCancelled = "Satış talebi satıcı tarafından iptal edildi",
  testDriveKeysReceived = "Test sürüşü aracının anahtarlarını aldınız",
  testDriveEndedCustomer = "Test sürüşü sona erdi",
  starting = "Başlatılıyor...",
  startTestDrive = "Test sürüşü başlat",
  spawningTestDriveVehicle = "Test sürüşü aracı oluşturuluyor...",
  testDriveReady = "Test sürüşü hazır",
  testDriveWalkToVehicle = "Test sürüşü aracı haritanızda işaretlenen noktada oluşturuldu. Müşteriyi araca götürün. Müşteriye anahtarları verdikten sonra, döndüğünde test sürüşünü manuel olarak sonlandırmanız gerekecek.",
  givingKeys = "Anahtarlar veriliyor...",
  continueAndGiveKeys = "Devam et ve anahtarları ver",
  endTestDrive = "Test sürüşünü sonlandır",

  -- v2: Stock/Orders/Prices
  globalStockLimitReached = "Bu araç için stok yok",
  globalStockLimitExceeded = "Sadece %{value} adet mevcut",
  orderNotFoundOrFulfilled = "Sipariş bulunamadı veya zaten tamamlandı",
  priceBelowMinimum = "Fiyat %{value} değerinden düşük olamaz",
  priceAboveMaximum = "Fiyat %{value} değerinden yüksek olamaz",
  stockUpdated = "Stok güncellendi",
  changesSaved = "Değişiklikler kaydedildi",
  noStockAvailable = "Stok mevcut değil",
  orderPlaced = "Sipariş verildi",
  remainingInStock = "global stokta kalan",
  exceedsStockLimit = "Stok limitini aşıyor",
  setStockQty = "Stok miktarını ayarla",
  invalidStockValue = "Lütfen geçerli bir stok değeri girin",
  errorSettingStock = "Stok ayarlanırken hata oluştu",
  stockQuantity = "Stok miktarı",
  currentStock = "Mevcut stok",
  priceLimitsEnabled = "Fiyat limitlerini etkinleştir",
  priceLimitsDescription = "Etkinleştirildiğinde, bayi yöneticileri fiyatları sadece belirtilen aralıkta ayarlayabilir.",
  minPrice = "Minimum fiyat",
  maxPrice = "Maksimum fiyat",
  optional = "Opsiyonel",
  unlimitedStock = "Sınırsız stok",
  globalStockLimit = "Global stok limiti",
  globalStockLimitDescription = "Tüm bayilerde sipariş edilebilecek maksimum birim sayısını belirleyin.",
  currentlyOrdered = "Şu anda sipariş edilen",
  priceRange = "Fiyat aralığı",
  noMinimum = "Minimum yok",
  noMaximum = "Maksimum yok",
  vehicleStock = "Araç stoğu",

  -- v2: Sales
  allSales = "Tüm satışlar",
  paidInFull = "Tam ödendi",
  salesVolume = "Satış hacmi",
  pastMonth = "Geçen ay",
  pastYear = "Geçen yıl",

  -- v2: Management misc
  exploitAttemptDetected = "Scripti istismar etmeye çalışmayı bırakın",
  dealershipNoJobConfigured = "Bayinin yapılandırılmış bir işi yok",
  modelDoesNotMatchDb = "Araç modeli veritabanıyla eşleşmiyor",
  importFailed = "İçe aktarma başarısız: %{value}",
  notInDealershipZone = "Bu komutu kullanmak için bir bayi bölgesinde olmalısınız",
  notAnEmployee = "Bu bayinin çalışanı değilsiniz.",
  failedToPrepareDelivery = "Teslimat hazırlanamadı",

  -- v2: Spawning/vehicles
  vehicleModelDoesNotExist = "Araç modeli mevcut değil - bir yöneticiyle iletişime geçin",
  vehiclePlateInvalid = "Bu aracın plakası geçersiz (daha fazla detay için F8'e basın)",
  currentlyInRagdollState = "Şu anda ragdoll durumundasınız",
  vehicleDoesNotExistContactAdmin = "Araç mevcut değil. Lütfen bir yöneticiyle iletişime geçin!",
  vehicleSecurityBreachDetected = "Araç güvenlik ihlali tespit edildi",

  -- v2: Admin vehicles
  allVehicles = "Tüm araçlar",
  unassignedVehicles = "Bayi atanmamış",
  searchDealerships = "Bayi ara...",

  -- v2: Trucking mission
  truckingGetInTruck = "Teslimatınızı başlatmak için işaretli konumdaki kamyona binin",
  truckingDriveToDelivery = "Teslimat noktasına sürün",
  truckingCompleteDelivery = "Teslimatı tamamla",
  truckingDeliveryComplete = "Teslimat tamamlandı: Teslimatı başarıyla tamamladınız!",
  truckingDeliveryFailed = "Teslimat başarısız: Teslimatla ilgili bir sorun oluştu",
  truckingDriveToPickup = "Treyleri almak için teslim alma noktasına sürün",
  truckingMissionFailedSpawnCargo = "Görev başarısız: Kargo treyleri oluşturulamadı",
  truckingMissionFailedFindCargo = "Görev başarısız: Oluşturulan kargo bulunamadı",
  truckingVehiclesLoaded = "%{count} araç yüklendi",
  truckingWrongTrailer = "Yanlış treyler! Doğru görev treylerini bağlamalısınız.",
  truckingTrailerAttached = "Treyler bağlandı - devam etmeye hazır",
  truckingDriveToPickupLocation = "Teslim alma noktasına sürün",
  truckingWaitingForVehicles = "Araç yüklenmesi bekleniyor...",
  truckingDriveUnderTrailer = "Bağlamak için treylerin altına sürün",
  truckingGetInTruckContinue = "Devam etmek için kamyona binin",
  truckingMissionStarted = "Nakliye görevi başladı: Teslim alma noktası - %{location}",
  truckingMissionCancelled = "Görev iptal edildi: Nakliye görevini iptal ettiniz",
  truckingNoActiveMission = "İptal edilecek aktif nakliye görevi yok",
  deliveryNotPrepared = "Teslimat hazırlanmadı - lütfen tekrar deneyin",
  deliveryConfigMismatch = "Teslimat yapılandırması uyuşmuyor",
  deliveryPreparationExpired = "Teslimat hazırlığı süresi doldu - lütfen tekrar deneyin",
  noTruckingVehicleCoordinates = "Nakliye aracı koordinatları ayarlanmamış",
  pickupLocationUnavailable = "Teslim alma noktası artık mevcut değil - lütfen tekrar deneyin",
  failedToSpawnTruck = "Kamyon oluşturulamadı",
  clientFailedToStartMission = "İstemci görevi başlatamadı",

  -- v2: Trucking UI/Keys
  keyDismiss = "Kapat",
  keyDeliverCargo = "Kargoyu teslim et",
  keyContinueToDelivery = "Teslimat devam et",
  startDeliveryMission = "Teslimat görevini başlat",
  orderDetails = "Sipariş detayları",
  pickupLocation = "Teslim alma noktası",
  deliveryStatus = "Teslimat durumu",
  selectOrders = "Siparişleri seç",
  carTrailer = "Araç treyleri",
  container = "Konteyner",
  deliveryRoute = "Teslimat rotası",
  startDelivery = "Teslimatı başlat",

  -- v2: Direct sales UI
  waitingForCustomer = "Müşteri bekleniyor",
  cancelRequest = "Talebi iptal et",
  saleComplete = "Satış tamamlandı!",
  done = "Tamam",
  saleDeclined = "Satış reddedildi",
  close = "Kapat",

  -- v2: Display vehicle placement
  movement = "Hareket",
  rotate = "Döndür",
  forward = "İleri",
  backward = "Geri",
  left = "Sol",
  right = "Sağ",
  rotateLeft = "Sola döndür",
  rotateRight = "Sağa döndür",

  -- v2: Showroom misc
  originalPrice = "Orijinal fiyat",
  discount = "İndirim",
  createInteraction = "Etkileşim oluştur",
  viewAll = "Tümünü görüntüle",
  fetchingPlayers = "Oyuncular getiriliyor",
  refresh = "Yenile",
  loadingPlayers = "Oyuncular yükleniyor...",
  failedToLoadPlayers = "Oyuncular yüklenemedi",
  selectAPlayer = "Bir oyuncu seç",
  failedToLoadPlayersRetry = "Oyuncular yüklenemedi. Tekrar denemek için 'Yenile'ye tıklayın.",

  -- v2: Self-service & Categories
  selfServiceDealership = "Self-servis bayilik",
  categories = "Kategoriler",

  -- v2: Admin navigation & general
  jgScripts = "JG Scripts",
  locations = "Konumlar",
  createNew = "Yeni oluştur",
  enable = "Etkinleştir",
  disable = "Devre dışı bırak",
  loading = "Yükleniyor...",
  errors = "Hatalar",
  update = "Güncelle",
  create = "Oluştur",

  -- v2: Dealership creation/editing
  createDealership = "Bayilik oluştur",
  editDealership = "Bayiliği düzenle",
  essentials = "Temel bilgiler",
  advanced = "Gelişmiş",
  noDealershipLocations = "Bayilik konumu yok",
  noDealershipLocationsDesc = "Yeni bir konum ekleyebilir, yapılandırmanızdan içe aktarabilir (v1'den geçiş yapıyorsanız) veya varsayılan konumları otomatik olarak ekleyebilirsiniz.",

  -- v2: Location sections
  dealershipZone = "Bayilik bölgesi",
  showroomAndManagement = "Showroom ve yönetim",
  openShowroom = "Showroom'u aç",
  openManagement = "Yönetimi aç",
  enableSellVehicle = "Araç satışını etkinleştir",
  percentageOfVehicleValue = "Araç değerinin %'si",
  enablePurchase = "Satın almayı etkinleştir",
  purchasedVehicleSpawn = "Satın alınan araç spawn",
  enableTestDrive = "Test sürüşünü etkinleştir",
  testDriveVehicleSpawn = "Test sürüşü araç spawn",
  truckDelivery = "Kamyon teslimatı",
  truckDeliveryVehicleSpawn = "Teslimat aracı spawn",

  -- v2: Location advanced settings
  paymentMethods = "Ödeme yöntemleri",
  supportsFinancing = "(finansman destekler)",
  enableFinance = "Finansmanı etkinleştir",
  cameraPreset = "Kamera",
  preset = "Ön ayar",
  custom = "Özel",
  vehiclePosition = "Araç pozisyonu",
  zoomPositions = "Zoom pozisyonları (virgülle ayrılmış)",
  zoomPositionsPlaceholder = "örnek: 5,8,12,8",
  vehicleColour = "Araç rengi",
  selectionType = "Seçim türü",
  noColourSelection = "Renk seçimi yok",
  rgbColourWheel = "RGB renk tekerleği",
  listOfRgbColours = "RGB renk listesi",
  listOfColourIds = "Renk ID listesi",
  accessControl = "Erişim kontrolü",
  showroomJobWhitelist = "Showroom iş beyaz listesi",
  showroomGangWhitelist = "Showroom çete beyaz listesi",
  societyPurchaseJobWhitelist = "Topluluk satın alma iş beyaz listesi",
  societyPurchaseGangWhitelist = "Topluluk satın alma çete beyaz listesi",
  setInGame = "Oyun içinde ayarla",
  addNew = "Yeni ekle",

  -- v2: Job/Gang whitelist editor
  job = "İş",
  gang = "Çete",
  jobWhitelist = "İş beyaz listesi",
  gangWhitelist = "Çete beyaz listesi",
  addJob = "İş ekle",
  addGang = "Çete ekle",
  editJob = "İşi düzenle",
  editGang = "Çeteyi düzenle",
  manageJobs = "İşleri yönet",
  manageGangs = "Çeteleri yönet",
  jobName = "İş adı",
  gangName = "Çete adı",
  selectGrades = "Rütbeleri seç",
  selectAll = "Tümünü seç",
  deselectAll = "Tümünü kaldır",
  invalidJobName = "Geçersiz iş adı. Framework yapılandırmanızı kontrol edin.",
  invalidGangName = "Geçersiz çete adı. Framework yapılandırmanızı kontrol edin.",
  grades = "Rütbeler",
  noJobsConfigured = "Yapılandırılmış iş yok",
  noGangsConfigured = "Yapılandırılmış çete yok",
  click = "Tıkla",
  toGetStarted = "başlamak için.",
  more = "daha fazla",
  jobPlaceholder = "Örneğin: cardealer",
  jobOptionalDescription = "İsteğe bağlı olarak bayilik rollerini bir framework işine bağlayın. Çalışanlar işe alındığında/kovulduğunda, framework işleri de güncellenecektir.",
  jobRankPermissions = "İş rütbe izinleri",
  roleToJobRankMapping = "Rol-iş rütbe eşlemesi",
  addPerm = "İzin ekle",

  -- v2: Colour selector
  searchColours = "Renk ara...",
  noColoursFound = "Renk bulunamadı",

  -- v2: Interactions creator
  noInteractions = "Etkileşim yok",
  highlightInteractions = "Etkileşimleri vurgula",
  explorationMode = "Keşif modu",
  pressEsc = "ESC'ye bas",
  toWalkAround = "dolaşmak için",
  toReturnToUI = "UI'ye dönmek için",
  points = "noktalar",
  location = "konum",
  manageLocations = "Konumları yönet",

  -- v2: Interaction modal
  interactionType = "Tür",
  nicknameOptional = "Takma ad (İsteğe bağlı)",
  invalidModel = "Geçersiz model",
  failedToValidateModel = "Model doğrulanamadı",
  pedScenario = "Ped senaryosu",
  coords = "Koordinatlar",
  size = "Boyut",
  blip = "Blip",
  enableBlip = "Blip'i etkinleştir",
  blipIconId = "Blip simge ID",
  blipColourId = "Blip renk ID",
  blipSize = "Blip boyutu",
  marker = "İşaretçi",
  enableMarker = "İşaretçiyi etkinleştir",
  markerStyleId = "İşaretçi stil ID",
  markerSize = "İşaretçi boyutu",
  markerColor = "İşaretçi rengi",
  markerBobUpAndDown = "Yukarı aşağı sal",
  markerFaceCamera = "Kameraya bak",
  markerRotate = "Döndür",
  markerDrawOnEnts = "Varlıklar üzerine çiz",
  updatePosition = "Pozisyonu güncelle",
  setPosition = "Pozisyonu ayarla",

  -- v2: Interaction types
  interactionPoint = "Nokta",
  interactionPointDesc = "İsteğe bağlı işaretçili tek yeniden boyutlandırılabilir nokta",
  interactionPolyzone = "Polyzone",
  interactionPolyzoneDesc = "Belirli bir etkileşim alanı oluşturmak için çoklu koordinat bölgesi",
  interactionVehicle = "Araç",
  interactionVehicleDesc = "Bir araç modeli oluştur, target veya 3D metin UI etkileşim yöntemleri için ideal",
  interactionObject = "Nesne",
  interactionObjectDesc = "Bir nesne modeli oluştur, target veya 3D metin UI etkileşim yöntemleri için ideal",
  interactionPed = "Ped",
  interactionPedDesc = "İsteğe bağlı senaryolu bir ped modeli oluştur, target veya 3D metin UI etkileşim yöntemleri için ideal",

  -- v2: Import modal
  importLocationsTitle = "Konumları içe aktar",
  syncStockLabel = "Stoku senkronize et",
  syncStockDescription = "Her bayiliğin stokuna kategorilerine göre araçlar ekle",
  importSourceSelectorDesc = "Hazır kurulum için varsayılan konumları içe aktarabilir veya Dealerships v1'den geçiş yapıyorsanız mevcut konumları yapılandırmanızdan içe aktarabilirsiniz.",
  importSourceSelectorSkipDesc = "Veritabanında zaten var olan konumlar atlanacak; yalnızca yeni konumlar içe aktarılacak.",
  successfullyImported = "Başarıyla içe aktarıldı",
  alreadyExist = "Zaten mevcut",
  defaultLocations = "Varsayılan konumlar",
  defaultLocationsDesc = "Önceden yapılandırılmış bayilik konumlarını içe aktar (PDM, Lüks, Tekneler, Hava, Kamyon)",
  existingConfig = "Mevcut yapılandırma",
  existingConfigDesc = "config.lua'dan konumları içe aktar (v1 geçişi için)",

  -- v2: Category stock sync
  categorySyncNewLocationDesc = "Seçilen kategorilere göre bu bayiliğin stokuna otomatik olarak araçlar eklemek ister misiniz?",
  categorySyncEditDesc = "Bu bayiliğin kategorilerini değiştirdiniz. Araç stokunu otomatik olarak güncellemek ister misiniz?",
  addVehicles = "Araç ekle",
  removeVehicles = "Araç kaldır",
  fromNewCategories = "yeni kategorilerden",
  fromSelectedCategories = "seçilen kategorilerden",
  fromRemovedCategories = "kaldırılan kategorilerden",
  categoriesAdded = "Eklenen kategoriler:",
  categoriesRemoved = "Kaldırılan kategoriler:",
  skip = "Atla",
  syncStock = "Stoku senkronize et",

  -- v2: Vehicle import modal
  checkingSourceAvailability = "Kaynak uygunluğu kontrol ediliyor...",
  vehiclesAvailableToImport = "içe aktarılabilecek araç",
  includesDealershipIds = "bayilik ID'lerini içerir",
  sourceUnavailable = "Kaynak mevcut değil",
  noVehiclesAdminDescription = "Araçları manuel olarak ekleyebilir veya framework'ünüzden içe aktarabilirsiniz.",
  appendBehaviour = "Ekle",
  overwriteBehaviour = "Üzerine yaz",
  appendDescription = "Yalnızca veritabanında bulunmayan yeni araçları ekle",
  overwriteDescription = "Mevcut tüm araç verilerini sil ve yeniden içe aktar",
  stockAssignmentMethod = "Stok atama yöntemi",
  useDealershipIdsFromSource = "Kaynaktan bayilik ID'lerini kullan",
  matchByVehicleCategory = "Araç kategorisine göre eşleştir",
  byShopDescription = "Araçlar, kaynak verilerindeki 'shop' alanına göre bayiliklere atanacak",
  byCategoryDescription = "Araçlar, eşleşen kategorilere sahip bayiliklere atanacak",
  overwriteWarning = "Uyarı: Üzerine yazmak mevcut tüm araçları, siparişleri, sergi araçlarını ve satış verilerini silecektir.",
  qbcoreSharedVehicles = "QBCore shared/vehicles.lua",
  qboxSharedVehicles = "Qbox shared/vehicles.lua",
  esxVehiclesTable = "ESX araç tablosu",
  selectCategory = "Kategori seç",

  -- v2: Management menu items
  vehiclesMenu = "Araçlar",
  displayVehiclesMenu = "Sergi araçları",
  ordersMenu = "Siparişler",
  salesMenu = "Satışlar",
  bankAccountMenu = "Banka hesabı",
  employeesMenu = "Çalışanlar",
  couponsMenu = "Kuponlar",
  settingsMenu = "Ayarlar",
  noPermissionAccessManagement = "Yönetim özelliklerine erişim izniniz yok.",
  backToAdmin = "Yöneticiye dön",
  viewingAsAdmin = "YÖNETİCİ OLARAK GÖRÜNTÜLEME",

  -- v2: Coupons table
  code = "Kod",
  uses = "Kullanım",
  perPlayer = "Oyuncu başına",
  never = "Asla",
  noCoupons = "Kupon yok",
  noCouponsDescription = "Müşteriler araç satın alırken kupon girebilir ve para tasarrufu yapabilir.",

  -- v2: Coupon modal
  couponCodeLabel = "Kupon kodu",
  couponCodePlaceholder = "örn. YAZ2024 veya TASARRUF10",
  couponCodeHelp = "Özel bir kod girin (en fazla 25 karakter, yalnızca harfler, rakamlar ve tire) veya 'Oluştur'a tıklayın.",
  maxNumberOfUsesPlaceholder = "Maksimum kullanım sayısı",
  maxUsesPerPlayerPlaceholder = "Oyuncu başına maksimum kullanım",
  vehicleRestrictionsPlaceholder = "Spawn kodlarını virgülle ayırarak girin (örn. adder, t20, zentorno)",
  allowOnFinancedPurchases = "Finansman satın almalarda izin ver",
  createCoupon = "Kupon oluştur",
  updateCoupon = "Kuponu güncelle",

  -- v2: Coupon validation messages
  couponCodeRequired = "Kupon kodu gerekli",
  couponCodeMaxLength = "Kod 25 karakter veya daha az olmalı",
  couponCodeInvalidChars = "Kod yalnızca büyük harfler, rakamlar ve tire içerebilir",
  discountTypeRequired = "İndirim türü gerekli",
  discountValueRequired = "İndirim değeri gerekli",
  discountValueMin = "İndirim değeri 0'dan büyük olmalı",
  discountValueMaxPercent = "Yüzde 100'ü aşamaz",
  maxUsesRequired = "Maksimum kullanım sayısı gerekli",
  maxUsesMin = "En az 1 olmalı",
  perPlayerLimitRequired = "Oyuncu başına limit gerekli",
  expiryDateRequired = "Son kullanma tarihi gerekli",
  vehicleRestrictionsRequired = "Araç kısıtlamaları gerekli",
  categoryRestrictionsRequired = "Kategori kısıtlamaları gerekli",
  selectAtLeastOneCategory = "En az bir kategori seçin",

  -- v2: Dashboard
  today = "Bugün",
  thisMonth = "Bu ay",
  allTime = "Tüm zamanlar",
  recentSales = "Son satışlar",
  noSalesYet = "Henüz satış yok!",
  noSalesDescription = "Araç satışları ilk satıştan sonra burada görünecek.",
  past7Days = "Son 7 gün",
  past6Months = "Son 6 ay",
  numberOfSales = "Satış sayısı",
  noDataAvailableForPeriod = "Bu dönem için veri yok",

  -- v2: Display vehicles
  displayVehiclesDescription = "Sergi araçları, stokunuzu sergilemek ve müşterileri satın almaya teşvik etmek için kullanılan sabit showroom modelleridir.",

  -- v2: Employees
  frameworkJobsEnabled = "Framework işleri etkin",
  frameworkJobsDescription = "Çalışan yönetimi framework iş sistemi üzerinden yapılır. Bayilik işine sahip oyuncular rütbelerine göre otomatik erişime sahip olacak. İş izinlerini yönetici paneli konum ayarlarında yapılandırın.",
  joinedColumn = "Katıldı",
  youBadge = "Sen",

  -- v2: Orders
  noOrdersTitle = "Sipariş yok",
  noOrdersDescription = "Sipariş vermek için 'Araçlar' sekmesini açın ve yenilemek istediğiniz araçta 'Sipariş'e tıklayın.",
  inProgress = "Devam ediyor",
  awaitingDelivery = "Teslimat bekleniyor",
  orderedBy = "Sipariş veren",
  viewDeliveryInfo = "Teslimat bilgilerini görüntüle",

  -- v2: Delivery
  startDeliveryMissionTitle = "Teslimat görevini başlat",
  startDeliveryDescription = "Bu araç siparişi için teslimat görevi başlatmak üzeresiniz. Alım noktasına gitmeniz, kargo römorku almanız ve bayiliğe geri teslim etmeniz gerekecek.",
  totalDistanceAndDriveTime = "Toplam mesafe ve sürüş süresi",
  roundTrip = "gidiş-dönüş",
  deliveryCompleteTitle = "Teslimat tamamlandı",
  deliveryInProgressTitle = "Teslimat devam ediyor",
  deliveredAt = "Teslim edildi:",
  startedAt = "Başladı:",
  deliveredBy = "Teslim eden:",
  beingDeliveredBy = "Teslim eden:",

  -- v2: Multi-delivery
  noOrdersAvailableForDelivery = "Teslimat için sipariş yok. Siparişlerin hazır olması ve aktif teslimatta olmaması gerekir.",
  confirmDeliveryTitle = "Teslimatı onayla",
  configureDeliveryTitle = "Teslimatı yapılandır",
  trailerCapacityExceeded = "Römork kapasitesi aşıldı! %{usedSlots} slot seçtiniz, ancak maksimum %{maxSlots} slot.",
  smallVehiclesSlotInfo = "Not: Küçük araçlar 1 slot, orta araçlar 1,5 slot kaplar.",
  fetchingRoute = "Getiriliyor...",
  getRouteButton = "Rota al",
  selectTrailerType = "Römork türü seç",
  carTrailerLabel = "Araç taşıyıcı",
  smallMedium = "(Küçük/Orta)",
  containerLabel = "Konteyner",
  large = "(Büyük)",
  carTrailerDescription = "Araç taşıyıcının 2 sırası var. Her sıra 3 küçük (her biri 1 slot) veya 2 orta (her biri 1,5 slot) alır. Toplam maksimum 6 slot.",
  containerDescription = "Konteyner römorku 1 büyük araç taşır",
  selectOrdersTitle = "Siparişleri seç",
  slots = "slotlar",
  noOrdersForTrailerType = "Bu römork türü için sipariş yok.",
  qty = "Miktar:",
  inTransit = "yolda",
  totalVehicles = "Toplam araç:",
  estimatedTime = "Tahmini süre:",
  unknown = "Bilinmiyor",

  -- v2: Sales
  salesEmptyDescription = "Araç satışları ilk satıştan sonra burada görünecek.",

  -- v2: Orders/Stock modals
  orderPlacedTitle = "Sipariş verildi!",
  orderPlacedTruckingDescription = "Siparişiniz almaya hazır. Tamamlamak için siparişler sayfasına gidin.",
  orderPlacedTimedDescription = "Siparişiniz %{value} dakika içinde gelecek.",
  goToOrders = "Siparişlere git",
  noStockAvailableDescription = "Bu araç için stok yok. Global stok limiti aşıldı.",
  stockUpdatedDescription = "Stok miktarı başarıyla güncellendi.",

  -- v2: Direct sales tablet
  activeTestDrives = "Aktif test sürüşleri",
  tracking = "İzleme",
  track = "İzle",
  endButton = "Bitir",
  endTestDriveTitle = "Test sürüşünü bitir",
  endTestDriveConfirmation = "Bu test sürüşünü bitirmek istediğinizden emin misiniz? Araç silinecek ve yolcular bayiliğe geri ışınlanmayacak.",
  vehicleLocationOnMap = "Aracın konumu haritanızda işaretlendi.",
  sell = "Sat",
  couponCodeOptional = "Kupon kodu (İsteğe bağlı)",
  pleaseEnterCouponCode = "Lütfen kupon kodu girin",
  invalidCouponCode = "Geçersiz kupon kodu",
  failedToValidateCoupon = "Kupon doğrulanamadı",
  apply = "Uygula",
  applying = "Uygulanıyor...",
  allStock = "Tüm stok",
  inStockFilter = "Stokta",
  outOfStockFilter = "Stokta yok",
  noResultsFound = "Sonuç bulunamadı",
  noResults = "Sonuç yok",
  noVehiclesMatchSearch = "Aramanızla eşleşen araç yok",
  noVehiclesMatchFilters = "Mevcut filtrelerle eşleşen araç yok",
  noItemsMatchSearch = "Aramanızla eşleşen öğe yok",
  noItemsMatchFilters = "Mevcut filtrelerle eşleşen öğe yok",
  selectColour = "Renk seç",
  refreshNearbyPlayers = "Yakındaki oyuncuları yenile",
  you = "Sen",
  items = "öğeler",
  waitingForCustomerToRespond = "Müşterinin yanıtı bekleniyor...",
  vehicleSpawnedMessage = "Araç haritanızda işaretlenen noktada oluştu - müşteriyi oraya götürün.",
  customerDeclinedMessage = "Müşteri satın alma talebini reddetti.",

  -- v2: Direct sale confirm purchase
  signHerePlaceholder = "BURAYA İMZALA",
  acceptAndPurchase = "Kabul et ve satın al",
  couponApplied = "%{code} kuponu uygulandı! %{discount} tasarruf ettiniz",

  -- v2: Zone creator (instructional prompts)
  zoneCreatorMinPoints = "Bölgeyi tamamlamak için en az 3 nokta gerekli! (Şu anda %{value})",
  addPoint = "Nokta ekle",
  removeLast = "Sonuncuyu kaldır",
  completeZone = "Bölgeyi tamamla",
  spawnPreview = "Spawn önizlemesi",
  up = "Yukarı",
  down = "Aşağı",
  confirm = "Onayla",
  placePoint = "Nokta yerleştir",
  radius = "Yarıçap",

  -- v2: Blip labels
  soldVehicleLocation = "Satılan araç konumu",
  testDriveVehicleBlip = "Test sürüşü aracı",

  -- v2: Stock sync
  stockSyncResult = "Stok senkronizasyonu: %{added} eklendi, %{removed} kaldırıldı",
  stockSyncAdded = "Stok senkronizasyonu: %{value} araç eklendi",
  importSuccessful = "İçe aktarma başarılı! %{imported} araç içe aktarıldı (toplam %{total})",

  -- v2: Tooltip actions
  findOnMap = "Haritada bul",
  adminPanel = "Yönetici paneli",

  -- v2: Common dropdown
  selectOne = "Birini seç",
}
