Locales = Locales or {}

Locales["cs"] = {
  back = "Zpět",
  previous = "Předchozí",
  next = "Další",
  search = "Hledat",
  page = "Stránka",
  of = "z",
  every = "každý",
  show = "Zobrazit",
  delete = "Smazat",
  copied = "Zkopírováno",
  copyToClipboard = "Kopírovat do schránky",
  searchHandling = "Hledat vlastnosti handlingu",
  viewChanges = "Zobrazit změny",
  applyHandling = "Použít handling",
  clearChanges = "Vymazat změny",
  preview = "Náhled",
  applied = "Použito",
  apply = "Použít",
  exportTo = "Exportovat do:",
  overwrite = "Přepsat",
  modify = "Upravit",
  configType = "Typ konfigurace:",
  configForTuningLua = "Konfigurace pro config.tuning.lua:",
  xml = "XML:",
  handlingName = "Název handlingu",
  handlingNameNeedsChecking = "Zkontrolujte název handlingu",
  handlingNameWarning = "Název handlingu nelze spolehlivě zjistit. Před zkopírováním XML tuto hodnotu zkontrolujte nebo upravte.",
  missingHandlingName = "Zadejte název handlingu",
  deleting = "Mazání...",
  successfullyLoaded = "úspěšně načteno",
  loadProfile = "Načíst profil",
  name = "Název",
  vehicleName = "Název vozidla",
  editedAt = "Vytvořeno dne",
  editedBy = "Vytvořil",
  resetHandlingToStock = "Obnovit handling vozidla na výchozí",
  resetHandling = "Obnovit handling vozidla",
  vehicleReset = "Vozidlo obnoveno na výchozí hodnoty",
  profileName = "Název profilu",
  saving = "Ukládání...",
  save = "Uložit",
  saveAsProfile = "Uložit jako profil",
  discardChanges = "Zahodit změny",
  advancedEditor = "Pokročilý editor",
  simplifiedEditor = "Zjednodušený editor",
  export = "Export",
  savedProfiles = "Uložené profily",
  resetToDefault = "Obnovit výchozí",
  handlingPreviewMode = "Režim náhledu handlingu",
  selectMechanicMode = "Vyberte režim dat mechanika",
  processing = "Zpracování...",
  confirm = "Potvrdit",
  currentHandling = "Aktuální handling",
  ignoreServicing = "Ignorovat servis",
  useBaseHandling = "Použít základní handling",
  timingToolReset = "RESET",
  noPresetSelected = "Žádný preset nevybrán",
  applyTemporarily = "Použít dočasně (do despawnu vozidla)",
  applyToPlate = "Použít vždy na tuto SPZ (uložit do DB)",
  applyToModel = "Použít vždy na všechna vozidla tohoto modelu (uložit do DB)",
  handlingApplyType = "Jak chcete tento handling aplikovat?",

  -- Dlouhé zprávy
  applyHandlingIfJGMechanic = "Pokud používáte JG Mechanic, tyto úpravy jsou přepsáním a poškození ze servisu nebude aplikováno, dokud nebude vozidlo resetováno.",
  noHandlingChanges = "V handlingu nejsou žádné změny!",
  confirmationDeleteProfile = "Opravdu chcete smazat tento profil?",
  resetHandlingToStockMsg = "Handling tohoto vozidla byl upraven tímto nástrojem. Můžete vozidlo resetovat na sériové nastavení (handling profil, který mělo před úpravou v tomto editoru) kliknutím na tlačítko níže. Pokud byl handling uložen do databáze, data budou smazána; a pokud bylo vybráno použití na všechna vozidla tohoto modelu, budou resetována i ta.",
  bodyRollLeft = "Posuňte doleva, pokud se vozidlo naklání ve směru jízdy nebo je příliš tuhé/nemá náklon karoserie",
  bodyRollRight = "Posuňte doprava, pokud se vozidlo převrací v zatáčkách nebo má velký náklon karoserie/není dostatečně tuhé",
  handlingNotApplied = "Změny handlingu, které jste provedli, nebyly aplikovány na vozidlo.",
  continueAreYouSure = "Opravdu chcete pokračovat?",
  previewRtnToEditor = "Stiskněte [BACKSPACE] pro návrat do editoru.",
  mechanicDataModeExplain = "Handling tohoto vozidla byl upraven pomocí JG Mechanic. Můžete zvolit úpravu handlingu tak, jak je (možnost 1), úpravu handlingu bez jakýchkoli modifikací (možnost 3), nebo pouze bez poškození ze servisu (možnost 2).",
  currentHandlingExplain = "Pracujte s aktuálním handlingem vozidla, včetně všech úprav tuningu a servisu.",
  ignoreServicingExplain = "Získejte aktuální handling vozidla, ale bez poškození ze servisu (pokud je relevantní).",
  useBaseHandlingExplain = "Použijte základní handling vozidla bez ohledu na jakékoli modifikace provedené JG Mechanic.",
  applyToModelWarning = "Toto se nedoporučuje, protože to může přidat značnou zátěž na váš server. Místo toho exportujte a aktualizujte soubor handling.meta vozidla.",

  -- Kategorie tuningu
  allCategories = "Všechny kategorie",
  aero = "Aerodynamika",
  transmission = "Převodovka",
  traction = "Přilnavost kol",
  suspension = "Podvozek",
  damage = "Poškození",
  chassis = "Podvozek (šasi)",
  engine = "Motor",
  brakes = "Brzdy",
  antiroll = "Stabilizátory",
  flags = "Příznaky",
  other = "Ostatní",
  acceleration = "Zrychlení",
  topSpeed = "Maximální rychlost (%s)",
  transmissionGearbox = "Převodovka (řazení)",
  drivetrain = "Pohon (RWD, AWD atd.)",
  downforce = "Křídlo (přítlak)",
  bodyRoll = "Náklon karoserie",

  -- Nástroj pro měření času
  ready = "Připraveno",
  recording = "Nahrávání",
  stopVehicle = "Zastavit vozidlo",
  idle = "Nečinný",
  loading = "Načítání",

  -- Oznámení
  noSavedHandlings = "Nebyly uloženy žádné konfigurace handlingu",
  noResultsFound = "Nebyly nalezeny žádné výsledky",
  noHandlingChangesMade = "Nebyly provedeny žádné změny handlingu",
  handlingSaved = "Handling uložen",
  notInVehicle = "Nejste ve vozidle",
  notCompatibleWithHandlingEditor = "Vozidlo není kompatibilní s editorem handlingu",
  handlingApplied = "Handling profil úspěšně aplikován",
  requiresAdmin = "K použití musíte být admin",
  noPermission = "Nemáte oprávnění k použití",
  couldNotCreateProfile = "Nepodařilo se vytvořit nový profil",

  -- Vyhledávání/tabulky
  noItemsMatchSearch = "Žádné položky neodpovídají vašemu hledání.",
  noItemsMatchFilters = "Žádné položky neodpovídají vašim filtrům.",
  items = "položek",
}
