Locales = Locales or {}

Locales["de"] = {
    back = "Zurück",
    previous = "Vorherige",
    next = "Nächste",
    search = "Suchen",
    page = "Seite",
    of = "von",
    every = "jede",
    show = "Anzeigen",
    delete = "Löschen",
    copied = "Kopiert",
    copyToClipboard = "In Zwischenablage kopieren",
    searchHandling = "Handling-Eigenschaften durchsuchen",
    viewChanges = "Änderungen anzeigen",
    applyHandling = "Handling anwenden",
    clearChanges = "Änderungen zurücksetzen",
    preview = "Vorschau",
    applied = "Angewendet",
    apply = "Anwenden",
    exportTo = "Exportieren nach:",
    overwrite = "Überschreiben",
    modify = "Bearbeiten",
    configType = "Konfigurationstyp:",
    configForTuningLua = "Konfiguration für config.tuning.lua:",
    xml = "XML:",
    handlingName = "Handling-Name",
    handlingNameNeedsChecking = "Handling-Namen prüfen",
    handlingNameWarning = "Handling-Namen können nicht zuverlässig erkannt werden. Prüfe oder bearbeite diesen Wert, bevor du das XML kopierst.",
    missingHandlingName = "Handling-Namen eingeben",
    deleting = "Lösche...",
    successfullyLoaded = "erfolgreich geladen",
    loadProfile = "Profil laden",
    name = "Name",
    vehicleName = "Fahrzeugname",
    editedAt = "Erstellt am",
    editedBy = "Erstellt von",
    resetHandlingToStock = "Fahrzeug-Handling auf Standard zurücksetzen",
    resetHandling = "Handling zurücksetzen",
    vehicleReset = "Fahrzeug wurde auf Standard zurückgesetzt",
    profileName = "Profilname",
    saving = "Speichere...",
    save = "Speichern",
    saveAsProfile = "Als Profil speichern",
    discardChanges = "Änderungen verwerfen",
    advancedEditor = "Erweiterter Editor",
    simplifiedEditor = "Vereinfachter Editor",
    export = "Exportieren",
    savedProfiles = "Gespeicherte Profile",
    resetToDefault = "Auf Standard zurücksetzen",
    handlingPreviewMode = "Handling-Vorschaumodus",
    selectMechanicMode = "Mechaniker-Datenmodus auswählen",
    processing = "Verarbeite...",
    confirm = "Bestätigen",
    currentHandling = "Aktuelles Handling",
    ignoreServicing = "Wartungsschäden ignorieren",
    useBaseHandling = "Basis-Handling verwenden",
    timingToolReset = "ZURÜCKSETZEN",
    noPresetSelected = "Kein Preset ausgewählt",
    applyTemporarily = "Temporär anwenden (bis das Fahrzeug despawnt)",
    applyToPlate = "Immer auf dieses Kennzeichen anwenden (in DB speichern)",
    applyToModel = "Immer auf alle Fahrzeuge dieses Modells anwenden (in DB speichern)",
    handlingApplyType = "Wie soll dieses Handling angewendet werden?",

    -- Long Messages
    applyHandlingIfJGMechanic =
    "Wenn du JG Mechanic verwendest, überschreiben diese Änderungen das aktuelle Handling. Wartungsschäden werden erst wieder angewendet, nachdem das Fahrzeug zurückgesetzt wurde.",
    noHandlingChanges = "Es wurden keine Handling-Änderungen vorgenommen!",
    confirmationDeleteProfile = "Bist du sicher, dass du dieses Profil löschen möchtest?",
    resetHandlingToStockMsg =
    "Dieses Fahrzeug wurde mit diesem Tool bearbeitet. Du kannst das Fahrzeug auf das ursprüngliche Standard-Handling zurücksetzen (das Handling vor der Bearbeitung durch diesen Editor), indem du unten klickst. Falls das Handling in der Datenbank gespeichert wurde, werden diese Daten gelöscht. Wenn ‚Auf Modell anwenden‘ gewählt wurde, werden alle Fahrzeuge dieses Modells zurückgesetzt.",
    bodyRollLeft =
    "Nach links verschieben, wenn das Fahrzeug sich in Fahrtrichtung zu stark neigt oder zu steif wirkt / kein Body Roll hat",
    bodyRollRight =
    "Nach rechts verschieben, wenn das Fahrzeug in Kurven kippt oder zu viel Body Roll hat / nicht steif genug ist",
    handlingNotApplied = "Die vorgenommenen Handling-Änderungen wurden noch nicht angewendet.",
    continueAreYouSure = "Bist du sicher, dass du fortfahren möchtest?",
    previewRtnToEditor = "Drücke [BACKSPACE], um zum Editor zurückzukehren.",
    mechanicDataModeExplain =
    "Dieses Fahrzeug wurde durch JG Mechanic modifiziert. Du kannst das aktuelle Handling bearbeiten (Option 1), ohne Wartungsschäden (Option 2) oder das Basis-Handling ohne jegliche Modifikationen verwenden (Option 3).",
    currentHandlingExplain = "Teste das aktuelle Handling des Fahrzeugs inklusive Tuning- und Wartungsänderungen.",
    ignoreServicingExplain =
    "Verwende das aktuelle Handling des Fahrzeugs, jedoch ohne Wartungsschäden (falls vorhanden).",
    useBaseHandlingExplain = "Verwende das Basis-Handling des Fahrzeugs und ignoriere alle Änderungen durch JG Mechanic.",
    applyToModelWarning =
    "Dies wird nicht empfohlen, da es zusätzliche Serverlast verursachen kann. Stattdessen solltest du das Handling exportieren und die handling.meta-Datei direkt anpassen.",

    -- Tuning Categories
    allCategories = "Alle Kategorien",
    aero = "Aerodynamik",
    transmission = "Getriebe",
    traction = "Rad-Traktion",
    suspension = "Federung",
    damage = "Schaden",
    chassis = "Chassis",
    engine = "Motor",
    brakes = "Bremsen",
    antiroll = "Stabilisatoren",
    flags = "Flags",
    other = "Sonstiges",
    acceleration = "Beschleunigung",
    topSpeed = "Höchstgeschwindigkeit (%s)",
    transmissionGearbox = "Getriebe (Gangschaltung)",
    drivetrain = "Antrieb (RWD, AWD, etc.)",
    downforce = "Flügel (Abtrieb)",
    bodyRoll = "Karosserieneigung",

    -- Timing Tool
    ready = "Bereit",
    recording = "Aufzeichnung läuft",
    stopVehicle = "Fahrzeug anhalten",
    idle = "Leerlauf",
    loading = "Lädt",

    -- Notifications
    noSavedHandlings = "Keine Handling-Konfigurationen gespeichert",
    noResultsFound = "Keine Ergebnisse gefunden",
    noHandlingChangesMade = "Es wurden keine Handling-Änderungen vorgenommen",
    handlingSaved = "Handling gespeichert",
    notInVehicle = "Du befindest dich in keinem Fahrzeug",
    notCompatibleWithHandlingEditor = "Dieses Fahrzeug ist nicht mit dem Handling-Editor kompatibel",
    handlingApplied = "Handling-Profil erfolgreich angewendet",
    requiresAdmin = "Du musst Admin sein, um dies zu verwenden",
    noPermission = "Du hast keine Berechtigung hierfür",
    couldNotCreateProfile = "Neues Profil konnte nicht erstellt werden",

    -- Search/tables
    noItemsMatchSearch = "Keine Einträge entsprechen deiner Suche.",
    noItemsMatchFilters = "Keine Einträge entsprechen deinen Filtern.",
    items = "Einträge",
}
