Locales = Locales or {}

Locales["fr"] = {
  back = "Retour",
  previous = "Précédent",
  next = "Suivant",
  search = "Rechercher",
  page = "Page",
  of = "de",
  every = "tous les",
  show = "Afficher",
  delete = "Supprimer",
  copied = "Copié",
  copyToClipboard = "Copier dans le presse-papier",
  searchHandling = "Rechercher les propriétés de gestion",
  viewChanges = "Voir les modifications",
  applyHandling = "Appliquer le handling",
  clearChanges = "Effacer les modifications",
  preview = "Aperçu",
  applied = "Appliqué",
  apply = "Appliquer",
  exportTo = "Exporter vers :",
  overwrite = "Écraser",
  modify = "Modifier",
  configType = "Type de configuration :",
  configForTuningLua = "Configuration pour config.tuning.lua :",
  xml = "XML :",
  deleting = "Suppression...",
  successfullyLoaded = "chargé avec succès",
  loadProfile = "Charger un profil",
  name = "Nom",
  vehicleName = "Nom du véhicule",
  editedAt = "Édité à",
  editedBy = "Édité par",
  resetHandlingToStock = "Réinitialiser le handling du véhicule aux valeurs d'usine",
  resetHandling = "Réinitialiser le handling du véhicule",
  vehicleReset = "Véhicule réinitialisé aux valeurs par défaut",
  profileName = "Nom du profil",
  saving = "Enregistrement...",
  save = "Enregistrer",
  saveAsProfile = "Enregistrer comme profil",
  discardChanges = "Annuler les modifications",
  advancedEditor = "Éditeur avancé",
  simplifiedEditor = "Éditeur simplifié",
  export = "Exporter",
  savedProfiles = "Profils enregistrés",
  resetToDefault = "Réinitialiser aux valeurs par défaut",
  handlingPreviewMode = "Mode aperçu du handling",
  selectMechanicMode = "Sélectionner le mode données du mécanicien",
  processing = "Traitement...",
  confirm = "Confirmer",
  currentHandling = "Handling actuel",
  ignoreServicing = "Ignorer les modifications de maintenance",
  useBaseHandling = "Utiliser le handling de base",
  timingToolReset = "RÉINITIALISER",
  noPresetSelected = "Aucun preset sélectionné",
  applyTemporarily = "Appliquer temporairement (jusqu'à ce que le véhicule despawn)",
  applyToPlate = "Appliquer à cette plaque tout le temps (stocké en DB)",
  applyToModel = "Appliquer à tous les véhicules de ce modèle tout le temps (stocké en DB)",
  handlingApplyType = "Comment souhaitez-vous appliquer ce handling ?",

  -- Long Messages
  applyHandlingIfJGMechanic = "Si vous utilisez JG Mechanic, ces modifications remplacent les données existantes et les dommages de maintenance ne seront pas appliqués jusqu'à ce que le véhicule soit réinitialisé.",
  noHandlingChanges = "Il n'y a pas de modifications à apporter au handling !",
  confirmationDeleteProfile = "Êtes-vous sûr de vouloir supprimer ce profil ?",
  resetHandlingToStockMsg = "Ce véhicule a été modifié par cet outil. Vous pouvez le réinitialiser aux valeurs d'usine (le profil de handling qu'il avait avant d'être modifié par cet éditeur) en cliquant sur le bouton ci-dessous. Si le handling a été conservé dans la base de données, les données seront supprimées ; et si l'option 'appliquer à tous les véhicules de ce modèle' a été sélectionnée, cela réinitialisera tous ces véhicules.",
  bodyRollLeft = "Déplacez vers la gauche si le véhicule bascule dans la direction du mouvement ou si le véhicule est trop rigide/sans roll corporel",
  bodyRollRight = "Déplacez vers la droite si le véhicule bascule lors des virages ou s'il a beaucoup de roll corporel/pas assez rigide",
  handlingNotApplied = "Les modifications de handling que vous avez faites n'ont pas été appliquées au véhicule.",
  continueAreYouSure = "Êtes-vous sûr de vouloir continuer ?",
  previewRtnToEditor = "Appuyez sur [BACKSPACE] pour revenir à l'éditeur.",
  mechanicDataModeExplain = "Le handling de ce véhicule a été modifié par JG Mechanic. Vous pouvez choisir d'éditer le handling tel qu'il est (option 1), d'éditer le handling sans aucune modification (option 3), ou simplement sans dommages de maintenance (option 2).",
  currentHandlingExplain = "Jouez avec le handling actuel du véhicule, y compris toutes les modifications de réglage et de maintenance.",
  ignoreServicingExplain = "Obtenez le handling actuel du véhicule, mais sans aucun dommage de maintenance (si applicable).",
  useBaseHandlingExplain = "Utilisez le handling de base du véhicule, en ignorant toutes les modifications apportées par JG Mechanic.",
  applyToModelWarning = "Ceci n'est pas recommandé ; car cela peut ajouter beaucoup de charge supplémentaire à votre serveur. Au lieu de cela, exportez et mettez à jour le fichier handling.meta du véhicule.",

  -- Tuning Categories
  allCategories = "Toutes les catégories",
  aero = "Aérodynamique",
  transmission = "Transmission",
  traction = "Traction des roues",
  suspension = "Suspension",
  damage = "Dommages",
  chassis = "Châssis",
  engine = "Moteur",
  brakes = "Freins",
  antiroll = "Barres anti-roulis",
  flags = "Drapeaux",
  other = "Autre",
  acceleration = "Accélération",
  topSpeed = "Vitesse maximale (%s)",
  transmissionGearbox = "Transmission (Boîte de vitesse)",
  drivetrain = "Système de transmission (RWD, AWD, etc...)",
  downforce = "Aile (Downforce)",
  bodyRoll = "Roll corporel",

  -- Timing Tool
  ready = "Prêt",
  recording = "Enregistrement",
  stopVehicle = "Arrêter le véhicule",
  idle = "Inactif",
  loading = "Chargement",

  -- Notifications
  noSavedHandlings = "Aucune configuration de handling n'a été enregistrée",
  noResultsFound = "Aucun résultat trouvé",
  noHandlingChangesMade = "Aucun changement de handling n'a été effectué",
  handlingSaved = "Handling enregistré",
  notInVehicle = "Vous n'êtes pas dans un véhicule",
  notCompatibleWithHandlingEditor = "Le véhicule n'est pas compatible avec l'éditeur de handling",
  handlingApplied = "Profil de handling appliqué avec succès",
  requiresAdmin = "Vous devez être un administrateur pour utiliser ceci",
  noPermission = "Vous n'avez pas la permission d'utiliser ceci",
  couldNotCreateProfile = "Impossible de créer un nouveau profil",

  -- Search/tables
  noItemsMatchSearch = "Aucun article ne correspond à votre recherche.",
  noItemsMatchFilters = "Aucun article ne correspond à vos filtres.",
  items = "articles",
}
